Uniswap/interface

src/helpers/exchange-utils.js

ERC20 to ERC20 calculateInput & calculateOutput

---

src/components/CurrencyInputPanel/currency-panel.scss

Add focus-within border

---

src/assets/images/pending.svg
src/components/Web3Status/index.js
src/components/Web3Status/web3-status.scss
src/index.scss

Closes #65 
Closes #63
(This PR doesn't include the approval/unlock stuff. Just tried them both together in the gif in order to do something for pending transactions)
Right now, the link to etherscan won't work because I didn't add the rinkeby subdomain.

Pending transactions modal

---

src/ducks/index.js
src/ducks/web3connect.js
src/pages/App.js
src/pages/App.scss
src/pages/Pool/AddLiquidity.js
src/pages/Pool/index.js
src/pages/Swap/index.js

- Partial Refactor of Swap
- Finish calculation for Add Liquidity

Add Web3Connect Watcher to replace drizzle

---

src/components/CurrencyInputPanel/index.js
src/components/Web3Status/index.js
src/ducks/swap.js
src/helpers/approval-utils.js
src/helpers/contract-utils.js
src/helpers/exchange-utils.js
src/pages/Swap/index.js

Reset after confirmed swap

---

src/helpers/exchange-utils.js

Closes #48 #50 #51 #52 #53 #54

Create send/transfer utils

---

src/components/AddressInputPanel/index.js
src/components/CurrencyInputPanel/index.js
src/ducks/index.js
src/ducks/send.js
src/helpers/exchange-utils.js
src/pages/Send/index.js

Connect send page with exchange utils

---

src/assets/images/plus-blue.svg
src/ducks/web3connect.js
src/pages/Pool/AddLiquidity.js
src/pages/Pool/pool.scss
src/variables.scss

Handle first liquidity deposit and add warning message

---

src/ducks/web3connect.js

Fix instant removal of pending

---

src/pages/Pool/AddLiquidity.js
yarn.lock

Normalize token decimals before calculating exchange rate

---

src/pages/Pool/AddLiquidity.js

Add different transaction details for 1st liquidity

---

src/pages/Send/index.js
src/pages/Swap/index.js
src/pages/Swap/swap.scss

Middle arrow flips input/output for swap/send

---

src/components/CurrencyInputPanel/currency-panel.scss

Improve scroll performance of Token List

---

src/components/ContextualInfo/contextual-info.scss
src/components/ContextualInfo/index.js
src/pages/Pool/AddLiquidity.js
src/pages/Pool/CreateExchange.js
src/pages/Pool/RemoveLiquidity.js
src/pages/Pool/pool.scss
src/pages/Send/index.js
src/pages/Swap/index.js
src/pages/Swap/swap.scss

changing the transaction details modal into expanding panel para feedback.

refactor transaction details modal into expanding panel

---

src/pages/App.scss

no more breakpoints, just max width #183

fix bug w/ wrapper width

---

src/contexts/Tokens.js

https://etherscan.io/address/0x8da198a049426bfcf1522b0dc52f84beda6e38ff#tokentxns
https://etherscan.io/address/0x5a4ade4f3e934a0885f42884f7077261c3f4f66f

Update new SNX exchange and new token address

---

src/contexts/Tokens.js

add pnk and mod

---

src/pages/Pool/AddLiquidity.js
src/pages/Pool/RemoveLiquidity.js
src/pages/Send/index.js

fix various 0 decimal bugs

---

src/components/NavigationTabs/index.js
src/components/Web3Status/index.js
src/contexts/Application.js
src/contexts/LocalStorage.js
src/index.js
src/pages/Send/index.js
src/pages/Swap/index.js

permanently dismiss that pesky beta message
also remove arrow from connect, and invert rates to start

add localstorage support

---

src/components/TransactionDetails/index.js

allowing leading dot slippage

---

package.json
src/components/ContextualInfo/index.js
src/components/Footer/index.js
src/components/Header/index.js
src/components/TransactionDetails/index.js
src/pages/App.js
src/theme/index.js
yarn.lock

Added a footer for linking to useful information. 
Fixed some scrolling behavior on mobile.
Footer also includes the theme toggle for light <--> dark modes.
Could use an eye for layout issues based on changing the container structure.

Add theme toggle and footer

---

src/components/ExchangePage/index.jsx
src/pages/Pool/AddLiquidity.js
src/utils/index.js

Closes #440 
Closes #358
When user clicks balance within the add liquidity page it populate field with balance

make balances clickable on add liquidity page

---

src/pages/Pool/AddLiquidity.js

- null value was gettign passed to formatter when linking to page with url parameter
-update to wait for decimals to get value first

fix big on linking to add liquidity

---

src/components/NavigationTabs/index.js
src/contexts/LocalStorage.js
src/contexts/Tokens.js
src/theme/index.js
src/utils/index.js

- basic ui skeleton and balance checking to prep for DAI migration 
- still waiting on migration tool to go live and MCD addresses
- if you hold SAI, you'll get a general warniing
- if you provide liquidity for SAI, you'll get a provider warning on the Pool tab

Dai Migration - UI Updates

---

src/components/CurrencyInputPanel/index.js
src/pages/Pool/AddLiquidity.js

Fixes #515 
- Catches error when doing max approve on tokens that restrict approval amount 
- if approve fails tries again with the users balance , if fails again enters regular error state

Bug fixer on tokens with restricted approvals

---

package.json
src/components/WalletModal/Option.js
src/components/WalletModal/PendingView.js
yarn.lock

- Prevent MetaMask display when using other browser wallets on desktop

Update to loading state for injected desktop browsers 

---

src/components/ExchangePage/index.jsx
src/components/TransactionDetails/index.js

Added deadline input field to 'Advanced Details' dropdown section.
Resolves #232

Allow to set custom deadline

---

src/components/Identicon/index.js

I forked Uniswap's wallet system a while ago and since I started to get this error occasionally logged in my console:
- [Can't perform a React state update on an unmounted component](https://stackoverflow.com/questions/53949393/cant-perform-a-react-state-update-on-an-unmounted-component)
I got a lot of side effect Hooks, so the cause may not be the Identicon component, but it's a code smell anyway. Hope it helps.

Add dependency array to "Identicon" side effect

---

src/components/ExchangePage/index.jsx
src/components/TransactionDetails/index.js

- update default slippage option to 50 bips

update default slippage to 50 bips

---

src/components/WalletModal/Option.js
src/components/WalletModal/index.js
yarn.lock

fix some random sc gibberish
when web3-react throws an unsupported chain id error, don't eat it like normal, instead propagate it to the app.
bump away from supposedly vulnerable handlebars version

web3-react improvement

---

src/components/NavigationTabs/index.js
src/pages/App.js

fix linking bug

---

src/components/CurrencyInputPanel/index.js

- fix bug where site crashes on some token pastings

Token pasting fix

---

src/constants/index.js

**PLEASE DO NOT SUBMIT TOKEN ADDITIONS AS PULL REQUESTS**
All token requests should be made via an issue.

Update WalletConnect naming

---

src/components/CurrencyInputPanel/index.js

- update to only match address on search if input begins with '0x'

update search on token input

---

src/components/ExchangePage/index.jsx

- show warning on tokens added through URL route on swap and send pages

Token warning updates 

---

src/components/ExchangePage/index.jsx
src/pages/Pool/AddLiquidity.js
src/pages/Pool/RemoveLiquidity.js

- update event values to be eth only 
- add txn hash to GA events 
- create new event category for tracking hashes (add custom dimension to test on old events, "dimension1" is syntax from ReactGA)

add txn hash to analytics

---

src/components/AddressInputPanel/index.js
src/components/ExchangePage/index.tsx
src/components/Menu/index.js
src/components/NavigationTabs/index.js
src/components/SearchModal/index.js
src/contexts/Balances.tsx
src/contexts/Exchanges.tsx
src/contexts/LocalStorage.js
src/contexts/Tokens.tsx
src/pages/App.js
src/pages/Supply/AddLiquidity.tsx
src/pages/Supply/RemoveLiquidity.tsx

- hide advanced mode and dark mode toggle until more complete 
- fix bug when user has no balances

Hide dark and advanced, fix bug on empty balances

---

src/contexts/Balances.tsx

- catch bug if ETH found as address in local storage balance, overwrite as WETH to be used to instantiate TokenAmount

add fix for ETH balance fetching

---

public/locales/en.json
src/components/AddressInputPanel/index.js
src/components/CurrencyInputPanel/index.js
src/components/ExchangePage/index.tsx
src/components/SearchModal/index.js
src/components/WalletModal/index.js
src/connectors/index.js
src/constants/index.ts
src/contexts/Balances.tsx
src/contexts/Exchanges.tsx
src/contexts/Tokens.tsx
src/pages/App.js
src/pages/Supply/AddLiquidity.tsx
src/pages/Supply/index.js

- Change message to show currently connected testnet 
- bug fixes on input parsing for new pairs 
- update linking from swap page -> create exchange 
- fix bugs on balance fetching

Update message for testnet, bug fixes 

---

src/components/PositionCard/index.js
src/contexts/Balances.tsx
src/contexts/Pairs.tsx
src/contexts/Routes.tsx
src/pages/Supply/AddLiquidity.tsx
src/pages/Supply/RemoveLiquidity.tsx

- Update pair hook 
- fix dependency arrays

Fix rerender bugs

---

src/components/AccountDetails/Copy.js
src/components/AccountDetails/Transaction.js
src/components/AccountDetails/index.js
src/components/AddressInputPanel/index.js
src/components/AdvancedSettings/index.js
src/components/Button/index.js
src/components/Card/index.js
src/components/ConfirmationModal/index.js
src/components/CurrencyInputPanel/index.js
src/components/ExchangePage/index.tsx
src/components/Footer/index.js
src/components/Header/index.js
src/components/Identicon/index.js
src/components/Menu/index.js
src/components/Modal/index.js
src/components/NavigationTabs/index.js
src/components/NumericalInput/index.tsx
src/components/OversizedPanel/index.js
src/components/Question/index.js
src/components/SearchModal/index.js
src/components/WalletModal/Option.js
src/components/WalletModal/PendingView.js
src/components/WalletModal/index.js
src/components/WarningCard/index.js
src/components/Web3ReactManager/index.js
src/components/Web3Status/index.js
src/pages/App.js
src/pages/Supply/RemoveLiquidity.tsx
src/theme/components.js
src/theme/index.js

- change theme colors to match design library in Figma
- remove unused declarations in theme 
- update radio buttons to sustain selected option

Radio button edits, theme updates

---

public/locales/en.json
src/components/AddressInputPanel/index.js
src/components/AdvancedSettings/index.js
src/components/Button/index.js
src/components/Card/index.js
src/components/ConfirmationModal/index.js
src/components/CurrencyInputPanel/index.js
src/components/ExchangePage/index.tsx
src/components/Header/index.js
src/components/Modal/index.js
src/components/NavigationTabs/index.js
src/components/PositionCard/index.js
src/components/SearchModal/index.js
src/components/TxnPopup/index.js
src/components/Web3Status/index.js
src/contexts/Pairs.tsx
src/contexts/Routes.tsx
src/contexts/Tokens.tsx
src/contexts/Transactions.js
src/pages/App.js
src/pages/Supply/AddLiquidity.tsx
src/pages/Supply/RemoveLiquidity.tsx
src/pages/Supply/index.js
src/theme/components.js
src/theme/index.js

- Update header UI with new connect button and pending state 
- Update approval errors to live on main button instead of currency input panel 
- Update supply -> pool 
- Update warning messages below and above main body 
- Update slippage copy and helper text 
- other small UI changes 
- Fix bug on route context - need to store Pair entities in Pairs store (causes bugs when used as a hook like before)

UI Updates, Route Context Updates

---

public/locales/en.json
src/constants/index.js
src/pages/Pool/AddLiquidity.js

- Disable adding for current exchanges with ERC-777 tokens

Disable adding for ERC-777 tokens

---

.github/ISSUE_TEMPLATE/token-request.md

Adds a warning to the GitHub issue template, to hopefully help curb losses like we saw over the weekend.

Adds warning about ERC-777 tokens and the like.

---

src/components/ExchangePage/index.jsx

- Allow only ETH to be selected as output
- closes #673

allow solo ETH output in query params

---

src/components/ExchangePage/index.jsx

- allow solo ETH output in query params 
- closes #673

allow solo ETH output in query params (#690)

---

src/contexts/Balances.tsx

- Fix to correctly pull address from WETH[chain] object when detecting old local storafe balance for token address 'ETH'

bug fix on local storage balance reference

---

package.json
src/components/BalanceCard/index.tsx
src/components/Button/index.js
src/components/Card/index.js
src/components/CurrencyInputPanel/index.js
src/components/ExchangePage/index.tsx
src/components/Header/index.js
src/components/Popups/index.js
src/components/Question/index.js
src/components/Slider/index.js
src/components/SlippageTabs/index.js
src/components/TxnPopup/index.js
src/contexts/Balances.tsx
src/pages/App.js
src/pages/Supply/AddLiquidity.tsx
src/pages/Supply/RemoveLiquidity.tsx
src/theme/index.js
yarn.lock

- setup basic funcitonality for adavanced mode and balances

add basic structure for advanced mode

---

src/components/ExchangePage/index.tsx
src/components/Slider/index.js
src/components/WalletModal/index.js
src/pages/Supply/AddLiquidity.tsx
src/pages/Supply/RemoveLiquidity.tsx

- multiple bug fixes (crashing max button)
- add back in slider 
- wallet modal auto close

add slider, big fixes

---

src/components/ExchangePage/index.tsx
src/components/Modal/index.tsx

- update params in modal component to stop warnings

fix DOM warnings

---

src/components/AccountDetails/index.tsx
src/components/AddressInputPanel/index.tsx
src/components/ExchangePage/index.tsx
src/components/Header/index.tsx
src/components/Menu/index.tsx
src/connectors/index.ts
src/constants/abis/v1_factory.json
src/constants/index.ts
src/data/Allowances.ts
src/data/Balances.ts
src/data/V1.ts
src/data/index.ts

to test this with metamask, you'll need to add `1` to the injected connector config

add v1 slippage checks (only for mainnet)

---

src/components/AccountDetails/Transaction.tsx
src/components/TxnPopup/index.tsx
src/components/Web3Status/index.tsx
src/state/transactions/actions.ts
src/state/transactions/hooks.tsx
src/state/transactions/reducer.ts
src/state/transactions/updater.tsx
src/state/wallet/hooks.ts

Improve the transaction render style

---

src/components/CurrencyInputPanel/index.tsx

- tokens with long symbol names block input
- set hard cap on symbol length and abbreciate long ones

set token length

---

src/components/SlippageTabs/index.tsx
src/components/swap/AdvancedSwapDetails.tsx

add route visualization

---

src/components/Menu/index.tsx

add a discord link, icons to menu

---

src/components/SearchModal/CommonBases.tsx
src/components/SearchModal/index.tsx
src/components/SearchModal/sorting.ts
src/constants/index.ts
src/data/Reserves.ts
src/hooks/Trades.ts
src/state/user/hooks.tsx

centralize all lists of bases
pin some pairs

introduce batched usePairs

---

package.json
src/components/ConfirmationModal/index.tsx
src/components/swap/SwapModalFooter.tsx
src/components/swap/SwapModalHeader.tsx
src/constants/index.ts
src/hooks/useSwapCallback.ts
src/pages/AddLiquidity/index.tsx
src/pages/RemoveLiquidity/index.tsx
src/pages/Send/index.tsx
src/pages/Swap/index.tsx
src/utils/index.ts
yarn.lock

support proposed new FoT-capable methods

---

src/hooks/useSwapCallback.ts
src/index.tsx

this is an alternative solution to hard coding forced FoT router tokens

if swap fails in FoT router but not in regular router, throw an error

---

src/components/WalletModal/WalletConnectData.tsx

add border to QR scanner

---

src/pages/AddLiquidity/index.tsx
src/pages/RemoveLiquidity/index.tsx

- add similar approve flow as swap to add and remove 
- move removal signature to main body and out of confirmation

improvement(add/remove liquidity): update approve flow on add + remove

---

src/pages/AddLiquidity/index.tsx
src/pages/RemoveLiquidity/index.tsx

clear signature on input in remove

fix approval bugs

---

src/components/swap/SwapModalFooter.tsx

change copy on confirm view

---

src/pages/AddLiquidity/index.tsx
src/state/mint/hooks.ts

fix(add liquidity): fix the mint hooks to return a price as well as return the dependent amount in the input currency

---

cypress/integration/token-warning.ts
package.json
src/components/TokenWarningCard/index.tsx
src/pages/AppBody.tsx
src/pages/Swap/index.tsx
src/state/user/hooks.tsx
src/theme/index.tsx
src/theme/styled.d.ts
yarn.lock

- more extreme warning UI for imported tokens

improvement(token warnings): show better warnings for imported tokens

---

src/components/Logo/index.tsx

- change the token icon to circle with quesion mark, current one is scary

improvement(styles): update token icon for warning

---

src/components/Popups/PopupItem.tsx

add right margin to mobile token list update notification lists

---

src/components/Popups/PopupItem.tsx

update token list update margin for even smaller mobile devices

---

src/pages/Vote/index.tsx

fix style of proposals text block in vote page

---

src/state/lists/updater.ts

fixes https://github.com/Uniswap/uniswap-interface/issues/1161

fix(token lists): stop showing notifications for lists that are not selected

---

src/pages/Vote/VotePage.tsx

fix(vote): make the vote page responsive

---

src/constants/index.ts
src/pages/Vote/VotePage.tsx

- update block duration average from 14s to 13s 
- update estimation method for proposal end

update vote timestamp estimation

---

src/pages/Vote/VotePage.tsx
src/pages/Vote/index.tsx

fix(typo): toggle

---

src/components/Header/index.tsx
src/components/Settings/index.tsx
src/constants/index.ts

- add wbtc to routing
- small style updates

improvement(routing): use WBTC pairs for routing swaps, style updates

---

src/components/Header/index.tsx

addresses #1298
We should get something in place to address browser style support systematically if we can.

fix a prominent safari css failure

---

src/components/swap/AdvancedSwapDetails.tsx

I wanted to get into the codebase and this seemed to be a straightforward change that was marked as a `p0`.

Update view pair analytics analytics link. Fix #1299.

---

src/state/claim/hooks.ts

fixes https://github.com/Uniswap/uniswap-interface/issues/1334

fix(merkle drop): make claim a post request

---

src/components/Settings/index.tsx
src/state/user/hooks.tsx

https://github.com/Uniswap/uniswap-interface/issues/1343
Move GA event from setSingleHopOnly hook to toggle function

Move single hop toggle GA event

---

src/connectors/index.ts

fixes  https://github.com/Uniswap/uniswap-interface/issues/1351

fix(walletlink): fix logo url

---

src/state/lists/hooks.ts
src/state/lists/updater.ts
tsconfig.json

- issues in list parsing are causing crashes on the app
- temporary fix

Hot fix for token error parsing

---

src/components/Header/Polling.tsx

I see the hovering behavior wasn't look like the codes trying to do, so I made some styling updates.
The screent shot below shows what it looks like

Update polling block number breathing behavior

---

src/components/earn/StakingModal.tsx
src/hooks/useERC20Permit.ts
src/pages/MigrateV2/MigrateV2Pair.tsx
src/pages/RemoveLiquidity/index.tsx
src/pages/Swap/index.tsx

try manual approve if erc712 doesn't work

---

package.json
yarn.lock

sdk bugfix bump

---

src/hooks/useV3PositionFees.ts
src/pages/Pool/PositionPage.tsx
src/state/burn/v3/hooks.ts

fix(collect): compute fees correctly

---

src/pages/Swap/index.tsx

Fixes #1496
- do not wrap button elements
- prevent currency border from shrinking

tweak element sizing/wraping in approve button

---

src/pages/App.tsx

lazy load uncommon routes to reduce initial bundle size

---

src/pages/App.tsx

Reverts Uniswap/uniswap-interface#1597
Causing flash. Need to add a suspense below the header nav.

Revert "lazy load uncommon routes to reduce initial bundle size"

---

src/components/SearchModal/ManageTokens.tsx

fix: handle custom token overflow

---

package.json
yarn.lock

fixes https://github.com/Uniswap/uniswap-interface/issues/1488

fix: working copy to clipboard button in walletconnect qr code modal

---

src/pages/AddLiquidity/index.tsx

fixes https://github.com/Uniswap/uniswap-interface/issues/1508

fix: do not crash when user switches eth -> weth in add

---

src/constants/misc.ts

fix: display pool shares < 10%

---

src/state/mint/hooks.ts

fix: handle insufficient input amount error in v2 add liquidity

---

src/hooks/useUSDCPrice.ts
src/hooks/useV2Trade.ts
src/state/swap/hooks.ts

will update v3 in a follow-up PR

fix: stabilize fiat value by fixing max hop and increasing USDC out to 100k

---

package.json
src/components/Identicon/index.tsx
src/react-app-env.d.ts
yarn.lock

fix: replace jazzicon to @metamask/jazzicon

---

src/state/mint/hooks.ts

fix: catch errors from Pair.getLiquidityMinted

---

src/components/Popups/ClaimPopup.tsx
src/state/claim/hooks.ts

fixes https://github.com/Uniswap/uniswap-interface/issues/1337

fix: improve privacy of the claim popup

---

.storybook/preview.tsx
public/index.html
src/components/ErrorBoundary/index.tsx
src/components/Modal/index.tsx
src/index.css
src/index.tsx
src/pages/App.tsx
src/theme/index.css
src/theme/index.tsx

fixes https://github.com/Uniswap/uniswap-interface/issues/1730 by triggering the fonts to load as soon as the html + css loads, which always beats the js in my testing

refactor: remove the fixed global style component

---

src/components/Badge/RangeBadge.tsx
src/pages/RemoveLiquidity/V3.tsx

chore: change `inactive` to `closed`

---

public/index.html

specifically when the google translate extension triggers it

fix: some instances of the removeChild issue

---

src/pages/MigrateV2/MigrateV2Pair.tsx

fix[migrate]: use proper slippage check

---

src/pages/Pool/PositionPage.tsx

Fix second part of issue #1834

fix: translate both text in PositionPage.tsx

---

src/pages/AddLiquidity/index.tsx
src/pages/AddLiquidityV2/PoolPriceBar.tsx
src/pages/RemoveLiquidity/V3.tsx
src/state/burn/v3/hooks.ts

fixed.
Please add a translation for "Enter a percent".

fix: untranslated parts

---

src/pages/Pool/v2.tsx

Fixed an error that was occurring in the development environment.

fix: props for ResponsiveButtonPrimary

---

cypress/support/commands.js

fix: test integration key change

---

src/pages/AddLiquidity/index.tsx
src/pages/AddLiquidityV2/index.tsx
src/pages/MigrateV2/index.tsx
src/pages/Pool/PositionPage.tsx
src/pages/Pool/v2.tsx
src/pages/PoolFinder/index.tsx

Added SwitchLocaleLink to pages that do not have a button to switch languages.

fix: Add SwitchLocaleLink to a page where it does not exist

---

src/components/NavigationTabs/index.tsx
src/pages/AddLiquidity/index.tsx

chore: small UX tweaks / bug fixes

---

src/state/multicall/actions.ts
src/state/multicall/hooks.ts
src/state/multicall/reducer.test.ts
src/state/multicall/reducer.ts

fixes https://github.com/Uniswap/uniswap-interface/issues/1877

fix: improve how we use blocks per fetch in the memoization of the listeners

---

package.json
yarn.lock

https://github.com/Uniswap/uniswap-interface/issues/1560

fix: error messages from walletconnect provider

---

src/pages/AddLiquidity/index.tsx
src/pages/Pool/CTACards.tsx

This resolves the small UX bug issue I opened, fixes https://github.com/Uniswap/uniswap-interface/issues/1991.

fix: #1991 - Updating two public-facing URLs to docs

---

src/pages/Pool/PositionPage.tsx

lower/upper were given in the wrong order to the hook

fix: min/max price inverted in positions page

---

src/pages/Earn/Manage.tsx

Fixes https://github.com/Uniswap/uniswap-interface/issues/1927

fix: add optional chaining for stakingInfo

---

src/components/LiquidityChartRangeInput/index.tsx

fix(2033): keep liquidity chart text center aligned on mobile

---

src/components/NetworkAlert/AddLiquidityNetworkAlert.tsx
src/components/NetworkAlert/MinimalNetworkAlert.tsx
src/components/NetworkAlert/NetworkAlert.tsx
src/components/OptimismDowntimeWarning/index.tsx
src/pages/AddLiquidity/index.tsx
src/pages/AddLiquidity/styled.tsx

fix(L2): add liquidity warning and network notification

---

src/components/Header/NetworkCard.tsx
src/components/Popups/index.tsx
src/components/TransactionConfirmationModal/index.tsx
src/pages/AddLiquidity/index.tsx
src/pages/Swap/index.tsx
src/state/transactions/hooks.tsx

- auto dismiss txn confirmation modal if on L2 and txn is confirmed on chain and modal still open 
- update styling on network selector (padding, popup padding)

fix: dismiss txn confirmation modal if on L2

---

src/pages/AddLiquidity/index.tsx
src/pages/AddLiquidity/styled.tsx
src/state/mint/v3/hooks.ts

- fixes #2028 
- disable create button unless tokens and starting price are selected 
- dont redirect to pool page after create txn 
- can test with ETH/DAI 1% on Optimistic Kovan Dai address: 0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1

fix: support for isolated pool creation 

---

src/components/LiquidityChartRangeInput/Chart.tsx
src/pages/AddLiquidity/index.tsx

Reverts Uniswap/uniswap-interface#2042

fix: revert remove x-axis clamping behavior in liquidity chart

---

src/state/swap/hooks.ts

fix: update balance check in derived swap state

---

src/components/TransactionSettings/index.tsx
src/state/user/hooks.tsx

fix(L2): set 5 min deadline on swaps and hide UI on L2

---

src/hooks/Tokens.ts
src/pages/AddLiquidity/index.tsx

fixes https://github.com/Uniswap/uniswap-interface/issues/1763

fix: prevent error if user selects ETH and WETH in add liquidity

---

package.json
yarn.lock

this should help with failed connections

fix: upgrade walletconnect to 1.5.1

---

src/components/OptimismDowntimeWarning/index.tsx

fix(L2): update downtime warning copy

---

src/components/NetworkAlert/AddLiquidityNetworkAlert.tsx
src/components/NetworkAlert/MinimalNetworkAlert.tsx
src/components/NetworkAlert/NetworkAlert.tsx
src/components/NetworkAlert/styles.ts

fix(L2): add link to read more about Optimism 

---

package.json
yarn.lock

fixes https://github.com/Uniswap/uniswap-interface/issues/2115

fix: upgrade ethers to allow constructing transaction data compatible with eip-1559

---

src/components/NavigationTabs/index.tsx

fix: center import pool text V2 

---

package.json
yarn.lock

chore: upgrade to walletconnect 1.5.2

---

src/utils/isTradeBetter.ts

fixes https://github.com/Uniswap/uniswap-interface/issues/2149

fix: `#isTradeBetter` should check that output currencies are equal

---

src/components/Settings/index.tsx
src/hooks/useAllV3Routes.ts
src/pages/Swap/index.tsx
src/state/swap/hooks.ts
src/state/user/actions.ts
src/state/user/hooks.tsx
src/state/user/reducer.ts

new routing api does not support single hop

fix: removed single hop setting

---

package.json

This seems to be integrated into styled-components.

chore: rm unused styled-system

---

.env
package.json
src/connectors/index.ts
yarn.lock

fixes https://github.com/Uniswap/uniswap-interface/issues/2238

fix: walletconnect on L2 issues with Rainbow

---

src/hooks/Tokens.ts
src/state/lists/reducer.ts
tsconfig.json
yarn.lock

Upgrade types, typescript, and formatters.

chore: upgrade type system

---

package.json
src/hooks/useAllCurrencyCombinations.ts
src/state/user/hooks.tsx
yarn.lock

chore: use native flatMap

---

src/constants/misc.ts
src/state/application/hooks.ts
src/state/application/reducer.ts
src/state/transactions/updater.tsx

- reduce popup dismiss time to 5s on l2

feat: reduce popup dismiss time on l2

---

src/hooks/useApproveCallback.ts
src/pages/Swap/index.tsx

will be useful once we launch routing to track an increase in approvals

chore: start tracking approvals in ReactGA

---

src/pages/AddLiquidity/index.tsx

Fixed upper case to lower case to be consistent with src/components/SearchModal/ImportList.tsx

fix: letter case consistency

---

src/components/earn/ClaimRewardModal.tsx
src/pages/AddLiquidity/index.tsx

Fixed lower case to upper case to be consistent with:
src/pages/AddLiquidityV2/index.tsx
src/pages/RemoveLiquidity/index.tsx
src/pages/Swap/index.tsx
src/state/burn/hooks.ts
src/state/burn/v3/hooks.ts
src/state/mint/hooks.ts
src/state/mint/v3/hooks.ts
src/state/stake/hooks.ts
src/state/swap/hooks.ts

style: Fix letter case consistency

---

src/state/governance/hooks.ts

fix: avoid replaceAll

---

src/components/Header/ChainConnectivityWarning.tsx
src/components/Header/Polling.tsx
src/constants/chains.ts
src/state/application/actions.ts
src/state/application/reducer.ts
src/state/application/updater.ts

feat(chain-connectivity): warn when the user is not receiving blocks

---

public/index.html

i know the user scalable doesn't work on iOS anymore, but maybe it's nice for android

fix: improve the meta tags

---

.gitignore
package.json
src/constants/locales.ts
src/i18n.tsx
yarn.lock

Effectively renders the page with one less network request in the default case.

perf(i18n): bundle default locale with main chunk

---

yarn.lock

Saves 20kb of gzipped payload.

chore: dedup @ethersproject

---

src/components/LiquidityChartRangeInput/Brush.tsx

fix: infinite loop when brushing

---

src/components/CurrencyLogo/index.tsx
src/components/SearchModal/CommonBases.tsx
src/constants/routing.ts
src/constants/tokens.ts

These common bases are now available on L2 networks. The tokens don't have assets in the trustwallet repo though, so images won't show up until that data is populated.

fix(L2): add common bases to L2s

---

src/components/analytics/GoogleAnalyticsReporter.tsx

adds a custom dimension to ga tracking w/ current chainId

fix: set custom dimension on chainId change

---

src/state/swap/hooks.ts

closes #2444
introduced https://github.com/Uniswap/interface/commit/cc9650b74b832740f0c04c582b7478c154186ff7#diff-318f71979bcd6f187ed8cea8e5ea499dacbcbc6cbd547d314cd7c295a860d9d3L161

fix: force v3 when use=v3

---

src/components/analytics/GoogleAnalyticsReporter.tsx
src/pages/AddLiquidity/index.tsx

fix: quick fix for broken token select on add

---

src/pages/AddLiquidityV2/index.tsx

- fixes #2470 
- proper fix described here in #2455

fix: hot fix for v2 token select bug

---

src/components/WalletModal/index.tsx

This change fixes Uniswap/interface#2692

fix: walletconnect modal reopen after user rejection

---

src/components/SearchModal/CurrencySearchModal.tsx
src/state/lists/hooks.ts

before this fix, clicking a token in the list would just sometimes not work because the list re-renders constantly
fixes https://github.com/Uniswap/interface/issues/2686

fix: memoize the list stuff so the tokens are consistently clickable

---

src/pages/AppBody.tsx

fix: increase liquidity form off center

---

src/constants/chains.ts

optimism team deprecated this URL

fix: remove deprecated optimism status url

---

src/state/application/updater.ts

prior code was assuming that the most recent block was received when the component mounted :|

fix(L2): update block warning updater to check most recent block timestamp

---

src/hooks/useAllCurrencyCombinations.ts

chore: fix typo in useAllCurrencyCombinations.ts

---

src/constants/chains.ts
src/hooks/Tokens.ts
src/hooks/useIsSwapUnsupported.ts

uses this pattern: https://github.com/Uniswap/token-lists/issues/51
see also: https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/35/files

fix(L2): block L2 tokens explicitly linked to L1 tokens that are blocked

---

src/state/application/updater.ts

check for support on all connectors, and disable when the connector (or lack thereof) no longer supports 3085

fix(L2): better eip 3085 support

---

src/constants/locales.ts

update Finnish from person (Suomalainen) to language (suomi)

fix: Update locales.ts. Finnish language to a correct one

---

src/components/ErrorBoundary/index.tsx

fixes https://github.com/Uniswap/interface/issues/2572

fix: do not show urls if issue is not occurring on app.uniswap.org

---

src/state/wallet/hooks.ts

fix: give more gas to balanceOf

---

src/components/SearchModal/Manage.tsx
src/components/SearchModal/ManageLists.tsx

fixes https://github.com/Uniswap/interface/issues/1945

fix: double scroll in manage token list

---

src/components/Button/index.tsx
src/components/Header/NetworkSelector.tsx
src/components/Header/index.tsx
src/components/Menu/index.tsx
src/components/NetworkAlert/NetworkAlert.tsx
src/components/PositionList/index.tsx
src/components/SearchModal/CommonBases.tsx
src/components/Web3Status/index.tsx
src/pages/AddLiquidity/index.tsx
src/pages/Pool/CTACards.tsx
src/pages/Pool/index.tsx
src/pages/Swap/index.tsx
src/state/user/actions.ts
src/state/user/hooks.tsx
src/state/user/reducer.ts

Re-styles the bridge card to be more minimal and persistent. Also removes downtime warnings as they are no longer necessary.

fix(style): improve the bridge assets style

---

src/components/Web3Status/index.tsx
src/hooks/useENSName.ts

Issue #2838
Note that I don't know TypeScript and frontend. In my tests (just printing `console.log`s), what I did here seems to work, but I have no idea if this is acceptable code or not... Someone should please review this. Thanks.

fix: Add ENSName and address check to Web3Status

---

src/constants/tokenLists/unsupported.tokenlist.json

- Add 0xa82AA729AE2F0d78e961D66db53949e27a9E866d to unsupported token list

fix: update unsupported list

---

package.json
src/lib/components/Web3Provider.tsx
src/lib/hooks/useActiveWeb3React.ts
src/lib/state/web3.ts
yarn.lock

bringing this one into main from limbo
* add empty connector
add url connector
* naming

fix: web3-react-fixes (#3066)

---

src/hooks/useENSAvatar.ts

fix: Add `{id}` replacement for ERC-1155

---

src/connectors/index.ts

fix(L2): add polygon to supported walletlink chainIds

---

src/components/WalletModal/index.tsx

fixes https://github.com/Uniswap/interface/issues/2740

fix: Update wrong network message

---

package.json
yarn.lock

https://twitter.com/waynebrodoteth/status/1480974513106001922

chore(deps): bump walletconnect

---

package.json
yarn.lock

Fixes #3060 for client side sor

chore: bump sor to 2.5.10

---

src/lib/components/Error/ErrorGenerator.tsx
src/lib/components/Swap/Toolbar.tsx
src/lib/errors.ts

shows the "wrong chain" message instead of throwing an error on incorrect chain connection

feat(widgets): incorrect chain message

---

src/lib/components/Swap/Input.tsx
src/lib/components/Swap/Output.tsx
src/lib/components/Swap/Summary/Summary.tsx
src/lib/components/Swap/Summary/index.tsx
src/lib/components/Swap/SwapButton.tsx
src/lib/components/Swap/Toolbar.tsx
src/lib/hooks/useTransactionDeadline.ts
src/lib/state/settings.ts

- fixes https://www.notion.so/uniswaplabs/dcde9145238445b4bfd5436a3c5d813d?v=be065901c104466c9dfb0f948accb2fd&p=4f3710105c14469ca9490fb481be04c5
- fixes https://www.notion.so/uniswaplabs/dcde9145238445b4bfd5436a3c5d813d?v=be065901c104466c9dfb0f948accb2fd&p=b78599c919a34d71918acd546674456e

feat: format usd prices, add loading states

---

src/lib/components/Popover.tsx
src/lib/components/Swap/Settings/MaxSlippageSelect.tsx
src/lib/components/Swap/Settings/TransactionTtlInput.tsx
src/lib/components/Swap/Settings/components.tsx
src/lib/components/Swap/Summary/Details.tsx
src/lib/components/Swap/Summary/index.tsx
src/lib/components/Tooltip.tsx
src/lib/hooks/useTransactionDeadline.ts
src/lib/icons/index.tsx
src/lib/state/settings.ts

feat: slippage warning ux

---

src/lib/components/Swap/Summary/Summary.tsx
src/lib/components/Swap/Toolbar.tsx

- fixes [this](https://www.notion.so/uniswaplabs/dcde9145238445b4bfd5436a3c5d813d?v=be065901c104466c9dfb0f948accb2fd&p=c355b8be03db481ab82278ad903207b8) - % broken on swap summary 
- fixes untracked bug on incorrect rate showing on swap page (rate not inverting on rate click)

fix: fix pricing displays

---

src/lib/components/Swap/Summary/Details.tsx
src/lib/components/Swap/Summary/index.tsx
src/lib/components/Swap/Toolbar/Caption.tsx
src/lib/components/Swap/Toolbar/RoutingTooltip.tsx
src/lib/components/Swap/Toolbar/index.tsx
src/utils/prices.ts

feat: ux warnings

---

src/lib/components/ActionButton.tsx
src/lib/components/TokenSelect/TokenButton.tsx
src/lib/theme/index.tsx
src/lib/theme/theme.ts

fix(widgets): white accentText color on some buttons

---

src/lib/components/Swap/Toolbar/Caption.tsx

fix(widgets): remove extra } in Trade caption

---

src/components/analytics/GoogleAnalyticsReporter.tsx
src/components/analytics/index.ts

fixes https://github.com/Uniswap/interface/issues/3204

feat: track google analytics clientIds

---

src/lib/theme/index.tsx

- uses named colors where appropriate (brand, white, black)
- fixes typo in dark theme accent color
- hardcodes dark theme onAccent color

fix: theme colors

---

src/lib/components/TokenSelect.fixture.tsx
src/lib/components/TokenSelect/TokenOptions.tsx
src/lib/hooks/useNativeEvent.ts
src/lib/hooks/useScrollbar.ts

- Unifies TokenSelect handling of inputs (tabs, arrows, mouse)
- Fixes a visual bug caused by lagging useNativeEvent due to non-memoized args

fix: token select input handling

---

src/lib/components/Swap/index.tsx
src/lib/components/TokenSelect.fixture.tsx
src/lib/components/TokenSelect/TokenOptions.tsx
src/lib/components/TokenSelect/TokenOptionsSkeleton.tsx
src/lib/components/TokenSelect/index.tsx
src/lib/hooks/useTokenList/index.ts

- Improves token list fetching logic in stale cases
- Prefetches token balances for TokenSelect
- Adds a skeleton loader for TokenSelect
- Adds a block period (1500ms) to the TokenSelect options render to allow balances to load

fix: token select ux

---

src/lib/theme/index.tsx

fix: import fonts through sass only

---

package.json
src/lib/components/Swap/Input.tsx
src/lib/components/Swap/TokenInput.tsx
src/lib/cosmos/components/Widget.tsx
yarn.lock

- Adds walletconnect to cosmos so that a provider is available for testing in Safari (WebKit)
- Fixes max input selection, which was cut off by precedence of the blur event

fix: max on WebKit

---

src/lib/components/Error/ErrorDialog.tsx

- Fixes jumping text from the scrollbar rendering during expansion.
- Fixes transitions for the header icon during expansion.

fix: error dialog transition

---

src/lib/components/TokenSelect/TokenOptions.tsx
src/lib/hooks/useBlockNumber.ts

- Fixes token balance UI to avoid horizontal overflow
- Fixes useBlock to avoid clearing the block number on window visibility change
- This prevents re-fetching still valid data

fix: token balance reloading

---

src/constants/governance.ts
src/pages/CreateProposal/index.tsx
src/pages/Vote/VotePage.tsx
src/state/governance/hooks.ts

- shows ` / QUORUM` after the For vote totals for all proposals against the current governor
- fixes the For/Against percentage bar logic
- makes vote totals currency amounts

fix: Improve Vote page

---

src/lib/components/Widget.tsx
src/lib/theme/index.tsx
src/lib/theme/theme.ts

Updates the font family type and logic so that overriding the font family will also override the variable font family.

fix: font family overrides

---

src/lib/hooks/swap/useSwapInfo.tsx

Destructures the call to useCurrencyBalances. As all currency balances come in, this object will be updated with every balance - however, the destructured balances are referentially stable. Destructuring in this way prevents extra renders, which is important because useComputeSwapInfo is expensive to run, and the re-renders were multiplying that cost.
Rearranges the hook by "theme", but does not change any other logic.

fix: destructure currencies for ref equality

---

src/lib/hooks/useTokenList/index.ts

Avoids refetching an already-fetched token list

fix: token list fetching performance

---

src/pages/Vote/VotePage.tsx

https://app.uniswap.org/#/vote/2/12
proposals without votes are currently crashing the app

fix(vote): allow 0-vote proposals to render

---

src/lib/hooks/routing/useClientSideSmartOrderRouterTrade.ts

Fixes https://www.notion.so/uniswaplabs/Display-thrashing-with-route-data-3ea2ae65beb044e88b3bdce6a61e937c
(May need to be in conjunction with https://github.com/Uniswap/interface/pull/3539).

fix: only debounce input amounts

---

src/lib/components/Swap/Summary/index.tsx

fix: update code formatting for prettier

---

src/hooks/useERC20Permit.ts

Reverts Uniswap/interface#3580

revert: "fix: retain permit validity for lesser amounts"

---

src/lib/hooks/useActiveWeb3React.tsx

This should be backed out once it is fixed upstream.

fix: walletconnect numeric chain id

---

src/hooks/useAutoSlippageTolerance.ts
src/hooks/useUSDCPrice.ts
src/lib/components/Swap/index.tsx
src/lib/hooks/swap/useSwapInfo.tsx
src/lib/hooks/useBlockNumber.ts
src/lib/state/multicall.tsx

- Simplifies block and swap info updaters
- Fixes block updater to not return another chain's block number
- Support chains with no token list (eg to show a balance)
- Gate unnecessary RPCs called by swap info updater

fix: stale data edge cases

---

src/hooks/useColor.ts
src/lib/components/Swap/index.tsx
src/lib/components/Widget.tsx
src/lib/hooks/swap/useSyncTokenDefaults.ts
src/lib/hooks/useCurrencyColor.ts

- Defers layout effects, which otherwise display a warning on nextjs
- Defers token sync until a token list is available, so that it can have an effect

fix: defer layout effects

---

src/hooks/useAutoSlippageTolerance.ts
src/hooks/useUSDCPrice.ts
src/lib/components/TokenImg.tsx
src/lib/hooks/swap/useBestTrade.ts
src/lib/hooks/swap/useSwapInfo.tsx
src/lib/hooks/useSlippage.ts

- Prevents re-rendering of swap info when no values have actually changed

fix: update hook deps to improve ref equality checks

---

src/lib/components/Swap/Toolbar/Caption.tsx
src/lib/components/Swap/Toolbar/index.tsx
src/lib/components/Swap/index.tsx
src/lib/hooks/useActiveWeb3React.tsx

Displays "Connecting" in the toolbar.
https://user-images.githubusercontent.com/5403956/163024388-f2c9053d-f0fe-4cad-92e1-8d2272152fbe.mov
_NB: The copy was been changed to "Connecting..." after this screencap was made._

feat: display connecting state

---

src/components/AccountDetails/Copy.tsx
src/components/ConnectedAccountBlocked/index.tsx
src/components/TopLevelModals/index.tsx
src/hooks/useAccountRiskCheck.ts
src/pages/App.tsx
src/state/application/reducer.ts
src/state/user/updater.tsx

block addresses from using the hosted interface if their risk value surpasses a threshold

feat(compliance): risk screening

---

src/components/WalletModal/index.tsx

Removes links to API usage and wallet information from the wallet connect modal
Moves ToS text to the bottom of the card

feat: changes wallet connect terms of service layout

---

src/components/PrivacyPolicy/index.tsx
src/components/WalletModal/PendingView.tsx

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), and should start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):
- build: Changes that affect the build system or external dependencies (example scopes: yarn, eslint, typescript)
- ci: Changes to our CI configuration files and scripts (example scopes: vercel, github, cypress)
- docs: Documentation only changes
- feat: A new feature
- fix: A bug fix
- perf: A code change that improves performance
- refactor: A code change that neither fixes a bug nor adds a feature
- style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- test: Adding missing tests or correcting existing …

style: standardize fonts

---

src/components/WalletModal/index.tsx

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), and should start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):
- build: Changes that affect the build system or external dependencies (example scopes: yarn, eslint, typescript)
- ci: Changes to our CI configuration files and scripts (example scopes: vercel, github, cypress)
- docs: Documentation only changes
- feat: A new feature
- fix: A bug fix
- perf: A code change that improves performance
- refactor: A code change that neither fixes a bug nor adds a feature
- style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- test: Adding missing tests or correcting existing …

docs: remove unnecessary WalletModal comment

---

src/components/Header/NetworkSelector.tsx

fix: center NetworkSelector circles

---

src/state/routing/useRoutingAPITrade.ts

The logic for understanding otherAmount is confusing with nested ternaries, so I wrote it out more verbosely

style: simplify otherAmount calculation

---

src/components/SearchModal/CommonBases.tsx
src/components/SearchModal/CurrencyList/__snapshots__/index.test.tsx.snap
src/components/SearchModal/CurrencyList/index.tsx
src/components/SearchModal/ImportRow.tsx

Make token selector accessible via keyboard navigation to resolve https://github.com/Uniswap/interface/issues/3865
https://user-images.githubusercontent.com/41491154/172245742-3685a03b-8a25-487b-afeb-9e6a1c310596.mp4

fix: add keyboard accessibility to token selector

---

.github/workflows/crowdin-sync.yaml
.github/workflows/crowdin.yaml
.github/workflows/lint.yml
.github/workflows/release.yaml
.github/workflows/tests-e2e.yaml
.github/workflows/tests-unit.yaml
.gitignore

- Parallelizes cypress CI runs
- Cleans up CI workflow files
- Aggressively cache node_modules to improve _all_ build times

build: optimize github actions

---

src/components/Web3Provider/index.tsx

Eager connection for MetaMask connector hangs in web3-react. I will fix it in there later, but for now we special case to activate if we know we're in MetaMask's browser.

feat: fix metamask mobile browser connection

---

src/components/Explore/TokenRow.tsx
src/components/Explore/TokenTable.tsx

added mobile responsiveness break point for token table

fix: add mobile responsiveness break point

---

src/components/Explore/TokenRow.tsx

feat: add mobile view responsiveness stacking token name and symbol

feat: stack token name and symbol (mobile view)

---

src/components/Explore/TokenRow.tsx
src/components/Explore/TokenTable.tsx

feat: add loading state for token table when data is still being fetched

feat: add token table loading state

---

src/components/Explore/FavoriteButton.tsx
src/components/Explore/TimeSelector.tsx
src/pages/Explore/index.tsx

Add favorites button frontend component and filters row container on Explore page (will contain favorites button, time selector, search bar, and network filter)

feat: add favorites button frontend component

---

src/components/Explore/TokenRow.tsx

fixed sizing and padding of percent change arrow on token row

fix: small arrow sizing detail

---

src/components/Explore/FavoriteButton.tsx
src/components/Explore/TimeSelector.tsx
src/components/Explore/TokenRow.tsx
src/components/Explore/TokenTable.tsx
src/pages/Explore/index.tsx

Filter favorite tokens by pressing the favorite button & ability to add/remove favorite tokens

feat: filter favorite tokens

---

src/components/CurrencyInputPanel/index.tsx

fix: fiat row fix so button doesn't jump on swap

fix: token button jump

---

src/components/Explore/TokenRow.tsx
src/components/Explore/constants.ts

remove swap button and fix responsiveness since swap button is removed
Todo: center and fix SVG

feat: remove swap button

---

src/components/Explore/TokenDetail.tsx

fix: token details color fix

---

.github/workflows/release.yaml

- Re-enables auto-release M-Th
- Conditions release on a successful test suite

build: enable auto-release

---

src/pages/Vote/VotePage.tsx

- Fix missing white space in blurb

fix: Fix spacing type

---

src/components/Explore/FavoriteButton.tsx
src/components/Explore/TokenDetail.tsx
src/components/Explore/TokenRow.tsx
src/components/Explore/TokenTable.tsx
src/components/Explore/state.ts
src/components/Header/NetworkSelector.tsx
src/pages/Explore/index.tsx
src/theme/index.tsx
src/theme/styled.d.ts

insert token table hover states and favorite button active state styling

feat: header hover states and favorite active state styling

---

yarn.lock

Update the active browserslists.

build: update caniuse-lite

---

src/components/FeeSelector/shared.tsx

compare to https://github.com/Uniswap/interface/pull/3724/files, the polygon version of this pr

feat: enable 1bp optimism fee tier

---

src/components/RoutingDiagram/__snapshots__/RoutingDiagram.test.tsx.snap
src/components/SearchModal/CurrencyList/__snapshots__/index.test.tsx.snap
src/lib/state/multicall.tsx
yarn.lock

fix https://github.com/Uniswap/interface/issues/4114

fix: increase celo blocksPerFetch to 5 to improve interface performance

---

src/components/Header/NetworkSelector.tsx

Fixes https://github.com/Uniswap/interface/issues/4133

fix: don't toggle desktop NetworkSelector on click

---

src/pages/App.tsx

In the last pull request https://github.com/Uniswap/interface/pull/4121, we've refactor the code to access router data like `location` etc. with hooks, so there's no need to wrap components in a `Route`.

refactor: clean floating Route

---

src/components/Explore/NetworkFilter.tsx
src/components/Explore/SearchBar.tsx
src/pages/Explore/index.tsx

Searchbar goes to newline on smaller width

fix: search responsiveness and expand state

---

.vscode/settings.json
src/components/Explore/TokenTable/FavoriteButton.tsx
src/components/Explore/TokenTable/NetworkFilter.tsx
src/components/Explore/TokenTable/SearchBar.tsx
src/components/Explore/TokenTable/TimeSelector.tsx
src/components/Explore/TokenTable/TokenRow.tsx
src/theme/index.tsx
src/theme/styled.d.ts

color / style changes based on new designs for Explore page

fix: Explore color changes

---

src/constants/tokenLists/unsupported.tokenlist.json

Updates the unsupported token list with 7 new tokens.

feat: update unsupported token list

---

src/components/Explore/TokenTable/TokenRow.tsx

Needed because of React Router upgrade!

fix: use absolute path for TokenRow Link

---

src/components/Header/index.tsx
src/pages/App.tsx

Moves explore under the phase0 flag

feat: feature flag for explore

---

src/featureFlag/index.tsx

This is until we actually set up amplitude! Tomorrow I will make it also be the case for Vercel.

build: default enabled flag on local

---

package.json
src/components/Charts/PriceChart.tsx
src/components/Explore/TokenDetails/LoadingTokenDetail.tsx
src/components/Explore/TokenDetails/TokenDetail.tsx
yarn.lock

Moved the token price & delta percentage from the tokendetails component into the price chart component & overlayed them onto the chart svg so that crosshair will appear when hovering over the whitespace above the chart

refactor: moved token detail price into chart

---

src/theme/index.tsx
src/theme/styled.d.ts

fix theme color files from merge

fix: update theme color files on explore

---

src/theme/index.tsx
src/theme/styled.d.ts

fix: theme add hover state and flyout colors

fix: theme add hover state and flyout colors

---

src/components/Explore/TokenTable/TokenTable.tsx
src/pages/App.tsx
src/theme/components.tsx

About to add the widget--this lazy loads the token-details page

feat(token-details): lazy load some heavy stuff

---

src/components/AmplitudeAnalytics/constants.ts
src/pages/App.tsx
src/state/user/hooks.tsx

requested by @willhennessy to start logging expert mode in user model.

feat: log is expert mode in amplitude user model

---

src/components/SearchModal/CurrencyList/__snapshots__/index.test.tsx.snap

test: update snapshots based on color change

---

src/components/FeatureFlagModal/FeatureFlagModal.tsx
src/components/Menu/index.tsx
src/featureFlags/index.tsx
src/state/application/hooks.ts
src/state/application/reducer.ts

feat: add feature flag modal in local/staging environments
Hamburger screen (only shows locally/staging): 
Feature Flag modal (only shows locally/staging):

feat: add feature flag modal in local/staging environments

---

src/components/Menu/index.tsx

fix feature flagging for staging name env

fix: fix feature flag for staging env

---

src/components/AmplitudeAnalytics/constants.ts
src/components/WalletModal/index.tsx

remove O(n) properties so user properties are O(1)

feat: remove unnecessary user properties

---

src/components/SearchModal/CurrencyList/__snapshots__/index.test.tsx.snap
src/components/SearchModal/CurrencyList/index.tsx

Token safety Icons will now only appear when feature flags are enabled

fix: token safety icon not under phase0 flag

---

src/components/FeatureFlagModal/FeatureFlagModal.tsx
src/featureFlags/flags/phase1.ts
src/featureFlags/index.tsx

feat: Phase 1 flag

---

src/components/SearchModal/CurrencyList/__snapshots__/index.test.tsx.snap
src/components/SearchModal/CurrencyList/index.tsx

Fixed token labels in token selector being out of place after recent changes

fix: token selector spacing

---

src/components/Charts/LineChart.tsx
src/components/Charts/PriceChart.tsx
src/components/Charts/SparklineChart.tsx
src/components/Explore/TokenDetails/ShareButton.tsx
src/components/Explore/TokenTable/TokenRow.tsx

replaced static svg with sparkline chart component. Abstracted linechart out of pricechart, so that sparklinechart & pricechart can use same line

feat: added token sparklines to explore page

---

src/components/AccountDetails/index.tsx

Simplied logic for displaying ENS name instead of wallet address

refactor: removing duplicate AccountDetails code

---

src/components/Charts/PriceChart.tsx

fix naming in price chart to be correct (timePeriod)

fix: fix naming in pricechart

---

package.json
yarn.lock

Removes this dep until we decide which feature flag vendor to actually implement.

chore: remove @amplitude/experiment-js-client

---

src/constants/governance.ts
src/state/governance/hooks.ts

fixes the formatting of calls for https://app.uniswap.org/#/vote/2/24?chain=mainnet
function sigs from https://sig.eth.samczsun.com/
franchiser factory address from https://github.com/NoahZinsmeister/franchiser/releases/tag/v1

fix: improve calldata formatting

---

src/components/AmplitudeAnalytics/index.ts

feat: fail gracefully when amplitude api key is not present

---

src/components/Header/NetworkSelector.tsx

fix: await selectChain before closing modal

---

src/components/Header/NetworkSelector.tsx
src/pages/App.tsx

refactor: move useSyncChainQuery to NetworkSelector

---

src/components/FeatureFlagModal/FeatureFlagModal.tsx
src/featureFlags/flags/navBar.ts
src/featureFlags/index.tsx

Add navBar feature flag and a small update to the style of the Feature Flag modal.

feat: add navbar feature flag and small style update

---

package.json
src/components/AmplitudeAnalytics/index.ts
yarn.lock

get rid of console error by updating to latest v

chore: update amplitude version

---

src/pages/TokenDetails/index.tsx
src/theme/token-details-widget-theme.ts
src/utils/token-details-widget-config.ts

feat(widget): light and dark themes

---

src/components/NavBar/Navbar.css.ts
src/components/NavBar/Navbar.tsx
src/components/NavBar/index.ts
src/pages/App.tsx

Adds a placeholder file onto which to build the phase 0 navbar and toggles it using the navbar feature flag

feat: add a feature flagged blank navbar

---

src/nft/pages/collection/index.tsx
src/pages/App.tsx

Adds a placeholder file onto which to build the phase 1 collection page and toggles it using the phase1 feature flag

feat: add a feature flagged blank collections page

---

src/components/AmplitudeAnalytics/constants.ts
src/components/Header/index.tsx
src/pages/App.tsx
src/pages/Explore/index.tsx

Switches token explore to /tokens and changes the nav item.

fix: rename /explore to /tokens

---

src/components/Explore/TokenDetails/LoadingTokenDetail.tsx

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), and should start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):
- build: Changes that affect the build system or external dependencies (example scopes: yarn, eslint, typescript)
- ci: Changes to our CI configuration files and scripts (example scopes: vercel, github, cypress)
- docs: Documentation only changes
- feat: A new feature
- fix: A bug fix
- perf: A code change that improves performance
- refactor: A code change that neither fixes a bug nor adds a feature
- style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- test: Adding missing tests or correcting existing …

chore: Usetheme hook fix

---

src/components/Button/index.tsx
src/components/Loader/index.tsx
src/components/Modal/index.tsx
src/components/WalletModal/Option.tsx
src/components/WalletModal/PendingView.tsx
src/components/WalletModal/index.tsx
src/theme/colors.ts
src/theme/index.tsx
src/theme/styled.d.ts

feat: wallet connect redesign

---

src/components/Tokens/TokenTable/TokenRow.tsx

jira: https://uniswaplabs.atlassian.net/browse/WEB-780?atlOrigin=eyJpIjoiNThlZGZiM2FjOWEwNDM3MTlkMjk2ODIxZDdhMjM5YjEiLCJwIjoiaiJ9

feat: fix favorite tokens design

---

src/pages/Pool/PositionPage.tsx
src/pages/Pool/index.tsx
src/pages/Tokens/index.tsx
src/theme/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-677?atlOrigin=eyJpIjoiMWY4MjgwMTg1NjUxNDQ4MTg1ODI3M2QwNjY5OWRiY2UiLCJwIjoiaiJ9

feat: fix explore and pools titles to match designs. 

---

src/pages/App.tsx

https://uniswaplabs.atlassian.net/browse/WEB-785?atlOrigin=eyJpIjoiMTNmYmZjNjU2YjQ2NGJkMGJhZWI4NGFlODUyMGU3NWQiLCJwIjoiaiJ9

feat: fix padding

---

src/components/TokenSafety/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-772?atlOrigin=eyJpIjoiNGFhOTRhYmE2NTYwNDM5MTlhZWE3NWNiYTVlMjhmZWYiLCJwIjoiaiJ9

feat: Safety label speedbump: fix copy

---

src/components/Tokens/TokenTable/TokenRow.tsx

move favorites to the right and fix no header highlight on hover

fix: move favorites to right and fix header highlight

---

src/pages/Vote/Landing.tsx

https://uniswaplabs.atlassian.net/browse/WEB-681?atlOrigin=eyJpIjoiMTY4OThiMWRkMDA4NGViYjlmMGFmN2QyMjE3NTdlOWUiLCJwIjoiaiJ9

feat: fix hover color on vote page items

---

src/components/NavBar/MobileSidebar.tsx
src/components/NavBar/Navbar.tsx

- add tab to `/nfts` in mobile and desktop navbar

feat: add NFTs tab to navbar

---

src/components/NavBar/SearchBar.css.ts
src/components/NavBar/SuggestionRow.tsx

Fixes unintentional flicker when mouse out on skeleton loading state

fix: fix skeleton hover state bug

---

src/components/CurrencyInputPanel/index.tsx

fix: fix add liquidity select tokens alignment

---

src/components/FeatureFlagModal/FeatureFlagModal.tsx
src/components/NavBar/MobileSidebar.tsx
src/components/NavBar/Navbar.tsx
src/featureFlags/flags/nft.ts
src/featureFlags/flags/phase1.ts
src/featureFlags/index.tsx
src/pages/App.tsx

-rename phase1flag to nftflag
- I specifically did not pluralize to `nfts` in this case as the capitalization gets tricky for an acronym so this was the most straightforward

refactor: rename phase1flag to nftflag

---

src/components/NavBar/SearchBar.tsx
src/components/NavBar/SuggestionRow.tsx

enable NFT collection search results when feature flag is enabled

feat: enable NFT search results

---

src/graphql/data/TokenPriceQuery.ts
src/graphql/data/schema.graphql

Fetched updated schema as requests were failing

fix: updated schema

---

src/components/Tokens/TokenDetails/PriceChart.tsx
src/components/Tokens/TokenDetails/TokenDetail.tsx
src/components/Tokens/TokenTable/TokenRow.tsx
src/graphql/data/TokenDetailQuery.ts
src/graphql/data/TokenRowQuery.ts
src/utils/formatDollarAmt.tsx

add token details query and token row query
** will change token row to be 1 request for top tokens in separate PR

feat: add token details and token row table query

---

src/components/Tokens/TokenDetails/ShareButton.tsx
src/components/Tokens/TokenTable/NetworkFilter.tsx
src/components/Tokens/TokenTable/TimeSelector.tsx
src/theme/colors.ts
src/theme/index.tsx
src/theme/styled.d.ts

update flyout drop shallow and deep shadow based on Uniswap theme - https://uniswaplabs.atlassian.net/browse/WEB-680
before:
After:

refactor: removes flyoutDropShadow, adds shallowShadow

---

src/components/FeatureFlagModal/FeatureFlagModal.tsx
src/featureFlags/flags/tokensNetworkFilter.ts
src/featureFlags/index.tsx
src/pages/Tokens/index.tsx

Flag the network filter until the API supports L2s

fix: flag NetworkFilter

---

package.json
patches/@vanilla-extract+css+1.7.2.patch
yarn.lock

fixes this issue: https://github.com/seek-oss/vanilla-extract/issues/771

build: patch vanilla extract to speed up build time

---

src/components/NavBar/MenuDropdown.css.ts
src/components/NavBar/MenuDropdown.tsx
src/components/NavBar/MobileSidebar.tsx
src/components/NavBar/NavDropdown.css.ts
src/components/NavBar/NavDropdown.tsx
src/components/NavBar/NavIcon.css.ts
src/components/NavBar/NavIcon.tsx
src/nft/css/sprinkles.css.ts

- cleans up light mode and dark mode overflow modal
- adds active state to overflow icon
- fixes right alignment of modals
Overflow modals:

fix: cleanup styles for overflow modal

---

src/components/NavBar/SearchBar.css.ts
src/components/NavBar/SearchBar.tsx
src/nft/components/icons.tsx

- Updates the search icons & fixes alignment
Desktop:
Mobile:
Alignment:

feat: update search icon

---

src/components/SearchModal/styleds.tsx
src/components/Tokens/TokenDetails/TokenDetail.tsx

https://uniswaplabs.atlassian.net/browse/WEB-897?atlOrigin=eyJpIjoiNjIxYWQzNzJiODQ5NGRmYTlkNGE0ZGNkMzY3YjVlMWUiLCJwIjoiaiJ9

fix: Web 897 redesign general token selector from swap focusing text input has incorrect background color

---

src/components/Tokens/TokenDetails/ShareButton.tsx
src/components/Tokens/TokenDetails/TokenDetail.tsx
src/pages/TokenDetails/index.tsx

fix token details 'share to twitter' information - https://uniswaplabs.atlassian.net/browse/WEB-877
before:
after:

fix: fix token details 'share to twitter' information

---

src/components/Tokens/TokenDetails/FooterBalanceSummary.tsx

fix: update swap CTA button color

---

src/components/NavBar/Navbar.tsx
src/components/WalletDropdown/index.tsx

There is no task for this, I'm addressing this now that we have clarity on the correct breakpoints

fix: added in correct wallet breakpoints

---

src/components/NavBar/Navbar.css.ts
src/components/NavBar/Navbar.tsx
src/components/NavBar/SearchBar.css.ts
src/components/NavBar/SearchBar.tsx
src/nft/components/collection/Card.css.ts
src/nft/components/collection/CollectionNfts.css.ts
src/nft/components/collection/CollectionStats.css.ts
src/nft/components/collection/CollectionStats.tsx
src/nft/components/explore/Banner.css.ts
src/nft/css/sprinkles.css.ts
src/nft/hooks/useIsMobile.ts

- updates sprinkles breakpoints to the latest values

feat: update sprinkles breakpoints

---

src/components/swap/styleds.tsx
src/pages/AddLiquidity/index.tsx
src/pages/AddLiquidity/styled.tsx
src/pages/CreateProposal/index.tsx
src/pages/Earn/Manage.tsx
src/pages/Earn/index.tsx
src/pages/Pool/PositionPage.tsx
src/pages/Pool/index.tsx
src/pages/Pool/styleds.tsx
src/pages/Swap/index.tsx
src/pages/TokenDetails/index.tsx
src/pages/Tokens/index.tsx
src/pages/Vote/Landing.tsx
src/pages/Vote/VotePage.tsx

* updates appropriate padding across all non nft pages

chore: updating navbar padding for token pages

---

src/theme/index.tsx
src/theme/styled.d.ts

Opening this pr to get feedback and decide what theming for this could/should look like

feat: Sample transitions pr

---

src/components/Tokens/TokenDetails/BalanceSummary.tsx

fix: network balances summary styling

---

src/pages/Tokens/index.tsx

* adding explore buttons/search on loading

fix: adding explore buttons on loading

---

src/theme/token-details-widget-theme.ts

fix: update widget color scheme

---

src/components/Tokens/TokenTable/SearchBar.tsx

I also added translation of the placeholder.

fix: rename search to filter tokens

---

src/components/Tokens/TokenTable/TokenRow.tsx
src/theme/index.tsx
src/theme/styled.d.ts

https://user-images.githubusercontent.com/5773490/186736049-98122ea3-15b3-457e-aa6e-92b6828a359f.mov

feat: add background-color transitions to table color changes

---

src/components/FeatureFlagModal/FeatureFlagModal.tsx

- Improves the styles around feature flags
- Adds a toggle to enable/disable any group's flags which are based on the BaseVariant

feat: add group flag toggles

---

src/components/Tokens/TokenDetails/PriceChart.tsx
src/components/Tokens/TokenTable/SearchBar.tsx

1. https://uniswaplabs.atlassian.net/browse/WEB-974
2. https://uniswaplabs.atlassian.net/browse/WEB-961

fix: Updating search token width and adding margin between token delta and price

---

src/components/Button/index.tsx
src/pages/AddLiquidity/index.tsx
src/theme/colors.ts
src/theme/index.tsx
src/theme/styled.d.ts

fix: yellow button redesign, improve add liquidity page readability

---

src/theme/token-details-widget-theme.ts

fix: widget module color

---

src/components/NavBar/SearchBar.css.ts
src/components/NavBar/SearchBar.tsx
src/components/NavBar/SuggestionRow.tsx

Removes top margin from no results container
Also reliant on #4528 
Screenshots:

feat: search when no results there is too much top padding

---

src/components/Tokens/TokensBanner.tsx

fix the link for the tokens promo banner

fix: tokens banner link works

---

src/components/Tokens/TokenTable/SearchBar.tsx

* idle and hovered colors are reversed

style: switching hovered and idle colors

---

src/components/SearchModal/CurrencySearchModal.tsx
src/components/TokenSafety/TokenSafetyModal.tsx
src/components/TokenSafety/index.tsx
src/pages/Swap/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1003?atlOrigin=eyJpIjoiZGVkODg2ZjI1MzRhNDhiM2FlZTlkNzQ4NDE2ZGJkMzAiLCJwIjoiaiJ9

fix: add back cancel button in token safety for swap

---

src/components/AmplitudeAnalytics/constants.ts
src/components/WalletModal/index.tsx

We think this may be causing issues with Infura

fix: don't track balances/values

---

src/components/NavBar/ChainSwitcher.tsx
src/components/NavBar/MenuDropdown.tsx
src/components/NavBar/NavIcon.css.ts
src/components/NavBar/Navbar.css.ts
src/components/NavBar/Navbar.tsx
src/components/NavBar/SearchBar.css.ts
src/components/NavBar/SearchBar.tsx
src/nft/components/modals/Overlay.css.ts
src/nft/css/sprinkles.css.ts

- Based of demo feedback we now show the bottom bar at smaller screen width in favor of changing the searchbar to the Magnifying Glass icon at larger widths. 
- I've also updated the searchbar to display in absolute positioning to go over the other elements in the navbar instead of pushing them out or going full screen early
Screenshots:
Breakpoints
Search at different breakpoints

feat: nav update to new responsive designs

---

src/components/swap/SwapModalFooter.tsx
src/state/transactions/updater.tsx

remove get stablecoin usd val hook in logging to reduce infura usage /spend.

fix: remove stablecoin usd val fetch in logging to reduce infura spend

---

src/hooks/useNetworkTokenBalances.ts
src/pages/TokenDetails/index.tsx

* catches invalid address error on token details page and redirects to token explore

fix: catch invalid address token details

---

src/components/NavBar/SearchBar.tsx

Auto sets the cursor when clicking anywhere on the searchbar or the magnifying glass icon on small screens
Screenshots:

feat: auto set cursor on searchbar opening

---

src/components/Icons/index.tsx
src/components/NavBar/ChainSwitcher.tsx
src/components/Web3Status/index.tsx
src/nft/components/icons.tsx

connect wallet redesign: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-App-Spec-(Phase-0-%26-Phase-1)-%5BWIP%5D?node-id=1813%3A41532
Resolves these jira tickets:
1) https://uniswaplabs.atlassian.net/browse/WEB-1079?atlOrigin=eyJpIjoiNDhjMTY0NzhjNTExNDA3ZmFkMTAwMzRhNWI0MmNiOTQiLCJwIjoiaiJ9
2) https://uniswaplabs.atlassian.net/browse/WEB-1050?atlOrigin=eyJpIjoiMWM2NTYxOGRmNWFjNGQ1OTg2MzllMzBiYzBjODIxYmQiLCJwIjoiaiJ9
Screenshot:

fix: connect wallet button chevron styling fixes

---

src/components/NavBar/SearchBar.tsx

* fix for search icon being offset

fix: search icon bug

---

src/components/Web3Status/index.tsx

fix: Prod has chevron

---

src/components/CurrencyLogo/index.tsx
src/components/ListLogo/index.tsx
src/components/Logo/index.tsx
src/components/SearchModal/CurrencyList/index.tsx
src/components/Tokens/TokenDetails/TokenDetail.tsx
src/components/Tokens/TokenTable/TokenRow.tsx

https://uniswaplabs.atlassian.net/browse/WEB-982?atlOrigin=eyJpIjoiY2M4ODFhY2ExZjcxNDVjNWIyMDMxYjFkNjliOWQ1NDIiLCJwIjoiaiJ9

fix: missing logo redesign

---

src/components/Widget/index.tsx

feat: disable branding on swap widget

---

src/pages/AddLiquidity/index.tsx

Fixes: #4549
Fixes: #4488 
Fixes: #4430

fix: handled liquidity minPrice and maxPrice are empty case.

---

src/components/Tokens/TokenDetails/BalanceSummary.tsx
src/pages/TokenDetails/index.tsx

show current user balance in token detail for current network. show nothing when balance is zero.

feat: show real values for current network balance

---

src/components/Popover/index.tsx
src/components/WalletDropdown/index.tsx
src/pages/App.tsx
src/theme/components.tsx
src/theme/index.tsx

pointed out by kenzie in slack: https://uniswapteam.slack.com/archives/CKX7SR7E1/p1660760838891389
Before: 
After:

fix: ensure nav bar goes above all other components when scrolling

---

src/components/Tokens/TokenDetails/TokenDetail.tsx
src/components/Tokens/TokenTable/TokenRow.tsx
src/components/Tokens/state.ts

Jira Tickets
1: https://uniswaplabs.atlassian.net/browse/WEB-1114
2. https://uniswaplabs.atlassian.net/browse/WEB-1109
What I did
1. I refactored the code so they both use the same styled components for the hearts.  They both now have the same color in light and dark mode. 
2.  The liked heart wasn't persisting b/c it was comparing address values with different cases.  I made everything lowercase for consistency
3. I added a hook to determine if an address is liked for consistency

fix: fixing token colors and token select persistence

---

src/hooks/useSyncChainQuery.ts

This makes it so the ?chain=polygon query parameter is used on initialization or update (when user manually changes the url). When it maps to a supported chain id, we will prompt web3-react to switch chains.
However, we no longer will keep the chain synced in the query parameters to prevent against race conditions. For example, this solves the bug where ?chain=polygon is completely ignored on load currently.
I think this is a reasonable trade-off for now, and if we decide to move to a place where more of the page state is represented in the URL vs in redux/jotai state then we can re-evaluate a better way of architecting the sync.

fix: only initialize using chain query

---

package.json
yarn.lock

This has some potential performance fixes for minimizing Infura calls.

chore: update smart-order-router

---

src/nft/components/collection/Card.css.ts
src/nft/components/collection/Card.tsx
src/nft/components/collection/CollectionAsset.tsx
src/nft/components/collection/CollectionNfts.tsx

* updating the nft collection cards to work with audio and video media

feat: audio video nft collection cards

---

src/components/NavBar/SearchBar.tsx

* fixed issue which caused searchbar to rerender every cycle

fix: search rerender

---

src/nft/components/explore/Explore.css.ts
src/nft/css/sprinkles.css.ts

* updating the sprinkles z indices to match that of the styled theme

chore: updating sprinkles z indices

---

src/nft/components/collection/Card.css.ts
src/nft/components/collection/Card.tsx
src/nft/components/collection/CollectionAsset.tsx
src/nft/components/collection/CollectionNfts.tsx
src/nft/pages/collection/index.tsx
src/nft/types/collection/collection.ts

* checks if all cards in collection are the same height and if not sets them to a square aspect ratio

feat: cards resize to uniform height

---

src/components/Tokens/TokenDetails/FooterBalanceSummary.tsx

fix: link to swap with inputCurrency from mobile token detail

---

src/components/NavBar/SearchBar.tsx

fix: remove search overlay

---

src/components/Web3Status/index.tsx

Flex isn't needed in this case so removed it vs fixing typo

style: remove broken flex property

---

src/components/NavBar/ChainSwitcher.css.ts
src/components/NavBar/NavIcon.tsx
src/components/NavBar/SearchBar.tsx
src/components/Web3Status/index.tsx
src/nft/components/icons.tsx

Makes sure all navbar buttons are 40px.

fix: normalize NavBar button heights

---

src/assets/svg/socks.svg
src/components/Identicon/StatusIcon.tsx

Updates design of Unisocks icon and adjusts positioning to suit new design

fix: update Unisocks status icon and positioning

---

src/components/FeatureFlagModal/FeatureFlagModal.tsx
src/featureFlags/flags/featureFlags.ts
src/featureFlags/flags/tokensNetworkFilter.ts
src/pages/Tokens/index.tsx

This will be released in phase0 now so we don't need to gate it anymore.

chore: remove tokensNetworkFilter feature flag

---

src/components/FeatureFlagModal/FeatureFlagModal.tsx
src/components/Tokens/TokenDetails/ChartSection.tsx
src/components/Tokens/TokenTable/TokenRow.tsx
src/featureFlags/flags/favoriteTokens.ts
src/featureFlags/flags/featureFlags.ts
src/pages/Tokens/index.tsx

I just noticed in the design that the Network Filter goes before the TimeSelector as well

chore: feature flags token favorites

---

src/components/Web3Status/index.tsx

fix: fully round corner on account dropdown

---

src/components/Tokens/TokenDetails/StatsSection.tsx
src/graphql/data/Token.ts
src/pages/TokenDetails/index.tsx

feat: add tvl to token details page

---

src/components/Tokens/TokenTable/TokenTable.tsx
src/graphql/data/Token.ts
src/graphql/data/TopTokens.ts

- uses relay's subscription api
- unsubscribes on re-fetch to prevent double loading state errors

feat(explore): rewrite top tokens hook

---

craco.config.cjs
src/analytics/Trace.tsx

Will be helpful for logging/debugging

feat: add git commit hash on build

---

src/components/TokenSafety/TokenSafetyMessage.tsx
src/constants/tokenSafety.tsx
src/pages/TokenDetails/index.tsx

also some small fixes related to array rendering and text whitespace
https://uniswaplabs.atlassian.net/browse/WEB-1270

feat(token-details): fix crash on undefined object access

---

src/theme/colors.ts
src/theme/index.tsx
src/theme/styled.d.ts

Will be used in the re-designed Swap.

chore(theme): add stateOverlayPressed

---

src/components/Tokens/TokenDetails/PriceChart.tsx

fix: left align TimeOptions until small breakpoint

---

src/components/CurrencyInputPanel/FiatValue.tsx
src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
src/components/HoverInlineText/index.tsx
src/components/swap/styleds.tsx
src/pages/Swap/index.tsx

fix: update swap box styles

---

src/components/NavBar/SearchBar.css.ts

Inputs should not be considered clickable

fix: no cursor pointer on SearchBar input

---

src/graphql/data/TopTokens.ts

https://uniswaplabs.atlassian.net/browse/WEB-1371?atlOrigin=eyJpIjoiZGRhNjMxMmMyZGE4NGI4MTgyOGQyMTgwODI4ZTUxNjAiLCJwIjoiaiJ9

fix: resolve bug where changing duration when filter string is applied does not change data (original duration is still applied)

---

src/components/Popover/index.tsx
src/pages/Swap/index.tsx

- Fixes color values so that the icons for token approval are visible
- Transitions to the Loader icon immediately upon clicking the Approve button, without waiting for wallet interaction

fix: approval pending ux

---

src/components/NavBar/SearchBar.tsx

fix: left align SearchBar when text present

---

src/components/SearchModal/CurrencyList/__snapshots__/index.test.tsx.snap
src/components/SearchModal/CurrencyList/index.tsx
src/components/SearchModal/styleds.tsx
src/components/TokenSafety/TokenSafetyIcon.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1258?atlOrigin=eyJpIjoiM2Y0MzgzZTU4YWY4NDA4NDhjNGUwOGVlNTA3YTU1MTIiLCJwIjoiaiJ9

fix: restores styling for verified and blocked tokens

---

public/index.html
src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
src/components/swap/styleds.tsx
src/pages/App.tsx
src/pages/AppBody.tsx

Moves font-feature-settings directly into AppWrapper, instead of being located in index.html and various other parts of the App. However, this doesn't seem to fix the slashed zeros yet.

fix: use font-feature-settings in AppWrapper

---

src/nft/components/collection/CollectionAsset.tsx
src/nft/components/explore/Cells/Cells.tsx
src/nft/utils/currency.ts

* removing extra decimals on cards

chore: remove extra decimals on cards

---

src/components/NavBar/SearchBar.css.ts

fix: shorten SearchBar height

---

src/components/Tokens/TokenDetails/About.tsx
src/components/Tokens/TokenDetails/ChartSection.tsx
src/components/Tokens/TokenDetails/StatsSection.tsx
src/theme/animations.ts
src/theme/index.tsx

feat: fade in text on details page

---

src/nft/components/collection/CollectionStats.tsx

* solid background color for collection stats icon

style: filling background color for collection header

---

src/components/Charts/SparklineChart.tsx
src/components/Tokens/TokenDetails/PriceChart.tsx
src/components/Tokens/TokenTable/TimeSelector.tsx
src/components/Tokens/state.ts
src/graphql/data/Token.ts
src/graphql/data/util.ts

https://uniswaplabs.atlassian.net/browse/WEB-1404?atlOrigin=eyJpIjoiOTEwMjM1MmQwNTc0NDMxZmE3NzkxYzIzOGQ2MDc3YzMiLCJwIjoiaiJ9
after change:

fix: remove ALL in time periods (temporary until  v2 backend data available)

---

src/nft/components/collection/CollectionNfts.tsx
src/nft/components/collection/PriceRange.tsx
src/nft/components/layout/Input.tsx
src/nft/hooks/useCollectionFilters.ts

1. If you try and put a decimal in the price range then nothing happens.  This fixes that issue

fix: fixing issue with decimal in price range

---

src/components/WalletDropdown/AuthenticatedHeader.tsx
src/components/WalletDropdown/IconButton.tsx

fix(IconButton): improves code quality and fixes a console error re: incorrect data- attribute syntax

---

src/components/WalletModal/PendingView.tsx
src/components/WalletModal/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-712?atlOrigin=eyJpIjoiNDg5NzI0YTg4ZGFlNDVmZDhkMWE3NTViMzYzODFiZTAiLCJwIjoiaiJ9
changes:
- make disclaimer text bigger
- new link
- remove disclaimer from wallet connection pending state

feat: privacy disclaimer change

---

src/components/Tokens/TokenDetails/LoadingTokenDetails.tsx
src/components/Widget/index.tsx

added new widget skeleton component to loading state

feat: added widget skeleton to loading state

---

src/pages/App.tsx
src/pages/Tokens/index.tsx

/tokens/ethereum -> /tokens/ethereum
/tokens -> /tokens/ethereum
/tokens/ethereum/tokenAddress -> /tokens/ethereum/tokenAddress

fix: add redirect from /tokens to /tokens/ethereum

---

src/components/Tokens/TokenTable/TokenRow.tsx
src/components/Tokens/TokenTable/TokenTable.tsx
src/graphql/data/TopTokens.ts
src/graphql/data/util.ts

fixes the following: 
1) used to load twice (flash of data then reload) when duration is changed
2) used to flash cached data then reload when network is changed

fix: more explore table fixes

---

src/components/Tokens/TokensBanner.tsx
src/components/TopLevelModals/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1448?atlOrigin=eyJpIjoiODBlNDJhMjIwMWQwNDdhZWIxOTg0NzYxMGI5YzlhNjQiLCJwIjoiaiJ9

fix: link to explore table when explore tokens banner clicked

---

src/components/Tokens/TokenDetails/BalanceSummary.tsx
src/pages/TokenDetails/index.tsx

https://user-images.githubusercontent.com/5773490/194357479-18333fa0-2493-4828-9494-cede2e74a905.mov

feat(token-details): link between native:wrapped assets in the balance summary

---

src/components/Tokens/TokenDetails/PriceChart.tsx
src/graphql/data/Token.ts

feat: chart states polish

---

src/nft/components/profile/view/FilterSidebar.tsx
src/nft/components/profile/view/ProfilePage.css.ts
src/nft/components/profile/view/ProfilePage.tsx
src/nft/components/profile/view/WalletAssetDisplay.tsx
src/nft/utils/asset.ts

- adds button to profile page to go into Sell Mode, this allows cards to be selected and added to the listing tag
- Select all button only visible in Sell Mode
- Toggling Sell Mode reset sell state
- remove sort and search which will not be included in phase1 launch

feat: Sell Mode Button

---

package.json
src/components/Widget/index.tsx
yarn.lock

fix: do not load token list

---

src/components/Tokens/TokenDetails/ChartSection.tsx
src/components/Tokens/TokenDetails/InfoTip.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1422?atlOrigin=eyJpIjoiMTdiYjhlNmM1NTNmNGNlNThhZDg3ODdkNTVlZjEwNzciLCJwIjoiaiJ9

fix: make sure every duration has latest price point

---

src/components/Charts/AnimatedInLineChart.tsx
src/components/Tokens/TokenDetails/PriceChart.tsx

The chart also doesn't need to have the children passed to it so I moved them around

fix: animation on mount wasn't happening

---

src/components/Tokens/TokensBanner.tsx

feat(WEB-1457): update banner text

---

src/components/SearchModal/CurrencyList/__snapshots__/index.test.tsx.snap
src/components/SearchModal/CurrencyList/index.tsx
src/components/SearchModal/CurrencySearch.tsx

stop token selector from briefly flashing to "no tokens" state, and instead show this while loading:

fix: remove no tokens state and replace w loading

---

src/components/Tokens/TokenTable/TokenTable.tsx

fix: minor typo

---

src/components/NavBar/MenuDropdown.tsx
src/components/Tokens/TokenDetails/About.tsx
src/components/WalletModal/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1507?atlOrigin=eyJpIjoiZjA1MjFmNmU0YzY5NDQzN2ExY2JhMzY5NjU5ZTgyOTIiLCJwIjoiaiJ9

fix: revise strings on token details + change privacy disclaimer edits to be enabled by phase 1 flag

---

src/components/NavBar/SuggestionRow.tsx
src/components/Tokens/TokenDetails/BalanceSummary.tsx
src/components/Tokens/TokenDetails/MobileBalanceSummaryFooter.tsx
src/components/Tokens/TokenDetails/PriceChart.tsx
src/components/Tokens/TokenDetails/StatsSection.tsx
src/components/Tokens/TokenTable/TokenRow.tsx
src/components/swap/TradePrice.tsx
src/pages/Swap/index.tsx
src/utils/formatDollar.test.ts
src/utils/formatDollar.ts
src/utils/formatNumbers.test.ts
src/utils/formatNumbers.ts

Covers items number 1 and number 4 on this ticket: https://uniswaplabs.atlassian.net/browse/WEB-1487

fix: second part of price fixes 

---

package.json
yarn.lock

feat: upgrade widget build

---

src/components/swap/TradePrice.tsx
src/utils/formatNumbers.ts

https://uniswaplabs.atlassian.net/browse/WEB-1520?atlOrigin=eyJpIjoiMjBmMzU1ZTc1ZGY4NDc1MGFiZTUwMmFlMjkwNmNiYjEiLCJwIjoiaiJ9

fix: remove double $ render

---

src/components/Tokens/TokenDetails/ChartSection.tsx
src/components/Tokens/TokenDetails/ShareButton.tsx

links to NATIVE chains were also broken (ie: polygon, ethereum). fixed those too in this pr. 
https://uniswaplabs.atlassian.net/browse/WEB-1528?atlOrigin=eyJpIjoiZDk3YzdiNTc3NDFkNDZjYzlmNzEyMjcxYjU4NTYxMTciLCJwIjoiaiJ9

fix: fix twitter links

---

package.json
src/components/Widget/index.tsx
src/components/Widget/inputs.tsx
src/components/Widget/settings.ts
yarn.lock

Reverts Uniswap/interface#4866
it causes infinite rendering

revert: "fix: use widget network connection"

---

package.json
src/components/Widget/index.tsx
src/components/Widget/inputs.tsx
src/components/Widget/settings.ts
yarn.lock

revert: "revert: "fix: use widget network connection""

---

public/index.html

Updates the preload to have the dark-mode Ethereum background.

fix: update default html background-color

---

src/components/Tokens/TokenDetails/MobileBalanceSummaryFooter.tsx
src/components/Tokens/TokensBanner.tsx
src/pages/TokenDetails/index.tsx
src/pages/Tokens/index.tsx

Changes for after deploy today

revert: add back phase0 bug fixes

---

src/components/Web3Status/index.tsx

issue reported by @zzmp here: https://www.notion.so/uniswaplabs/Phase0-Feedback-Bug-Reports-91e548ec69b5491e88a64a4997eb678a#2085ac954fa5421fa14191b4a9483202
before this change only the text and svg were clickable, even though `cursor: pointer` communicated otherwise.

fix: click area should match button effect

---

src/pages/Swap/index.tsx

fix: update font-weight values to match spec

---

public/index.html
public/manifest.json
src/components/Tokens/TokensBanner.tsx

- pwa and mobile theme color updates
- TokenBanner spacing on very small screens

fix: mobile tweaks

---

src/components/Tokens/TokenTable/TokenRow.tsx
src/utils/formatNumbers.test.ts
src/utils/formatNumbers.ts

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), and should start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):
- build: Changes that affect the build system or external dependencies (example scopes: yarn, eslint, typescript)
- ci: Changes to our CI configuration files and scripts (example scopes: vercel, github, cypress)
- docs: Documentation only changes
- feat: A new feature
- fix: A bug fix
- perf: A code change that improves performance
- refactor: A code change that neither fixes a bug nor adds a feature
- style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- test: Adding missing tests or correcting existing …

fix: display 0 instead of '-' on explore table

---

src/components/Header/index.tsx
src/components/TopLevelModals/index.tsx
src/featureFlags/flags/tokens.ts
src/pages/App.tsx

Removes Tokens flag completely

chore: remove tokens flag

---

src/components/SearchModal/CurrencyList/index.tsx
src/components/SearchModal/CurrencySearchModal.tsx
src/featureFlags/flags/tokenSafety.ts

Removes Token Safety flag completely

chore: remove tokenSafety flag

---

src/nft/components/collection/CollectionStats.tsx

Adds 24-hour floor price change to Collection Stats (to match Figma)

feat: NFT Collections: add 24-hour price change and delta arrow

---

src/components/Tokens/TokenTable/NetworkFilter.tsx

We may want to consider a better error state here, but at least this will not cause a crash.

fix: don't crash on unexpected chain

---

src/components/WalletModal/Option.tsx
src/components/WalletModal/index.tsx

one piece of removing the redesign flag within the codebase

chore: rm redesign flag in WalletModal

---

src/components/QuestionHelper/index.tsx
src/components/TransactionSettings/index.tsx

one piece of removing the redesign flag within the codebase

chore: remove redesign flag in settings

---

src/components/CurrencyInputPanel/FiatValue.tsx
src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
src/components/CurrencyInputPanel/index.tsx

We probably should re-consolidate these two panels soon as well, but seems like a separate problem.

chore: rm redesign flags from CurrencyInputPanel

---

src/nft/components/bag/Bag.tsx
src/nft/components/bag/BagHeader.css.ts
src/nft/components/bag/EmptyContent.tsx
src/nft/components/bag/__snapshots__/bag.test.tsx.snap
src/nft/components/bag/bag.test.tsx
src/pages/Pool/CTACards.test.tsx
src/pages/Pool/index.test.tsx
src/test-utils.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1631?filter=10089

fix(nft): empty bag state render

---

src/nft/components/details/AssetPriceDetails.tsx

* adding the ability to add and subtract the number of erc1155 tokens to bag on details page

feat: erc1155 specific functionality to details page

---

src/components/NavBar/SearchBar.css.ts
src/nft/css/sprinkles.css.ts

https://uniswaplabs.atlassian.net/browse/WEB-1560?atlOrigin=eyJpIjoiNDNlZTBiNjk1NTdlNDYyZTg5MzI4OGRlODRmMjg3OTIiLCJwIjoiaiJ9
before:
after:

fix: truncate search token name earlier

---

src/constants/tokens.ts
src/lib/hooks/useCurrency.ts
src/utils/index.ts

https://uniswaplabs.atlassian.net/browse/WEB-1662?atlOrigin=eyJpIjoiZWJhNGZkNDIxMDRkNDA0NmEwOWE4N2E5ZjYxM2E4YzUiLCJwIjoiaiJ9

fix: resolve some tokens not searchable by contract address in token selector cx bug

---

src/nft/components/bag/BagFooter.tsx
src/nft/components/bag/BagHeader.tsx
src/theme/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1575

fix: total and 'my bag' text style update

---

src/nft/components/bag/BagRow.tsx

also cleaned up the template a bit

fix: bag row item usd price alignment

---

src/nft/components/collection/CollectionStats.css.ts

https://uniswaplabs.atlassian.net/browse/WEB-1689?atlOrigin=eyJpIjoiY2YwZWMyYjYyNDc5NDdiZjg4ZDg2Mzc3MmZlNzJlMDkiLCJwIjoiaiJ9

fix: enlarge stat line font

---

src/nft/components/collection/CollectionStats.css.ts
src/nft/components/collection/CollectionStats.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1590?atlOrigin=eyJpIjoiZWZmZWI0Mjg1OTYzNGVmMmI3NzBiN2ZhOWI0ZGNkODMiLCJwIjoiaiJ9
based on this mock: https://www.figma.com/file/bCN7G6oArm7pPts03jvJ5x/Unification?node-id=9679%3A75335

fix: fixes show more / show less

---

src/nft/components/collection/Card.tsx
src/nft/components/details/AssetDetails.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1447?atlOrigin=eyJpIjoiMTM5MzgwYzU3MjU5NGU4OWFmYTRhNzJlNjVlODM2MDYiLCJwIjoiaiJ9

fix: change suspicious activity warning txt

---

src/analytics/constants.ts
src/nft/pages/asset/Asset.tsx

Adds a page view event for NFT details and an entry in the PageName constant (NFT_DETAILS_PAGE)

feat: page view event on NFT Details

---

src/nft/components/bag/BagRow.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1553

fix: hover flash

---

src/components/NavBar/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1620?atlOrigin=eyJpIjoiZDIxYTU2NjNkMGEzNDg1NmJjMzJiNGNkNzFmYjcwNjUiLCJwIjoiaiJ9

fix: remove chain selector for nft pages

---

src/components/Widget/index.tsx

Prevents widget from firing onTokensChange when the onTokensChange handler reference updates.

fix: do not flicker when navigating tokens

---

src/nft/components/bag/MobileHoverBag.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1567

fix: update "item" to "nft" in closed bag mobile copy

---

src/graphql/data/Token.ts
src/lib/hooks/useCurrency.ts
src/pages/TokenDetails/index.tsx

Reduces latency and on-chain calls when instantiating a token from query data.
WEB-1751

fix: fetch decimals from token query

---

src/nft/pages/collection/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1524?atlOrigin=eyJpIjoiMzZjYjIxY2JkYjUwNDI5NTk5Mzk3ZGU0MjljMDhjOTQiLCJwIjoiaiJ9

fix: adjust padding on collection page from 32 to 48

---

src/nft/components/collection/CollectionNfts.tsx
src/nft/css/sprinkles.css.ts
src/nft/themes/darkTheme.ts
src/nft/themes/lightTheme.ts

https://uniswaplabs.atlassian.net/browse/WEB-1544?atlOrigin=eyJpIjoiYWM2MzU5MzNiOTc4NDdmZjkwZjFjNTdkZmU0ZWI2NmUiLCJwIjoiaiJ9
figma: https://www.figma.com/file/bCN7G6oArm7pPts03jvJ5x/Unification?node-id=306%3A3494

fix: Web 1544 filter bar remove transparent bg on nft collection pages

---

src/components/Button/index.tsx
src/nft/components/bag/BagHeader.tsx
src/nft/components/bag/BagRow.css.ts
src/nft/components/bag/BagRow.tsx

- hover states on "remove" button
- hover states on the ❌  close icon for the bag
- adds a new general use `<MediumButton />` component that matches the design components figma doc
https://uniswaplabs.atlassian.net/browse/WEB-1794

feat: add medium-button and use it nft bag for removal

---

src/nft/components/collection/CollectionStats.css.ts

https://uniswaplabs.atlassian.net/browse/WEB-1589?atlOrigin=eyJpIjoiY2QyYzQ5NDRlNDUzNDgzN2E0Y2Y4MDExNGFmYWQ1YTgiLCJwIjoiaiJ9

fix: modify hyperlink styling in nft collection descriptions

---

src/nft/queries/genie/AssetsFetcher.ts
src/nft/queries/genie/CollectionPreviewFetcher.ts
src/nft/queries/genie/CollectionStatsFetcher.ts
src/nft/queries/genie/MultipleCollectionStatsFetcher.ts
src/nft/queries/genie/RouteFetcher.ts
src/nft/queries/genie/SingleAssetFetcher.ts
src/nft/queries/genie/SweepFetcher.ts
src/nft/queries/genie/TransactionsFetcher.ts
src/nft/queries/genie/WalletAssetsFetcher.ts
src/nft/queries/genie/logListing.ts
src/nft/queries/genie/triggerPriceUpdatesForCollection.ts
src/nft/queries/looksRare/createLooksRareOrder.ts
src/nft/queries/x2y2/index.ts

Updates all nft api fetchers to use v3 api endpoint

refactor: update all nft fetchers to use v3 endpoint

---

.env

https://uniswapteam.slack.com/archives/C023ZR8Q1DE/p1666967317793309
Any thoughts on the verbiage? or if I should add more explicit comments?

docs: adding comment to env

---

src/components/WalletDropdown/AuthenticatedHeader.tsx
src/pages/App.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1565?atlOrigin=eyJpIjoiMmRlM2MzYWM2NGMyNGIyMGE4MmYwMGZiNzA2MzA0NGUiLCJwIjoiaiJ9

fix: when scrolled, remove blur on nav bar

---

src/nft/types/collection/collection.ts

https://uniswaplabs.atlassian.net/browse/WEB-1617?atlOrigin=eyJpIjoiMmI2MDcxOTAzNjA1NDBiMDk3MDc2YTQ3OWU0YjUyOTEiLCJwIjoiaiJ9

fix: copywriting change

---

src/nft/components/collection/Activity.css.ts
src/nft/types/collection/collection.ts

https://uniswaplabs.atlassian.net/browse/WEB-1616?atlOrigin=eyJpIjoiNmI4MDUxZWY4ZTAxNDY5ZDllY2E0MjIxMWI1YTE2YWQiLCJwIjoiaiJ9

fix: Web 1616 make time stamp body bodysmall

---

src/nft/components/collection/TraitSelect.tsx
src/nft/pages/collection/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1814?atlOrigin=eyJpIjoiZjNjODZmY2U5MWJlNGJmYjljMjkwNmUyMGU3NTIyOGEiLCJwIjoiaiJ9

fix: collection banner sizing

---

src/nft/components/collection/CollectionStats.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1908?atlOrigin=eyJpIjoiNWYyNjI3NjRkYWFmNDllNDg1YjBiOTBmNjlkZDFjMjAiLCJwIjoiaiJ9

fix: stat line polish

---

src/components/WalletDropdown/AuthenticatedHeader.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1648?atlOrigin=eyJpIjoiNjc5M2ZkN2Y4NzRmNDg0ZDkzZWFmZjBiZjEyOTE2MzIiLCJwIjoiaiJ9

fix: button color

---

src/theme/RadialGradientByChainUpdater.ts

https://uniswaplabs.atlassian.net/browse/WEB-1937?atlOrigin=eyJpIjoiMzg1NTEyNzYwZTg2NGRjNmFhYzc0NmExNDI2NDdiZDUiLCJwIjoiaiJ9

fix: remove radial gradient background effect from nft pages

---

src/components/NavBar/SearchBarDropdown.tsx

fix: sometimes show verified nft collections first

---

src/nft/components/collection/Activity.css.ts
src/nft/components/collection/ActivityCells.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1488?atlOrigin=eyJpIjoiMTA3ZmMxZGI3NzAzNDMwMzlmOWQ0YTFkZWUyZmFiOGIiLCJwIjoiaiJ9

fix: stop nft id tag from getting cut off 

---

src/nft/components/collection/Activity.css.ts
src/nft/components/collection/Activity.tsx
src/nft/components/collection/ActivityCells.tsx
src/nft/components/collection/CollectionStats.css.ts
src/nft/css/sprinkles.css.ts
src/nft/pages/collection/index.tsx
src/nft/themes/darkTheme.ts
src/nft/themes/lightTheme.ts

1) https://uniswaplabs.atlassian.net/browse/WEB-1628?atlOrigin=eyJpIjoiZGJjNTA5OTQ2ZWU1NGVlZGIxMTM5MzY0MzZiOTZhNzUiLCJwIjoiaiJ9
2) https://uniswaplabs.atlassian.net/browse/WEB-1775?atlOrigin=eyJpIjoiMjcyMjFhZWZmYzA0NDA5MmFjMDlkM2UyNWQzNWM1ODIiLCJwIjoiaiJ9

fix: make addresses clickable

---

src/components/NavBar/MenuDropdown.tsx
src/components/NavBar/NavIcon.css.ts
src/components/NavBar/NavIcon.tsx
src/components/NavBar/ShoppingBag.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1726?atlOrigin=eyJpIjoiNTAyYzczMzUyZjFhNDg4ZThiYzY1NzAwYjczZWQ4Y2EiLCJwIjoiaiJ9

fix: nav bar icon sizes

---

src/nft/components/collection/Activity.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1722?atlOrigin=eyJpIjoiYjVhOGIzOTU5NDMxNDg5OTk2ZDBhNjc0N2JhMjJkYTUiLCJwIjoiaiJ9

fix: event filter styling adjustment

---

src/nft/components/profile/view/ProfilePage.tsx
src/nft/pages/collection/index.css.ts
src/nft/pages/collection/index.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1940?atlOrigin=eyJpIjoiNDA1OWMyNmY5MmM1NGYxNWEyMTQzMGQyMjNhM2JmNDYiLCJwIjoiaiJ9

fix: dynamic padding based on screen sizes for collections + my nft 

---

src/nft/components/bag/MobileHoverBag.css.ts

https://uniswaplabs.atlassian.net/browse/WEB-1724

fix: adjust mobile view bag z-index

---

src/graphql/data/nft/Asset.ts

Handle graphql prices passed in as scientific notation

fix: prices passed in scientific notation

---

src/nft/components/bag/BagFooter.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1967

fix: remove border-top-x-radius

---

src/nft/components/collection/Activity.css.ts
src/nft/components/collection/Activity.tsx
src/nft/components/collection/ActivityCells.tsx
src/nft/types/collection/collection.ts

- Reduce padding on L/R of each row
- Remove rarity
- Shift timestamps underneath token name
- include prices underneath event type

feat: Collection Activity mobile fixes

---

.env
src/nft/components/collection/Activity.css.ts
src/nft/components/collection/Activity.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1991?atlOrigin=eyJpIjoiMTlkMzA5MTIxMzUxNGE1MDk0ODU5MTQxOGI2ZjhmYzQiLCJwIjoiaiJ9

fix: activity page polish

---

src/nft/components/explore/Explore.css.ts
src/nft/components/explore/Table.tsx

Removes rank on trending collection table (mobile-only) and unused NFT Explore styles

fix: Remove rank on trending collection table (mobile)

---

src/graphql/data/nft/Collection.ts

This correctly formats traits for a collection

fix: gql traits for collection

---

src/nft/utils/urlParams.ts

I have a separate PR WIP to move this all to react-router, but for now replacing should solve the issue.

fix: replaceState instead of pushState for collection filters

---

src/nft/components/collection/Activity.tsx
src/nft/components/collection/ActivitySwitcher.tsx
src/nft/components/collection/Card.css.ts
src/nft/components/collection/Card.tsx
src/nft/components/collection/CollectionNfts.tsx
src/nft/components/collection/CollectionSearch.tsx
src/nft/components/collection/CollectionStats.css.ts
src/nft/components/collection/CollectionStats.tsx
src/nft/components/collection/FilterButton.tsx
src/nft/components/profile/view/ProfilePage.tsx

* updating mobile collection page styles to match figmas

style: updating collection page for mobile

---

src/nft/components/collection/PriceRange.tsx

* numbers were being passed to set min which were expected to be strings

fix: wrong types for set min

---

src/nft/components/collection/Card.tsx

* image was scaling out of bounds for some reason this prevents that

fix: for cutoff border radius

---

src/components/RoutingDiagram/__snapshots__/RoutingDiagram.test.tsx.snap
src/components/SearchModal/CurrencyList/__snapshots__/index.test.tsx.snap
src/components/TextInput/__snapshots__/index.test.tsx.snap
src/theme/colors.ts

I am unclear if this is enough to merge incrementally, or if we need further component level changes first.

chore: update design-system grays

---

src/nft/components/bag/BagContent.tsx
src/nft/components/collection/TransactionCompleteModal.tsx

Fixes usd_value on Bag Success, and an issue with bag_quantity on Bag Changed

fix: Event property fixes 

---

src/components/RoutingDiagram/__snapshots__/RoutingDiagram.test.tsx.snap
src/theme/colors.ts
src/theme/index.tsx
src/theme/styled.d.ts

Updates various theme values with updated design system

chore: add new background to theme

---

.github/workflows/release.yaml

Reverts Uniswap/interface#5085

build: Revert "build: deploy on friday AMs"

---

src/components/Tokens/TokenDetails/PriceChart.tsx
src/nft/components/collection/CollectionStats.tsx

https://uniswaplabs.atlassian.net/browse/WEB-2031?atlOrigin=eyJpIjoiMjAzODVhZjEwNmM4NDQ3MThmMzQ4NzE1NTRhNDMzZmIiLCJwIjoiaiJ9

fix: collection stat line fixes

---

src/graphql/data/nft/Asset.ts

Adds more null checks for Asset gql query

fix: add more null checks for Asset gql query

---

src/components/NavBar/ShoppingBag.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1945?atlOrigin=eyJpIjoiZDUzZWYzNjA5MTJlNDdjMzgyZTFhYzg4Y2ZjZDhhMmEiLCJwIjoiaiJ9

feat(sell-bag): patch open/close behavior

---

src/graphql/data/nft/Asset.ts
src/nft/components/collection/Filters.css.ts
src/nft/components/collection/TraitSelect.tsx

Adds virtual containers for Traits to improve page latency. Big shout-out to @lynnshaoyu with the assist for AutoSizer.

feat: virtual containers for collection pages

---

src/graphql/data/fetchGraphQL.ts

Updating the nft gql fetching endpoint and headers. Still need to do CORS infra work to connect directly to beta/prod endpoints. Local env variables will also need to be updated

refactor: update nft gql fetcher endpoint

---

src/graphql/data/nft/NftBalance.ts
src/nft/components/profile/view/WalletAssetDisplay.tsx

NftBalance schema had a minor alternation when moved to prod, this supports that alteration. Listed profile Cards should load as expected

fix: updates to wallet asset schemas
