- src/nft/hooks/useCollectionFilters.ts
we still order these at the top
> fix: default to buy now disabled

- src/components/NavBar/ShoppingBag.tsx
- src/nft/components/bag/Bag.tsx
- src/nft/components/profile/view/ProfilePage.tsx
- src/nft/hooks/useSellAsset.ts
https://uniswaplabs.atlassian.net/browse/WEB-1945
> feat(sell-bag): closing link sell bag open/close state with sell mode activation

- src/nft/components/explore/Cells/Cells.tsx
- src/nft/components/explore/Table.tsx
Fix font weight to match Figma (Collection Names)
> style: Font weight on Trending Collections table

- src/components/NavBar/index.tsx
- src/hooks/useIsNftPage.ts
- src/nft/components/bag/Bag.tsx
- src/nft/components/bag/EmptyContent.tsx
- src/theme/RadialGradientByChainUpdater.ts
This is getting re-used in a lot of places.
> refactor: useIsNftPage hooks

- src/nft/components/collection/FilterButton.css.ts
> fix: accentAction for FilterButton

- src/components/PrivacyPolicy/index.tsx
- src/components/WalletModal/index.tsx
Updated wallet-connect & legal/privacy modals to link to the new privacy policy
> feat: replaced protocol disclaimer with privacy policy link

- src/components/Popover/index.tsx
- src/components/Tooltip/index.tsx
- src/nft/components/collection/Card.tsx
- src/nft/components/collection/CollectionAsset.tsx
- src/nft/components/profile/view/ViewMyNftsAsset.tsx
figma: https://www.figma.com/file/bCN7G6oArm7pPts03jvJ5x/Unification?node-id=15013%3A85118&t=y97NT4sIm9RHuXwY-0
jira: https://uniswaplabs.atlassian.net/browse/WEB-1858?atlOrigin=eyJpIjoiMDg0MmNmYzdlYTU1NDY4MjgxZTdlOGU5ODdjNzk0MDIiLCJwIjoiaiJ9
> feat: Web 1858 disabled card 1155 when sell mode is on

- src/nft/components/bag/Bag.tsx
- src/nft/components/bag/BagFooter.css.ts
https://uniswaplabs.atlassian.net/browse/WEB-2042
> fix(bag-footer): remove double border top and excess margin

- src/nft/components/profile/view/ProfilePage.tsx
- src/nft/components/profile/view/ViewMyNftsAsset.tsx
https://uniswaplabs.atlassian.net/browse/WEB-1947?atlOrigin=eyJpIjoiNzJlZjI4N2YyYjZkNGU0NThiY2FlYzc3YjNhNmQ4OWEiLCJwIjoiaiJ9
> feat: image cropping / sizing on view my nfts

- src/nft/components/collection/Card.tsx
- src/nft/components/collection/CollectionPageSkeleton.tsx
- src/nft/components/profile/view/ProfilePage.tsx
- src/nft/components/profile/view/ViewMyNftsAsset.tsx
- src/nft/pages/collection/index.tsx
- src/nft/types/sell/sell.ts
1) also fixes bug where loading state collection banner is still the old height (smaller, 160px) instead of the new 276px height. 
2) dont include erc 1155 and sus marked nft's when selecting all
> fix: only disable erc 1155 in sell mode

- src/nft/components/collection/TraitChip.tsx
- src/nft/components/profile/view/ProfilePage.tsx
Fixes https://uniswaplabs.atlassian.net/browse/WEB-2056.
> style: Reduce radius and increase padding of trait chips on collection/profile pages

- src/nft/components/explore/Banner.tsx
Updated the banner text content, size, and color. 
Fixes https://uniswaplabs.atlassian.net/browse/WEB-2047.
> style: Update banner text, font size, color.

- src/nft/components/collection/CollectionNfts.tsx
- src/nft/components/collection/MarketplaceSelect.tsx
- src/nft/components/collection/TraitChip.tsx
Adds marketplace logos to filter and chips on collection page
https://uniswaplabs.atlassian.net/browse/WEB-2058
> feat: add market logos to filters and chips

- src/nft/components/bag/Bag.css.ts
- src/nft/components/bag/BagFooter.tsx
- src/nft/components/bag/BagHeader.tsx
- src/nft/components/bag/EmptyContent.tsx
- src/theme/components.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2059
> fix(bag): simplify header

- src/graphql/data/nft/Details.ts
- src/graphql/data/nft/NftBalance.ts
- src/nft/components/profile/view/ProfilePage.tsx
- src/nft/pages/asset/Asset.tsx
- src/nft/pages/profile/profile.tsx
Uses proper pattern for loading and lazy loading data for profile and asset details page.
> refactor: lazy load asset details and profile page

- src/components/Button/index.tsx
- src/nft/components/bag/BagRow.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2015
> fix(bag): review asset buttons

- src/nft/components/explore/Cells/Cells.tsx
- src/nft/components/explore/CollectionTable.tsx
- src/nft/components/explore/Table.tsx
- src/nft/components/explore/TrendingCollections.tsx
> fix: do not show floor/volume change on all

- src/nft/components/collection/CollectionStats.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2224
> fix(1155): don't show unique owners on collection page

- src/components/NavBar/Bag.tsx
- src/components/NavBar/index.tsx
So that it can be consistent with nft/components/Bag
> refactor: rename ShoppingBag to Bag

- src/nft/components/collection/Sweep.tsx
* allowing you to sweep specific marketplaces
> fix: sweep marketplaces

- package.json
- yarn.lock
think this won't install for a build reason, but lets see
> chore: bump redux-multicall

- src/nft/components/profile/view/ProfilePage.tsx
This is an incremental step to removing "sell mode" in the NFT product.
> fix: remove Select All and Sell buttons in Profile

- src/nft/components/explore/Cells/Cells.tsx
- src/nft/components/explore/CollectionTable.tsx
Fix WEB-2246, implemented a workaround as per ticket
> fix: limit max volume change value to 9999%

- src/hooks/useERC20Permit.ts
This brings signature logic to parity with widget.
See WEB-2259
> fix: retain permit sig if amount decreases

- .github/CODEOWNERS
This requires all PRs must be approved by an engineer on the web team.
> ci: GitHub CODEOWNERS

- src/nft/components/explore/Explore.css.ts
- src/nft/components/explore/Table.tsx
- src/theme/colors.ts
- src/theme/components.tsx
- src/theme/index.tsx
- src/theme/styled.d.ts
Fixes WEB-2178
Fixes WEB-2181
I will extend this code to accept the "network" parameter, but this will come under a different PR. There's a separate ticket for adding glow to Swap/Pool pages, and that's where the network comes into play. 
It's WEB-1809 if you want to check for more details.
> feat: add glow to trending table

- src/nft/components/explore/Banner.tsx
Screenshots on Slack. Removed overflow will play nicely with the table glow.
> feat: render background below navbar + remove overflow

- .github/workflows/release.yaml
switch to using cloudflare web3 gateway
> chore: update deploy action

- package.json
- src/nft/components/bag/profile/utils.ts
- src/nft/queries/openSea/PostOpenSeaSellOrder.ts
- src/nft/queries/x2y2/index.ts
- src/nft/utils/listNfts.ts
- yarn.lock
- Abstract away OS listing to BE endpoint
- Allow for relisting of X2Y2 assets
- Support new LR listing strategy
- Fixes bug with incorrectly formatted basis points (creator royalties)
Tested by being able to successfully list and relist to all 3 marketplaces
> fix: Can list and relist to all marketplaces

- src/nft/components/explore/Banner.tsx
Adding a small `transform: scale(1.1);` dramatically improves the blur effect. Removes blotchy effects that occur when the blur algorithm runs our of pixels at the edges of images.
> style: polish explore banner blur effect

- src/components/NavBar/Bag.tsx
- src/nft/components/bag/EmptyContent.tsx
- src/nft/components/icons.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2287
> fix(bag): icon update to remove front handle

- craco.config.cjs
- package.json
- src/nft/components/explore/CarouselCard.tsx
- yarn.lock
As a follow-up, we should consider using that module everywhere for NFT prices as it's compatible with the Notion spec. This is going to be tracked in a separate ticket.
> feat: improve formatting of NFT prices with shared module

- src/nft/components/collection/Card.tsx
- src/nft/components/collection/CollectionNfts.css.ts
https://uniswaplabs.atlassian.net/browse/WEB-2260
> fix: adjust gap down to 16px on large screens

- src/nft/components/collection/TransactionCompleteModal.css.ts
Add some horizontal padding to fix bug with shadow being cutoff
Align items center
> fix: tx screen tweak

- src/nft/components/collection/CollectionAsset.tsx
* fix lets video and audio play on nft cards
> fix: play video on asset card

- src/pages/Swap/index.tsx
> fix: fixing button color

- src/nft/components/profile/view/ProfilePage.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2294
> style: correct padding for view my nfts

- src/nft/components/profile/view/ProfilePage.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2234
> style: moving mobile sell bag above tab bar

- src/nft/components/bag/Bag.tsx
- src/nft/components/profile/list/ListPage.tsx
- src/nft/pages/profile/profile.css.ts
- src/nft/pages/profile/profile.tsx
- fix bug where profile assets couldn't scroll
- removes deprecated mobile styles
> fix: working profile scroll on mobile

- src/nft/components/collection/CollectionPageSkeleton.tsx
* fixes incorrect padding on loading animations
> style: correct collection loading

- src/nft/components/profile/view/ProfilePageLoadingSkeleton.tsx
* updating the profile page skeleton to match appropriately
> style: updating profile skeleton

- src/nft/components/bag/EmptyContent.tsx
List bag empty state now mirrors buy bag
> fix: empty sell tag state

- src/nft/pages/asset/Asset.tsx
- src/nft/pages/explore/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2322
> fix: close bag automatically on details

- src/pages/Pool/index.tsx
Per design feedback, sizes down new position button to match the more flyout button.
> fix: size down new position button

- src/nft/components/profile/view/ProfilePage.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2327
> style: light mode background style for floating sell bag

- src/nft/pages/collection/index.tsx
* bag should auto close when going to collection page - but not from collection to collection
> fix: bag autoclose when going to collection page

- src/components/Tooltip/index.tsx
- src/nft/components/profile/view/ViewMyNftsAsset.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2328?atlOrigin=eyJpIjoiODk5YzU5ODhiNjRmNGQxYmI4MDYxMjRlYmVhMzg3ZTUiLCJwIjoiaiJ9
> fix: erc 1155 tooltip behavior on mobile

- src/nft/css/sprinkles.css.ts
- src/nft/themes/darkTheme.ts
- src/theme/colors.ts
Adds Gray950 hex and remaps backgroundBackdrop to it
> chore: add Gray950 and remap backgroundBackdrop to it

- src/nft/utils/txRoute/combineItemsWithTxRoute.ts
* pooled assets always triggered a price adjustment to popup this fixes that
> fix: no price adjustment popups for pooled assets

- src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
> fix: swap input size difference

- src/nft/components/profile/view/ProfilePage.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2356?atlOrigin=eyJpIjoiOWI4NzcwMmU5NGIwNGUwMjk1ZGU2MWJiMWIzZDJlM2IiLCJwIjoiaiJ9
> fix: mobile profile bag copywriting change

- src/nft/components/profile/view/FilterSidebar.tsx
Essentially updates the mobile filters into being a modal.
> fix: show mobile filters on top of nav

- src/nft/components/bag/profile/ListingModal.tsx
You're welcome Patrick & Adrian
> feat: approve collections in parallel on desktop, sequentially on mobile

- src/nft/components/details/AssetDetails.tsx
- src/nft/components/details/AssetPriceDetails.tsx
- src/nft/components/details/TraitsContainer.tsx
- src/nft/utils/asset.ts
* updating details to new design
* moving asset name and collection name to right side
> style: updating details

- src/nft/queries/genie/SearchCollectionsFetcher.ts
- src/nft/queries/genie/SearchTokensFetcher.ts
- src/nft/queries/genie/TrendingCollectionsFetcher.ts
- src/nft/queries/genie/TrendingTokensFetcher.ts
Added check for whether API_URL's exist from process.env
> fix: searchbar fetching promise resolve fallback

- src/nft/components/explore/CarouselCard.tsx
> feat: handle 0 in banner card

- src/nft/components/profile/view/ViewMyNftsAsset.tsx
Fixes https://uniswaplabs.atlassian.net/browse/WEB-2388
> fix: Update copy for viewing 1155 assets.

- src/nft/components/details/AssetPriceDetails.tsx
- src/nft/utils/asset.ts
* hover listing state
* tweet url
> fix: a few bugs on details

- src/nft/components/collection/ActivityCells.tsx
- src/nft/components/details/AssetPriceDetails.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2422
> fix: changing buy now to add to bag

- src/nft/components/collection/CollectionAsset.tsx
- src/nft/types/common/common.ts
https://uniswaplabs.atlassian.net/browse/WEB-2417
> fix: adding pool icon to sudo assets

- src/nft/components/details/AssetPriceDetails.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2418
> style: adding links to marketplace icons on details

- src/nft/components/details/AssetDetails.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2412
> style: open all containers on details

- src/nft/components/collection/TransactionCompleteModal.css.ts
- src/nft/components/details/AssetPriceDetails.tsx
- src/nft/utils/transactionResponse.ts
Reduces the size of a single purchases asset in success screen. Also aligns the unicorn icon with the Header text.
> fix: reduce success image size

- src/nft/components/bag/BagContent.tsx
- src/nft/components/bag/BagRow.tsx
- src/nft/components/bag/TimedLoader.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2404
> fix: no title for unavailable nft

- src/nft/hooks/useBag.ts
https://uniswaplabs.atlassian.net/browse/WEB-2413
> fix: remove last item behavior from bag

- src/nft/components/explore/CarouselCard.tsx
> chore: reduce border by 1px

- src/nft/components/explore/WelcomeModal.tsx
Will require quick rebase after https://github.com/Uniswap/interface/pull/5417 is merged.
Fixes WEB-2443
> chore: update welcome banner copy

- src/nft/components/nftExploreBanner/NftExploreBanner.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2450?atlOrigin=eyJpIjoiMWJlOWE5NzM2N2EyNGViMzhmMzJiYWNkN2U1MmE4NDAiLCJwIjoiaiJ9
> fix: copywriting nft banner

- src/nft/components/explore/WelcomeModal.tsx
Fixes WEB-2429
This is an exception from application-wide link style
> chore: update link color

- src/components/NavBar/index.tsx
- src/components/NavBar/style.css.ts
> fix: add outline to bottom navigation

- src/components/Polling/index.tsx
> fix(polling): correct gas price color

- src/nft/components/nftExploreBanner/NftExploreBanner.tsx
- src/theme/components/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2419?atlOrigin=eyJpIjoiZjZjYmIzYzAyMmI0NGNhZDk1MGViYWQ4Y2RmOTQzZjQiLCJwIjoiaiJ9
> fix: nft explore banner polish

- src/pages/Pool/index.tsx
> fix: adjust margin on icon/button on pool page

- src/components/AirdropModal/index.tsx
https://uniswapteam.slack.com/archives/C04822DFATE/p1669344116753819
> fix: transaction not waiting

- src/nft/components/collection/TransactionCompleteModal.css.ts
- src/nft/components/collection/TransactionCompleteModal.tsx
- src/nft/css/sprinkles.css.ts
- src/nft/themes/darkTheme.ts
- src/nft/themes/lightTheme.ts
Fixes WEB-2434
If anyone wants to help with testing and perform a real transaction, that would be much better! For testing, I mocked few booleans to render a preview, but was missing some content.
> fix: style on transaction modal

- src/nft/components/collection/CollectionNfts.tsx
- src/nft/components/profile/view/ProfilePage.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2383?atlOrigin=eyJpIjoiM2E0ZDAyNDUwZDcyNGU0ZGI2NGM3YjI0YTliZjNmMDMiLCJwIjoiaiJ9
> fix: use same loader in view my nfts as collection

- src/nft/components/details/AssetPriceDetails.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2462?atlOrigin=eyJpIjoiMTc3ZTQzMDNmZGJmNDVkOGFjMzdhOTAyNzFhMGI2YzEiLCJwIjoiaiJ9
> fix: color on button in nft details

- src/nft/components/collection/Sweep.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2438
> fix: sweep adding the correct assets from amms

- src/pages/App.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2435?atlOrigin=eyJpIjoiOGEwZDc2YzkzOTBkNGQ1NWJmMjBiN2EyMTY4ZjdkNTciLCJwIjoiaiJ9
> fix: remove animation on nav

- src/nft/components/bag/BagRow.css.ts
- src/nft/components/bag/BagRow.tsx
- src/nft/components/bag/profile/ProfileAssetRow.tsx
Fixes WEB-2421
Screenshot of a hit target in ^ Jira ticket
> feat: increase hit-target for remove button

- src/nft/components/explore/Banner.tsx
- src/nft/components/explore/CarouselCard.tsx
- src/nft/components/explore/TrendingCollections.tsx
- src/theme/index.tsx
Fixes WEB-2303
Fixes WEB-2304
Align banner and trending section with each other (see Slack)
Related:
Added a new `xs` breakpoint since it started appearing in Figma already
> chore: various banner responsive tweaks

- src/nft/components/bag/Bag.css.ts
- src/nft/components/bag/Bag.tsx
this commit added some regressions: https://github.com/Uniswap/interface/commit/af2725ec25ad8c4660b00e721ef7da192801baac
The new BagContainer causes a couple of issues
1. adding a bunch of items causes the "pay" button go off screen
2. The overlay when the bag opens does not always function properly
> fix: reverting to previous styles

- src/nft/components/collection/Activity.css.ts
- src/nft/components/collection/Activity.tsx
- src/nft/components/details/AssetDetails.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2453?atlOrigin=eyJpIjoiMmQ0ODYzODlmNmVmNDM0ZWJhM2MzY2VkY2Q4MzUxMGQiLCJwIjoiaiJ9
> fix: button colors

- src/nft/components/collection/TransactionCompleteModal.tsx
- src/nft/utils/asset.ts
* share link on transaction complete modal
> feat: share link on transaction page

- .env
> chore: remove unused keys

- src/components/NavBar/SearchBar.tsx
- src/nft/css/common.css.ts
Fixes: 
- low contrast light mode "slash" box
- incorrectly offset search box outline
> fix: fixes search styling nits

- src/nft/components/bag/Bag.tsx
Listing modal needs the bag styles to properly size
This is a quick fix for expediency
> fix: lisiting modal

- src/graphql/data/nft/Asset.ts
- src/graphql/data/nft/NftBalance.ts
> fix: supporting commas

- src/graphql/data/nft/Asset.ts
- src/graphql/data/nft/NftBalance.ts
- src/nft/utils/currency.ts
- src/nft/utils/listNfts.ts
Abstract common function to handle scientific notation and comma delimited values
> refactor: scientific notation helper fn

- src/nft/components/explore/Banner.tsx
* making the underlying explore blur full width
> style: full width explore banner

- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/landingPage.ts
to be used for an upcoming feature
> chore: landing page feature flag

- src/featureFlags/flags/favoriteTokens.ts
all the favorite token logic was removed a couple months ago, but i forgot to remove this flag
> chore: remove unused favoriteTokens flag

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/NavBar/SearchBar.css.ts
- src/components/NavBar/SearchBar.tsx
- src/components/NavBar/SearchBarDropdown.tsx
- src/components/NavBar/index.tsx
- src/components/TopLevelModals/index.tsx
- src/components/WalletDropdown/AuthenticatedHeader.tsx
- src/components/WalletModal/index.tsx
- src/components/Web3Status/index.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/nft.ts
- src/pages/App.tsx
Now that it's ungated we can remove the feature flag fully.
> chore: remove nft feature flag

- src/nft/components/details/AssetActivity.tsx
- src/nft/components/details/AssetDetails.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2212
> style: adding loading state for asset activity

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
Forgot to add it to the modal. We should figure out how to simplify this process a bit.
> chore: add landing page flag to modal

- src/components/PrivacyPolicy/index.tsx
- src/components/SearchModal/CurrencyList/index.tsx
- src/components/SearchModal/CurrencySearchModal.tsx
- src/components/SearchModal/styleds.tsx
- src/components/TokenSafety/index.tsx
- src/components/Tokens/TokenDetails/About.tsx
- src/components/Tokens/TokenDetails/AddressSection.tsx
- src/components/Tokens/TokenDetails/PriceChart.tsx
- src/components/Tokens/TokenDetails/StatsSection.tsx
- src/components/Tokens/TokenDetails/TimeSelector.tsx
- src/components/Tokens/TokenTable/TokenRow.tsx
- src/components/Widget/index.tsx
even more of these. this is smaller than the other prs bc i'm tired and don't wanna do more rn haha
> chore: remove some unused exports

- package.json
- src/nft/components/explore/Table.tsx
- yarn.lock
https://uniswaplabs.atlassian.net/browse/WEB-2487
> fix: add back previously deleted trending row selected event

- src/nft/components/collection/Activity.tsx
- src/nft/components/collection/ActivityLoader.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2440?filter=10136
> style: updating page loader for activity

- src/components/WalletModal/index.test.tsx
- src/connection/utils.ts
Injected confuses people, hopefully this is clearer!
> feat: show Browser Wallet instead of Injected

- src/components/swap/TradePrice.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2218?atlOrigin=eyJpIjoiOGY1ZmQzZmMxZmM4NGRlZjhjMzRhNmQ2YThmMDk0OTUiLCJwIjoiaiJ9
> fix: more precise numbers in swap exchange price

- src/components/Popups/FailedNetworkSwitchPopup.tsx
- src/components/Popups/PopupItem.tsx
https://uniswaplabs.atlassian.net/browse/WEB-1328?atlOrigin=eyJpIjoiOWZkZjI4NzM1YzljNGI0ZGI5NTM2MDE0NDU3YjllOWMiLCJwIjoiaiJ9
> fix: improve network switching error to new design

- src/constants/chainInfo.ts
https://uniswaplabs.atlassian.net/browse/WEB-2499?atlOrigin=eyJpIjoiMjEwNDQ3ODE1NzJjNDZmOGIzZDBlNmY1MGIzNTEzYjkiLCJwIjoiaiJ9
> fix: broken polygon bridge link

- .env
This was removed unintentionally in this pr: https://github.com/Uniswap/interface/pull/5217
> build: no eslint errors on local build

- src/pages/Landing.tsx
> fix: update copy on landing page

- src/components/Button/index.tsx
- src/components/swap/styleds.tsx
- src/pages/Landing.tsx
- src/pages/Landing/index.tsx
> feat: add learn more button

- src/components/AccountDetailsV2/index.tsx
- src/components/WalletDropdown/TransactionMenu.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2068?atlOrigin=eyJpIjoiYjMxZGQ0NDhjMGM3NGFlZjlhOWZhMzJlZDMwYzA1YjciLCJwIjoiaiJ9
after changes in this pr:
> fix: remove border on last item in txn list on wallet dropdown

- src/pages/About/Step.tsx
- src/pages/About/index.tsx
future pr will handle selected state
> fix: update swap description in about, remove transfer

- src/components/Tokens/TokenDetails/PriceChart.tsx
- src/components/Tokens/TokenDetails/Skeleton.tsx
https://uniswaplabs.atlassian.net/browse/WEB-1303?atlOrigin=eyJpIjoiNzU0ZjgwZjUyMjc4NDkyMzkzZDY2Y2U4ZGM1OTM1NzAiLCJwIjoiaiJ9
> fix: token details loading state fixes

- src/pages/About/Step.tsx
- src/pages/About/index.tsx
will add updated images in a future pr
> feat: add selected state for about steps

- src/pages/About/index.tsx
easiest is to check the preview. basically, makes sure the padding is correct and makes the "powered by" section go last on mobile
> feat: /about mobile responsive

- src/pages/About/index.tsx
> fix: tablet responsiveness on /about

- src/pages/About/Card.tsx
This handles external and internal links differently.
> fix: update links in /about cards

- src/pages/About/index.tsx
> feat: dynamically add padding-top on /about

- src/pages/About/index.tsx
Not sure why 200 works specifically, might want to look into it more.
> fix: switch to scrollHeight and add less padding

- src/pages/Landing/index.tsx
> fix: makes sure padding-bottom isn't overriden in Landing

- src/pages/About/constants.ts
- src/pages/About/index.tsx
Need the light mode swap asset to add into this PR before merging!
> fix: handle light mode image in About step

- src/pages/Landing/index.tsx
> fix: center the subtext by using a container

- src/pages/Landing/index.tsx
> fix: landing page font-size changes

- src/pages/About/Step.tsx
- src/pages/About/index.tsx
Also removes the descriptions based on design feedback
> fix: update about preview on hover

- src/pages/About/Card.tsx
- src/pages/About/Step.tsx
> fix: update /about cards and step sizings

- src/components/Tokens/TokenDetails/PriceChart.tsx
- src/components/Tokens/TokenDetails/Skeleton.tsx
- src/components/Tokens/TokenDetails/TimeSelector.tsx
https://uniswaplabs.atlassian.net/browse/WEB-1188?atlOrigin=eyJpIjoiNjdlNTkzMDE0ZTM0NDRlMTk2YTVkNDVmNmFjNDk2OGYiLCJwIjoiaiJ9
> fix: token details chart x axis and time selector style tweaks

- src/components/WalletDropdown/DefaultMenu.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2469?atlOrigin=eyJpIjoiMTQzODIxYmMzOWNlNDlk
> feat: add inline preview of pending txn in wallet dropdown

- src/pages/About/index.tsx
- src/pages/Landing/index.tsx
> fix: copy changes for /about

- public/index.html
- src/pages/App.tsx
- src/pages/Landing/index.tsx
https://user-images.githubusercontent.com/4899429/206876451-fa6aeb52-e269-46b9-bea0-feb9032f7fc0.mov
> fix: show swap hover state on landing page

- src/pages/About/index.tsx
> fix: centers /about Panels

- src/pages/Landing/index.tsx
> fix: update landing page paddings

- src/pages/About/index.tsx
> fix: make background header a background-image

- src/pages/About/index.tsx
> fix: remove period in landing page copy

- src/pages/About/index.tsx
> fix: use background-size cover for about banner

- src/components/swap/styleds.tsx
- src/pages/Landing/index.tsx
- src/pages/Swap/index.tsx
> fix: pointer events on Swap

- src/pages/About/index.tsx
Decreases gap and font size and adds margin to external link arrow icon
> fix: responsive styling for info button

- src/pages/Landing/index.tsx
Moves gradient up to obscure more of the swap box
> style: add transition to button and move gradient up

- src/pages/Landing/index.tsx
Tweaks landing page buttons to match Figma.
> fix: tweak landing page buttons

- .github/workflows/release.yaml
Reverts Uniswap/interface#5615
> build: re-start scheduled builds

- cypress.config.ts
- cypress/e2e/landing.test.ts
- cypress/e2e/remove-liquidity.test.ts
- cypress/e2e/wallet-dropdown.test.ts
- src/components/WalletDropdown/index.tsx
- src/components/Web3Status/index.tsx
- src/featureFlags/flags/landingPage.ts
Just want the PR ready for when we decide to deploy this change
> feat: release new landing page

- src/hooks/useScreenSize.ts
- src/nft/hooks/useIsMobile.ts
- src/nft/hooks/useIsTablet.ts
- src/nft/utils/scrollToTop.ts
* this is implementing new useScreenHook to deprecate useIsTablet and useIsMobile
> chore: adding useScreenSize hook

- .github/workflows/revert.yaml
Adds a revert.yaml workflow to revert the deployment to a prior tag.
> build: add a revert workflow

- src/components/NavBar/index.tsx
- src/components/swap/styleds.tsx
- src/pages/App.tsx
- src/pages/Pool/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2407?atlOrigin=eyJpIjoiNGFiZDRlOWMxNzRlNDVmYzlmMmQwYTllY2JmMmFjMTIiLCJwIjoiaiJ9
note: I opened the vercel build link on my mobile device and tested in safari. you can't see the bug in the safari desktop mobile developer testing env.
> fix: jumpy nav on safari mweb

- src/featureFlags/flags/landingPage.ts
Reverts Uniswap/interface#5679
> chore: turn landing page flag on

- src/pages/Landing/index.tsx
Avoids the state for now where on mobile the button isn't clickable
> fix: allow landing page scroll

- src/pages/Landing/index.tsx
Reverts Uniswap/interface#5692
> fix: Revert "fix: allow landing page scroll"

- src/pages/Landing/index.tsx
Previous fix worked for some browsers, but not on certain safari browsers.
> fix: used sticky position for landing page content

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/landingPage.ts
- src/pages/App.tsx
- src/pages/Landing/index.tsx
Can merge this after release happens
> chore: remove landing page flag

- package.json
- yarn.lock
bumps to `@uniswap/conedison@^1.1.1`
> fix: bump conedison

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/landingRedirect.ts
Will be used for redirecting the user when their wallet is already connected.
> chore: add landing page redirect flag

- src/nft/components/profile/list/ListPage.tsx
- src/nft/components/profile/list/NFTListingsGrid.tsx
https://uniswaplabs.atlassian.net/browse/WEB-1893
Made header on list sticky
> fix: adding fixed header

- src/nft/components/collection/Card.tsx
- src/nft/components/collection/CollectionAsset.tsx
- src/nft/components/collection/CollectionNfts.tsx
- src/nft/components/profile/view/ViewMyNftsAsset.tsx
- src/nft/types/collection/collection.ts
* updates the cards to use custom aspect ratio if able
> style: updating cards to use appropriate aspect ratio

- cypress/e2e/nfts.test.ts
I believe this modal was removed and Updating tests to reflect that
> fix: modal was removed, updating test to accommodate 

- src/state/user/reducer.ts
> chore: remove unused NFT redux user reducer state

- .env.production
Quick PR so that I can trigger a release action manually afterwards
> feat: enable Sentry

- src/nft/components/collection/TransactionCompleteModal.tsx
- src/nft/utils/asset.ts
- Updates the share icon shown in the top right of the transaction complete modal to be a gray Twitter icon
- Wrap static text in Trans component for internationalization
- Update Tweet text to tag @Uniswap
> feat: update tx complete share icon

- .github/workflows/release.yaml
Code freeze is over, restarting daily releases.
Undoes #5765
> build: restart daily releases

- package.json
- src/components/FiatOnrampAnnouncement/index.tsx
- src/components/WalletDropdown/AuthenticatedHeader.tsx
- src/components/Web3Status/index.tsx
- src/state/application/hooks.ts
- yarn.lock
https://uniswaplabs.atlassian.net/browse/WEB-2597
[WEB-2597]: https://uniswaplabs.atlassian.net/browse/WEB-2597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use analytics-events exported event names for sendAnalyticsEvent calls

- src/graphql/data/__generated__/types-and-hooks.ts
* was missing from generated type
> fix: updating generated graphql types

- src/nft/components/profile/list/NFTListRow.tsx
No functional difference, should only deprecate use of VE in this file
> chore: Migrate NFTListRow from vanilla-extract to styled-components

- src/components/Tokens/TokenDetails/BalanceSummary.tsx
Updates styling of the "Your balance" component to match the [design spec](https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=2071%3A72058)
https://uniswaplabs.atlassian.net/browse/WEB-1122?atlOrigin=eyJpIjoiYTVmOTdmZGU1ZTgwNGYyNWFkODIyMDBmMGFkZDJkM2MiLCJwIjoiaiJ9
[WEB-1122]: https://uniswaplabs.atlassian.net/browse/WEB-1122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: adjust the styling of BalanceSummary component to match design

- src/graphql/data/nft/Asset.ts
- src/nft/components/collection/CollectionNfts.tsx
- src/nft/components/collection/Sweep.tsx
- src/nft/utils/asset.ts
* assets in sudoswap xyk pools were crashing the app this prevents them from being shown
> fix: do not show assets in sudoswap xyk pools

- src/nft/components/profile/list/ListPage.css.ts
- src/nft/components/profile/list/MarketplaceRow.tsx
- src/nft/components/profile/list/NFTListRow.tsx
- src/nft/components/profile/list/RoyaltyTooltip.tsx
- src/nft/components/profile/list/shared.tsx
- migrated component styles from VE to styled-components
- moved shared style to shared style file
- improve tooltip styles
> chore: migrate MarketplaceRow to styled-components

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/nftListV2.ts
We're redesigning the sell page. To not affect the current page this new page will be hidden behind a feature flag.
> feat: add nft list page v2 feature flag

- src/pages/Pool/CTACards.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2689?atlOrigin=eyJpIjoiMGE5MmI2N2ZjZjhlNDc3NThkMTlmZjRkNzc5YjA3OGQiLCJwIjoiaiJ9
> fix: correct link on add liquidity page

- src/graphql/data/nft/Asset.ts
- src/nft/components/collection/CollectionAsset.tsx
- src/nft/components/collection/CollectionNfts.tsx
- src/nft/components/collection/Sweep.tsx
- src/nft/utils/asset.ts
- src/nft/utils/pooledAssets.ts
* This scales the prices on the frontend to handle sudoswap xyk pool
* good collection to test: White Hearts 1.0
> feat: adding price scaling for sudoswap xyk pool

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/payWithAnyToken.ts
* creates feature flag for pay with any token
> feat: pay with any token feature flag

- src/nft/components/bag/BagFooter.tsx
* creates initial pay with any token setup
* dropdown does not change the input currency
* ETH is the only input currency currently for demonstration purposes
* does not affect the previous implementation
> feat: initial pay with any token setup

- src/components/WalletDropdown/AuthenticatedHeader.tsx
- src/components/WalletDropdown/DefaultMenu.tsx
- src/components/WalletDropdown/index.tsx
> fix: spacing and other small cosmetic errors in for account dropdown

- package.json
- yarn.lock
> build: upgrade @uniswap/widgets@2.25.1

- src/components/WalletDropdown/SlideOutMenu.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2794
after:
> fix: txn and language dropdown styling fix

- src/pages/Swap/index.tsx
Changes the allowance buttons to use non-warning colors.
> fix: use non-warning colors for allowance button

- src/featureFlags/flags/permit2.ts
Reverts Uniswap/interface#5833
> revert: "feat: enable permit2"

- cypress/e2e/token-explore-filter.test.ts
Skips flakey e2e tests added by #5839
> test: skip token explore filter tests

- src/nft/components/bag/BagFooter.tsx
- src/nft/components/bag/tokenSelector/BagTokenSelectorModal.tsx
- src/nft/components/bag/tokenSelector/CurrencyRow.tsx
- src/nft/hooks/useTokenInput.ts
* this allows you to select and updates the input token
* does not actually update price
> feat: select input token for pay with any token

- craco.config.cjs
- package.json
- src/components/Widget/settings.ts
- src/components/Widget/theme.ts
- yarn.lock
adds missing colors to the widget theme. some new colors were added in the last release.
> fix: widget theme integration

- src/components/Polling/ChainConnectivityWarning.tsx
- src/components/Polling/index.tsx
- src/constants/chainInfo.ts
- src/hooks/useIsLandingPage.ts
- src/hooks/useMachineTime.ts
- src/pages/App.tsx
Reverts Uniswap/interface#5873
Should only be removing gwei indicator, not block number as well.
> fix: Revert "fix: remove gwei indicator", restore block number

- src/components/Tokens/TokenDetails/ChartSection.tsx
- src/components/Tokens/TokenDetails/index.tsx
- src/components/Tokens/TokenTable/TokenTable.tsx
- src/graphql/data/Token.ts
- src/graphql/data/TokenPrice.ts
- src/graphql/data/TopTokens.ts
- src/graphql/data/__generated__/types-and-hooks.ts
- src/graphql/data/apollo.ts
- src/graphql/data/util.tsx
- src/pages/TokenDetails/index.tsx
Removes loading state when navigating to already-viewed Token Details/Explore pages, also adds polling to Token Explore
> feat: caching and polling on apollo token queries

- src/nft/components/bag/BagFooter.tsx
- src/nft/components/bag/tokenSelector/BagTokenSelectorModal.tsx
- src/nft/components/bag/tokenSelector/CurrencyRow.tsx
* displays price of new token
* does not implement loading indicator
> feat: quote token price for nfts

- src/nft/components/profile/list/ListPage.tsx
- src/nft/components/profile/list/Modal/ListModal.tsx
- src/nft/pages/profile/profile.tsx
- src/nft/pages/profile/shared.ts
Adds mobile support for Listing Page V2 and the Listing Modal
> feat: [ListV2] Add mobile styles

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/Tokens/TokenDetails/Skeleton.tsx
- src/components/Tokens/TokenDetails/index.tsx
- src/components/Widget/index.tsx
- src/components/Widget/inputs.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/swapWidget.ts
- src/pages/Swap/index.tsx
adds a new feature flag to the interface for toggling the Widget in the main swap page.
also made a small change to the Widget code so we can preset the INPUT currency instead of the OUTPUT currency
> feat: create feature flag for swap widget

- package.json
- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/Tokens/TokenDetails/Skeleton.tsx
- src/components/Tokens/TokenDetails/index.tsx
- src/components/Widget/index.tsx
- src/components/Widget/inputs.tsx
- src/components/Widget/theme.ts
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/swapWidget.ts
- src/graphql/data/__generated__/types-and-hooks.ts
- src/pages/Swap/index.tsx
- yarn.lock
upgrade our widget version and provide a set of zIndex definitions (this is needed to make the widget dialogs work correctly)
> feat: add zIndex to widget theme

- .github/workflows/test.yml
- README.md
https://uniswaplabs.atlassian.net/browse/WEB-2733
> feat: add jest coverage to github action

- src/pages/Landing/index.tsx
fixes the landing page styling for the widget-enabled variant (see preview link for the difference between test and control)
> fix: landing page styling of widget

- src/components/DoubleLogo/index.tsx
- src/components/Logo/AssetLogo.tsx
- src/components/Logo/CurrencyLogo.tsx
- src/components/NavBar/SuggestionRow.tsx
- src/components/Tokens/TokenDetails/BalanceSummary.tsx
- src/components/Tokens/TokenDetails/Skeleton.tsx
- src/components/Tokens/TokenDetails/index.tsx
- src/components/Tokens/TokenTable/TokenRow.tsx
Updates L2 icon to be part of AssetLogo component. Pre-req for moving to widget repo
> refactor: L2 icons in component

- src/constants/governance.ts
https://ethereum.org/en/developers/docs/blocks/#block-time
> fix: block time is 12 seconds now

- src/nft/components/profile/list/Dropdown.tsx
- src/nft/components/profile/list/MarketplaceRow.tsx
- src/nft/components/profile/list/NFTListingsGrid.tsx
- src/nft/components/profile/list/SelectMarketplacesDropdown.tsx
- src/nft/components/profile/list/SetDurationModal.tsx
- src/nft/types/common/common.ts
Updates price and duration dropdowns to the latest design. Created a re-useable dropdown component used between the two.
Duration
Price
Mobile:
> feat: [ListV2] Update price and duration dropdowns

- src/constants/lists.ts
https://uniswaplabs.atlassian.net/browse/WEB-2687
> fix: remove roll list

- src/nft/components/bag/profile/ListingButton.tsx
- src/nft/components/profile/list/ListPage.tsx
- src/nft/components/profile/list/MarketplaceRow.tsx
- src/nft/components/profile/list/NFTListRow.tsx
- src/nft/components/profile/list/NFTListingsGrid.tsx
- src/nft/components/profile/list/SetDurationModal.tsx
- src/nft/pages/profile/profile.tsx
- src/nft/pages/profile/shared.ts
A couple of changes requested from the debugging session:
- Improved grid responsiveness at tablet and mobile breakpoints
- Dynamic button width on mobile
- Duration warning text no longer wraps on large inputs
- Don't allow listings at the same price as current
- Don't show loading spinner on listing button in V2
> feat: [ListV2] Changes based off Bug Bash

- src/featureFlags/flags/nftListV2.ts
Enables ListV2 Feature Flag for release in later today.
> feat: [ListV2] Enable ListV2 feature flag

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/gqlRouting.ts
- src/graphql/data/__generated__/types-and-hooks.ts
- src/graphql/data/nft/Routing.ts
- src/nft/components/bag/Bag.tsx
- src/nft/components/bag/bag.test.tsx
- src/test-utils.tsx
* the boilerplate for the gql routing endpoint
* feature flags for gql routing
> chore: setting up feature flags and boilerplate gql for routing gql endpoint

- src/components/NavBar/MenuDropdown.tsx
> feat: add feedback link to ... menu

- src/utils/swapErrorToUserReadableMessage.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2809?atlOrigin=eyJpIjoiYTdkNmFjMDk2YzU4NDAyY2JkOWJkNDZjNWQ2OWMxNmIiLCJwIjoiaiJ9
> fix: handle wallets that don't send default 4001 error code for user rejected txns

- src/components/Tokens/TokenDetails/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-1992?atlOrigin=eyJpIjoiM2Q5MGFjOWIwY2UzNGQ3M2IyMTE2NDFjNzE0YjAyNGMiLCJwIjoiaiJ9
> fix: Web 1992 token details update blocked token detail pages

- src/components/Tokens/TokenTable/TokenRow.tsx
- src/components/Tokens/TokenTable/TokenTable.tsx
- src/graphql/data/TopTokens.ts
https://uniswaplabs.atlassian.net/browse/WEB-2855
> fix: use general sort rank instead of only volume rank for row numbers

- src/components/NavBar/index.tsx
- src/pages/MigrateV2/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2677?atlOrigin=eyJpIjoiZjAyMWU0NzU2OGEyNGE1MjllNWQwNzY0ZTkwYjI3MWUiLCJwIjoiaiJ9
> fix: update some urls to match current page structure

- src/components/PositionList/index.tsx
- src/components/PositionListItem/PositionListItem.test.tsx
- src/components/PositionListItem/index.tsx
- src/pages/Pool/index.tsx
- src/utils/urlChecks.test.ts
- src/utils/urlChecks.ts
https://uniswaplabs.atlassian.net/browse/WEB-2802
> fix: don't render LP position when token name or symbol includes a url

- src/components/Tokens/TokenTable/TokenRow.tsx
https://uniswapteam.slack.com/archives/C04D07TQBT4/p1676319727906339
> fix: correct copy on TVL 

- package.json
- yarn.lock
Resolves an issue with permit signatures not working with smart contract wallets overloading the signature field.
> fix: allow signing with smart contract wallets

- cypress/e2e/nfts.test.ts
- cypress/e2e/pool.test.ts
- cypress/support/e2e.ts
- src/utils/nativeTokens.ts
testing some changes to reduce flakiness in e2e tests
> fix: wait for page to load in e2e tests

- src/components/FiatOnrampModal/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2810
> feat: support moonpay iframe theme

- cypress/e2e/wallet-dropdown.test.ts
> fix: change e2e test language

- src/featureFlags/flags/gqlRouting.ts
- src/featureFlags/flags/payWithAnyToken.ts
- src/graphql/data/__generated__/types-and-hooks.ts
** Not to be merged before 8:30 am 2/22/23
> feat: enable pay with any token

- src/components/FiatOnrampModal/index.tsx
> fix: darkmode FoR iframe wrapper background color

- src/nft/components/bag/Bag.tsx
- src/nft/components/modals/Overlay.css.ts
- src/nft/pages/collection/index.tsx
the z-index needs to decrease and not increase to show correctly on mobile
> fix: token selector correct zIndex on mobile for pwat

- src/pages/MigrateV2/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2632
> fix: back arrow from migration should take you to v3 pool page

- src/constants/TokenLogoLookupTable.ts
- src/hooks/Tokens.ts
- src/utils/listSort.ts
- src/utils/nativeTokens.ts
https://uniswaplabs.atlassian.net/browse/WEB-2877?atlOrigin=eyJpIjoiYjFkNDYxNWIyMWJhNDAwMzkxMWFhOWMzNTY5MGIyZWEiLCJwIjoiaiJ9
> fix: token list load issue WEB-2083

- src/nft/pages/collection/index.tsx
- src/nft/queries/genie/SearchCollectionsFetcher.ts
- src/nft/queries/genie/TrendingCollectionsFetcher.ts
- src/nft/utils/collection.ts
Adds a blocklist of ip infringing collections. The collections will not show on the Explore page, search results, or have a viewable collection page.
> feat: add collection blocklist for ip infringement

- package.json
- yarn.lock
Various updates from widget for the swap migration
> chore: update widget

- package.json
- yarn.lock
This means that cancelled user requests are sent with a 4001 error code, vs being an undefined error.
> chore: update coinbase-wallet sdk

- src/nft/hooks/useFetchAssets.ts
- src/nft/hooks/usePurchaseAssets.ts
- src/nft/hooks/useSendTransaction.ts
- src/nft/utils/bag.ts
- src/nft/utils/txRoute/combineItemsWithTxRoute.ts
- src/nft/utils/updatedAssets.ts
* note didn't refactor the old fetch code since it will be removed
> chore: refactor useFetchAssets to make it more readable

- src/components/NavBar/SuggestionRow.tsx
> fix: hide missing % changes/prices

- package.json
- yarn.lock
Latest, which adds current ethers version in widget and also the smart-order-router upgrade in both
> build: upgrade widgets version and smart-order-router

- src/components/NetworkAlert/NetworkAlert.tsx
- src/components/swap/styleds.tsx
- src/pages/Swap/index.tsx
- src/theme/components/RadialGradientByChainUpdater.ts
current dark mode treatment from fred: 
PENDING: radial gradient for background design from fred, wip.
> fix: design treatment from @infredible for bnb support

- cypress/e2e/add-liquidity.test.ts
- cypress/e2e/remove-liquidity.test.ts
- cypress/e2e/universal-search.test.ts
- cypress/support/ethereum.ts
> test: e2e tsts for goerli

- cypress/support/ethereum.ts
typo from Uniswap/interface#6066
> fix: remove $ in hexlified string

- src/nft/components/collection/CollectionNfts.tsx
> fix: react router updated appropriate fix

- package.json
- src/constants/misc.ts
- src/hooks/useUniversalRouter.ts
- src/nft/components/bag/Bag.tsx
- src/nft/hooks/useSendTransaction.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/Pool/PositionPage.tsx
- src/pages/RemoveLiquidity/V3.tsx
- src/utils/calculateGasMargin.ts
- yarn.lock
Reverts Uniswap/interface#6073
This is leading to LP add liquidity to fail.
> fix: Revert "fix: deep link by swapping sooner after user interaction"

- .github/dependabot.yml
adds reviewers to dependabot PRs
> chore: add reviewers to dependabot PRs

- package.json
- src/components/WalletModal/index.tsx
- src/components/Widget/inputs.tsx
- yarn.lock
https://user-images.githubusercontent.com/66155195/223581915-27304a00-2396-45a0-941f-532b3f0bdad8.mov
https://user-images.githubusercontent.com/66155195/223581636-cb89451f-61a6-4f31-95b3-61d233985385.mov
> fix: unsupported chain bugs

- package.json
- yarn.lock
This removes duplicate versions of web3-react and zustand from being installed.
> chore: upgrade widgets

- src/components/NavBar/SearchBar.tsx
- src/graphql/data/__generated__/types-and-hooks.ts
- src/graphql/data/nft/Collection.ts
- src/graphql/data/nft/CollectionSearch.ts
- Adds hook to use GQL query for searching collections
- Converts some functionality of Collection query to shared function
- Conditionally call search based off feature flag
> feat: NFT Collection Search via GraphQL

- package.json
- src/graphql/data/__generated__/types-and-hooks.ts
- yarn.lock
upgrade widget for latest fixes and features
> feat: upgrade widget again

- src/assets/svg/celo_logo.svg
[Brand Update](https://blog.celo.org/the-celoevolution-is-here-a-note-from-our-founders-6b458336303b)
> chore: update Celo logo with new version

- src/components/Button/index.tsx
- src/pages/AddLiquidity/index.tsx
Removes this warning as people know how concentrated liquidity works now.
> fix: remove full range warning in AddLiquidity

- scripts/test-size.js
Updates the test sizes specified in test-size.js, and improves the message output to the terminal.
> fix: update test-size

- src/components/TaxServiceModal/index.tsx
- fix: Update tax buttons to use HTML instead of js
> fix: Use html for linking to tax services

- src/components/PositionListItem/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2138?atlOrigin=eyJpIjoiOWVkMDU1NTFhM2QwNDg3MDg3NzZhN2NiN2ZiNzNmYmUiLCJwIjoiaiJ9
before:
after:
> fix: fix overflowing lp ui

- src/components/Widget/inputs.tsx
fixes the "back" bug with TDP widget inputs and cleans up the logic in this hook a little bit
main swap
https://user-images.githubusercontent.com/66155195/224459487-1a0bd30b-c270-4154-9c58-cacb02875f5f.mov
TDP and "back" bug fixed
https://user-images.githubusercontent.com/66155195/224459534-19df1d0f-4463-4cbd-8af6-fb60878800cb.mov
> fix: allow defaultTokens to reset state in Widget

- cypress/e2e/token-details.test.ts
- src/components/CurrencyInputPanel/FiatValue.tsx
- src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
- src/components/CurrencyInputPanel/index.tsx
- src/components/NavBar/SuggestionRow.tsx
- src/components/Tokens/TokenDetails/ChartSection.tsx
- src/components/Tokens/TokenDetails/PriceChart.tsx
- src/components/Tokens/TokenDetails/index.tsx
- src/components/Tokens/TokenTable/TokenRow.tsx
- src/components/Widget/transactions.ts
- src/components/swap/ConfirmSwapModal.tsx
- src/components/swap/SwapModalFooter.tsx
- src/components/swap/SwapModalHeader.tsx
- src/components/swap/TradePrice.tsx
- src/graphql/data/RecentlySearched.ts
- src/graphql/data/SearchTokens.ts
- src/graphql/data/Token.ts
- src/graphql/data/TokenPrice.ts
- src/graphql/data/TokenSpotPrice.ts
- src/graphql/data/TopTokens.ts
- src/graphql/data/TrendingTokens.ts
- src/graphql/data/util.tsx
- src/hooks/useSwapCallback.tsx
- src/hooks/useUSDPrice.ts
- src/hooks/useUniversalRouter.ts
- src/lib/utils/analytics.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/Swap/index.tsx
- src/state/routing/useRoutingAPITrade.ts
- src/utils/computeFiatValuePriceImpact.tsx
returns TDP to use on-chain price due to backend issues, but returns swap to use off-chain price to unblock bnb fixes
> fix: pricing sources

- src/nft/utils/collection.ts
We were requested to block a collection for ip infringement
collection: [0x32d7e58933fceea6b73a13f8e30605d80915b616](https://app.uniswap.org/#/nfts/collection/0x32d7e58933fceea6b73a13f8e30605d80915b616)
> feat: add infringing collection to blocklist

- src/pages/Pool/PositionPage.tsx
- src/utils/formatTickPrice.ts
> feat: use tx formatting for PositionPage cards

- src/state/routing/slice.ts
Adds a performance trace for `quote`.
> feat: trace quote

- package.json
- yarn.lock
TSIA
will check the widget input test case list on the preview link
> feat: upgrade widget

- src/hooks/usePoolTickData.ts
fixes lp chart not working after refactor PR yesterday
> fix: use proper apollo client for ticks query

- src/components/NavBar/MenuDropdown.tsx
- src/components/TaxServiceModal/TaxServiceBanner.tsx
- src/state/application/hooks.ts
- src/state/application/reducer.ts
> feat: add tax service discount to help menu

- src/components/NavBar/SearchBarDropdown.tsx
- should only show up on BNB
- will be deactivated automatically when we add a backend name mapping for BNB
> feat: bnb network notif badge in search

- scripts/fetch-schema.js
- uses npx instead of relying on the package already being present
- uses node's `fs` package instead of `tee` to write to disk
- logs error if there is one
> fix: improve fetch-schema logging and platform support

- src/components/Badge/RangeBadge.tsx
- src/components/PositionListItem/index.tsx
- src/nft/themes/darkTheme.ts
- src/theme/colors.ts
figma: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=1841-40683&t=KkDVTI0Fc4fcHUxS-4
Updated:
Before:
> feat: design refresh on pool list items

- src/components/NavBar/MenuDropdown.tsx
https://uniswaplabs.atlassian.net/browse/WEB-3078
> fix: update tax services copy

- codecov.yml
- set patch coverage to 80%
- reduce tolerance threshold
- remove unused keys in yaml
> chore: update codecov yaml

- src/state/user/hooks.test.tsx
- src/state/user/reducer.test.ts
- src/state/user/reducer.ts
- src/state/wallets/hooks.test.tsx
- src/state/wallets/reducer.test.ts
adding unit tests for basic redux functionality
`yarn test`
> test: add unit test coverage to some redux state files

- .github/pull_request_template.md
add notes about testing mobile layouts to the test plan prompts
_[Summary of change, motivation, and context.]_
- _Link to JIRA ticket, slack thread, or relevant docs helpful for providing context to reviewers._
- _Note: Your PR title must follow conventions [outlined here](https://github.com/Uniswap/interface#contributions)._
| Before           | After           |
| ---------------- |-----------------|
|  _insert_before_ | _insert_after_  |
_[Steps of how you are testing the change and ensuring no regression.]_
> feat: Update pull_request_template.md

- .github/pull_request_template.md
Updates the `pull_request_template.md` to improve usability and add additional instructions.
The majority of changes are moving instructions to comments, which are not rendered in the preview.
To see the updated template, attempt to edit this PR description and view the content below this line:
_JIRA ticket:_
| Before                  | After (Desktop)        | After (Mobile)         |
| ----------------------- |----------------------- | ---------------------- |
|  |  |  |
1.
> docs: use comments for pull_request_template

- src/lib/i18n.tsx
Removes the duplicate error reporting from a locale failing to load. This is already reported as a ChunkLoadError through the ErrorBoundary or the global onerror handler.
> fix: do not double-report i18n exception

- src/components/AccountDrawer/DownloadButton.tsx
- src/components/AccountDrawer/UniwalletModal.tsx
Updates the link and description for the wallet
| Before       | After |
| ------------ |---------------- |
| <img width="427" alt="image" src="https://user-images.githubusercontent.com/39385577/231300946-acf95798-68cf-4230-a782-5b86e69b72ea.png"> | <img width="427" alt="image" src="https://user-images.githubusercontent.com/39385577/231300874-45f9eb04-12ce-449e-bf13-db1d27ab6882.png">      | paste_after    |
> fix: use updated wallet links/language

- src/components/WalletModal/index.tsx
Adds more logging to tryActivation callback in WalletModal/index.tsx in an attempt to uncover the MetaMask stuck-loading0-state bug
[Jira Ticket](https://uniswaplabs.atlassian.net/browse/WEB-3162)
> feat: log connection activation/errors

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/nftDetails.ts
- src/nft/components/details/NftDetails.tsx
- src/nft/pages/asset/Asset.tsx
sets up new feature flag for details v2 (also created with statsig) - also creates a default page for v2 details
> feat: creating feature flag for details v2 page

- src/pages/Landing/index.tsx
Translates "Get started" on the landing page.
> fix: translate "Get started" on landing page

- src/components/AccountDrawer/DownloadButton.tsx
Update to app store link from download button (which renders on iOS mweb only) so that we can track conversion.
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1681922156180509
- Open preview link on iOS mobile
- Click download app
- Verify it links to updated url with tracking params
n/a
> feat: Update to app store link with tracking params

- cypress/e2e/swap.test.ts
- cypress/e2e/token-details.test.ts
- src/components/Settings/index.tsx
- src/pages/Swap/index.tsx
updates the swap flow e2e tests - adds some test cases, and fixes and re-enables an existing test case.
also adds some e2e tests for the widget on TDP
https://uniswaplabs.atlassian.net/browse/WEB-3164?atlOrigin=eyJpIjoiYTlkZWI1ZTQ2NDE5NDYzNGI3ZGNlYWQ2MjA4ZjI0NDYiLCJwIjoiaiJ9
tests pass
> test: swap flow cypress tests

- cypress/e2e/swap.test.ts
- cypress/support/e2e.ts
- cypress/support/hardhat.ts
- src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
- src/components/SearchModal/CurrencySearch.tsx
- src/components/TransactionConfirmationModal/index.tsx
- src/constants/addresses.ts
- src/constants/tokens.ts
- src/utils/constructSameAddressMap.ts
This PR includes an example cypress test which:
1. accesses initial chain state w/ idiomatic cypress syntax (`cy.then`)
2. fills out and executes an exactOutput swap
3. asserts expected UI state
4. asserts expected chain state
> feat: example swap test

- src/nft/components/collection/CollectionAsset.test.tsx
- src/nft/components/collection/__snapshots__/CollectionAsset.test.tsx.snap
- src/nft/components/profile/view/ViewMyNftsAsset.test.tsx
- src/nft/components/profile/view/__snapshots__/ViewMyNftsAsset.test.tsx.snap
- src/test-utils/constants.ts
* Adding snapshot testings for collection assets and wallet assets
> chore: adding snapshot tests for nftCard components

- src/tracing/errors.test.ts
- src/tracing/errors.ts
Similar to https://github.com/Uniswap/interface/pull/6365, except handles CSS chunks additionally. Abstracts the function that checks window.performance.
_JIRA ticket:_ https://uniswaplabs.atlassian.net/browse/INFRA-172
> fix: filter CSS related 499 chunk errors

- src/components/swap/SwapDetailsDropdown.tsx
removes the info icon tooltip from the toolbar - this is in accordance with the new designs mentioned in the jira ticket.
_JIRA ticket:_ https://uniswaplabs.atlassian.net/browse/WEB-3239
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1682007265763589
| Before       | After (Desktop) | After (Mobile) |
| ------------ |---------------- | -------------- |
| <img width="753" alt="image" src="https://user-images.githubusercontent.com/66155195/233441826-130d1868-2ca4-4d8a-b93f-7fd0831a71b8.png"> | <img width="753" alt="image" src="https://user-images.githubusercontent.com/66155195/233441768-0be73681-d40b-455c-98e3-c51f298f2a54.png">      | <img width="919" alt="image" src="https://user-images.githubusercontent.com/66155195/233703240-5e8c520a-1e8b-4423-a9bd-becf75993022.png"> …
> fix: remove the info icon popover from the toolbar

- .github/workflows/test.yml
- codecov.yml
adds flags to the codecov report uploads so they are separated by type of test (unit, e2e).
adds flag configuration to `codecov.yml` so the full feature set is unlocked
_Relevant docs:_ https://docs.codecov.com/docs/flags
_Jira Ticket :_ https://uniswaplabs.atlassian.net/browse/WEB-3061?atlOrigin=eyJpIjoiMmRmNGQ4Mzc1YTNjNDgwZDhlOGU4MWZmYmZkNjIzMWEiLCJwIjoiaiJ9
> feat: use codecov flags

- .github/workflows/test.yml
Uses two cores for unit tests on GitHub Actions to speed up tests. By default, jest will use 50% of cores, but this is unnecessary on a dedicated CI machine.
> test: shard GH action unit tests

- src/state/lists/utils.test.ts
Expect and squelch the console.debug statements from tests.
_JIRA ticket:_ Partial fix for https://uniswaplabs.atlassian.net/browse/WEB-3132?search_id=f82d1daf-33c0-40da-8e38-097a920b30eb
> test: squelch console.debug

- .github/workflows/test.yml
- package.json
- Updates `yarn test` to not display coverage for faster testing
- Updates `test.yml` to not use `--silent`, and to display coverage
_JIRA ticket:_ https://uniswaplabs.atlassian.net/browse/WEB-3132
> build: update default test settings

- src/nft/components/bag/Bag.tsx
- src/nft/hooks/useSubscribeScrollState.ts
During the creation of the Traits component in the new details page we created a hook to handle scroll state for dynamic scrim/border behaviour. We added a tech debt task to update the Bag to use this new hook.
_JIRA ticket:_ https://uniswaplabs.atlassian.net/browse/NFT-1190
Working scroll for both Bag and new Traits component
> chore: refactor Bag to use scroll hook

- src/hooks/useUniversalRouter.ts
- src/pages/Swap/index.tsx
Add analytics context to swap flow events as event properties. specifically we care mostly about the `page` property because we want to differentiate between TDP and main swap page.
1.  set `debug: true` on the amplitude initialization and view the events in chrome inspector - see that the `page` is not included
> fix: add amplitude page context to swap flow events

- cypress/e2e/swap.test.ts
this test is flakey and needs to be fixed
> test: skip flakey e2e test

- package.json
- yarn.lock
- Bumps to latest token-lists version (1.0.0-beta.31)
- this latest version allows empty name and symbol in token lists, fixing current validation errors we see on coingecko token list. also fixes issue with tokens on coingecko list not being searchable in swap selector. 
_JIRA ticket:_
| Before       | After (Desktop) | After (Mobile) |
| ------------ |---------------- | -------------- |
| <img width="339" alt="image" src="https://github.com/Uniswap/interface/assets/105068213/73dc4788-cf3a-499e-b089-0a9abfb79ea9"> | <img width="431" alt="image" src="https://github.com/Uniswap/interface/assets/105068213/9e7f7944-d4ce-448e-9d5d-cbfde4eb2842">     | <img width="288" alt="image" src="https://github.com/Uniswap/interface/assets/105068213/98aed9c2-b9da-4fbe-971c …
> chore(deps): bump @uniswap/token-lists

- src/serviceWorker/index.ts
- src/serviceWorker/utils.test.ts
- src/serviceWorker/utils.ts
Addresses this comment: https://github.com/Uniswap/interface/pull/6486#discussion_r1185340642
> refactor: return onDemandEntries instead of mediaURLs

- .github/workflows/4-deploy-to-prod.yml
This PR effectively duplicates our standard `release.yml` to deploy from our `releases/prod` branch for the new CI configuration.
Note that this PR intoduces the `prod` environment which will contain the deployment secrets necessary for this new deployment pipeline.
Once all of the CI-related PRs have been merged we will do manual end-to-end testing of the whole staging and production CI flow.
> ci: GH action for deploying to production

- .github/CODEOWNERS
Updates workflow CODEOWNERS to a new web-admins group, to disambiguate admins from reviewers.
Workflows control deployment flows (CI/CD), so this should be restricted to admins, not reviewers.
> build: update workflow owners

- .github/actions/report/action.yml
- .github/workflows/test.yml
- src/index.tsx
Reports test failures via Slack
_Slack thread:_ https://uniswapteam.slack.com/archives/C02T729PMQE/p1683730705255649
> build: report test failures via Slack

- .github/workflows/1-main-to-staging.yml
- .github/workflows/3-staging-to-prod.yml
This PR updates our CI pipeline to correctly configure git committer before trying to do any git pushes.
> ci: More CI pipeline fixes

- src/nft/components/details/detailsV2/DataPageTraits.tsx
- src/nft/components/details/detailsV2/TraitRow.tsx
- src/nft/components/details/detailsV2/__snapshots__/DataPageTraits.test.tsx.snap
- Hide quantity column of Traits table when on small screens
_Figma:_ https://www.figma.com/file/jG2aAlirIlv3uEtMIGUpo1/%F0%9F%8F%99%EF%B8%8F-Detail-Page-v2?type=design&node-id=1686%3A104012&t=fWRAJuqjiGTk4r52-1
- updated snapshot
> feat: [DetailsV2] Mobile support for traits

- src/nft/components/details/detailsV2/InfoChips.tsx
_JIRA ticket:_
| Before       | After (Desktop) | After (Mobile) |
| ------------ |---------------- | -------------- |
| paste_before | past_after      | paste_after    |
1.
> feat: using flexwrap and a break for top traits

- src/nft/components/details/detailsV2/DataPage.tsx
- src/nft/components/details/detailsV2/__snapshots__/DataPage.test.tsx.snap
This was the result of a merge conflict and the container wasn't re-added
Some reference screenshots:
Without padding container
With padding container
> fix: use padding component

- .github/workflows/2-deploy-to-staging.yml
- .github/workflows/4-deploy-to-prod.yml
- .github/workflows/notify-slack-on-release-merge.yml
This PR introduces the following fixes to the deployment CI pipeline:
- Truncates Slack merge messages to 3,000 characters (API limit)
- Emits Slack messages for (1) a build starting, (2) a deploy starting, and (3) a deploy completing
- Updates Cloudflare pages deployments to specify `main` branch
> ci: Final CI fixes pass

- .github/workflows/4-deploy-to-prod.yml
This PR fixes some broken spacing in the production deployment CI job yaml definition, which has in turn broken the job.
> ci: Fix YAML spacing

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/unifiedRouter.ts
adds the client side code for a new feature flag to control the unified routing API usage
_JIRA ticket:_
_Slack thread:_ https://uniswapteam.slack.com/archives/C055BQ3P83S/p1684428397915649
> feat: add feature flag for URA

- .github/workflows/notify-slack-on-release-merge.yml
Runs slack notification workflow from a protected environment.
_Linear ticket:_ https://linear.app/uniswap/issue/INFRA-12/isolate-the-slack-webhook-url-to-an-environment
> build: notify from notify/releases

- src/components/About/Card.tsx
React was complaining about these
> fix: use ephemeral props for styled component

- src/pages/Swap/index.tsx
logs an event to amplitude when the top-level swap button is clicked. previously we only logged the clicks on the "confirm swap" button in the subsequent modal
> feat: log swap button click

- .github/workflows/release.yaml
Disables the scheduled release (M-Th), in favor of our new release pipeline.
> build: disable scheduled releases

- src/components/Web3Provider/index.test.tsx
- src/components/Web3Provider/index.tsx
- src/connection/activate.ts
- src/pages/App.tsx
- src/utils/urlRoutes.test.ts
- src/utils/urlRoutes.ts
adds the `InterfacePageName` to the analytics event `WALLET_CONNECT_TXN_COMPLETED`
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-1990/misc-logging-analytics-improvements
auto-connect on swap page:
manual connect on swap page:
token page:
> feat: page wallet connect txn completed

- src/nft/components/details/detailsV2/__snapshots__/DataPage.test.tsx.snap
TSIA
---
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> #### What Changed
> Added
> - class names
> #### Testing
> Run tests and verify that the component renders correctly.
> fix: update snapshots

- src/components/Button/index.tsx
- src/components/swap/PriceImpactModal.tsx
- src/components/swap/PriceImpactWarning.tsx
- src/pages/Swap/index.tsx
Implements the price impact modal
https://www.loom.com/share/bdc0bbaece1744db9f276592a798d859
> feat: adding price impact modal

- package.json
- yarn.lock
upgrades the coned package to get this change: https://github.com/Uniswap/conedison/pull/19
1. Try to sign a permit2 signature with trustwallet ios on optimism or arbitrum - it will fail without this change.
> feat: upgrade conedison

- src/hooks/useUnmountingAnimation.ts
I had a difficult time figuring out how this hook was intended to be used, so I'm adding some docs.
> chore: add better documentation to a complicated hook

- cypress/README.md
> docs(e2e): cypress README

- cypress/e2e/token-explore-filter.test.ts
Simplifies and re-enables the token explore filter test, which had been disabled due to flakiness.
> test(e2e): simplify and re-enable token explore filter test

- cypress/e2e/token-details.test.ts
re-enables the TDP e2e tests since they are passing
> fix: re-enable TDP tests

- cypress/e2e/permit2.test.ts
- src/components/swap/PendingModalContent/PendingModalContent.test.tsx
- src/components/swap/PendingModalContent/index.tsx
update the content of the permit2 flow
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2185/update-permit2-content
| ![image](https://github.com/Uniswap/interface/assets/66155195/cbbf50aa-c3cb-4612-a589-7d49917624fd) | paste_before |
| paste_after  | <img width="565" alt="image" src="https://github.com/Uniswap/interface/assets/66155195/ac997124-a7c2-45fd-a177-f9b926a89af6"> |
> feat: update content in permit2 flow

- src/pages/Swap/index.tsx
logs swap failures to sentry for more data gathering
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2210/investigate-cx-reported-swap-failures
_Slack thread:_ https://uniswapteam.slack.com/archives/C03ESADBQPK/p1685973352773609
> feat: log swap errors to sentry

- cypress/e2e/wallet-connection/connect.test.ts
> ci: fix wallet disconnect test regression

- src/components/swap/PendingModalContent/index.tsx
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2151/permit2-fix-dialog-window-height
| paste_before | <img width="516" alt="image" src="https://github.com/Uniswap/interface/assets/66155195/4b7320c3-9bd3-4c5c-8d28-341a5ae7fa4f"> |
| paste_after  | ![image](https://github.com/Uniswap/interface/assets/66155195/8b112a05-39d5-4a01-b412-47a7d74d040f) |
> fix: bottom padding on swap modal

- src/components/swap/PendingModalContent/index.tsx
remove the step indicators in the success state
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2150/permit2-upon-success-remove-dot-indicators
| paste_before | <img width="516" alt="image" src="https://github.com/Uniswap/interface/assets/66155195/e16aa495-d942-487c-9f44-5ffea4e141ad"> |
| paste_after  | ![image](https://github.com/Uniswap/interface/assets/66155195/2ea77f95-b428-450b-906b-59247011c80b) |
> fix: remove step indicators in sucess state

- src/components/swap/PendingModalContent/index.tsx
make the text white in the success state on mainnet
_Slack thread:_ https://uniswapteam.slack.com/archives/C04D07TQBT4/p1686671330054319
> fix: make text white in success state

- src/nft/components/bag/BagFooter.tsx
* fixes a bug where if you select the token select modal when connected to an unsupported network it will throw and error
> fix: currency select modal when chain is not supported

- src/components/swap/ConfirmSwapModal.tsx
Refactors the state management code in the ConfirmSwapModal: 
1. instead of having the same function (`startSwapFlow`) handle every step, we explicitly call the function with the step we want to enact under certain conditions.
2. remove `prepareSwapFlow` from the top level hook result, and instead call it internally within `startSwapFlow`, which just generates the steps and triggers the first step.
> feat: refactor ConfirmSwapModal for clarity

- cypress/e2e/swap/swap.test.ts
- src/hooks/useBestTrade.test.ts
- src/hooks/useBestTrade.ts
- src/state/routing/types.ts
- src/state/routing/useRoutingAPITrade.ts
the UX of the swap component depends on the trade becoming undefined to clear the *dependent* variable (i.e. the output amount, if the INPUT is the independent variable)
so this PR is needed to properly clear the output when the user clears the input.
https://github.com/Uniswap/interface/assets/66155195/934b5d88-3020-4a39-811a-cc5f66c3cd6c
https://github.com/Uniswap/interface/assets/66155195/d3ac1a2c-8efd-4623-9467-da37824634fd
> fix: clear dependent variable when trade inputs become invalid

- src/components/WalletModal/Option.tsx
> fix: update copy per Fred's input

- cypress/e2e/wallet-dropdown.test.ts
- src/components/AccountDrawer/SettingsMenu.tsx
- src/components/AccountDrawer/TestnetsToggle.tsx
- src/components/NavBar/ChainSelector.tsx
- src/constants/chains.ts
Adds a settings toggle in all environments to allow access to testnets.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2244/show-testnets-in-dropdown-selector
> feat(testnets): add toggle for testnets

- src/components/NavBar/ChainSelector.tsx
- src/constants/chains.ts
> fix: remove unused types

- lingui.config.ts
- package.json
- src/constants/locales.ts
Removes the unused pseudo-locale.
> chore: rm pseudo locale

- cypress/e2e/permit2.test.ts
- src/components/swap/PendingModalContent/index.tsx
- src/hooks/useTokenAllowance.ts
adds an automated e2e test for the special case of USDT mainnet requiring allowance revocation before increasing the allowance to the required minimum
> test: add e2e test for usdt special case

- src/components/AccountDrawer/AuthenticatedHeader.tsx
> fix: cut off wallet icon

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/WalletModal/Option.tsx
- src/components/WalletModal/index.tsx
- src/connection/index.ts
- src/featureFlags/flags/walletConnectV2.ts
- src/featureFlags/index.tsx
* putting wcv2 behind a feature flag to allow better testing / phasing out
> fix: putting wcv2 behind feature flag

- .github/workflows/2-deploy-to-staging.yml
- .github/workflows/4-deploy-to-prod.yml
Fixes the markdown formatting for slack deployment messages.
_Slack thread:_ https://uniswapteam.slack.com/archives/C052ARNFZGU/p1687370150431009
_Relevant docs:_ https://api.slack.com/reference/surfaces/formatting#visual-styles
> build: fix slack markdown

- src/connection/index.test.tsx
Moves https://github.com/Uniswap/interface/pull/6826/files#diff-d8e87b63743b6ba309436b4f091ebd9c1480b6e79319d9cf1a5194cdbad02868R22 over to releases/staging
This is preventing releases as currently unit tests are failing on staging branch.
> test: update connection test

- src/hooks/useBestTrade.ts
- src/lib/utils/analytics.ts
- src/pages/Swap/index.tsx
- src/state/routing/slice.ts
- src/state/routing/types.ts
- src/state/routing/useRoutingAPITrade.ts
- src/state/routing/v2Slice.ts
- src/state/swap/hooks.tsx
Same as #6807 but as a hotfix into staging
> feat: track quote method in Quote Received event (#6807)

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/WalletModal/Option.tsx
- src/components/WalletModal/index.tsx
- src/connection/index.test.tsx
- src/connection/index.ts
- src/featureFlags/flags/walletConnectV2.ts
- src/featureFlags/index.tsx
* adding wallet connect v2 behind a feature flag like we already did on staging
> fix: adding wallet connect v2 behind feature flag

- .github/actions/cache-on-main/action.yml
- .github/actions/setup/action.yml
- .github/workflows/test.yml
Improve check times for PRs by optimizing caching:
- Only cache based on yarn.lock, instead of descending into children lockfiles. Resolving the glob took ~10s.
- Only save the cache when running on `main`. Saving the cache takes ~10-20s, and all feature branches fork from `main`.
> build: improve workflow caching

- public/CODEOWNERS
Adds CODEOWNERS to `public/`, protecting our static assets.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2284/add-codeowners-to-interfacepublic
> chore: add CODEOWNERS to public

- src/pages/AddLiquidityV2/PoolPriceBar.tsx
- src/pages/MigrateV2/MigrateV2Pair.tsx
* divide by zero error was being caused by inverting the price when the quote currency was zero / did not exist it seems like
> fix: divide by zero error on pool page

- src/components/NavBar/ChainSelector.tsx
Chrome handles ties differently than other browsers which caused the chain sorting to appear reversed. This replaces the sort with two arrays to solve the issue, and in anticipation of labeling unsupported networks as a set.
Chrome
Chrome
1. Go to https://interface-git-main-uniswap.vercel.app/#/swap on Chrome and open Chain Switcher
> fix: chrome tie sort resolution

- cypress/e2e/swap/errors.test.ts
Skips a test that started failing for unknown (non-interface-code-change-related) reasons.
> test(e2e): skip failing slippage test

- package.json
- src/connection/WalletConnectV2.ts
- yarn.lock
Updates the modal library to latest which adds sourcemaps.
> chore: upgrade @walletconnect/modal

- package.json
- yarn.lock
Updates walletconnect dependencies, improves error handling.
Specifically, handles LocalStorage failures better.
> chore: upgrade @web3-react/walletconnect-v2

- package.json
- src/connection/WalletConnectV2.ts
- yarn.lock
Same as https://github.com/Uniswap/interface/pull/6850
> chore: update @walletconnect/modal

- package.json
- yarn.lock
Same as https://github.com/Uniswap/interface/pull/6864
> fix: upgrade @web3-react/gnosis-safe

- src/components/swap/SwapBuyFiatButton.test.tsx
- src/components/swap/SwapBuyFiatButton.tsx
- src/components/swap/__snapshots__/SwapBuyFiatButton.test.tsx.snap
- src/state/user/hooks.tsx
- src/state/user/reducer.ts
Removed blue dot next to buy for users that have completed the buy flow. 
_Linear ticket:_ WEB-2314
> fix: remove blue dot next to buy

- src/components/WalletModal/PrivacyPolicyNotice.tsx
updates the ToS / privacy policy note to reflect the most recent change date to the privacy policy:
> chore: update tos & privacy policy last updated date

- package.json
- src/constants/chains.ts
- src/constants/locales.ts
- src/nft/components/details/InfoContainer.tsx
- src/nft/components/details/detailsV2/TimePeriodSwitcher.tsx
- src/state/routing/utils.ts
- src/state/types.ts
- yarn.lock
An unrelated PR (https://github.com/Uniswap/interface/pull/6885) caused our prettier version to go up, which led to some lint changes being necessary. Instead of doing it in that PR, I'm making a separate PR for those changes.
> chore: upgrade prettier

- src/components/AccountDrawer/MiniPortfolio/Pools/useMultiChainPositions.tsx
- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/NavBar/ChainSelector.tsx
- src/components/NavBar/SearchBarDropdown.tsx
- src/components/NetworkAlert/NetworkAlert.tsx
- src/components/Tokens/TokenTable/NetworkFilter.tsx
- src/connection/WalletConnectV2.ts
- src/featureFlags/flags/avalanche.ts
- src/featureFlags/index.tsx
- src/pages/Swap/index.tsx
- src/state/swap/hooks.tsx
- src/theme/components/RadialGradientByChainUpdater.ts
- Add feature flag to gate Avalanche launch
_Slack thread:_ https://uniswapteam.slack.com/archives/C052ARNFZGU/p1689010169325719
> feat: add feature flag for avax

- package.json
- yarn.lock
Upgrades conedison to catch a new error message thrown by WCv2 when a method is unimplemented. See https://github.com/Uniswap/conedison/pull/23.
> fix: catch WC2 unimplemented methods

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/uniswapXUseSyntheticQuote.ts
- src/featureFlags/index.tsx
- src/lib/hooks/routing/useRoutingAPIArguments.ts
- src/state/routing/slice.ts
makes QA testing a bit easier
https://uniswapteam.slack.com/archives/C053G2YEK5M/p1689354359857839
> feat: Add feature flag for synthetic quotes

- src/lib/hooks/orders/updater.tsx
> fix: update updater.tsx

- cypress/e2e/buy-crypto-modal.test.ts
- cypress/e2e/permit2.test.ts
- hardhat.config.js
- src/graphql/data/nft/NftActivity.ts
- src/nft/utils/currency.ts
- update hardhat block height
- fix break for e2e nft tests
> fix: e2e tests

- src/components/swap/SwapModalHeaderAmount.tsx
- src/lib/hooks/orders/updater.tsx
- src/state/signatures/hooks.ts
- src/state/signatures/reducer.ts
- src/state/signatures/updater.tsx
- src/state/swap/hooks.tsx
comment fixes and type changes
> chore: bunch of nits

- src/components/swap/AdvancedSwapDetails.tsx
- src/components/swap/GasBreakdownTooltip.tsx
- src/components/swap/SwapModalFooter.tsx
- src/state/signatures/hooks.ts
mostly updating translation macros
> fix: translations etc

- src/state/signatures/types.ts
Removing these since these aren't used anywhere and are unnecessary for now~
> chore: Remove placeholder signature types

- src/components/swap/ConfirmSwapModal.tsx
- src/components/swap/SwapModalHeader.test.tsx
- src/components/swap/SwapModalHeader.tsx
- src/pages/Swap/index.tsx
- inputCurrency should only be needed for X txs, made it optional
> feat: make inputCurrency optional for swapheader

- cypress/e2e/buy-crypto-modal.test.ts
- cypress/e2e/permit2.test.ts
- hardhat.config.js
- src/components/AccountDrawer/MiniPortfolio/Activity/parseLocal.test.ts
- src/components/swap/ConfirmSwapModal.tsx
- src/components/swap/SwapModalHeader.test.tsx
- src/components/swap/SwapModalHeader.tsx
- src/graphql/data/nft/NftActivity.ts
- src/pages/Swap/index.tsx
- src/state/signatures/hooks.ts
> test: add signatureToActivity undefined tests

- package.json
- yarn.lock
> fix: update token lists schema

- src/lib/hooks/orders/types.ts
- src/pages/Swap/index.tsx
- src/state/signatures/hooks.ts
- src/state/signatures/updater.tsx
- src/state/user/hooks.test.tsx
- use codebase-standard base type
- add test for uniswapx test hook
- simplify useAllSignatures usages
> chore: some last nits

- src/hooks/useTokenAllowance.ts
> fix: pwat stack overflow

- src/pages/AddLiquidityV2/PoolPriceBar.test.tsx
- src/pages/AddLiquidityV2/PoolPriceBar.tsx
* turns out my old fix did not correctly fix the divide by 0 error it needed to be wrapped in a try catch
* added regression test
> fix: v2 liquidity divide by zero

- src/components/swap/TradePrice.test.tsx
- src/components/swap/TradePrice.tsx
* divide by zero error caused by not wrapping inverting price in a try catch
* added regression test
> fix: swap divide by zero

- src/pages/Swap/UniswapXOptIn.tsx
hotfix #6959 directly to prod to fix launch dashboard metrics
> fix: log opt in impression

- cypress/e2e/buy-crypto-modal.test.ts
Default the flag to "on" for the buy crypto modal mobile test.
Fixes flakiness, eg https://github.com/Uniswap/interface/actions/runs/5579580871.
> test(e2e): buy crypto modal flag

- src/components/analytics/GoogleAnalyticsProvider.tsx
- the eslint disable command needed to be updated to properly silence and not spam PRs with `Unchanged files with check annotations`
- you're welcome
> fix: Silence linter warnings for GA

- public/apple-app-site-association
To allow mobile app to handle deeplinks, we need this file to be served from https://app.uniswap.org/apple-app-site-association
> feat: add apple-app-site-association

- src/constants/networks.ts
- add infura url for base and base goerli to RPC_URLs
- fixes bug where uniwallet could not connect
_Slack thread:_ https://uniswapteam.slack.com/archives/C03NZGRTS3A/p1689721285990569
> fix: add infura url for base and base goerli

- src/nft/utils/asset.tsx
* fixes hardcoded purchase tweet collection url
> fix: purchase tweet url

- src/components/Suspense/SuspenseWithPreviousRenderAsFallback.tsx
- src/nft/components/collection/CollectionNfts.tsx
- Adds the two hotfixes below from main to staging ahead of release
- https://github.com/Uniswap/interface/pull/6996
- https://github.com/Uniswap/interface/pull/6994
_Slack thread:_ https://uniswapteam.slack.com/archives/C052ARNFZGU/p1690231685478669
> fix: staging hotfixes for price range and search bar

- src/pages/AddLiquidityV2/redirects.tsx
- src/pages/App.tsx
- src/pages/Pool/v2.tsx
> fix: disable v2 liq

- src/hooks/useAccountRiskCheck.ts
Updates the screening check to a more reasonable cache time.
_Slack thread:_ https://uniswapteam.slack.com/archives/C023ZR8Q1DE/p1690311895079359
> fix: update safety check cache time

- .github/workflows/3-staging-to-prod.yml
Updates the sha in the promotion check to be derived correctly from the context.
This enables checking tests before deploying to prod.
> build: fix promotion sha

- package.json
- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/forceUniswapXOn.ts
- src/featureFlags/index.tsx
- src/lib/hooks/routing/useRoutingAPIArguments.ts
- src/state/routing/slice.ts
- yarn.lock
bumps uniswapx-sdk for new contract addresses
> feat: bump uniswapx-sdk

- cypress/e2e/permit2.test.ts
- src/lib/hooks/useBlockNumber.tsx
Fix mainnet block updater by making sure mainnetBlock is preserved through all sets to the state.
Fixes a bug introduced by #6981 .
> fix: update mainnet block

- src/components/AccountDrawer/UniwalletModal.tsx
- src/connection/WalletConnectV2.ts
main PR to fix deeplinking, corresponding to this hotfix PR into staging: https://github.com/Uniswap/interface/pull/7016
> fix: use deeplink instead of universal link

- cypress/e2e/swap/errors.test.ts
- src/components/AccountDrawer/MiniPortfolio/Activity/parseLocal.ts
- src/components/swap/ConfirmSwapModal.tsx
- src/components/swap/PendingModalContent/PendingModalContent.test.tsx
- src/components/swap/PendingModalContent/index.tsx
- src/state/transactions/hooks.tsx
updates ConfirmSwapModal to actually wait for the transaction status to be reported, not just for the TransactionResponse (which may not indicate a successful transaction).
this new logic now corresponds with the Mini Portfolio and notification Popups, so they should all update at the same time.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2577/when-tx-fails-ui-is-showing-success
_Slack thread:_ https://uniswapteam.slack.com/archives/C04D07TQBT4/p1690491370411699
if swap is reverted on chain, we recognize that as a successful swap in the ConfirmSwapModal
successful swap - updates at the same time the popup appears
https://github.com/Uniswap/interface/assets/66155195/d0e349e9-256a-4a75-a939-ff61bbd207e2
1. lower slippage tolerance so that the swap is reverted on chain
> fix: reverted swap state

- cypress/e2e/universal-search.test.ts
- src/components/NavBar/SearchBarDropdown.tsx
- src/components/NavBar/SuggestionRow.tsx
- src/components/NavBar/__snapshots__/SearchBarDropdown.test.tsx.snap
Reverts #7002 and refactors the tests for the universal search bar. These now pass reliably locally.
> test: deflake and clean universal search

- public/.well-known/assetlinks.json
Adds public deeplink information to uniswap app for mobile devices to identify with. 
_Linear ticket:_ https://linear.app/uniswap/issue/MOB-976/[android]-[deeplinks]-add-assetlinks-to-uniswaporgwellknown
> feat: add mobile deeplinks json to public folder

- src/lib/hooks/useTokenList/fetchTokenList.test.ts
- src/lib/hooks/useTokenList/fetchTokenList.ts
removes this variable since it's unused in product code, it's actually a duplicate, `UNI_LIST` has the same value
updated tests and tests pass
> fix: remove unused variable

- src/pages/Pool/v2.tsx
Fixes `Read more about providing liquidity` link in `v2` pools to new [link](https://docs.uniswap.org/contracts/v2/concepts/core-concepts/pools).
_Linear ticket:_ WEB-2585
> fix: update v2 pool information link

- src/state/routing/slice.ts
> fix: re-enable UniswapX after disabling

- cypress/e2e/wallet-connection/connect.test.ts
- src/components/Web3Provider/index.tsx
- src/hooks/useOrderedConnections.ts
reverts #6928 on staging to resolve https://uniswaplabs.pagerduty.com/incidents/Q332GT7AO8MQ6J
> fix: revert #6928

- .gitignore
- package.json
- yarn.lock
Previously used beta wrangler version was merged into newest update and deprecated. Updates wrangler version to fix any issues caused with missing package.
> fix: update wrangler version

- src/components/AccountDrawer/MiniPortfolio/Activity/hooks.ts
> fix: activity nonce xchain prod

- cypress/e2e/universal-search.test.ts
We've been struggling with this one but may as well give it some breathing room until we invest more into figuring it out (maybe upgrade cypress and pray?)
> fix: bring back flake retries for flaky test (only flakes ~33% of time)

- functions/nfts/asset/__snapshots__/nft.test.ts.snap
- functions/nfts/collection/__snapshots__/collection.test.ts.snap
- functions/tokens/__snapshots__/token.test.ts.snap
Fixes tests broken by routing changes in snapshots caused by the transition to path based routing.
> fix: cloud tests broken by path based

- src/components/AccountDrawer/MiniPortfolio/Activity/OffchainActivityModal.tsx
- src/components/swap/PendingModalContent/index.tsx
mirror PR for hotfix pr into prod [here](https://github.com/Uniswap/interface/pull/7096)
> fix: uniswapx review modal success display

- src/state/routing/slice.ts
https://uniswapteam.slack.com/archives/C02T729PMQE/p1691507534359689?thread_ts=1691444333.641919&cid=C02T729PMQE
looks like this line got dropped in the merge
> fix: add back correct fellback setter

- public/.well-known/assetlinks.json
The nesting for deeplinks with multiple apps was wrong. This fixes it. 
tried with vercel link and adb commands
> fix: fixing deeplinks json nesting

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/multichainUx.ts
- src/featureFlags/index.tsx
- Adds a statsig feature flag in preparation for the multichain ux improvements
- https://console.statsig.com/5M2TFMQiHkbY9RML95FAEa/gates/multichain_ux
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2547/setup-the-multichain-ux-feature-flag-in-statsig-and-the-interface
_Relevant docs:_ https://www.notion.so/uniswaplabs/MultiChain-Web-UX-127bdec19777423abf12b7b7ad98a60f
> feat: add multichain_ux flag

- src/graphql/data/util.tsx
adds BASE mainnet to the list of gql-backend-supported chains. this unlocks balance fetching and transaction history
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2617/add-support-for-mp-for-base
> feat: query base backend

- src/components/Logo/AssetLogo.tsx
- src/components/Tokens/TokenTable/__snapshots__/TokenRow.test.tsx.snap
- src/components/swap/__snapshots__/SwapModalHeader.test.tsx.snap
- src/pages/Landing/__snapshots__/index.test.tsx.snap
fixes an issue with the formatting of an unknown token logo in the swap flow.
1. manual testing and eyes
> fix: unknown token logo styling

- package.json
- yarn.lock
> feat: Upgrade uniswapx-sdk for eth output

- .swcrc
> fix: fix jest breaking with new swc setting

- .gitignore
- package.json
- src/hooks/useContract.ts
- src/hooks/useUniversalRouter.ts
- yarn.lock
> fix: fail UR transaction if chain IDs don't match

- package.json
- yarn.lock
> feat: bump version of uniswapx-sdk for eth output trades

- src/components/NavBar/SearchBarDropdown.tsx
- src/components/Tokens/constants.ts
- src/constants/chains.ts
- src/graphql/data/SearchTokens.ts
- src/graphql/data/util.tsx
- Add full support to BASE for Token Explore and Universal Search
- Adds BASE as a supported chain for UniWallet
- Adds filtering from hotfix #7164 
- We will cherypick this PR and https://github.com/Uniswap/interface/pull/7155 into staging before tomorrow's release
_Slack thread:_ https://uniswapteam.slack.com/archives/C04D07TQBT4/p1692096823352609
1.
> feat: Add base support to Explore & Search

- cypress/e2e/universal-search.test.ts
- src/components/NavBar/SearchBarDropdown.tsx
- src/components/NavBar/SuggestionRow.tsx
- src/components/Tokens/constants.ts
- src/constants/chains.ts
- src/graphql/data/SearchTokens.ts
- src/graphql/data/util.tsx
- Cherrypick fixes #7155 and #7165 from `main` to `releases/staging`
_Slack thread:_ https://uniswapteam.slack.com/archives/C052ARNFZGU/p1692115047345969
> fix: Cherrypick main fixes to staging

- src/hooks/useDebouncedTrade.ts
Fixes loading state for debounced quotes, and omits loading state for wrap quotes.
|    Before   | After |
| ------------ | --- |
| <video src="https://github.com/Uniswap/interface/assets/5403956/b4f096b0-7d03-4aed-b746-f58fc70aed5c"> | <video src="https://github.com/Uniswap/interface/assets/5403956/06c8a419-9af5-4483-8a75-d17ea9883b0b"> |
> fix: debouncing as a loading state

- src/constants/tokenSafetyLookup.ts
- src/hooks/useEagerlyConnect.ts
- src/hooks/useStateRehydrated.ts
- src/state/lists/updater.ts
Fix sentry error:
`TypeError: Cannot read properties of undefined (reading 'current')`
will hotfix to prod when this is merged
_Slack thread:_ https://uniswapteam.slack.com/archives/C03NZGRTS3A/p1692724036927089
> fix: ensure lists are present before running update

- cypress/e2e/mini-portfolio/accounts.test.ts
Cypress was failing on main. This isolates some flakey spy assertions into their own contexts.
> fix: isolate assertions into single tests

- src/tracing/utils.ts
hotfix #7213  to reduce the error counts in prod
> fix: null check on elapsedTime for some browsers

- src/components/PrivacyPolicy/index.tsx
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1692625017980549
> fix: repair broken link

- src/state/routing/slice.ts
- Routing team quested to just log incident of no route found instead of paging
- prod hotfix equivalent to https://github.com/Uniswap/interface/pull/7242
> refactor: log NO_ROUTE found instead of paging

- src/hooks/Tokens.ts
fixes an exception in the Token List code - if there is no list for a given chain then this code will throw an error. we periodically fetch lists for all chains and sync the user's persisted lists, but it's not very frequent (10 mins)
https://uniswap-labs.sentry.io/issues/4413049055/events/cd4b42d01cb04f3bb5535517a71e17a7/?project=4504255148851200&referrer=next-event
manually verified that an undefined list here no longer causes a crash.
> fix: null check in lists code

- src/hooks/Tokens.ts
> fix: destructure current undefined prod

- src/utils/formatNumbers.test.ts
* typecheck failing on main because types were updated and main wasn't pulled against it before merging
> fix: typecheck failing on main

- src/components/NavBar/SearchBarDropdown.tsx
- src/graphql/data/util.tsx
- GQL now supports BNB so we can unblock it from Explore and Search
- I also re-ordered the Token Explore Chain dropdown to match our app wide Chain Switcher ordering
_Slack thread:_ https://uniswapteam.slack.com/archives/C05NXMASXNZ/p1692822552494749
> feat: add BNB support to Token Search and Explore

- src/tracing/SwapEventTimestampTracker.ts
- src/tracing/swapFlowLoggers.test.ts
- src/tracing/swapFlowLoggers.ts
add unit tests for the swapFlowLoggers
> test: unit tests for swapFlowLoggers

- src/featureFlags/index.tsx
Updates which statsig flag is used to gate FOT logic. The current flag used in prod is having issues possibly related to caching or an incident on statsig's end
> fix: use updated feature flag

- src/hooks/useUniversalRouter.ts
Would be cool to filter out failures by autoslippage or not
> feat: Log auto slippage setting for gas estimate failed event

- src/lib/utils/analytics.ts
- src/pages/Swap/index.tsx
Include the input/output token taxes in the Swap Quote Received event.
> fix: add tax amounts to swap quote received

- src/components/AccountDrawer/AuthenticatedHeader.tsx
- src/components/Tokens/TokenDetails/BalanceSummary.tsx
- src/components/Tokens/TokenTable/FilterOption.tsx
- src/components/Tokens/TokenTable/NetworkFilter.tsx
- src/components/Tokens/TokenTable/TimeSelector.tsx
Fixes many general issues in the interface related to spore.
| <img width="150" alt="Screenshot 2023-09-11 at 5 05 46 PM" src="https://github.com/Uniswap/interface/assets/1355319/6759f052-bd8a-4924-9f14-12797bb99b5f"> | <img width="186" alt="Screenshot 2023-09-11 at 5 05 27 PM" src="https://github.com/Uniswap/interface/assets/1355319/9b76317a-7895-4991-b975-38fd5dc084f4"> |
| <img width="317" alt="Screenshot 2023-09-11 at 5 06 07 PM" src="https://github.com/Uniswap/interface/assets/1355319/612188dc-1460-4d45-8c3a-84cf48018597"> | <img width="340" alt="Screenshot 2023-09-11 at 5 06 03 PM" src="https://github.com/Uniswap/interface/assets/1355319/47724228-7564-44c1-9ea1-221e49919fc8"> |
| <img width="432" alt="Screenshot …
> fix: [Spore] general polish items

- package.json
- src/components/FeeSelector/index.tsx
- src/components/PrivacyPolicy/index.tsx
- src/components/analytics/index.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/AddLiquidityV2/index.tsx
- src/pages/MigrateV2/MigrateV2Pair.tsx
- src/pages/Pool/PositionPage.tsx
- src/pages/RemoveLiquidity/V3.tsx
- src/pages/RemoveLiquidity/index.tsx
- src/theme/components/index.tsx
- yarn.lock
this is part of #6554 based on the feedback on that PR - instead of completely removing those events we'll log them to amplitude.
in a follow up PR i'll actually delete the dead GA code
> feat: move ga events to amplitude

- functions/nfts/asset/__snapshots__/nft.test.ts.snap
- functions/nfts/collection/__snapshots__/collection.test.ts.snap
- functions/tokens/__snapshots__/token.test.ts.snap
cloud tests were failing on main--this updates the snapshots
> test: update cloud test snapshots

- .github/workflows/1-main-to-staging.yml
> fix: ci added CODEOWNERS github format

- package.json
- src/components/Web3Provider/index.test.tsx
- src/components/Web3Provider/index.tsx
- src/connection/activate.ts
- yarn.lock
1. include the wallet "client version", if available, as a user property
2. change event name for wallet_connected
3. add `CHAIN_ID` user property
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2660/improved-logging
> feat: improved logging 9 12

- src/pages/AddLiquidityV2/index.tsx
fixes a ui bug when adding liquidity to a v2 pool.
1. navigate to pools > more > v2 pools
2. try to add liquidity
> fix: v2 pool ui

- cypress/e2e/redirects.test.ts
- cypress/e2e/remove-liquidity.test.ts
- src/pages/RemoveLiquidity/V3.tsx
- src/pages/RemoveLiquidity/index.tsx
* redirecting 'remove/v2/duplicate/duplicate' to Position Unavailable; '/remove/v2/single' to 404; 'remove/:nonexistent-pool' to Position Unavailable
* adding test cases that they redirect to 404 or error pages accordingly
* add 'loading token pair' check for v3
* waiting on updates to cypress-hardhat to support managing liquidity positions, before full hardhat functionality can be tested https://github.com/Uniswap/cypress-hardhat/pull/25
_Linear ticket:_ [WEB-2581](https://linear.app/uniswap/issue/WEB-2581/no-e2e-tests-for-remove-liquidity-fails-for-duplicate-or-single-token)
| paste_after  | …
> test: add remove-liquidity interface tests

- src/lib/hooks/useBlockNumber.tsx
Fixes block number memoization so that the context value is not recreated unnecessarily. This improves pageload by eliminating a re-render when the chain is first set.
Also changes the initial value (to minimize changes on pageload) and refactored a callback to be more conformant to others in the file.
Manually verified that the re-render did not occur through both logging and React Devtools profiling.
> fix: block number memoization

- src/nft/utils/collection.ts
- Legal requested we block collection `0xd4d871419714b778ebec2e22c7c53572b573706e` with a 48hr SLA
_Slack thread:_ https://uniswapteam.slack.com/archives/C014WRW57NJ/p1695119881034719
> chore: block requested collection

- src/nft/utils/collection.ts
> chore: block requested collection - staging

- src/components/NavigationTabs/index.tsx
- src/pages/AddLiquidity/index.tsx
- src/pages/AddLiquidityV2/index.tsx
- src/pages/RemoveLiquidity/V3.tsx
- src/pages/RemoveLiquidity/index.tsx
Removes settings menu from LP pages
_Linear ticket:_ WEB-2611
> fix: remove settings button from lp page

- functions/nfts/asset/__snapshots__/nft.test.ts.snap
- functions/nfts/collection/__snapshots__/collection.test.ts.snap
- functions/tokens/__snapshots__/token.test.ts.snap
- src/components/AccountDrawer/MiniPortfolio/Activity/index.tsx
- src/components/AccountDrawer/MiniPortfolio/Activity/utils.test.ts
- src/components/AccountDrawer/MiniPortfolio/Activity/utils.ts
increase test coverage in this folder
_Relevant docs:_ https://app.codecov.io/gh/Uniswap/interface/tree/main/src%2Fcomponents%2FAccountDrawer%2FMiniPortfolio%2FActivity
> test: unit tests for activity tab createGroups, and update cloud test snapshots

- src/components/SearchModal/CommonBases.test.tsx
- src/components/SearchModal/CommonBases.tsx
- src/components/SearchModal/__snapshots__/CommonBases.test.tsx.snap
right now we're hiding common bases on small screen widths. but we have a request to remove this restriction and just show them, so they appear on mobile devices.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2818/add-common-token-bases-to-mweb
> fix: show common bases on mobile

- package.json
- src/pages/App.tsx
- yarn.lock
add the git commit hash to the amplitude user properties, as requested in slack. see thread below
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2906/add-customuserpropertygit-commit-hash-to-logging
_Slack thread:_ https://uniswapteam.slack.com/archives/C03JAKVATU6/p1695339640739639
> feat: user property git commit hash

- src/pages/Landing/__snapshots__/index.test.tsx.snap
- src/pages/Swap/index.tsx
addressing design feedback here - don't show the spot price when there's no input amount.
note: we're still fetching the USD price when there's no input, to preload the price which helps later price checks load faster
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1695760705173299
> fix: hide price when no amount input

- src/connection/activate.ts
- Adds the error message to the Amplitude event that tracks Wallet Connection failures to help with debugging. 
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2915/%5Binvestigate%5D-trouble-connecting-metamask-now-and-also-happened-when-i
_Slack thread:_ https://uniswapteam.slack.com/archives/C04D07TQBT4/p1695864971471469
> feat: add error message to wallet connect fail event

- src/hooks/useUniswapXSwapCallback.ts
Duplicate of https://github.com/Uniswap/interface/pull/7402
> feat: Move UniswapX signature expiry back to deadline (copy for staging)

- src/components/swap/SwapDetailsDropdown.tsx
- src/components/swap/SwapLineItem.tsx
- src/components/swap/SwapModalFooter.tsx
- src/components/swap/__snapshots__/SwapDetailsDropdown.test.tsx.snap
- src/components/swap/__snapshots__/SwapLineItem.test.tsx.snap
- src/components/swap/__snapshots__/SwapModalFooter.test.tsx.snap
- src/state/routing/utils.ts
Implements new design for gas costs / network fees ui
| <img width="424" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/0c3a9566-983e-4e60-9022-33a743efec48"> | <img width="424" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/778ca289-8549-4354-9b6f-b7eab0e04fc2"> |
|    Before    |   After   |
| <img width="473" alt="Screenshot 2023-10-03 at 4 12 19 PM" src="https://github.com/Uniswap/interface/assets/39385577/41ed0587-0e1c-4874-9838-6aac8d2c82d6">  | <img width="475" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/02271f7d-bcbc-4493-90d1-9493a2b17948"> |
> feat: gas costs ui updates

- cypress/e2e/token-details.test.ts
- Replace low volume token used in tests with token we own with 0 volume for a steady testing state in e2e tests
_Slack thread:_ https://uniswapteam.slack.com/archives/C052ARNFZGU/p1696452931755889
> fix: use in house token for low volume test

- src/components/Tokens/TokenDetails/TokenDescription.test.tsx
- src/components/Tokens/TokenDetails/TokenDescription.tsx
- src/components/Tokens/TokenDetails/__snapshots__/TokenDescription.test.tsx.snap
- tests if the element is hidden or not
- updated the id
> fix: test if description is hidden or not

- cypress/e2e/swap/uniswapx.test.ts
- cypress/e2e/wallet-dropdown.test.ts
- cypress/support/commands.ts
force the opt-out feature flag to be off in e2e tests
> fix: disable UniswapX opt-out in e2e tests

- src/pages/App.tsx
> fix: override user pref in analytics

- .github/workflows/test.yml
this will allow us to go into the "test" action, choose a branch or PR, and run the tests for it
> feat: allow manual test runs

- src/pages/Pool/PositionPage.tsx
fixes a random crash i found - reproducible at https://app.uniswap.org/pool/ethereum
navigate to <preview_url>/pool/ethereum and note that the page doesn't crash :)
> fix: dont crash on invalid tokenId

- cypress/e2e/swap/settings.test.ts
- src/components/Settings/MaxSlippageSettings/index.test.tsx
- src/components/Settings/MaxSlippageSettings/index.tsx
- src/components/Settings/MenuButton/index.tsx
- src/components/swap/MaxSlippageTooltip.tsx
- src/components/swap/SwapDetailsDropdown.tsx
- src/components/swap/SwapLineItem.tsx
- src/components/swap/SwapModalFooter.tsx
- src/components/swap/__snapshots__/SwapDetailsDropdown.test.tsx.snap
- src/components/swap/__snapshots__/SwapLineItem.test.tsx.snap
- src/components/swap/__snapshots__/SwapModalFooter.test.tsx.snap
- src/utils/formatNumbers.test.ts
- src/utils/formatNumbers.ts
Updates UI for min/max received line items. Adds new "Max. slippage" line item. Updates slippage formatting to not include trailing zero's
| <img width="476" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/cbc2b275-8f76-4c85-8b44-77ccc71a1d98"> | <img width="474" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/283a3591-ab7e-4e6a-84f8-e723f196b354"> |
| <img width="475" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/b4ff381a-616e-41a8-8159-9d76b5d42f45"> | <img width="472" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/64f34258-8c7b-4372-90ac-aaead097d6d1"> |
|    Before    | …
> feat: updated slippage ui

- functions/[[index]].ts
- functions/components/metaTagInjector.test.ts
- functions/components/metaTagInjector.ts
- functions/nfts/asset/[[index]].ts
- functions/nfts/collection/[index].ts
- functions/tokens/[[index]].ts
- functions/utils/getRequest.ts
- src/pages/App.tsx
* add country code to meta tag
* use blocked paths header
* proper types
* add test
* Update functions/components/metaTagInjector.ts
* Update functions/components/metaTagInjector.ts
* Update src/pages/App.tsx
* pr suggestions
* skip failing e2e
* revert test change
* take file from main
---------
1.
> feat: support redirects for a list of header paths (#7411)

- src/components/Tokens/TokenDetails/BalanceSummary.tsx
- src/components/Tokens/TokenDetails/index.tsx
- src/featureFlags/flags/infoTDP.ts
Originally wanted to provide cost-basis, gain, and 24hr return in the Balance Summary box. Upon further investigation, those calculations are too complex rn, going to investigate w/ BE team but removing these balance boxes entirely for info project.
_Slack thread:_ https://uniswapteam.slack.com/archives/C05NXMASXNZ/p1696521446957029 & https://uniswapteam.slack.com/archives/C047U65H422/p1696523041004169?thread_ts=1675910436.894059&cid=C047U65H422
| <img width="200" alt="Screenshot 2023-10-05 at 5 56 45 PM" src="https://github.com/Uniswap/interface/assets/27475332/bfad60ef-662e-46f2-8111-c7ef7dc42b88"> | <img width="300" alt="Screenshot 2023-10-05 at 5 56 37 PM" src="https://github.com/Uniswap/interface/assets/27475332/02fc91d2- …
> feat: [info] remove balance summaries from TDP

- cypress/e2e/landing.test.ts
- public/sitemap.xml
- src/components/NavBar/UkBanner.tsx
- src/components/NavBar/UkDisclaimerModal.tsx
- src/components/TopLevelModals/index.tsx
- src/pages/App.tsx
- src/state/application/reducer.ts
* we need to add a banner for the uk on the top of the app that follows the guidelines here: https://www.figma.com/file/lTKWtn5cajzUdBCSov0jiv/UK-Legal-Request?type=design&node-id=0-1&mode=design&t=sWOrFgsSlzi1SbDR-0
> feat: uk disclaimer banner

- cypress/e2e/landing.test.ts
- functions/[[index]].ts
- functions/components/metaTagInjector.test.ts
- functions/components/metaTagInjector.ts
- functions/nfts/asset/[[index]].ts
- functions/nfts/collection/[index].ts
- functions/tokens/[[index]].ts
- functions/utils/getRequest.ts
- src/components/NavBar/UkBanner.tsx
- src/components/NavBar/UkDisclaimerModal.tsx
- src/components/TopLevelModals/index.tsx
- src/pages/App.tsx
- src/state/application/reducer.ts
> feat: uk hotfix

- src/components/NavBar/UkBanner.tsx
- src/pages/App.tsx
* removes scroll behavior when banner is on the swap page
* have to increase the height of the banners by one because of the bottom border adds 1px to the bottom
> fix: removing scrollbar on swap with banner

- public/.well-known/assetlinks.json
Updating deeplink package names for mobile, same as #7399
> chore(): update deeplink package names

- src/pages/App.tsx
this is a hotfix including changes from #7458  and #7442
> fix: hotfix update setting user.router_preference for analytics

- src/components/TransactionConfirmationModal/index.tsx
Fixes WEB-2802
_Linear ticket:_ WEB-2802
1.
> fix: fix contrast on l2 network text

- src/hooks/useContract.ts
- src/hooks/useSwapTaxes.ts
- src/lib/hooks/useCurrency.ts
fixes a serialization console error when trying to log the entire `contract` object. 
1. run the app and view "circular JSON" errors in the console
> fix: dont try to log unserializable objects

- src/pages/Swap/LimitOrderExpiryDropdown.tsx
- src/pages/Swap/LimitOrderForm.tsx
- src/pages/Swap/index.tsx
> feat: Expiry dropdown

- .github/workflows/semgrep.yml
Testing out Semgrep on interface.  This adds a semgrep github action.
> ci: basic semgrep configuration

- .github/workflows/4-deploy-to-prod.yml
Continues the release workflow even if IPFS pinning fails.
_Slack thread:_ https://uniswapteam.slack.com/archives/C052ARNFZGU/p1698695255283559
> build: continue release on failed ipfs pin

- src/components/swap/GasBreakdownTooltip.tsx
- src/components/swap/SwapLineItem.tsx
- src/components/swap/SwapModalFooter.test.tsx
- src/components/swap/__snapshots__/SwapLineItem.test.tsx.snap
Per product + design, changing some language related to fees
> fix: Changing some language around fees

- src/components/Tokens/TokenDetails/Skeleton.tsx
- src/components/Tokens/TokenDetails/TokenDescription.test.tsx
- src/components/Tokens/TokenDetails/TokenDescription.tsx
- src/components/Tokens/TokenDetails/__snapshots__/TokenDescription.test.tsx.snap
- src/components/Tokens/TokenDetails/index.tsx
- src/components/swap/SwapLineItem.tsx
- src/pages/PoolDetails/__snapshots__/index.test.tsx.snap
- src/pages/PoolDetails/index.tsx
- src/utils/getExplorerLink.ts
- Adds Token Description to TDP when feature flag is enabled
- Removes Token Description from PDP as it will be replaced by a [Links Section](https://www.figma.com/file/2yKuZXmQ2UvgBbXR3txz4O/Dot-Info?type=design&node-id=1547%3A229624&mode=dev)
- Update styles for Token Description according to the Figma
- Support showing fees in Token Description
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-3021/token-description
_Slack thread:_ https://uniswapteam.slack.com/archives/C05NXMASXNZ/p1697739765251329
_Relevant docs:_ https://www.figma.com/file/2yKuZXmQ2UvgBbXR3txz4O/Dot-Info?type=design&node-id=713%3A1775037&mode=dev
Hardcoded test to show differing fees
> feat: [info] Add token description to TDP

- src/components/SearchModal/CurrencySearch.tsx
- Fixes lint warning `React Hook useMemo has a missing dependency: 'chainId'.`
> fix: add chainId to dependency array

- src/pages/Swap/index.tsx
* disable exact output for FOT tokens
> chore: disabling exact output for fot tokens

- hardhat.config.js
- src/hooks/useUniversalRouter.ts
> test: update hardhat blocknumber

- src/constants/tokens.ts
- src/utils/nativeTokens.ts
Cherrypicked from https://github.com/Uniswap/interface/pull/7567
> fix: use NativeCurrency for polygon matic

- src/state/migrations.test.ts
- src/state/migrations.ts
- src/state/migrations/3.ts
- src/state/reducer.ts
we added migration 3 in #7544 but i don't think it's actually taking effect yet
> fix: set current redux version to 3

- src/state/migrations.test.ts
- src/state/migrations.ts
- src/state/migrations/3.ts
- src/state/migrations/4.test.ts
- src/state/migrations/4.ts
- src/state/reducer.ts
* cherry-picked #7578  and #7584
> fix: flushing user locale redux when locale is German

- src/state/routing/gas.ts
copy of https://github.com/Uniswap/interface/pull/7594
> fix: don't show approve gas costs for arbitrum [hotfix]

- cypress/e2e/swap/uniswapx.test.ts
- src/components/swap/ConfirmSwapModal.tsx
copy of https://github.com/Uniswap/interface/pull/7604
> fix: only change input currency to weth after eth wrap completes [hotfix]

- src/components/Banner/AndroidAnnouncementBanner/index.tsx
> fix: android banner DownloadButton onClick should not propagate up 

- src/nft/utils/blocklist.ts
- Add ip infringing collection `0x383e2070a38f3205be0f3ea4fb05a5c13ade6cf4` to blocklist
- Will cherry-pick to mono after
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-3180/remove-nft-collection-with-ip-infringement-under-skull
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1700578458873249
> fix: block ip infringing collection

- cypress/e2e/swap/errors.test.ts
Oops fixing cypress tests for https://github.com/Uniswap/interface/pull/7580
> fix: fix uniswapx feature flag test cleanup

- src/components/SearchModal/CurrencySearch.tsx
prod hotfix for https://github.com/Uniswap/universe/pull/5297
> fix(web): show search token if user-added
