Uniswap/interface

- src/pages/Pool/PositionPage.tsx
> fix: reduce size for remove liquidity button

- src/nft/queries/openSea/OSCollectionsFetcher.ts
Removes the filter for 1155 collections in the filter menu on profile. Allows them to be searchable as well. Can test by impersonating my wallet.
Before:
After:
> feat: show 1155s in collection filter

- src/nft/components/details/AssetDetails.css.ts
- src/nft/components/details/AssetDetails.tsx
Many NFT collections use embedded HTML pages to represent their artwork. This is achieved by setting the `animation_url` to a URI that hosts a static webpage. Supporting embedded `animation_url`s will allow Uniswap to showcase some of the most innovative NFT projects in their full glory on the Uniswap NFT platform.
This PR adds support for rendering embedded HTML artwork on the Asset Details page of the Uniswap NFT application.
A few collections that make use of embedded `animation_url`s:
- [ArtBlocks](https://opensea.io/assets/ethereum/0x99a9b7c1116f9ceeb1652de04d5969cce509b069/377000022) (currently the top collection on Uniswap NFT)
- [Tickle Beach](https://opensea.io/assets/ethereum/0x6f4388602c5dd6c593bf7c9cf3128aaa2a3e09ce/9440) (fully on-chain 3d rendered characters)
- …
> feat: Adds support for embedded animation_urls

- src/graphql/data/nft/NftBalance.ts
- src/nft/components/details/AssetPriceDetails.tsx
Previously there could be a BE discrepancy where an asset could be shown as owned by a user but when calling their NftBalance, the asset would not be present. This would cause a crash if they tried to list said asset. We now hide the owner container in Details unless the NftBalanceQuery for that asset returns data.
> fix: only show owner container if we have NftBalance data

- src/pages/AppBody.tsx
- src/pages/CreateProposal/index.tsx
- src/pages/RemoveLiquidity/V3.tsx
also fixes a visual bug that was occurring on v3 liquidity removal
> fix: update <AppBody /> to allow its intended prop passthrough

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/permit2.ts
Adds a Permit 2 / Universal Router feature flag.
Cleans up old feature flags, and the feature flags modal.
> feat: permit 2 feature flag

- src/components/TokenSafety/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-1988
> fix: link color for learn more in token safety msg

- src/nft/components/collection/CollectionStats.tsx
Previously the boolean that determines if the description should truncate and have a `read more` prompt didn't change when the collection changed. This fixes that bug. To test here and on main go to a collection with a truncated description such as cryptopunks and then switch to a collection with a short description like `0x01371a682ff3a9d0c9fa7d073c2983081ca938c8`.
Working gif:
> fix: change readMore val on address change

- src/components/WalletDropdown/AuthenticatedHeader.tsx
https://uniswaplabs.atlassian.net/browse/WEB-1572?atlOrigin=eyJpIjoiNzFmODRmNDU5YmIzNGFjOTk4ODYzNmQ4YjRmNTE1MDEiLCJwIjoiaiJ9
note: it also truncates the account name stuff with ellipsis (...) when too long
has ENS: 
no ENS:
> fix: show ens in wallet dropdown too if available

- src/state/routing/utils.ts
Uses a stable value for the trade's currencies, so that hooks depending on the currency are not rerendered. Practically, this fixes an issue where changing the input amount might reset approval state.
> fix: stable trade currency

- src/hooks/usePermit2.ts
- src/pages/Swap/index.tsx
Adds a PermitState.LOADING to avoid initiating a swap before PermitState is known.
This prevents swaps from failing because they have not yet been permitted.
> fix: disable swap while permit loading

- src/hooks/useUniversalRouter.ts
- src/utils/swapErrorToUserReadableMessage.tsx
Displays a more user-friendly error - "Transaction rejected" - when user rejects a UR swap. This is the same behavior as without UR.
> fix: handle user rejection

- src/pages/Landing/index.tsx
This is necessary so light mode works properly
> fix: textPrimary for landing page copy

- src/pages/Landing/index.tsx
> fix: add max-width to landing page subtext

- src/pages/Landing/index.tsx
This is so in light mode things look correct
> fix: CTAButton should use white text always

- src/pages/About/Card.tsx
> fix: light mode cards for /about

- src/pages/About/index.tsx
I'll make the buttons for the social links in a diff pr
> feat: add initial footer to /about

- src/pages/About/constants.ts
These will no longer be used. I will update the design of these cards in another PR.
> fix: remove Earn and Build dApps links

- public/index.html
- src/pages/App.tsx
These should be at 100% so inner Page components are able to take up the full page size.
> fix: body, #root, AppWrapper and BodyWrapper height: 100%

- src/components/NavBar/index.tsx
- src/components/NavBar/style.css.ts
- src/pages/Landing/index.tsx
- src/theme/index.tsx
Adding a glow to the Swap component on a landing page + fixing a z-index issue
> feat: add glow to landing page

- src/pages/About/index.tsx
No periods in headings to be consistent
> fix: remove period in about copy

- src/components/WalletModal/index.tsx
I would rather do this in some async fashion, but we don't have that set up in the app right now. I also think it can be confusing if there are random listeners all over, so maybe this is actually good to be explicit?
> feat: close landing page when wallet connected

- src/hooks/usePermitAllowance.ts
Fixes a bug where a user could submit a transaction, but would be required to re-sign a permit for a subsequent transaction, because the prior transaction's modification of allowance was not detected.
See https://github.com/Uniswap/widgets/pull/336.
> fix: observe submitted allowance immediately

- src/pages/Swap/index.tsx
If a `swapInputError` is present, shows that text instead of the approval button.
This codepath can be triggered by trying to swap an unapproved token for which you have insufficient balance to trade:
- _before_: shows approval flow
- _after_: shows "insufficient <TOKEN> balance" error
> fix: show error when present (not approval)

- src/nft/components/profile/list/SetDurationModal.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2508
Task requested ability to set days to empty when typing delete
Show error state with 0 or no amount set
No error state when value is set
> fix: allow empty states on days in listing

- src/pages/Landing/index.tsx
An alternative option to ship while we iterate on the landing page designs
> fix: remove learn more link on landing page

- cypress.config.ts
This was reverted by accident in this PR: https://github.com/Uniswap/interface/pull/5596
It's causing some tests to fail on main right now. In the future, we should be mocking network calls so we're not reliant on the chain state being synced.
> build: change cypress timeout to 24s

- cypress/e2e/wallet-dropdown.test.ts
These are consistently flaking so better to remove until we resolve the issue.
> test: skip wallet dropdown tests

- src/pages/Landing/index.tsx
This makes it so the button won't be hidden on any screens.
> fix: add more padding-bottom on mobile landing page

- cypress/e2e/wallet-dropdown.test.ts
reverting changes to walletdrop down test to run all tests in a single flow.  This is how the test have been for a while and were not flaky.
> fix: reverting some changes to wallet dropdown

- src/hooks/usePermit2.ts
- src/hooks/useTokenAllowance.ts
- src/lib/hooks/useApproval.ts
- src/pages/Swap/index.tsx
Add a `pending` state to `permit` which, once an approval is submitted, will flip to `true` and not flip back to `false` until the allowance has re-synced. This ensures that the UI stays in a pending state until an approval is processed, without re-prompting for approval.
> fix: await syncing allowance to update permit state

- src/components/Tokens/TokenDetails/BreadcrumbNavLink.tsx
Adds some CSS to the Token Details Page to constrain the width of the "< back" Link component. Previously it was flex-growing to fill the parent width, but that was causing the cursor-pointer effect to happen all the way to the right, over empty space.
> fix: constrain width on token details back button

- src/components/SearchModal/CommonBases.tsx
Changes the CSS color variable used in the "selected" state for the suggested tokens in CurrencySearchModal.
from design:
"what's wrong here is that the selected token chip is pink which means it's probably using our color variable action
it should be using our variable name active
our color variables are pair values that swap back and forth depending on light or dark mode. this is a common mistake here because action is blue in dark mode, pink in light mode, whereas active is blue in both light and dark modes"
tested by verifying that the new color is blue in both light and dark mode
> fix: correct color for selected token in CurrencySearchModal

- src/components/NavBar/SearchBar.tsx
this placeholder text wasn't updating properly when switching locales.
i think this is because it's a text attribute for a Pure Component, like [the example from the docs](https://lingui.js.org/guides/optimized-components.html)
we could probably also solve by extracting this component and wrapping with `withI18n`, as suggested there. but I didn't want to add another `Input` component to the codebase when this simple fix also works. We should standardize to one component as part of the [Web Component Library](https://www.notion.so/uniswaplabs/Web-Component-Library-198412dd549d43429382e687d7020c44) work.
before: 
https://user-images.githubusercontent.com/66155195/207982226-b9029d81-5f2f-4bfb-8a09-266a2429d3c1.mov
after:
https://user-images.githubusercontent.com/66155195/207982048-70ad075c-83 …
> fix: use render function for SearchBar placeholder translation

- cypress/e2e/redirects.test.ts
this test was not updated along with a recent code change.   This will cause a recurring failing cypress test for everyone.  This change fixes that failing test.  Tested and verified locally
> fix:  failing cypress test

- src/components/swap/SwapDetailsDropdown.tsx
- src/components/swap/SwapModalHeader.tsx
- src/components/swap/TradePrice.tsx
- src/pages/Swap/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-1505?atlOrigin=eyJpIjoiNjMxY2Q2YmVlYzgyNDMyZjk5Y2JlNjJiYzQxNzY3MjQiLCJwIjoiaiJ9
Changes the font size for this text to 14px, which matches the gas price on the right.
I also noticed that the `showInverted` state doesn't need to be held at the top level of `Swap` and get passed down via props. It can just live in the component that is using it, `TradePrice`.
I can split the changes into 2 PRs if needed.
> fix: correct font size for the trade rate to on safari

- src/pages/Landing/index.tsx
Wallet cached -> stay on landing page
Wallet not cached -> redirect to swap
This does not yet handle the case where the user clicks on the header or is linked specifically to the landing page yet.
> feat: navigate to /swap if user has a wallet cached

- src/pages/Landing/index.tsx
This prevents the flash of content when the landing page loads before there's a redirect to /swap.
> fix: wait to render Landing content until checking wallet cache

- src/components/NavBar/index.tsx
This makes sure that users who click on the nav bar always see the intro content. Otherwise, we would automatically redirect them back to swap if they had a wallet connected already.
> feat: push nav icon to /?intro=true

- src/pages/Landing/index.tsx
This enforces that the landing page will show when the query param is used, even for users with a conncted wallet. This is useful for linking via a Tweet or for usage elsewhere in the app.
> feat: force landing page to show based on `landing` query param

- src/pages/App.tsx
- src/pages/Swap/redirects.tsx
By this point we can assume that there aren't many active links to the /claim url. Instead, users could just claim from the menu.
> chore: remove /#/claim

- cypress/e2e/nfts.test.ts
- cypress/e2e/pool.test.ts
- cypress/support/e2e.ts
These skipped tests don't need to test the behavior of the announcement.
> test: disable fiat announcement on cypress tests

- .env
- .env.production
- .github/workflows/release.yaml
- src/components/ErrorBoundary/index.tsx
- src/index.tsx
- src/utils/env.ts
Fixes WEB-2623
This PR allows disabling Sentry with an environmental variable (instead of disabling it via Sentry dashboard) and provides a better UX when we don't have a way to follow up on a reported error ID.
> feat: better UX when Sentry disabled

- .github/workflows/release.yaml
Updates the source maps settings as per Sentry documentation (see below):
----
That is, if your file is similar to:
JavaScript
```
// -- end script.min.js
//# sourceMappingURL=script.min.js.map
```
and is hosted at http://example.com/js/script.min.js, then Sentry will look for that source map file at http://example.com/js/script.min.js.map. 
Your uploaded artifact must therefore be named http://example.com/js/script.min.js.map (or ~/js/script.min.js.map).
> fix: Sentry source maps URL

- .github/workflows/release.yaml
Pauses scheduled releases to coincide with the holidays.
This will be reverted after the holidays.
> build: pause scheduled releases

- src/nft/components/explore/Cells/Cells.tsx
- src/nft/components/explore/Table.tsx
- src/pages/Landing/index.tsx
`justify-content: end` doesn't work on safari. 
@zzmp @grabbou should own adding a lint rule to prevent using `end` in flex properties.
> fix: end -> flex-end

- src/nft/components/profile/view/EmptyWalletContent.tsx
Center Empty Wallet text on mobile. Also show ENS if present but this should be a very rare edge case which only happens if ens has registered the NFT to the wallet before our BE has indexed it.
New:
> fix: center empty wallet text on Profile Page Mobile

- src/constants/TokenLogoLookupTable.ts
- src/hooks/useAssetLogoSource.ts
Use chainId to select network-specific token logos in the Token Search modal results.
https://uniswaplabs.atlassian.net/browse/WEB-2350?atlOrigin=eyJpIjoiNTk4NDNlZGFmYTY4NDkxNjg0YTc4YjAzZjM5ZjIzYWIiLCJwIjoiaiJ9
the bug report says we should show "No results" in the case of pasting an address of a token from a different network. But I confirmed with product that we actually want to show an unknown token if the user pastes a token address into the search directly.
this change just ensures we don't incorrectly show a token logo from a different chain.
> fix: stop showing the token logos from different chains as a fallback

- cypress/e2e/token.test.ts
- src/components/Tokens/TokenDetails/About.tsx
- src/components/Tokens/TokenDetails/Skeleton.tsx
- src/components/Tokens/TokenDetails/index.tsx
- src/pages/TokenDetails/index.tsx
- src/utils/nativeTokens.ts
Shows the `AboutSection` for native tokens. To get the correct data from the TokenQuery for the native token, we need to use a different contract address than `nativeOnChain(pageChainId).wrapped.address` in some cases. This is because ETH is in the database with contractAddress="ETH". So, for some networks (celo, polygon) we can continue to query the wrapped native token but for ETH metadata we need to use this DB-specific key.
https://uniswaplabs.atlassian.net/browse/WEB-1982?atlOrigin=eyJpIjoiYTU0NjgwMTI4OGQyNGI5Njg5YzU4MWYxMmIyNGU3OGUiLCJwIjoiaiJ9
> fix: include descriptions and links for native tokens

- src/graphql/data/__generated__/types-and-hooks.ts
- src/nft/components/profile/list/ListPage.css.ts
- src/nft/components/profile/list/NFTListingsGrid.tsx
No functional difference, should only deprecate use of VE in this file and delete unused style.
> chore: Migrate NFTListingGrid from vanilla-extract to styled-components

- src/components/TokenSafety/TokenSafetyLabel.tsx
- src/components/TokenSafety/TokenSafetyMessage.tsx
- src/hooks/useTokenWarningColor.test.ts
- src/hooks/useTokenWarningColor.ts
- src/test-utils.tsx
- src/theme/colors.ts
https://uniswaplabs.atlassian.net/browse/WEB-1612?atlOrigin=eyJpIjoiYTgxYTE1MWU5ZjcyNDI5NWIwNTA0OTI0MzlhZGE1ZGMiLCJwIjoiaiJ9
updates the token warnings to use the correct colors matching design spec: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=8031%3A95901&t=KxoNn01mFw7AgQDh-0
also, updates the hooks for getting the colors so that we're not unnecessarily storing the colors in state variables.
and adds some unit tests for these hooks.
[WEB-1612]: https://uniswaplabs.atlassian.net/browse/WEB-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: colors in token warnings

- public/index.html
changes the default background colors for our root elements in the site.
the bug here is that we were always showing the dark linear-gradient when the page loaded. the theme-aware defaults in the CSS below were never visible. now, when the page loads, we use these theme-aware backgrounds. later, when the app runs, we still set the background of `#background-radial-gradient` as usual. ([see here](https://github.com/Uniswap/interface/blob/1802f50163bf8092dac6916d64b9e08ac2ae0a74/src/theme/components/RadialGradientByChainUpdater.ts#L30)).
now, when the page loads or reloads we will show the background corresponding to the user's preference in their OS/browser. note that this may not correspond to their most recent theme in our app, which we rely on javascript to store and propagate …
> fix: theme-aware root element color

- src/nft/components/profile/list/PriceTextInput.tsx
- no functional difference only changes the components to use styled components instead of VE
- the only exception is the location of the top right icon when setting a global price which is now better aligned
> chore: Migrate List PriceInput from vanilla-extract to styled-components

- package.json
- yarn.lock
Fixes WEB-2550
TL;DR we pinned it down due to a bug, it's fixed now, so we're good to go.
> chore: update Sentry version

- .env.production
We have already disabled Sentry last year. This flag is just to re-build our project with different error page (without Sentry error ID). 
We will turn this back on in the next 3-4 weeks, once we have improved our tracking with additional context, letting us resolve and most popular bug reports.
> chore: disable Sentry in production

- src/components/Web3Status/index.tsx
- src/state/application/hooks.ts
Fixes WEB-2736
When trying to connect to a network with a Metamask wallet, our application enters infinite render loop and crashes. The reason for that can be traced down to a recent commit https://github.com/Uniswap/interface/commit/802714377ce1e8a9d3ac7c57642bacbad7f86d57 where we added a modal to show on a connection error.
> TL;DR: Do not use any `toggle` functions with `useEffect`, as putting them as a dependency will cause `useEffect` to run infinitely.
This error is caused by a `useEffect` hook that listens to connection errors and in case a connection error happened (and we're using Metamask), it would toggle a special modal. 
Due to the architecture of our modal logic, each `toggle` hook is wrapped with a `useCallback` that depends on the state:
```ts
export function …
```
> fix: infinite render loop on connection error

- src/hooks/useENSAvatar.ts
Fixes WEB-2602
When ENS avatar is invalid, e.g. `eip155:1/erc721: 0xabEFBc9fD2F806065b4f3C237d4b59D9A97Bcac7 / 6058`, the application would crash when parsing.
In case of WEB-2602, this is caused by a token id containing whitespaces (we split by `/`). Looking at example provided above, the value of ID would be ` 6058`, causing the application to crash.
This PR guards ID parsing with a try/catch, similar to what we already do within `useContract` hook.
Note: I also tweaked the code to not pass an `id` to either `useERC721Uri` or `useERC1155Uri` since I believe no parameters should be passed when the address wasn't written in one of these protocols.  This code doesn't look beautiful, but this is caused by the throughout use of hooks in those functions, making it impossible to use …
> fix: crash when invalid ENS avatar

- src/components/AccountDetails/index.tsx
- src/components/WalletModal/index.test.tsx
- src/components/WalletModal/index.tsx
- src/components/Web3Status/index.tsx
- src/connection/utils.ts
Renames `getIsMetaMask` and `getIsCoinBaseWallet` to a less confusing (actually more accurate) names. At the same time, it also fixes a bug where `getIsMetaMask` was used to display a MetaMask specific message by introducing a proper `getIsMetaMask` function.
I also decided to make a second argument to `getConnectionName` optional, MetaMask helper is defined in the same file as `getConnectionName`, hence I don't consider that argument necessary to be passed explicitly.
> refactor: less confusing MetaMask extension/connection detection

- src/nft/components/bag/Bag.tsx
- src/nft/components/bag/profile/utils.ts
- src/nft/components/profile/list/ListPage.tsx
- src/nft/utils/currency.ts
First PR for the floating bottom bar for the new list page, hidden behind Listing V2 Feature Flag. Dynamically adjusts price and button status depending on user entered price. Overlay below the bar when items scroll underneath. Hides listing panel if flag is enabled until listing is started. Also deprecated some VE components.
Known issues to be resolved in follow up PRs:
- Bar width doesn't match grid width. This will be resolved when the grid layout is updated when we change over the Listing Bag to a centered modal.
- Bar overlaps into current Listing Bag. Will also be resolved when bag is moved to a centered modal
- Mobile. Currently unsupported and will get its own PR.
- Error states. Error states like listing below floor or above current list price will show a misaligned warning …
> feat: [List V2] Initial Floating Bar

- package.json
- src/lib/hooks/useTokenList/fetchTokenList.test.ts
- yarn.lock
Updates fetchTokenList.test.ts using jest-fetch-mock to match the tests in widget.
This removes the GitHub Action lint warning for the skipped test.
> test: enable skipped fetchTokenList test

- .github/workflows/release.yaml
Skips Monday releases. This can be reverted _after_ next Monday, which should be skipped due to holiday.
> build: skip Monday releases

- src/hooks/usePermitAllowance.ts
- src/utils/signTypedData.ts
Falls back to eth_sign if eth_signTypedData_v4 (ie EIP-712) is not implemented, eg for zerion.
This has been tested with zerion; other known wallets implement EIP-712.
Implementing this as a polyfill overriding JsonRpcSigner.prototype._signTypedData allows the fix to propagate to widgets as well. This is preferable to a utility method (eg `function signTypedData(...)`), as that would require additional changes/releases to widgets.
This will be ported to conedison, as well as proposed as an upstream change to ethers.
WEB-2792
> fix: fallback to eth_sign for permit approval

- src/pages/Swap/index.tsx
Fetches allowances off of the entered state, so that they can be fetched immediately and returned quicker.
> fix: fetch allowances without debouncing

- src/pages/Swap/index.tsx
Computes the price impact of the current debounced trade, to prevent state leaking between trades while a user types.
> fix: compute price impact off of debounced trade

- src/hooks/useUniversalRouter.ts
- src/utils/swapErrorToUserReadableMessage.tsx
- Retries gas estimation after an unexplained failure.
- Logs swap errors to the console as warnings, to aid in debugging.
CX-140
> feat: retry gas estimate and log to console

- src/pages/Swap/index.tsx
Removes the "Approval failed...retry" UI, because it is not reset between clearing inputs, or switching tokens, after a failure has occurred.
Maintaining it adds a lot of complexity, and it is safer to just remove it altogether.
> fix: rm "approval failed" UI

- src/utils/prices.test.ts
- src/utils/prices.ts
Considers a loading trade to have `0` price impact warning, so that the swap button does not use an `error`-colored background.
Fixes the flash of red (error) swap button while the swap is still loading.
> fix: avoid error swap state while loading

- src/utils/signTypedData.ts
Uses an unversioned call for signTypedData so that it is accepted by all wallets. SafePal hangs on _v4.
Practically, this uses eth_signTypedData for all wallets _except_ for MetaMask, which rejects it and falls back to eth_signTypedData_v4.
Tested with:
> fix: allow signing from safepal

- src/hooks/useUniversalRouter.ts
- src/utils/swapErrorToUserReadableMessage.tsx
Update the messaging on gas estimate errors.
New text will be: Your swap is expected to fail. Try increasing your slippage tolerance. Note: certain tokens are incompatible with Uniswap V3.
> fix: amend gas estimate error message

- src/components/WalletDropdown/SlideOutMenu.tsx
The change to use `webkit` fill available for title of the slideout menu breaks for non-webkit browsers ie firefox. This is a more general solution. Tested on both firefox and chrome.
Before:
After:
> fix: slideout menu title overlap on firefox

- src/components/AccountDetails/index.tsx
- src/components/WalletModal/index.test.tsx
- src/components/WalletModal/index.tsx
- src/connection/utils.ts
- src/react-app-env.d.ts
Fixes WEB-2729
Brave Wallet sets "isMetaMask" to true for compatibility purposes (it uses the same API). This PR updates the detection mechanism to ensure that we show "Connect with MetaMask" only when connecting with MetaMask. 
Breakdown of all possible combinations of Brave & MetaMask together with UI behavior is broken down in the Jira ticket.
> feat: detect Brave Wallet 

- src/components/WalletDropdown/AuthenticatedHeader.tsx
before: 
after:
tested on safari, chrome, firefox.
> fix: txn header styling for long ens names

- package.json
- yarn.lock
Upgrades @uniswap/universal-router-sdk to fix a bug where legacy wallets submitted unhandled legacy signature formats, with suffixes that failed to execute when calling estimateGas.
See ticket CX-140
> fix: sanitize legacy signature format

- src/components/Widget/index.tsx
Fixes "Connect Wallet" through the widget, by implementing a callback for onConnectWalletClick. This triggers the interface wallet modal, instead of connecting through the widget (which does not make the connection available to the interface).
WEB-2813
> fix: use wallet modal for widget-prompted connection

- cypress/e2e/nfts.test.ts
- src/graphql/data/__generated__/types-and-hooks.ts
We previously had an NFT test that checked to see you could buy an item on its Details page. That NFT is no longer for sale so the test broke. I'm changing the NFT we check to one I own and just listed for 6 months (max duration) for 1K ETH. This will allow me to fix this test when it breaks every 6mo without making a code change by re-listing it. If it sells, I'll split the 1K ETH with web 😘
Also it seems like someone didn't check in a change to the generated GQL files, please remember to add!
> fix: Broken NFT Details test

- src/nft/components/bag/Bag.tsx
- src/nft/components/bag/BagFooter.tsx
- src/pages/Swap/index.tsx
* Removes the call to fetch the usdPrice and gets it from the `useStablecoinValue` hook for the bag footer
* NOTE: when testing with pay with any token it breaks when going back from WETH -> ETH. This is actually a bug in `useStablecoinPrice` and happens on swap I am looking into it #5904
> chore: removeing fetch usd price for bag footer

- src/components/About/AboutFooter.tsx
- src/theme/components/index.tsx
make the "app" category links the same font-weight as the others.
this was broken because we were not using the global Link styling.
also - removed unnecessary props from External Links on this component
> fix: about footer link weights

- src/hooks/useStablecoinPrice.ts
* This adds a check between the last price and the new price if the currency itself changes. This is necessary because when used with `useStablecoinValue` when switching from a currency with the same numerator and denominator (which is what `equalTo` checks) will throw an invariant error because the `quote` function checks if the `CurrencyAmount`'s currency is the same as the base currency. This will result in never rendering the new price.
* this can be tested on main when you put in a value for WETH then switch to ETH it will load forever
> fix: useStablecoinPrice switching between WETH and ETH

- src/components/Widget/transactions.ts
currently we're not logging this event for widget transactions, because the [current logging logic](https://github.com/Uniswap/interface/blob/9719af66e5a74a5a3c58ed6333cba1340a838145/src/state/transactions/updater.tsx#L84) relies on interface-level state to exist (for a widget transaction, that state is managed in the widget instead, so the event is not logged)
note: this should be applied to the widget in token details too, so i'm not gating it behind the feature flag
> feat: widget on tx success callback

- src/components/WalletModal/PendingView.tsx
- src/components/WalletModal/index.tsx
Updates the connection error screen to show the actual error string, so that the user can take corrective action.
This is necessary for eg Frame, where on initial install no wallet is selected. In this case, the error is something like "No account selected".
Before:
WEB-2865
> fix: surface connection error

- src/components/WalletModal/PendingView.tsx
- src/components/WalletModal/index.tsx
Reverts Uniswap/interface#5931, as it risks showing an overly technical error message to the user.
It should be designed such that the user opts in to such a message (eg the error screen, where the user toggles open the technical error message).
> revert: "fix: surface connection error"

- src/nft/components/profile/list/ListPage.tsx
Add extra bottom padding to the grid of NFT's being listed. Prevents issue where listing multiple the bottom row would be covered by the bar
Before
After
> feat: [ListV2] Add extra bottom padding to collection assets

- src/nft/components/profile/list/Modal/ContentRow.tsx
- src/nft/components/profile/list/Modal/ListModal.tsx
- src/nft/components/profile/list/Modal/ListModalSection.tsx
- src/nft/hooks/useNFTList.ts
Adds the logic to support retry and removing listings/collection approvals in the case of failures and rejections. Also added autoscrolling to the actively signed row in the modal.
Retry panels:
> feat: [ListV2] Add retry and remove logic to listings and collection approvals

- src/nft/components/bag/profile/ListingButton.tsx
- src/nft/components/bag/profile/ListingModal.tsx
- src/nft/components/bag/profile/utils.ts
- src/nft/components/profile/list/ListPage.tsx
- src/nft/components/profile/list/Modal/ListModal.tsx
- src/nft/components/profile/list/Modal/ListModalSection.tsx
- src/nft/hooks/useNFTList.ts
- Previously removing a collection after rejecting/failing would get the user stuck where all approval states would reset and there would be no way to restart the flow. This maintains approved, rejected, and failed statuses to allow the user to continue on. 
- The old method for updating a rows status and callback would did not account for row removal, I've updated the logic to be dynamic and tied to the zustand hook
- Also fixes a bug where removing a collection would create duplicate approval rows.
To test you should try listing and approving multiple collections and markets on V1 and V2 and be able to reject, remove, and retry as expected
> fix: [ListV2] Better Collection and Listing Retry and Removal Logic

- src/nft/utils/listNfts.ts
Marketplace may fail the call when listing which we currently handle or return a failed bool which we now handle with this PR.
> fix: Handle Different Listing Failure Responses

- src/graphql/data/Token.ts
- src/graphql/data/TokenPrice.ts
- src/graphql/data/__generated__/types-and-hooks.ts
- src/utils/nativeTokens.ts
fixes issue where non-addressed native tokens would not normalize in cache correctly.
moves interface away from using `"ETH"` convention for natives, matches mobile's usage of `null`
> fix: default to null when query address is undefined

- package.json
- yarn.lock
Upgrades conedison to improve signing.
conedison@1.3 updates signTypedData to default to eth_signTypedData_v4 and only use eth_signTypedData for special-cased wallets.
---
Manually tested on:
> feat: upgrade conedison to improve signing

- src/components/Tokens/TokenDetails/index.tsx
- src/components/Widget/index.tsx
- src/components/Widget/inputs.tsx
- src/pages/Swap/index.tsx
enables the callsites of our Widget integration to pass either/both of the input and output currencies. 
this is needed to handle URL params for the /swap page. for example, see this link: 
https://app.uniswap.org/#/swap?inputCurrency=0x6B175474E89094C44Da98b954EedeAC495271d0F&outputCurrency=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
we still keep support for specifying a "default" token, which is currently just used to do automatic navigations on the token details page.
> fix: URL params for widget

- src/components/Widget/inputs.tsx
enables the "common bases" feature for the token selector that the widget uses
> fix: showCommonBases for widget token selector

- src/nft/components/profile/list/ListPage.tsx
- src/nft/components/profile/list/MarketplaceRow.tsx
- src/nft/components/profile/list/NFTListRow.tsx
- src/nft/components/profile/list/NFTListingsGrid.tsx
- Adds a hover state to listing rows
- When hovering display trash icon for removing listing
- When listing to multiple markets display all selected markets next to price
- When hovering over with multiple markets show expand/collapse icon to modify specific market listings
- specs: https://uniswaplabs.atlassian.net/browse/NFT-1088
Screenshots:
> feat: [ListV2] Changes to Multiple Market handling and row hovering

- src/hooks/useFetchListCallback.ts
- src/state/lists/updater.ts
fixes bug where new versions of tokenlists weren't being checked into cache
before (Gold1 is supposed to be blocked): 
after:
> fix: use latest version of tokenlists over cache

- src/nft/components/collection/TransactionCompleteModal.css.ts
- src/nft/components/collection/TransactionCompleteModal.tsx
When 1 asset would get purchased and the rest refunded the modal would wrap. This is a quick fix to address that problem.
Out of scope: refactor the TxComplete modals to styled components
Screenshots:
> fix: Mixed success modal wrapping

- src/components/SearchModal/CurrencySearch.tsx
adds a border radius to the CurrencySearch component explicitly, because Safari wasn't displaying this content correctly
https://uniswaplabs.atlassian.net/browse/WEB-2871?atlOrigin=eyJpIjoiMzczNmZkOWM2MGY0NGI5MGJiYWEzYTY5ZmU3NjdjOWEiLCJwIjoiaiJ9
> fix: round corners of CurrencySearch

- src/nft/components/profile/list/MarketplaceRow.tsx
- src/nft/components/profile/list/RoyaltyTooltip.tsx
Updated the fee tooltip to the latest mocks
Screenshots:
> feat: [ListV2] Updated fee tooltip style

- src/nft/components/profile/list/MarketplaceRow.tsx
- src/nft/components/profile/list/NFTListingsGrid.tsx
The table headers Z-Index was below the multiple marketplace icons layering which causes them to display over the set price by dropdown. This fixes that bug. There was also a bug where the remove marketplace on an expanded row just removed the first marketplace and not the one clicked.
After
Before
> fix: Market icons displaying over dropdown

- src/utils/swapErrorToUserReadableMessage.tsx
keep up to date with widget
context: ethers upgrade to 5.7.0 changed error code when user rejects txn, so we need to handle the extra edge case.
> fix: update user rejected txn errors to stay up to date with widget

- src/constants/lists.ts
changes our default token list to be the IPFS hosted one, while we investigate a cloudflare issue
> fix: use ipfs token list temporarily

- src/constants/lists.ts
same as #6006 but for the unsupported list and the extended list - temporarily use the IPFS gateway hosted version instead of the cloudflare ones
> fix: use ipfs token list as fallback for unsupported list

- src/components/Widget/index.tsx
based on design feedback, we should not be hiding this UI in the interface
> fix: dont hideConnectionUI for widget

- src/components/Widget/index.tsx
specify the default Chain ID for the widget - it should just match the current provider.
we actually weren't/aren't defaulting to the chain of the provider in the widget, so this change fixes some undesired behavior
> fix: widget defaultChainId

- src/components/Widget/inputs.tsx
This makes sure that you can't get to a state where the selected tokens are disabled.
> fix: reset tokens, amounts when switching chains

- .github/workflows/release.yaml
`upload` job id seems to have been changed to `pinata`
The release texts don't have valid ipfs URLs and also the crust step is always failing (but does not block the release)
> ci: references to old id `upload`

- src/components/Widget/index.tsx
Reverts Uniswap/interface#6010
based on design feedback, we actually want a different solution here - `hideConnectionUI` should still be true, but it should not hide the actual "connect wallet" button. (this part will require a PR in the Widget repo)
> revert: dont hideConnectionUI for widget

- src/graphql/data/__generated__/types-and-hooks.ts
looks like the schema changed and so the generated types need to change to match
> chore: schema changed gen types

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/nftlGraphql.ts
We're migrating 3 nft endpoints to GraphQL: activity, search collections, and trending. To facilitate this I've created a feature flag. This feature flag should be able to be toggled both by the local feature flag modal as well as via the statsig portal. The statsig gate is `nft_graphql_migration`.
> feat: add new statsig backed feature flag for nft graphql migration

- src/components/NavBar/SearchBarDropdown.tsx
- src/featureFlags/flags/nftlGraphql.ts
- src/graphql/data/__generated__/types-and-hooks.ts
- src/graphql/data/nft/TrendingCollections.ts
- src/nft/components/explore/Banner.tsx
- src/nft/components/explore/CarouselCard.tsx
- src/nft/components/explore/Cells/Cells.tsx
- src/nft/components/explore/CollectionTable.tsx
- src/nft/components/explore/TrendingCollections.tsx
- src/nft/types/discover/discover.ts
- Adds graphql hook for topCollections endpoint
- Used in Explore Table, Explore Carousel, and Search Suggestions when flagged
- Makes all fields in TrendingCollection optional
- There's some added conditional logic as floor from gql is in ETH whereas it is in wei from the REST api
> feat: Migrate trending nfts endpoint to graphql

- craco.config.cjs
Works around a bug where vanilla-extract compilation hangs on M1 macs, causing `yarn start` to never resolve.
See https://github.com/vanilla-extract-css/vanilla-extract/issues/771#issuecomment-1249524366.
This configures vanilla-extract class names to use 7+ character hashes, which will make them more difficult to debug. However, I don't know that the debug names are being used, and they are making it very difficult to develop with an M1 macbook, so this seems worthwhile.
> build: fix vanilla-extract for M1

- package.json
Updates to latest now that we don't need sdk-core's SupportedChainId to match up.
This won't actually change yarn.lock since 3.2.0 was already installed because of widget's requirement
> build: upgrade sdk-core

- cypress/e2e/send.test.ts
Unclear what caused this to start being flake-y but it does work on localhost for me. I will renable this once I can look at it later today, but just don't want this to block deploys on Monday.
> test: disable /send redirect test temporarily

- cypress/support/ethereum.ts
This will avoid bugs in the future where people don't know that the hex return is tied to the expected testnet id.
> refactor: variable for goerli in test

- src/hooks/useTokenAllowance.ts
Omit gas estimation from token.approve - it is unnecessary.
> fix: omit gas estimation from token.approve

- package.json
- src/components/WalletModal/index.tsx
- yarn.lock
https://uniswaplabs.atlassian.net/browse/WEB-2879?atlOrigin=eyJpIjoiZGQ1NTVmNDU2MzY1NGRmMjgwMzU4ZTM2MGYzYmEwMTMiLCJwIjoiaiJ9
log the "Peer wallet name" to the `WALLET_CONNECT_TXN_COMPLETED` event - this is the WalletConnect-ed wallet (i.e. if you use wallet connect to connect to Rainbow, this field will be Rainbow)
update: the actual value will be the Peer Wallet "Agent" which includes some more technical details about the connected wallet.
> feat: add Peer Wallet Name to WALLET_CONNECT_TXN_COMPLETED event

- src/components/TokenSafety/index.tsx
fixes a live bug in prod where we show an empty modal for tokens that don't match the current chain
i think we should use this as a short term fix, so we show _something_ in the case that we can't find the token. 
in the future, we may want to try auto-switching chains, or showing a message that says "try a different chain"
to test, append `?outputCurrency=0x4200000000000000000000000000000000000006` to the preview link (after `/swap`)
https://user-images.githubusercontent.com/66155195/223544058-aabd47c6-3114-4033-9369-7de492bc7e7a.mov
https://user-images.githubusercontent.com/66155195/223544401-d4011331-f019-4259-a539-1d86693dc7d7.mov
> fix: show error message when token is not found

- src/pages/App.tsx
- src/react-app-env.d.ts
Export the `GIT_COMMIT_HASH` onto the `window` object so that we can verify which version is deployed.
> feat: export window.GIT_COMMIT_HASH

- src/graphql/thegraph/apollo.ts
- src/index.tsx
- src/state/application/hooks.ts
- src/state/burn/hooks.tsx
- src/state/burn/v3/hooks.tsx
- src/state/hooks.ts
- src/state/index.ts
- src/state/lists/hooks.ts
- src/state/logging.ts
- src/state/mint/hooks.tsx
- src/state/mint/v3/hooks.tsx
- src/state/reducer.ts
- src/state/swap/hooks.tsx
- src/state/types.ts
- src/state/user/hooks.tsx
As per design doc, this PR implements Sentry Redux enhancer with an explicit list of whitelisted keys to track the data we need and to avoid any payload changes in case the underlying state shape changes in the future.
Here's a preview of what it looks like, when enabled:
> feat: implement Sentry for state tracking

- src/graphql/data/__generated__/types-and-hooks.ts
- src/graphql/data/nft/TrendingCollections.ts
For ease of use with relay style pagination, infra is removing `cursor` and `limit` from the new gql queries. This only affects the merged in topCollections query.
> chore: Remove limit from topCollections query

- src/hooks/useSyncChainQuery.ts
Previously, if the connector was still activating while a chain param came in, we'd ignore the update. Now, we cache the value until the connecter has activated, then update the chain.
> fix: use `chain` query param properly when activating

- src/hooks/useSyncChainQuery.ts
Reverts Uniswap/interface#6114
Cypress tests never passed for this PR (at any time), roll back pending further investigation to unblock manual releases.
> fix: Revert "fix: use `chain` query param properly when activating"

- src/featureFlags/flags/payWithAnyToken.ts
Universal router is supported for all chains in the interface, so this logic is no longer necessary.
Test:
- Make sure PWAT continues to load in both enabled and disabled states
> refactor: remove universal-router logic in pay with any token flag

- src/components/NavBar/Bag.tsx
- src/nft/components/bag/Bag.tsx
- src/nft/components/bag/BagFooter.tsx
- src/nft/components/profile/list/ListPage.tsx
- src/nft/components/profile/list/ListingButton.tsx
- src/nft/components/profile/list/Modal/ListModal.tsx
- src/nft/components/profile/list/utils.ts
- src/nft/components/profile/view/ProfilePage.tsx
shallow default export is deprecated in favor of a named export. this removes a lot of warnings in the dev console.
> chore: remove deprecated zustand import

- src/components/CurrencyInputPanel/FiatValue.tsx
- src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
- src/components/CurrencyInputPanel/index.tsx
- src/components/Widget/transactions.ts
- src/components/swap/ConfirmSwapModal.tsx
- src/components/swap/SwapModalFooter.tsx
- src/components/swap/SwapModalHeader.tsx
- src/components/swap/TradePrice.tsx
- src/graphql/data/TokenSpotPrice.ts
- src/graphql/data/util.tsx
- src/hooks/useSwapCallback.tsx
- src/hooks/useUSDPrice.ts
- src/hooks/useUniversalRouter.ts
- src/lib/utils/analytics.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/Swap/index.tsx
- src/state/routing/useRoutingAPITrade.ts
- src/utils/computeFiatValuePriceImpact.tsx
[will add more in the morning]
We were previously assuming USDC = $1 and routing all pricing through a token <-> USDC swap. That is sadgely no longer the case. This new algo does a route through ETH:
Token -> ETH -> USD where the ETH -> USD quote uses our gql endpoint to fetch ETH price.
> feat: Use ETH based pricing instead of USDC based pricing for quote USD values

- src/graphql/data/util.tsx
- src/hooks/useUSDPrice.ts
- Fix usd price loading case for WETH. To get the price of WETH in ETH, just return 1 lawl.
- GQL calls fail on testnets, so dont send them. Instead, route through old `useStablecoinValue`
> fix: USD price for WETH + don't call gql for testnets

- cypress/e2e/token-details.test.ts
- src/components/NavBar/SuggestionRow.tsx
- src/components/Tokens/TokenDetails/ChartSection.tsx
- src/components/Tokens/TokenDetails/PriceChart.tsx
- src/components/Tokens/TokenDetails/index.tsx
- src/components/Tokens/TokenTable/TokenRow.tsx
- src/graphql/data/RecentlySearched.ts
- src/graphql/data/SearchTokens.ts
- src/graphql/data/Token.ts
- src/graphql/data/TokenPrice.ts
- src/graphql/data/TopTokens.ts
- src/graphql/data/TrendingTokens.ts
Update our gql queries to call `token.project.markets.x` instead of `token.market.x` because the pricing is more accurate there. `token.market.x` refers to our subgraph which hardcodes usdc as the USD indicator
> fix: Use non-subgraph fields for calculating USD prices on explore and token details pages

- src/components/RangeSelector/PresetsButtons.tsx
- src/pages/AddLiquidity/index.tsx
- src/state/mint/v3/hooks.tsx
- src/utils/routes.ts
- urls should fill the inputs
- updates to the url should update the inputs
- updates to the inputs should update the url
- full range button should function
the following path should pre-fill a full range position on this pool https://interface-git-fork-jfrankfurt-fix-full-range-lp-uniswap.vercel.app/#/add/ETH/0x6B175474E89094C44Da98b954EedeAC495271d0F/3000?minPrice=0.0000000000000000000000000000000000000029543&maxPrice=338490000000000000000000000000000000000
> fix: full range lp shortcut

- src/components/WalletModal/index.tsx
- src/pages/App.tsx
Sets user properties before sending events with those properties, so that queries those events will include populated user properties. Current queries for those events - the first time the event occurs - include unpopulated user properties, so we assume they must be set prior to sending the event.
We believe this to be the cause of WEB-2998.
> fix: set user properties before event properties

- src/components/CurrencyInputPanel/FiatValue.tsx
- src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
- src/components/CurrencyInputPanel/index.tsx
- src/components/swap/ConfirmSwapModal.tsx
- src/components/swap/SwapModalFooter.tsx
- src/components/swap/SwapModalHeader.tsx
- src/components/swap/TradePrice.tsx
- src/hooks/useUSDPrice.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/Swap/index.tsx
- src/state/routing/useRoutingAPITrade.ts
This PR fixes the loading states for USD prices. If a USD route is not found (e.g. we can't get a price) for a token, then it should just stop showing the loading state and show nothing instead.
1. This PR also fixes the ETH amount out we're using for detecting price - we should be using raw amounts instead of parsed amounts. It filters out tokens with <100ETH liquidity on mainnet and 10ETH liquidity on L2s + Celo (10k matic on polygon), which matches closely to our prev strategy of $100k USDC trade.
2. Instead of detecting the loading state purely by the presence of `price` or not, this keeps track of a separate `isLoading` variable as part of the return data from the `useUSDPrice` hook. It captures the first time price load on both gql and rtk-query, and returns that as part of the …
> fix: loading states for USD prices

- src/graphql/data/TopTokens.ts
@matteenm noticed we were not fetching sparklines by volume; this fixes a bug where any tokens that were not in the top 100 TVL did not have a sparkline
before:
after:
> fix: fetch same tokens for topTokens and sparkline queries

- src/graphql/data/SearchTokens.ts
- src/graphql/data/nft/CollectionSearch.ts
In an effort to cut down on extraneous graphql queries, previously every pageload would do an empty query to SearchTokens with blank input. This skips all queries with empty input. We currently have collection search via graphql behind a feature flag so I've added this fix there as well.
> fix: don't fire off a graphql query on an empty search

- src/graphql/data/TokenSpotPrice.ts
- src/hooks/useUSDPrice.ts
This PR fixes an issue where we make extraneous network requests for ETH price.
Two parts:
1. Our default fetch-policy of `cache-and-network` means that every time the gql query hook runs, it will fire a network request regardless of cache status. Use the default `cache-first` policy so that it skips network requests if there exists a price in cache. We have a polling interval on the query, so I'm not too worried about data staleness.
2. We were also passing in `address = undefined` and saving `address = null` so we wouldn't hit the cache properly.
Is `cache-and-network` the right default policy? Am noticing that it is fetching extra network requests on the Token details page as well, but we should figure out a way to do TTLs on the apollo cache so we don't serve stale data. Look into …
> fix: Eth price fetch cache miss and use default fetch policy to remove extra network requests

- .env
- .env.production
- src/serviceWorker/document.ts
- src/utils/env.ts
Turns on Sentry for production builds.
Environment variables on CF seem to have no effect, so this actually enables Sentry.
The cypress tests use a production build, so this may send events from e2e tests, but they should still be tagged to their commit and URL so this is ok.
> feat: enable sentry via .env.production

- src/hooks/useUniversalRouter.ts
- src/tracing/index.ts
- src/tracing/trace.test.ts
- src/tracing/trace.ts
- src/utils/swapErrorToUserReadableMessage.tsx
Adds a performance trace for `swap.send`
Also adds the necessary abstraction for collecting that trace, in `src/tracing`.
> feat: trace swap.send

- src/hooks/useAutoSlippageTolerance.ts
- Instead of weighing gas by 10%, keep gas multiplier at 100%
- Change the range from [.5%, 25%] to [0.1%, 5%]
> fix: Auto-slippage logic

- src/nft/components/card/containers.tsx
there is actually a floating point error when setting width to 100% because of the way the columns are setup, and hiding the outline on lightmode shows this problem. So we decided to put the outline back in for lightmode to hide the off by 1
> fix: cards floating point error

- src/pages/Pool/PositionPage.tsx
This is a cherry-pick commit from the work related to https://uniswaplabs.atlassian.net/browse/WEB-3011
We want to link to a TDP link instead of an external explorer when possible. However, for chains that don't have support in the Uniswap interface we'll continue to link externally.
This also will open in a new tab regardless. That's to prevent the user from losing their existing page state.
https://user-images.githubusercontent.com/4899429/225652763-5a17e129-cdfb-40f5-b45c-8782bbd6fa98.mov
Test:
- Go to a position page on Mainnet, Arbitrum
- Click on one of the token links --  should be a TDP link
- Go to a position page on Goerli
- Click on one of the token links -- should be a scanner link
> feat: link to token details from /pool/{}

- src/pages/Pool/CTACards.tsx
Previously, one tile was weighted larger which led to the CTAs looking uneven. Now, the grid enforces the same width.
To test:
- Go to /pool
- Make sure the tiles are the same width
> fix: equal width for CTA tiles on /pool

- src/components/TaxServiceModal/TaxServiceBanner.tsx
- src/state/user/hooks.tsx
- src/state/user/reducer.ts
tax service banner was not showing for users who had used uniswap before in regular (not incognito) browsers due to cached redux initial state. we are not handling initial state changes correctly atm, so this is a stop gap fix to handle undefined initial state for tax service specifically. we need something to handle this more generally across interface for state updates tho, like mobile does: https://github.com/Uniswap/mobile/blob/main/src/app/migrations.ts (info from @tinaszheng )
> fix: handle undefined tax service banner counter in state 

- src/pages/Pool/index.tsx
Links directly to https://support.uniswap.org/hc/en-us/categories/8122334631437-Providing-Liquidity- instead of just the top level docs site.
To test:
- Go to /pool
- Open the submenu
- Click on the "Learn" button to lead to this doc
> fix: link to providing liquidity help doc

- src/pages/Pool/index.tsx
This menu option was leading to the same place as "Create position" above.
To test this, go to the /pool and make sure the menu does not have "Create position" as an option.
> fix: remove Create a pool menu option

- README.md
- cypress/e2e/landing.test.ts
- cypress/e2e/pool.test.ts
- cypress/e2e/wallet-dropdown.test.ts
- src/components/About/AboutFooter.tsx
- src/components/About/constants.tsx
- src/components/NavBar/index.tsx
- src/components/NavigationTabs/index.tsx
- src/components/PositionListItem/index.tsx
- src/hooks/useIsPoolPage.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/App.tsx
- src/pages/MigrateV2/index.tsx
- src/pages/Pool/PositionPage.tsx
- src/pages/Pool/index.tsx
- src/pages/Pool/v2.tsx
- src/pages/PoolFinder/index.tsx
- src/pages/RemoveLiquidity/V3.tsx
We want to have the nav say Pools instead of Pool, and be /pools instead of /pool. This is so we are consistent in the Nav (ex: Tokens, NFTs are pluralized).
Plan:
- Support both /pool and /pools for a bit. This is so external links don't break.
- Change all internal links to use /pools. Can happen in tandem with ^.
- Add a server redirect in CloudFlare to switch external links from /pool to /pools.
After this we should check that /pool isn't being logged in Amplitude.
Finally:
- Remove /pool Routes in codebase (since they will not be hit anymore).
This PR handles the first 2 steps of this plan.
> feat: support both /pool and /pools

- src/pages/PoolFinder/index.tsx
This was leading to an issue where the user would get to the migration flow from the /pool menu, click into import and then back would lead them to the v2 pools page.
Instead, we'll default to taking them to the main pools page.
Test:
- Go to /pool
- Click menu near "add position"
- Click migrate v2 liquidity
- Click import
- Click back
- You should be on /pool again now
> fix: back button should lead to /pools not /pools/v2

- .github/workflows/test.yml
Turns off cypress parallelization because machines are often started with different settings, requiring tests to be re-run.
Running them on one machine may take longer for a successful run, but is shorter overall if you assume that you may need to retry the run due to configuration.
> test: run cypress on one machine

- src/tracing/index.ts
- src/tracing/jsonrpc.ts
- src/tracing/trace.test.ts
- src/tracing/trace.ts
Conditionally adds a performance trace for `jsonrpc.send`, if it occurs during another active trace.
Also adds the necessary abstraction for conditionally collecting trace, in `src/tracing` (`maybeTrace`).
> feat: trace jsonrpc

- .github/workflows/test.yml
Parallelizes cypress tests by using a consistent container across them
Fixes cypress-tests to accurately reflect the status of cypress-test-matrix
> test: parallelize cypress (again) with a consistent container

- src/components/TaxServiceModal/TaxServiceBanner.tsx
note: I didn't want to change the type of taxServiceDismissals to a boolean flag in redux UserState because of the current data persistence issues of redux-localstorage-simple. Once we update to redux-persist I will remove the MAX_RENDER_COUNT variable altogether and change it to a boolean flag.
> fix: dismiss tax service toast after 1 dismissal instead of 3

- src/components/Tokens/TokenDetails/index.tsx
- src/components/Widget/index.tsx
- src/components/Widget/inputs.tsx
- src/graphql/data/util.tsx
- src/hooks/useOrderedConnections.ts
- src/pages/TokenDetails/index.tsx
this preserves the input/output currency on the TDP when you replace the "default" (detailed) token.
behavior:
1. when navigating to TDP, the detailed/default token is the output and input is empty
2. you can reverse input/output, and select a token to trade in either direction
3. when you replace the detailed token, we automatically navigate to the TDP for the output in the current selections (this could be the newly selected if you replaced the output, or the other token if you replaced the input)
4. <This PR>  we add a query param to the destination URL allowing us to preserve the input token when navigating
this seemed like a simple solution, but there may be alternatives - if we used a global state variable (jotai atom) we could preserve the input without a URL change. the downside …
> feat: preserve input currency on TDP when navigating

- src/pages/Pool/v2.tsx
- src/pages/Vote/Landing.tsx
Ideally, these buttons would have height based on a prop passed in (sm, md, lg) but for now setting a fixed height solves the issue. I'm open to a smaller height, but I think this fits the text size most reasonably.
To test:
- Go to /pools/v2 and make sure buttons are same height
- Go to /vote and make sure buttons are same height
> fix: set height on vote and v2 liquidity buttons

- src/pages/Pool/PositionPage.tsx
This cherry-picks one part of https://github.com/Uniswap/interface/pull/6201, which is a more complete solution for handling position pages across chains. However, we want to wait on that until we make sure that it fits with our multichain plans.
For now, this makes sure that we show an invalid state when there is no position information to render, instead of showing an infinite loading state.
To test this...
- Go to pools/364815 on mainnet to see the position render
- Switch chain to Polygon to see the error state
On main...:
- Go to pools/364815 on mainnet to see the position render
- Switch chain to Polygon to see an infinite loading state
Resolves https://uniswaplabs.atlassian.net/browse/WEB-3006 and resolves https://uniswaplabs.atlassian.net/browse/WEB-3010
> feat: show error state when on invalid position

- src/components/Tokens/TokenDetails/index.tsx
fixes the token details chain updater to use the new chain rather than the current chain when switching to the address of a cross-chain token provided by the backend
> fix: use correct chain var when switching

- src/components/FeeSelector/shared.tsx
when viewing the /add page you should see the 1bps pool option while connected to Arbitrum
https://interface-git-add-1bp-fee-tier-to-arbitrum-uniswap.vercel.app/#/add/0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9/0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8/100
> feat: add 1bps pool to arbitrum

- cypress/e2e/nfts.test.ts
- src/nft/components/profile/list/NFTListRow.tsx
fixes a crash when trying to list an NFT 
the crash happens to me every time i try to list an NFT. repro steps:
- go to your NFTs
- click "list for sale" on an NFT
- click "continue" in sidebar
```
Error: opacify: provided color #98A1C03d was not in hexadecimal format (e.g. #000000)
```
i also added the first half of an e2e test that would prevent this from happening in the future, but need to check w/ the team about they typically test goerli NFTs in e2e tests.
otherwise, i've manually tested and verified that this fixes the listing flow for me
> fix: crash in nft listing flow

- src/components/NavBar/SearchBarDropdown.tsx
The prior implementation assumed backend support would be rolled out comprehensively, but right now assets/portfolio info is supported, but search is not.
https://uniswaplabs.atlassian.net/browse/WEB-3014
> fix: remove backend name check from badge flag

- src/components/WalletDropdown/MiniPortfolio/Pools/index.tsx
was sending in entire token object previously, modify to just address and symbol.
> fix: modify mini portfolio pools row event properties

- src/components/Identicon/StatusIcon.tsx
- src/components/Web3Status/index.tsx
removes the tooltip from Unicons in the Authenticated Header. this is a [design feedback request](https://www.notion.so/uniswaplabs/Get-rid-of-the-Unicon-tooltip-9cba8e1752394d7194e89d393a712de9?pvs=4).
verified manually that the tooltip doesn't exist anymore:
https://user-images.githubusercontent.com/66155195/227617381-c977375d-bed6-420f-87ef-9252fb442e96.mov
> feat: remove unicon tooltip entirely

- src/pages/Pool/CTACards.tsx
This PR makes sure that the title and description for the "info" CTA in the pools page is aligned to the top. This makes sure it's even with the other CTA.
I simplified the code to just use a single CTA component, as we don't believe we need any style changes between the two. I also removed the display: flex as we don't actually need to use align-items or justify-content center here.
after:
before:
Test:
- Go to /pools in the preview
- Play around with how the CTAs look on different view widths
> fix: align /pools CTAs to the top

- src/components/Popups/PopupItem.tsx
- src/components/Popups/TransactionPopup.tsx
https://uniswaplabs.atlassian.net/browse/WEB-3052?atlOrigin=eyJpIjoiMGE3NzhkNDUwMmY3NDQ5Zjk5NTA4Y2Q5MjZjYjJlMGIiLCJwIjoiaiJ9
these notifications were incorrectly removed when we built the nav bar. see the discussion [here](https://uniswapteam.slack.com/archives/CKX7SR7E1/p1679506872715989) for the decision to keep/re-add them.
the component i'm adding here is a direct copy of the one that was reverted, but with imports modernized
i tested by sending swap transactions and verifying that the notifications appeared upon transaction success
> feat: re-add transaction activity popups

- src/graphql/data/util.tsx
- src/pages/Pool/PositionPage.tsx
Previously, the backend chain name was used for linking purposes. However, this is not ideal because those values are uppercased. Similarly, they won't support any chains that aren't supported by the backend (ex: Optimism Goerli).
Instead, we use the existing CHAIN_IDS_TO_NAME mapping.
Test:
- Go to a position page on a chain which the graphql API supports (ex: mainnet) and click on a token (should take to token details with a lowercase chain in url.
- Go to a position page on a chain which the graphql API does not support (ex: goerli) and click on a token (should take to etherscan).
> fix: link to lowercase chain name from position page

- .github/pull_request_template.md
- README.md
Updating the PR template to standardize how PR descriptions are written. The purpose is to help contributors provide useful context to reviewers to understand the changes being made and how they're being tested.
- Moved PR Title convention to `README.md`
- Took inspiration from backend + mobile PR templates.
n/a
> docs: Update PR template

- .eslintrc.js
- src/nft/hooks/useBag.ts
- src/nft/hooks/useCollectionFilters.ts
- src/nft/hooks/useFiltersExpanded.ts
- src/nft/hooks/useIsCollectionLoading.ts
- src/nft/hooks/useIsNftClaimAvailable.ts
- src/nft/hooks/useMarketplaceSelect.ts
- src/nft/hooks/useNFTList.ts
- src/nft/hooks/useNFTSelect.ts
- src/nft/hooks/usePriceRange.ts
- src/nft/hooks/useProfilePageState.ts
- src/nft/hooks/useSelectAsset.ts
- src/nft/hooks/useSellAsset.ts
- src/nft/hooks/useSendTransaction.ts
- src/nft/hooks/useSweep.ts
- src/nft/hooks/useTokenInput.ts
- src/nft/hooks/useTraitsOpen.ts
- src/nft/hooks/useTransactionResponse.ts
- src/nft/hooks/useWalletCollections.ts
the default import from `zustand` is deprecated, we should be using a named import instead. this fixes the console warnings and adds an eslint rule to prevent this from happening in the future.
https://uniswaplabs.atlassian.net/browse/WEB-1566?atlOrigin=eyJpIjoiMWUyZTM4NmExNDIwNGQ1MDkyZTVkZTVlYjFmNjcyOTkiLCJwIjoiaiJ9
> fix: remove deprecated default imports from zustand

- src/components/WalletDropdown/AuthenticatedHeader.tsx
- src/components/WalletDropdown/index.tsx
- change the "close" button's margin to match the drawer's
https://uniswaplabs.atlassian.net/browse/WEB-3117?atlOrigin=eyJpIjoiZjJiYTUxYmM4NTVkNGEyOGFlZTE1NTcwYjAyMDZlOWEiLCJwIjoiaiJ9
- change the drawer's padding values to match the design [here](https://www.figma.com/file/MOvvpkzygJdxCA3BY9mN1O/Mini-portfolio-v1?node-id=601-191098&t=9e3uPF7hb3KF5esR-0)
https://uniswaplabs.atlassian.net/browse/WEB-3095?atlOrigin=eyJpIjoiNWNkNzEwZGYxM2Q5NDYxY2E0M2YxNDljY2FmYTg0OGQiLCJwIjoiaiJ9
| Before           | After           |
| ---------------- |-----------------|
|  ![image](https://user-images.githubusercontent.com/66155195/228090122-43659ae9-53a3-46e8-8e88-4728447d3e6a.png) | <img width="468" alt="image" src="https://user-images.githubusercontent.com/66155195/228089921-394fcaa4-7090-4e4d-80fb-b351 …
> fix: mini portfolio layout fixes

- src/utils/prices.test.ts
- src/utils/prices.ts
- [jira ticket](https://uniswaplabs.atlassian.net/browse/WEB-3024?atlOrigin=eyJpIjoiMzcwZWE3MmI4MjU3NDVkYmFhZDY1NjgzOWJkMjIzZmIiLCJwIjoiaiJ9)
- [context for the bug report is here
](https://uniswapteam.slack.com/archives/C04D07TQBT4/p1678829853381139)
the Price Impact value we use to calculate this severity level is typically positive (above zero, not favorable). for a favorable trade the price impact is in the other direction, i.e. negative (less than zero).  note that we flip the sign when displaying the value.
- added unit test for `warningSeverity` function to verify the expected behavior
- manually tested a typical trade (in which the slippage is not favorable) to verify that the warning severity is still correct
> fix: dont block trade when price impact is favorable

- package.json
- src/components/Identicon/StatusIcon.test.tsx
- src/components/Identicon/StatusIcon.tsx
- src/components/Identicon/__snapshots__/StatusIcon.test.tsx.snap
Fixes a layout issue with the socks icon. This fix works because sibling order is taken into account with multiple absolutely-positioned items with the same z-index
https://uniswaplabs.atlassian.net/browse/WEB-3096?atlOrigin=eyJpIjoiN2NiZjZlMjdjYWZhNGY0Y2FjZTQ0MjFiOWQzOTJhNTMiLCJwIjoiaiJ9
| Before           | After           |
| ---------------- |-----------------|
|  ![image](https://user-images.githubusercontent.com/66155195/229616404-75edc585-e921-40b8-86bf-c9cdc5f8d141.png) | <img width="346" alt="Screenshot 2023-04-03 at 11 31 12 AM" src="https://user-images.githubusercontent.com/66155195/229616316-6ff3a44c-e146-4b23-a721-57eeb35b5192.png"> |
manually verified - see screenshots
> fix: z index issue with socks icon

- src/components/ErrorBoundary/index.tsx
removes the Amplitude event for "Swap Error" from the main page of the app. this was intended to be used to compare relative error counts between versions of the app with the widget and without. Since we're no longer using the widget on this page, we can remove this logging.
original PR: https://github.com/Uniswap/interface/pull/6008
> feat: remove amplitude swap error logging

- src/components/WalletDropdown/MiniPortfolio/Activity/ActivityTab.tsx
- src/components/WalletDropdown/MiniPortfolio/Activity/parseLocal.test.ts
- src/components/WalletDropdown/MiniPortfolio/Activity/parseLocal.ts
Updates useLocalActivity to only return activity for TX's that are related to a given account
https://uniswaplabs.atlassian.net/browse/WEB-3106
| Before (local tx's from diff account)           | After           |
| --------- |-----------------|
|  <img width="320" alt="image" src="https://user-images.githubusercontent.com/39385577/229193531-b88a46a4-f917-4071-9aff-5cd961faefdf.png"> | <img width="321" alt="image" src="https://user-images.githubusercontent.com/39385577/229193661-701c3c6d-5558-479f-9bd9-a8754b1eaf3c.png">  |
1. Make a transaction (i.e. swap) and view it on the acitivty tab
2. Switch to another account
3. Ensure the previous account's transaction is no longer populating the activity tab
Added a test in parseLocal.test.tsx that confirms the right number of transactions …
> fix: only use local txs for current account

- cypress.config.ts
Configures retries for Cypress CI, as documented in https://docs.cypress.io/guides/guides/test-retries.
This run actually had a flake, and can be observed retrying: https://cloud.cypress.io/projects/yp82ef/runs/9498/test-results/37de495e-3340-4443-b76d-0b3a0f89e67f.
_Jira ticket:_ https://uniswaplabs.atlassian.net/browse/INFRA-165
> test(e2e): configure cypress test retries for CI

- src/state/lists/updater.ts
- src/state/lists/utils.test.ts
- src/state/lists/utils.ts
use `console. debug` for this warning instead of `console.error`, so it doesn't appear in prod.
https://uniswaplabs.atlassian.net/browse/WEB-1566
manually tested by running the app and verifying that the optimism token list error wasn't shown unless i used the "verbose" console setting.
this error is currently firing in [prod](https://app.uniswap.org/) because the optimism token list needs to do a major version bump.
> fix: make token list version bump error quieter

- src/components/WalletDropdown/MiniPortfolio/NFTs.tsx
- src/graphql/data/nft/Asset.ts
- src/graphql/data/nft/NftBalance.ts
Reducing initial response size by reducing the requested amount of data for the assets query + making mini portfolio only load nft balance when opened
> chore: removing unnecessary data in assets query

- src/lib/hooks/useTokenList/fetchTokenList.test.ts
- src/lib/hooks/useTokenList/fetchTokenList.ts
this is one of the top web sentry errors that happens when the response from fetching a token list is not valid JSON. currently the parsing error is unhandled so it's being reported to sentry. This PR updates `fetchTokenList` so that the parsing error is caught, we log a debug message similar to other errors in the function, and then continue attempting more URLs for this token list.
note that we still log an error if all the token lists fail for any reason.
manually cleared the token list cache and verified that the normal fetching behavior is unchanged. also, I manually hard-coded invalid json into this function to verify that we do continue to other URLs in the case of a parsing error
> fix: catch json parse error in fetchTokenList

- src/components/Web3Status/index.tsx
- src/pages/Swap/index.tsx
Removes the `received_swap_quote` field from the `CONNECT_WALLET_BUTTON_CLICKED` event.
This field is one of two places in the app where the global Swap State is actually accessed "globally" or not in the swap component. Since we are trying to make the swap state local to the swap component, we wanted to remove this.
It's ok to remove this field because we already log an event for this information, `SWAP_QUOTE_RECEIVED`, and it's possible to link the two events by user/session id on amplitude. Further, accessing the swap state at this point (connecting wallet) doesn't even give the most accurate representation of whether the user *has* received a quote, because it's actually checking the user currently has a quote loaded for the swap inputs at that moment. …
> fix: remove "Received Swap Quote" field from Connect Wallet event

- src/components/WalletDropdown/AuthenticatedHeader.tsx
Seems like these buttons were switched around mini portfolio launch. We want them to be switched back so the not available in region message shows right beneath Buy crypto button. 
currently in prod: 
what we want in prod:
> fix: switch back buttons in mini portfolio 

- src/state/transactions/updater.tsx
This PR removes the `SWAP_TRANSACTION_COMPLETED` event from the Updater flow.
1. This flow was not implemented correctly - the event reads from the current Trade instead of the trade that has just completed. So if the swap state gets cleared or the user starts a new swap, the wrong values would be logged.
2. This flow also uses a dependency on global swap state, and we are trying to move to local swap state in preparation for componentization.
3. This event isn't used for any analytics rn, so safe to remove.
Slack thread here: https://uniswapteam.slack.com/archives/C03JAKVATU6/p1681140398058139
Do a swap and see that activity history is still updating correctly.
> chore: Remove SWAP_TRANSACTION_COMPLETED event

- src/tracing/errors.test.ts
- src/tracing/errors.ts
As part of a plan to reduce the number of Sentry errors, we are going through the most common issues and either fixing or catching errors.
This one is here: https://uniswap-labs.sentry.io/issues/4066659882/?project=4504255148851200&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=17
In this case, it's not caught by the error boundary (as seen because it says `handled: no`). We don't need to log this error because user rejections are considered valid, and are not actually an error in our product.
JIRA ticket: https://uniswaplabs.atlassian.net/browse/WEB-3187
I added a test here to show that user rejected error matching strings should get filtered out.
> fix: ignores "user rejected transaction" errors

- src/nft/utils/listNfts.ts
LR will no longer support orders to their v1 endpoint starting tomorrow 04/12. To upgrade to their v2 sdk will require updating our node version from 14 to 16 or getting LR to support 14, both solutions likely requiring more time than we have. In the interim this PR hides LR as a listing marketplace.
**Out of scope:**
Adding any logic to support listing to LR v2. All of that logic will be kept to its own PR(s). This PR is strictly to hide our current feature which will no longer work as of 04/12.
_Slack thread:_ [endpoint deprecation announcement](https://uniswapteam.slack.com/archives/C03RB5AEHDK/p1680808568805939)
With hidden LR marketplace
> feat: hide looksrare until we can support their sdk

- cypress/e2e/position.test.ts
Adds tests for the position pages, both invalid and valid pools. This sets us up for the next PR, which will make sure that unsupported chains also show the invalid state vs crashing.
The test works on Chrome only right now, since it's through Cypress.
> test: add test for position page states

- package.json
- src/components/AccountDrawer/DownloadButton.tsx
- src/components/AccountDrawer/SettingsMenu.tsx
- src/components/AccountDrawer/UniwalletModal.tsx
- src/components/Banner/UniswapWalletBanner.tsx
- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/NavBar/index.tsx
- src/featureFlags/flags/featureFlags.ts
- src/featureFlags/flags/mgtm.ts
- src/pages/App.tsx
- src/pages/Wallet/index.tsx
- yarn.lock
Replaces /wallet route w/ links to the external microsite
Removes the wallet_microsite feature flag
Adds specific analytics for microsite opens vs app store opens
* Enable the mgtm feature flag
* Open the uniswap wallet connector modal
* Click download while on desktop, expect microsite
* Click download while on iOS, expect app store
> feat: remove /wallet route

- src/components/ErrorBoundary/index.tsx
- src/components/Web3Provider/index.tsx
Adds `chain_id` as a tag in sentry logs from the ErrorBoundary. This means "handled" events will have the tag, and async events will not yet. Will add that support in a separate PR so that we can start instrumenting this sooner to debug some issues. This will allow us to filter by chain_id for events, and also see which chains are causing errors most often for different errors.
https://uniswapteam.slack.com/archives/C050USFTS5B/p1681254541015739
Manually create an error, and verify that it is sent to Sentry with a chainId as a tag.
> build: add chainId as tag in sentry ErrorBoundary

- src/nft/components/explore/Cells/Cells.tsx
- src/nft/components/explore/CollectionTable.tsx
We recently swapped out endpoint for trending collections from heroku to graphql. Floor prices previously given in wei are now given in eth. We checked for this in several locations but missed when a user toggles to see USD prices instead of eth and when a user sorts by floor price. This PR adds those checks.
As a not we generally remove the flag after a week of being live. This feature was launched Monday so sometime next week we will be removing the nftGraphQl flag and defaulting to the true case.
_JIRA ticket:_ https://uniswaplabs.atlassian.net/browse/NFT-1180?atlOrigin=eyJpIjoiMWI3NzAwYzI0NzhkNGY2NGI4ODQ2OTgxYzQxOWNhZDAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
_Slack thread:_ https://uniswapteam.slack.com/archives/C04BVC4J5HU/p1681327827268469
Testing all variations on table
1. …
> fix: App crashing when changing sorting or toggling usd price on trneding NFTs table

- src/tracing/errors.test.ts
- src/tracing/errors.ts
This is caused by HTML being returned for a chunk from Cloudflare. Usually, it's the result of a 499 exception right before it, which should be handled. Therefore, this can be ignored.
In the future, there will be a PR that handles the 499 exceptions via Cloudflare to ignore those exceptions in logging as well.
_JIRA ticket:_ https://uniswaplabs.atlassian.net/browse/INFRA-172
_Slack thread:_ https://uniswapteam.slack.com/archives/C050USFTS5B/p1681335647517689
This is not easily testable locally, so instead we can see if these errors are not showing up tomorrow in Setry.
> fix: ignore error caused by Cloudflare HTML response

- src/tracing/errors.ts
- src/tracing/index.ts
- src/tracing/trace.test.ts
Re-writes the URL sent to Sentry logs to not have a hash in it. We use HashRouter from react-router to support IPFS, but this leads to issues in Sentry where the hash is picked up as a fragment (see https://romain-clement.net/articles/sentry-url-fragments/#url-fragments).
Instead, we use the method shown in that post to remove the hash in the url.
app.uniswap.org -> app.uniswap.org
app.uniswap.org/# -> app.uniswap.org
app.uniswap.org/#/pools -> app.uniswap.org/pools
_Slack thread:_ https://uniswapteam.slack.com/archives/C050USFTS5B/p1681312677826209
> build: send url without hash to sentry

- .eslintignore
This pr https://github.com/Uniswap/interface/pull/6323 remove eslintignore which slowed down the local build significantly, and introduced a bunch of lint errors when running yarn start. This PR fixes that by adding it back
> fix: fix slow yarn start

- .github/actions/setup/action.yml
- .github/workflows/test.yml
- craco.config.cjs
- package.json
- tsconfig.json
- yarn.lock
Caches build steps - locally and in test.yml, our testing GH Action - to greatly reduce runtimes on repeated actions.
For most builds (eg for PRs with no changes to the lockfile), this halves the CI e2e run time.
1. Adds caching to the following build tools (all to the standard `node_modules/.cache/<build_tool_name>/` directory:
- eslint: configured in craco.config.js and the `yarn lint` script
- jest: configured in craco.config.js
- tsc (typescript): configured in tsconfig.json
2. Updates caching in the setup/action.yml and test.yml GitHub Action definitions:
- Explicitly omits node_modules/.cache from setup/action.yml caching, as no build steps have occured
- Adds node_modules/.cache to all jobs in test.yml, as each tool has its own cache
- Fixes cypress binary caching to reduce …
> build: utilize the node_modules/.cache

- src/tracing/errors.test.ts
- src/tracing/errors.ts
Filters out unsafe-eval errors caused by our content-security policy. This is what prevents unsafe javascript evaluation on our site which can be an attack vector. Since these are expected errors, we don't need to send them to Sentry.
> fix: filter CSP unsafe-eval errors

- .eslintrc.js
- craco.config.cjs
- Removes filename case sensitivity checks from the webpack pipeline.
These are already checked for by typescript, via `forceConsistentCasingInFileNames`
- Removes moment tree-shaking from the webpack piepline, as moment is unused.
Guards against future moment usage via eslint.
This does not have any noticeable improvement on CI tests.
_Relevant docs:_ https://www.notion.so/uniswaplabs/Optimizing-interface-build-performance-29adef9205ae44928bac0e04ed50e382?pvs=4
> build: remove unnecessary webpack plugins

- src/tracing/errors.test.ts
- src/tracing/errors.ts
This more generically checks for `unsafe-eval` errors that are related to content security policy. This is to make sure that this error is caught: https://uniswap-labs.sentry.io/issues/4008805391/?project=4504255148851200&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=24h&stream_index=13
> fix: filter out all `unsafe-eval` csp errors

- src/tracing/errors.test.ts
- src/tracing/errors.ts
This makes the regex matching more generic. This is because the text can say `error:`, but also things like `timeout:` or `missing:`. These should all be checked for 499s.
See: https://uniswap-labs.sentry.io/issues/4009148084/events/5e960da931d44c19bb54e977f8d651a4/?project=4504255148851200&query=is%3Aunresolved+release%3A95b9624bca2325ffc28bb513426120c9e4a1c8bb+%22timeout%3A%22&referrer=previous-event&sort=freq&statsPeriod=14d&stream_index=0
> fix: handle other types of chunk error codes

- src/state/routing/slice.ts
Removes non-serializable data from the redux payload when an error occurs. The error is serialized and stored in `.error`, so storing it in `.data` is redundant and only serves to generate noise / warnings in the console in testing _and_ in production.
_JIRA ticket:_ Partial fix for https://uniswaplabs.atlassian.net/browse/WEB-3132?search_id=f82d1daf-33c0-40da-8e38-097a920b30eb
N/A
> fix: rm non-serializable data

- src/tracing/errors.test.ts
- src/tracing/errors.ts
These are also a form of CSP errors, which prevent unsafe evaluation on the interface. https://uniswap-labs.sentry.io/issues/4009129049/?end=2023-04-25T15%3A57%3A59&project=4504255148851200&query=release%3A963121f19b0ea66590d648f83f940c9b9928f75b&referrer=issue-stream&sort=freq&start=2023-04-25T12%3A11%3A00&stream_index=16
We should eventually find a better way to catch all different strings for CSP errors, but for now we can just filter the ones that are showing up in sentry often enough to worry about.
> fix: filter WebAssembly compile errors

- package.json
Previous we'd get errors like this:
Instead, now we use `--only-mapped`:
> -m, --only-mapped: exclude "unmapped" bytes from the output. This will result in total counts less than the file size.
Some number of unmapped bytes is expected from modules that don't provide mappings or have code requires to build their module that don't have mappings.
> build: analyzes only mapped

- .github/workflows/notify-slack-on-release-merge.yml
This PR introduces a CI action that triggers on merge to any of the `releases/*` branches. When code is merged to any of the branches in question a message will be sent to Slack containing relevant information as to...
- Who merged the code?
- What was in the code?
- Was the merge a force push?
This in turn provides the UL engineering team with visibility into code changes for their CI pipeline.
This GH action definition was first committed to the PR with a `pull_request` target definition, meaning that it runs every time new code is committed to this PR.
I then confirmed that a test message was correctly sent to the expected Slack channel:
The PR was then updated to have the correct information in the Slack message (which cannot be fully tested as the contents of the GH action context …
> ci: Emit to slack on merge to releases/* branch

- src/components/NavBar/ChainSelector.tsx
- src/constants/chains.ts
_Slack thread:_ https://uniswapteam.slack.com/archives/C04D07TQBT4/p1682535435459049
| Before       | After (Desktop) |
| ------------ |---------------- |
| ![image](https://user-images.githubusercontent.com/5773490/234677262-d84f2c84-71b0-4789-8962-4c682a55938e.png) | <img width="466" alt="image" src="https://user-images.githubusercontent.com/5773490/234678357-135a6781-83fd-4f5e-8e96-b711a7e299d8.png">        |
connect to the app with the uniswap wallet and confirm both options are disabled
connect to the app with anything else and confirm all options are enabled
> fix: disable bnb network option on uniwallet

- cypress/support/e2e.ts
this simplifies our interceptors and enables fetching quotes from the routing api by adding a referer spoof
> fix: spoof origin and referer

- src/tracing/errors.test.ts
- src/tracing/errors.ts
Extends the match to handle this error: https://uniswap-labs.sentry.io/issues/4009216608/?project=4504255148851200&referrer=release-issue-stream
It says just OneKey instead of OneKey.app.
> fix: match OneKey more generically

- src/tracing/errors.test.ts
- src/tracing/errors.ts
https://uniswap-labs.sentry.io/issues/4009216613/events/df10a0f032eb4e80979d2947c46dbbce/?end=2023-05-01T16%3A10%3A59&project=4504255148851200&query=+browser.name%3AElectron&referrer=previous-event&sort=freq&start=2023-05-01T12%3A09%3A00&stream_index=1
This is an example of an error which is sourced from OneKey, but OneKey is not in the name or message. However, it is in the stack so we can filter by checking that instead.
> fix: filter errors with OneKey in stack

- src/hooks/useV3PositionFees.ts
https://uniswap-labs.sentry.io/issues/4086521318/?project=4504255148851200&query=call+revert+exception&referrer=issue-stream&sort=freq&statsPeriod=90d&stream_index=0
This error is happening when users go to the position page. We show the amount of uncollected fees they have in the UI before they actually send the collect transaction. However, that call isn't caught right now leading to errors being thrown.
This is noticed by seeing that this is a "dry-run" since it's a call revert, rather than a sendTransaction failure.
What's odd is that the call data is "0x", while it should have some hashed data. We don't know if this is an issue with the ethers logging, or due to an issue on our end. But it would be better to confirm that this fix is right before diving more into that.
With this, in …
> fix: add a catch on collect static call

- cypress/e2e/service-worker.test.ts
- src/serviceWorker/index.test.ts
- src/serviceWorker/index.ts
- src/serviceWorker/utils.test.ts
- src/serviceWorker/utils.ts
We are getting a significant number of errors where chunks are not being found:
https://uniswap-labs.sentry.io/issues/4009148084/?project=4504255148851200&referrer=release-issue-stream
https://uniswap-labs.sentry.io/issues/4131879787/?project=4504255148851200&referrer=release-issue-stream
We think this is caused by cache misses from the service worker. After some investigation, it seems like the logic for separating the pre-cached and on-demand cached content could be leading to the issue. Previously, we only pre-cached the document, but now we want to pre-cache all JS/CSS files, while all media assets can be on-demand cached.
The downside here is many files that may not be needed will get stored to disk, but this is a compromise we are willing to make for now. Over time we could make …
> fix: update service worker to precache css/js files

- src/utils/swapErrorToUserReadableMessage.tsx
The user-readable error formatting util was adding an unnecessary period.
before: 
https://uniswaplabs.atlassian.net/browse/WEB-3287
https://uniswapteam.slack.com/archives/C04D07TQBT4/p1683142590579389
> fix: errors are responsible for their own grammar

- src/theme/components/ThemeToggle.tsx
- src/utils/matchMedia.test.ts
- src/utils/matchMedia.ts
`addEventListener` is not defined on Safari versions below 14. This adds code to fallback to `addListener`.
https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener
https://uniswap-labs.sentry.io/issues/4044597264/?end=2023-04-25T15%3A57%3A59&project=4504255148851200&query=release%3A963121f19b0ea66590d648f83f940c9b9928f75b&referrer=issue-stream&sort=freq&start=2023-04-25T12%3A11%3A00&stream_index=19
Use Safari 13 (I haven't actually tried this) and try changing the dark mode preference on the system.
> fix: handle addEventListener being unsupported on Safari <14

- src/components/AccountDrawer/MiniPortfolio/Activity/parseLocal.test.ts
- src/components/AccountDrawer/MiniPortfolio/Activity/parseLocal.ts
- src/components/AccountDrawer/MiniPortfolio/Pools/cache.ts
- src/components/Popups/TransactionPopup.tsx
- src/hooks/Tokens.test.ts
- src/hooks/Tokens.ts
- src/lib/hooks/useTokenList/utils.ts
- src/state/lists/hooks.ts
Updates local tx parser to use useAllTokensMultichain, and updates useAllTokensMultichain to merge tokens from all lists w/ userAdded tokens.
This fixes an existing problem where Mini Portfolio and & the TX Notification toast would only render tokens from the default list.
[Slack thread](https://uniswapteam.slack.com/archives/C04QKTF9T35/p1683220935782969)
| Before       | After (Desktop) |
| ----------- |---------------- |
| <img width="393" alt="Screen Shot 2023-05-04 at 4 52 03 PM" src="https://user-images.githubusercontent.com/39385577/236327117-b6c87eb6-b019-4fa7-be1d-13723df91c4f.png"> | <img width="389" alt="image" src="https://user-images.githubusercontent.com/39385577/236327279-96cb4e97-47e9-416d-8cab-0e1abdc7801f.png">      |
1. Swap a token that is not included on the default …
> feat: update useAllTokensMultichain usage

- src/nft/components/profile/list/MarketplaceRow.tsx
- src/nft/components/profile/list/RoyaltyTooltip.tsx
- src/nft/components/profile/list/utils.ts
- src/nft/utils/listNfts.ts
- Update OS listing fee to be a flat 2.5% for all collections as opposed to 0.5% for collections with no royalties or 0% for collections with royalties as mentioned in their OS Pro announcement
- Use the fee from the ListingMarket object when creating OS's consideration items
_JIRA ticket:_ https://uniswaplabs.atlassian.net/browse/NFT-1193
_Slack thread:_ https://uniswapteam.slack.com/archives/C03MGBD2SNN/p1683553053120529
_Relevant docs:_ https://support.opensea.io/hc/en-us/articles/14068991090067
Updated fees
Successfully listing a 721 and an 1155
> fix: update OS listing fee

- cypress/support/e2e.ts
- package.json
- yarn.lock
Fixes flakiness in tests caused by slow loading of token lists over IPFS, by serving the default token list through an HTTP interceptor in cypress E2E tests.
> test(e2e): mock uniswap token lists from ipfs

- src/tracing/errors.test.ts
- src/tracing/errors.ts
It is possible for an AbortError to be sent to Sentry even if it's caused by the user navigating away from the page, because Sentry captures errors and exceptions occurring in your application, including those caused by user actions.
In the case of an AbortError, it typically occurs when a fetch request is aborted, often due to the user navigating away from the page or closing the browser tab. When this happens, the browser cancels the ongoing fetch request, and the JavaScript Promise associated with the request rejects with an AbortError.
> fix: filter AbortError from Sentry

- src/tracing/errors.test.ts
- src/tracing/errors.ts
According to MDN:
```
Note: When abort() is called, the fetch() promise rejects with an Error of type DOMException, with name AbortError.
```
https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort
Therefore, my previous filtering was failing because I checked for AbortError: to be the start of the error message. Really, that only happens when toString is called later on.
> fix: properly filter AbortErrors

- cypress.config.ts
Reverts a flakey e2e test so that we unblock deploys. I cherry-picked this from https://github.com/Uniswap/interface/pull/6524
> revert(e2e): waitForAnimations

- src/constants/lists.ts
Temporarily disables the CMC list. It previously was not working for a long time, until this PR fixed the URL to resolve CORS errors: https://github.com/Uniswap/interface/pull/6406
However, this leads to [QuotaExceededErrors](https://uniswap-labs.sentry.io/issues/4169030652/?project=4504255148851200&referrer=release-issue-stream). These are caused when the total size of localStorage is beyond ~5mb, depending on browser.
We will need a better long term solution, as this will continue to happen as token lists will increase in size. We also do want to be able to search the tokens that exist on CMC.
However, for now we should get back to a state where the localStorage updates can work. At the moment, any change to localStorage on our origin will fail, leading to issues like the selected …
> fix: disables CMC list temporarily

- src/nft/utils/buildSellObject.ts
** Backend removed the check for tokenType for routing and some endpoints don't pass the tokenType from nxyz so we have to remove the check on the frontend
> chore: removing token type check from routing

- src/tracing/errors.test.ts
- src/tracing/errors.ts
This reverts this PR: https://github.com/Uniswap/interface/pull/6330
I've changed my mind here, and think with the added context in Sentry these errors are worth monitoring again. We should know where we're not catching these errors, and address them.
> fix: propagates user rejection errors

- .github/workflows/1-main-to-staging.yml
- .github/workflows/2-deploy-to-staging.yml
- .github/workflows/3-staging-to-prod.yml
- .github/workflows/4-deploy-to-prod.yml
This PR contains the following fixes for the prod CI pipeline:
- Add `CODEOWNERS` into staging (this enables us to require `CODEOWNERS` correctly for staging -> prod)
- Remove automerge configuration for prod PR
- Force push from `releases/staging` -> `releases/prod` rather than cut a PR
> ci: CI pipeline fixes for merge issues

- src/pages/Swap/index.tsx
This should resolve these errors: https://uniswap-labs.sentry.io/issues/4174993328/?project=4504255148851200&query=release%3A59b757dda03c2772c73b710fe4690208a5c7b001&referrer=issue-stream&sort=freq&statsPeriod=7d&stream_index=19
I found the solution here: https://github.com/remix-run/react-router/issues/8834#issuecomment-1118083034
The claim is that a top-level fragment will have issues when the DOM node is attempted to be removed. In this case, the Fragment isn't even necessary.
I haven't actually been able to reproduce this locally.
I tested making sure the Swap page loads and works when I navigate away.
I don't think any new tests are necessary here beyond making sure existing tests pass.
> fix: remove top-level Fragment

- src/state/routing/slice.ts
This PR fixes the case where a user preference setting is on AUTO but it was falling back to client-side routing
Verified through network tab
> fix: catch RouterPreference.AUTO case for routing-api usage

- cypress/e2e/permit2.test.ts
since e2e tests are slower on GH actions, we want a looser check for the permit2 expiration here.
_Slack thread:_ https://uniswapteam.slack.com/archives/C055M7VAUGY/p1683911992673969
> fix: loosen permit2 expiration tolerance in e2e tests

- src/setupTests.ts
Instead of polyfilling manually in two places, this makes sure all polyfills in `polyfills.ts` are used in `setupTests.ts`.
> refactor: imports shared polyfills in setupTests

- src/tracing/errors.ts
Small refactor to return a boolean of whether to reject an error, instead of returning null in the helper function when we want to drop.
Now there is a comment explaining why we use null to drop events in a single location.
> refactor: filterKnownErrors -> shouldRejectError

- src/components/swap/AdvancedSwapDetails.test.tsx
- src/components/swap/AdvancedSwapDetails.tsx
Fixes: #6563 
Simple fix, just checking the trade.type same conditions as the value on line 84
| Before  |  After  |
|:-------:|:------:|
| <img width="400" alt="Screenshot" src="https://github.com/Uniswap/interface/assets/89173284/d493a3b6-2b57-4280-a69d-0f1a5a42a670"> | <img width="400" alt="Screenshot" src="https://github.com/Uniswap/interface/assets/89173284/dcded6c3-1847-4f5f-9a1a-8f6795f30b71"> |
1. Go to app.uniswap.org
2. Make a trade with an exact output
3. "Minimum output" row is showing the maximum input value
> fix: "Minimum output" should be "Maximum output" when trade is Exact Output

- src/tracing/errors.test.ts
- src/tracing/errors.ts
Switches all tests to be based on `beforeSend` instead of `filterKnownErrors`. This is so we don't test an internal function that was exported only for testing.
> test: move all tests to beforeSend

- src/tracing/errors.test.ts
- src/tracing/errors.ts
Removes this behavior in Sentry, since these should be grouped together. Also adds more tests.
> fix: remove trailing slash from request url

- src/pages/Swap/index.tsx
https://uniswap-labs.sentry.io/issues/3788318733/events/6d4f1062f25a40db900229797c48e1fe/?project=4504255148851200&referrer=next-event
`message: User rejected the request.` means the user rejected in their wallet when we prompt to switch chains. This is an example where that rejection is not caught.
Right now this ignores user rejected errors (meaning the user stays on the same chain) and continues to throw for other errors. This adds a note to a JIRA ticket to improve the failure case UX.
1. Connect to mainnet
2. Go to an arbitrum token details page
3. Click "connect to ethereum"
4. Cancel the request in wallet
5. See the error in console
I didn't add these because we can't switch chain via tests easily yet.
> fix: handle switchChain failure in swap

- src/components/AccountDrawer/MiniPortfolio/Activity/index.tsx
Updates nonce deduplication logic to not hide all transactions that are present on both backend and frontend cache. These transactions were previously hidden by recent changes meant to handle cancelled tx's.
| Before       | After (Desktop) | 
| ------------ |---------------- | 
| <img width="336" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/e8809293-21b7-4545-966f-4aa5ee8ef29a"> | <img width="392" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/de7a9ac4-6d0a-4c38-98d1-cc9901fe392d"> | 
1. Make a swap on mainnet, wait for it to confirm, and view the tx in your mini portfolio
2. Refresh the page (to fetch remote tx's) and the tx should no longer be in your mini portfolio
> fix: update nonce deduplication logic

- src/nft/components/details/detailsV2/DataPage.test.tsx
- src/nft/components/details/detailsV2/DataPage.tsx
- src/nft/components/details/detailsV2/DataPageHeader.tsx
- src/nft/components/details/detailsV2/LandingPage.test.tsx
- src/nft/components/details/detailsV2/LandingPage.tsx
- src/nft/components/details/detailsV2/NftDetails.tsx
- src/nft/components/details/detailsV2/__snapshots__/DataPage.test.tsx.snap
- src/nft/components/details/detailsV2/__snapshots__/DataPageHeader.test.tsx.snap
- Adds an InteractionObserver to check whether the NFT has been scrolled out of view
- Combined logic from these two examples: https://mtm.dev/sticky-stuck-styles & https://codepen.io/hey-nick/pen/mLpmMV
- Using the observer show/hide the data page header
- Data page header is sticky with a backdrop blur effect
> feat: [DetailsV2] Show data page header when nft scrolled out of view

- src/graphql/data/nft/Details.ts
- On the NFT Details page v2 we intended on showing multiple listings on the page. This was tested with several assets however an edge case we found was that our BE does not include pooled assets when fetching more than 1 listing. This caused a bug where if a user views a 721 asset listed on an AMM such as [this one](https://app.uniswap.org/#/nfts/asset/0xbd3531da5cf5857e7cfaa92426877b022e612cf8/243) on the collection page it will be purchaseable however on its Detail page it will be viewed as not for sale.
- BE will not be able to support this until after the migration so we will be reverting to only fetching 1 listing until then
_JIRA ticket:_ https://linear.app/uniswap/issue/NFT-1132/revert-to-requesting-1-listing-in-details-page …
> fix: only request 1 listing on NFTDetails page

- src/components/swap/AdvancedSwapDetails.tsx
- src/components/swap/PriceImpactWarning.tsx
- src/components/swap/__snapshots__/AdvancedSwapDetails.test.tsx.snap
- src/components/swap/__snapshots__/SwapDetailsDropdown.test.tsx.snap
- src/utils/formatPriceImpact.test.ts
- src/utils/formatPriceImpact.ts
It was accidentally removed from previous PR due to various designs in our Figma. Fixes WEB-2034
> fix: add price impact back

- .github/workflows/test.yml
- cypress/e2e/landing.test.ts
- cypress/e2e/swap/swap.test.ts
- cypress/e2e/wallet-dropdown.test.ts
- package.json
- yarn.lock
Adds `cypress/flake` as a first-class check in GitHub PRs. Once existing flakes are fixed, we can use it to block add'l flakes from merging in.
Configures Cypress to post a comment to PRs with test results and two additional checks: a group check (`cypress:e2e`), and a flakes check (`cypress/flake`). These checks can be used in branch protections to gate merging to `main`, and `cypress:e2e` can replace the more complex `cypress-tests` check currently in use. Also configures Cypress so that structured data (author, PR) are available in the cloud dashboard.
Upgrades Cypress to v12.12.0, which is necessary for the Cypress cloud dashboard to link back to the PR. `CYPRESS_PULL_REQUEST_*` env vars are not available until v12. This makes tests isolated, so each test must now begin with …
> test(e2e): configure Cypress to post PR status comments

- src/state/routing/slice.ts
We were previously using client-side-only routing for price fetching, and switched to API, and the increase in pricing requests for illiquid tokens spiked our 4xx errors, so revert back to client-side routing for now
> fix: Use client side router only for price fetching

- .github/workflows/test.yml
Runs test workflow from a protected environment if on `main`.
_Linear ticket:_ https://linear.app/uniswap/issue/INFRA-12/isolate-the-slack-webhook-url-to-an-environment
The logic (`${{ github.ref_name == 'main' && 'notify/test' }}`) was tested by modifying it to read `${{ github.ref_name == '6597/merge' && 'notify/test' }}` and observing the correct environment selection: https://github.com/Uniswap/interface/actions/runs/5019599122.
> build: notify from notify/test

- src/tracing/errors.test.ts
- src/tracing/errors.ts
For some reason, this tag wasn't sending properly to Sentry. But now that we're pretty sure the issue is related to network errors, this context is not necessary.
I'll wait to merge after seeing that this PR solves the chunk loading issues: https://github.com/Uniswap/interface/pull/6512
> chore: remove chunkResponseStatus tag

- src/constants/tokens.ts
- src/graphql/data/SearchTokens.ts
Special cases the ARB token on Arbitrum to always display over the ARB token on Mainnet in search results when both are returned by the backend, regardless of the user's current chain.
Also cleans up / renames the cross token search code to make functionality more clear.
_[Linear ticket](https://linear.app/uniswap/issue/WEB-1949/special-case-dollararb-in-search-so-the-arbitrum-network-one-shows-up)_
| Before       | After (Desktop) |
| ------------ |---------------- |
| <img width="261" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/d0b2044a-2939-4a61-9203-e38f9f31fad6"> |  <img width="301" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/be0fdbaa-8f34-46a1-a412-8ab32c478d3d">      |
> feat: special case arb search

- .github/actions/setup/action.yml
- lingui.config.ts
Removes the buggy caching layer for i18n:extract, to allow translation messages to be correctly extracted.
_Slack thread:_ https://uniswapteam.slack.com/archives/C02T729PMQE/p1684776627955079?thread_ts=1684775215.278659&cid=C02T729PMQE
1. Run the caching extractor locally, verify that it incorrectly strips message headers
2. Run the new non-caching extractor, verify that message headers are still there
> fix: do not attempt to cache i18n:extract

- src/pages/Swap/index.tsx
This bug happens when the `ConfirmSwapModal` is dismissed before  the `swapCallback`  promise resolves.
When the bug happens, the state is set like this:
1. user proceeds normally and opens the `ConfirmSwapModal` -> `showConfirm` is true (set on L783)
2. `handleSwap` is called and triggers the `swapCallback` (L426). `showConfirm` is still true at this point
3. `handleConfirmDismiss` is called and `showConfirm` is set to `false`
4. `swapCallback` resolves and sets `showConfirm` to an outdated value (L428) which re-opens the modal
1. see the [test results](https://github.com/Uniswap/interface/pull/6541) for the `swap/errors.test.ts` test suite - it's flaky because this race condition causes the modal to stay visible when it shouldn't
> fix: prevent race condition for swap state

- src/lib/utils/analytics.ts
- src/pages/Swap/index.tsx
The previous version of the hook was infinite looping when `trade` is always defined, so simplify logic to just keep track of `trade` changes. Also removes the time-based logging since we have stats on the backend now
No UI changes
Throw in a console.log right before `sendAnalyticsEvent` and see it firing like 1 million times lol
> fix: Simplify event logging for SWAP_QUOTE_RECEIVED

- src/nft/hooks/usePermit2Approval.ts
this logic was removed in #6127 which caused the bag not to fail properly when switching to an unsupported chain
> fix: allow unsupported chain in pwat

- .github/workflows/test.yml
Uses the repo secret for the slack test reporter webhook, instead of using an environment.
This is necessary to avoid "temporarily deployed to false" commit comments on the PR, as described in https://github.com/orgs/community/discussions/36919#discussioncomment-4110859, which are caused by using an environment for a workflow.
> build: use repository slack secret

- src/components/CurrencyInputPanel/FiatValue.tsx
- src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
- src/components/CurrencyInputPanel/index.tsx
- src/hooks/useUSDPrice.ts
- src/pages/Swap/index.tsx
As per the PR title and following screenshots, show the tooltip and `-` instead of empty space when we can't fetch a USD quote.
Unfortunately, due to the fact that we're using hooks quite extensively and that `useUSDPrice` always returns an object, it required an additional boolean in order to differentiate between `undefined` (indicating no USD price due to the user not providing all the information yet - in this case, we don't show `-`) and `data` being undefined (indicating no USD price due to insufficient liquidity - show `-`).
I have also refactored the component while on it, to remove deprecated UI components (such as `DeprecatedBody`) and replaced whitespace with Figma-defined `sm` spacing.
| Before       | After (Desktop) |
| ------------ |---------------- |
| …
> feat: show affordance in swap UI when we can't fetch usd quote

- .github/actions/setup/action.yml
- lingui.config.ts
Implements a caching i18n extractor to speed up lingui extraction. This saves minutes from build times, so it's a non-trivial change.
This builds on the old (broken) extractor: https://github.com/Uniswap/interface/blob/f3a80c62722b09ea82d4747b0ef93774fbfc9f05/lingui.config.ts#L13.
The old extractor was broken in that it assumed lingui extracted using the existing catalog as a basis, and only added to it. In fact, lingui extracts from every file every time, and fully reconstructs the catalog.
This new extractor works by man-in-the-middling lingui extraction. Lingui passes extractors a temporary `localeDir` to extract to. The extractor is expected to populate a new file, `${localeDir}/_build/${filename}.json`, with the extracted JSON. The caching extractor adds a few steps:
- Before …
> build: caching i18n extractor

- src/pages/App.tsx
Includes ServiceWorker metric with Web Vital analytics, so that pageload timing distributions can be segmented by service worker cache hit/miss.
> fix: include sw metric with web vitals

- .vscode/settings.json
Very simple just sets the formatter as my settings were overriding by default.
1.
> build: add vscode settings for default formatter

- src/hooks/useUSDPrice.ts
Reduces the ETH amount used to fetch the USD value of a token. This used to be 100 ETH, but that's a very aggressive quote which can lead to extra calls on the routing-api side to find the best route.
Instead, 50ETH is closer to the 100k USD amount we use on the `useStablecoinPrice` hook as well. We may eventually want a more dynamic way of setting this value.
> fix: reduce ETH amount on mainnet useUSDPrice request to 50

- src/components/NavBar/SearchBar.css.ts
- src/components/NavBar/SearchBar.tsx
- src/components/NavBar/SearchBarDropdown.tsx
- src/components/NavBar/index.tsx
- src/nft/css/sprinkles.css.ts
- src/theme/index.tsx
Adds scrolling support to search box.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2099/scale-global-search-with-screen-height
https://github.com/Uniswap/interface/assets/12100/b1e33e61-1e50-45cf-a59c-0bfdc7b080b6
> fix: prevent searchbar from overflowing the bottom of the window viewport (WEB-2099)

- cypress/e2e/permit2.test.ts
- src/pages/Swap/index.tsx
Fixes the swap flow for users who are still in expert mode  and need permit2 approvals for a token
added e2e test for full permit2 flow with expert mode enabled. 
failing test without the change:
passing test with change in the CI of this PR
PR already exists: https://github.com/Uniswap/interface/pull/6673?no-redirect=1
> fix: use ConfirmSwapModal in expert mode

- src/state/routing/useRoutingAPITrade.ts
This fixes a bug with the URA feature flagging logic where turning it on/off without reloading the page will cause stale trade results to show on the page (because both v2 trades and legacy trades can be cached in rtk-query). Note this is only a problem in dev/staging mode because regular feature flagging logic only resets on page loads, so only one of the trades can be defined at a time.
> fix: Bug with flipping ura feature flag on/off in dev mode

- src/constants/chainInfo.ts
Fixes the Polygon token bridge link on the Swap page when connected to the Polygon Network. Originally, the link took users to an Error 404 page before redirecting them to the proper bridging page.
Now the link takes users directly to the proper bridging page without navigating to the Error 404 page. This was done by changing the `bridge` link in `chainInfo.ts` from "https://wallet.polygon.technology/login" to "https://wallet.polygon.technology"
_Linear ticket:_ WEB-2101
1. Go to the Swap page and change network to Polygon
2. Click the "Polygon Token Bridge" banner
> fix: polygon bridge link leading to error page

- src/components/AccountDrawer/MiniPortfolio/PortfolioLogo.test.tsx
- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/SearchModal/CommonBases.tsx
- src/constants/routing.ts
- src/constants/tokens.ts
- src/featureFlags/flags/nativeUsdcArbitrum.ts
- src/featureFlags/index.tsx
- src/hooks/useStablecoinPrice.ts
This PR adds native USDC on arbitrum behind a feature flag that should be flipped on June 8th, the launch date.
Note: We should remove the legacy logic once native USDC is fully launched :D 
Enabled state:
Note we don't have the token logo yet because it's not available as part of any token lists. But as soon as any of our token list providers (including our own) adds, it will be available :D
> feat: Add Circle native Arbitrum USDC to common base tokens in token selector

- src/components/NavBar/ChainSelectorRow.tsx
Fixes the wallet connect loading state on network switch for Trust Wallet.
Prior to changes, all wallets (not just Trust Wallet) had an issue where the  `CheckMarkIcon` and `Loader` would appear at the same time. However, due to what I assume is a faster response rate?? within the other wallets, the ChainSelector menu would close almost immediately causing the issue to not be seen. However, with Trust Wallet, which has a slower response rate?? this issue is exacerbated making the issue more apparent.
Added an additional condition to display the `Loader` so that once we are on the current chain, it only displays the `CheckMarkIcon` while it waits for the ChainSelector to recognize the change the close the menu automatically.
_Linear ticket:_ WEB-2011 …
> fix: Trust wallet loading state

- src/components/swap/SwapDetailsDropdown.test.tsx
Tests depend on network requests, which may cause flakiness. These tests should have the network requests mocked, then be re-enabled.
> test: skip SwapDetailsDropdown tests

- src/constants/tokens.ts
- src/state/routing/types.ts
- src/state/routing/utils.ts
Fixes: #6704 
Currently Uniswap interface assumes that all chains except for Polygon have `ETH` as their native currency symbol:
https://github.com/Uniswap/interface/blob/20a06c9b5ac11bdd6078f14850ab3321a630aae9/src/state/routing/types.ts#L147-L152
https://github.com/Uniswap/interface/blob/20a06c9b5ac11bdd6078f14850ab3321a630aae9/src/state/routing/utils.ts#L181-L187
--- 
While this assumption was correct prior to BNB Chain support introduction, now we got one more native currency symbol, which is `BNB`. [It is included](https://github.com/Uniswap/smart-order-router/blob/dadd4961103d7924b869216a9bc4b4967832b7ff/src/util/chains.ts#L148-L234) in the list of native currencies in `smart-order-router`, so `routing-api` supports native `BNB` trades already.
> fix: swaps with native currency destination in BNB Chain 

- src/components/NetworkAlert/NetworkAlert.tsx
Fixes the pointer bug when selecting the token bridge banner on the Swap page. Before the banner would not be selected if the pointer came from the left side. Now the banner is selected from all locations on the banner.
Accomplished by adding some CSS styling to the `LinkOutToBridge` tag in the `NetworkAlert` component. First set `z-index` to 1 due to some weird overlap between the `LinkOutToBridge` tag and the `ContentWrapper` tag. Also removed the `margin-right` as it was causing the link to not cover the entirety of the banner's area. 
_Linear ticket:_ Web-2102
https://github.com/Uniswap/interface/assets/35351983/24d40a41-be51-4c84-bb32-9911afeca78b
https://github.com/Uniswap/interface/assets/35351983/eb7242d3-3f17-4d19-bb26-3b74bba42743
1. Go to the Swap page and change network to …
> fix: token bridge pointer bug

- cypress/e2e/wallet-connection/connect.test.ts
Skips a test that - due to a merge mishap - is failing due to testing an outdated feature.
> test(e2e): skip outdated disconnect-wallet test

- cypress/support/commands.ts
- cypress/tsconfig.json
fixes a type error in `cypress/support/commands.ts` causing the FeatureFlags to fail
> fix: type error in cypress infra

- src/components/Tokens/TokenDetails/PriceChart.tsx
* fixed interval overlapped caused by `interval.every(5)` being undefined initially so it was rendering 30 intervals (1 for every other second) which caused an overlap
* also there seems to be a cache issue which is causing a day to be sent automatically and thats whats initially being brought in for the hour
* update confirmed to be a bug on the BE side however this change is still better incase `interval` is undefined
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-1842/[web][tokens]-there-is-an-overlap-when-user-select-1h
> fix: time interval axis overlap

- src/connection/WalletConnectV2.ts
@JackShort found a bug caused by the duplicate inclusion of mainnet in `chains` and `optionalChains`
> fix: remove mainnet from optional chains list

- src/components/NavBar/SearchBar.tsx
* Language in search bar was not changing when accessing uni from url with lang param
* this was caused by double translating the strings it seems like, it was being translated in a function then translated again in the trans tag
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2214/language-does-not-update-in-search-bar
https://github.com/Uniswap/interface/assets/9094792/2a59f482-e96f-4547-8f4e-be3d05aeec33
https://github.com/Uniswap/interface/assets/9094792/4fe23259-5135-4077-9065-3e7ce1647fac
> fix: language updating in search bar

- src/graphql/data/nft/Details.test.ts
- src/graphql/data/nft/Details.ts
- We previously didn't handle scientific notation from the NFT Details page graphql query. This would cause the page to crash. 
- This PR uses the helper function `wrapScientificNotation` created for the other queries such as in `src/graphql/data/nft/Asset.ts`
- Adds test case
- We're going to discuss long term solutions with the backend at a later date. [See Slack thread](https://uniswapteam.slack.com/archives/C047U65H422/p1686062794714599).
1. Go to this page on [prod](https://app.uniswap.org/#/nfts/asset/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/77326181508430453689739176957591610751915480417413688521678058865045294703857) or [staging](https://app.corn-staging.com/#/nfts/asset/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/7732618150843045368973917695759161075191548041741368852167805886504 …
> fix: Handle scientific notation for NFT Details pricing

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/priceRoutingApi.ts
- src/featureFlags/index.tsx
- src/lib/hooks/routing/useRoutingAPIArguments.ts
- src/state/routing/slice.ts
- src/state/routing/utils.ts
- src/state/routing/v2Slice.ts
This PR adds a feature flag for moving price fetches to the routing-api. Currently all price fetches go through the client side router~
Note that price fetches = token -> ETH route. We always use gql to get ETH -> USD.
No UI changes
In local, toggle the feature flag `routing_api_price` on/off (also maybe in combination with `ura_enabled`) to see that the price quotes are going through the routing api instead of client side router.
> feat: Use routing-api or URA for price fetches behind feature flag

- src/state/routing/v2Slice.ts
routing-api v2 has a new error format where the `error.detail` is `No quotes available`, so catch this case for displaying insufficient liquidity.
> fix: Catch routing-api v2 no liquidity error case

- src/test-utils/nft/fixtures.ts
- We added some snapshot tests for the new NFT Details screens and used mock listings and offers. However the mock expirations were static so the tests started to fail as a month passed. This fix makes it so that the deadlines are dynamic based on current date.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2253/fix-flakey-snapshot-test
1. Run `yarn test` on main and several DataPage tests should fail
2. `yarn test` succeeds on this branch
> fix: [DetailsV2] flaky time relevant test

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/SearchModal/CommonBases.tsx
- src/constants/routing.ts
- src/featureFlags/flags/nativeUsdcArbitrum.ts
This PR just cleans up the feature flag logic for turning on native USDC in arbitrum's token selector as a common base.
Note we still use Bridged USDC for stablecoin price lookup (in the case that ETH price lookup fails) because it has a lot more TVL compared to native USDC, so the price lookup is more accurate on Bridged USDC for now.
> chore: Feature flag cleanup for Arbitrum native USDC

- src/components/AccountDetails/TransactionSummary.tsx
- src/components/AccountDrawer/MiniPortfolio/Activity/parseLocal.test.ts
- src/components/AccountDrawer/MiniPortfolio/Activity/parseLocal.ts
- src/components/AccountDrawer/MiniPortfolio/constants.ts
- src/hooks/useApproveCallback.ts
- src/hooks/useTokenAllowance.ts
- src/lib/hooks/useApproval.ts
- src/state/transactions/reducer.test.ts
- src/state/transactions/types.ts
Track the amount of the approval transaction, so that we can recognize revokes when the amount is zero.
https://github.com/Uniswap/interface/assets/66155195/83a3b381-4162-4076-a76d-8eb706266af0
> feat: add amount to local copy of Approval transactions

- src/components/Tokens/TokenDetails/PriceChart.tsx
Fixes ticks on x-axis for mobile devices so that the labels are responsive and reformat based on the size of the width. 
Added a function in `PriceChart.tsx` that splices the `ticks` array based on the current width of the screen/graph.
_Linear ticket:_ WEB-859
https://github.com/Uniswap/interface/assets/35351983/5d1d4377-3955-41e5-af13-0273ab0729b3
https://github.com/Uniswap/interface/assets/35351983/22c38f48-d5ad-475d-83c9-578919ab6edc
> fix: tick labels respond to width of the graph

- src/pages/Swap/index.tsx
reverts https://github.com/Uniswap/interface/pull/6698/files
this logging is too noisy and causing false positive alerts in sentry + pagerduty. we want this mostly for analytics, so it will be better to use amplitude instead
> fix: remove sentry logging for swap failures

- src/graphql/thegraph/apollo.ts
Uses the latest subgraph for arbitrum data. This doesn't resolve the CX linked within that ticket, but it will make sure we use a more recently updated graph.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2031/switch-out-arbitrum-subgraph-for-updated-one
As long as existing tests pass, I think that's good.
> fix: update arbitrum subgraph

- src/state/user/reducer.ts
- resolves the bug found in prod where the app crashed for users previously connected via Uniswap because they had `UNIWALLET` as the selectedWallet in localStorage and it was updated to `UNISWAP_WALLET`. This resolves by autocasting to to the latter. Verified locally and by using vercel deploys.
> fix: handle both UNIWALLET and UNISWAP_WALLET in LocalStorage

- src/connection/types.ts
- src/state/user/reducer.ts
adds deprecated value back to enum and remove ts-ignore
> refactor: add deprecated value back to enum

- src/components/AccountDrawer/MiniPortfolio/index.tsx
- src/state/transactions/hooks.tsx
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2010/ui-disconnect-between-activity-history-loading-and-interaction
| paste_before | <img width="410" alt="image" src="https://github.com/Uniswap/interface/assets/5773490/4756afc4-cbb2-42c4-ae44-6347cf7b5106">  |
|  mobile | <img width="405" alt="image" src="https://github.com/Uniswap/interface/assets/5773490/93604340-93e3-4680-bc86-b481626c3069"> |
> feat: add loading indicator to activity tab in mini portfolio

- src/components/swap/PendingModalContent/ErrorModalContent.tsx
fixes an incorrect padding on the swap error modal
1. induce an error during the swap flow (e.g. by using WCv2.0 with a wallet that doesn't support signatures yet)
> fix: bottom padding on error modal

- src/tracing/errors.test.ts
- src/tracing/errors.ts
Filters errors like https://uniswap-labs.sentry.io/issues/4187963215/?project=4504255148851200&referrer=slack which caused an alert/page.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2339/improve-sentry-filtering-to-catch-mozilla-extensions
> feat: filter moz-extension errors

- src/hooks/useAutoSlippageTolerance.ts
We were seeing increased rate of swap failures after changing slippage guides - bump min default to 0.50% to see if this helps!
See discussion [here](https://uniswapteam.slack.com/archives/C04JQHU6W5C/p1686171916083419)
> feat: Bump default auto-slippage to 0.5%

- src/components/swap/ConfirmSwapModal.tsx
- src/components/swap/PendingModalContent/index.tsx
- src/hooks/useTokenAllowance.ts
adds a new, optional, first step to the ConfirmSwapModal flow which resets USDT (mainnet) approval to zero before asking for a new, increased, approval amount. this is only needed for USDT mainnet.
from the USDT mainnet token contract:
```
/**
* @dev Approve the passed address to spend the specified amount of tokens on behalf of msg.sender.
* @param _spender The address which will spend the funds.
* @param _value The amount of tokens to be spent.
*/
function approve(address _spender, uint _value) public onlyPayloadSize(2 * 32) {
// To change the approve amount you first have to reduce the addresses`
//  allowance to zero by calling `approve(_spender, 0)` if it is not
//  already 0 to mitigate the race condition described here:
// …
```
> feat: revoke USDT approvals in ConfirmSwapModal

- .github/workflows/1-main-to-staging.yml
- .github/workflows/crowdin-sync.yaml
- .github/workflows/crowdin.yaml
Downloads translations as part of the release process, by downloading and committing them when promoting from `main` to `releases/staging`.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2279/generate-translations-as-part-of-release-pipeline
_Relevant docs:_ https://www.notion.so/uniswaplabs/Include-web-translations-in-the-release-pipeline-baa996cba77c49db95c88306f0cb64c1?pvs=4
https://github.com/Uniswap/interface/actions/runs/5292544115/jobs/9579548363 shows a test run where changes are downloaded but not committed. Building off of that, this should download and commit them using the service account.
This should be tested in a cut to staging, and can be reverted if it does not behave as expected.
> build: download translations when pushing to staging

- .github/workflows/1-main-to-staging.yml
Removes src/locales/en-US.po before adding src/locales/*.po, so that git will not fatally error on adding a .gitignore'd file.
See recent failure: https://github.com/Uniswap/interface/actions/runs/5292757297/jobs/9580029550
> build: rm ignored en-US

- src/pages/Swap/index.tsx
logs swap failures to amplitude for trend tracking.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2307/log-swap-failures-to-amplitude
1. enabled debug mode locally and verified the `tradeToConfirm` is properly included in the
> feat: log swap failures to amplitude

- src/hooks/usePermitAllowance.ts
- src/utils/errors.ts
We are currently debugging a permit-related bug in walletconnect v2 and this catch block is logging `[object Object]` instead of the `error.message` value.
_Linear:_ https://linear.app/uniswap/issue/WEB-2368/improve-permit2-error-logging
> fix: log the error message instead of [object Object]

- src/constants/routing.test.ts
- src/constants/routing.ts
- src/constants/tokens.ts
Added OP and ARB as base tokens on Optimism and Arbitrum respectively.
Added `OP` and `ARB` to `COMMON_BASES` array when on Arbitrum and Optimism. Added `OP` as a token. 
_Linear ticket:_ WEB-2146
> fix: added op and arb as base tokens

- package.json
- yarn.lock
Upgrades @walletconnect/ethereum-provider to a version which reduces `No matching key` errors. https://uniswap-labs.sentry.io/issues/4252488102/?end=2023-06-23T14%3A08%3A59&project=4504255148851200&query=release%3A9202f2e2e4e9360c02478543206eb034944ac647&referrer=issue-stream&sort=freq&start=2023-06-22T20%3A18%3A00&stream_index=0
Need to ask Jack how he repro'd, but there is no error showing up for me in the console now.
N/A
> chore: upgrade @web3-react/walletconnect-v2

- .github/actions/setup/action.yml
Removes the global yarn cache, as implemented through [actions/setup-node](https://github.com/actions/setup-node).
Although this is the _recommended_ way to cache, it is anecdotally less performant with (classic) yarn v1, which we use. Instead, it is more performant (by 20-40s) to directly cache `node_modules/` only. Caching _both_, as is currently done, spends 20-40s unzipping the global cache, which is then unused if `node_modules/` is already present.
Test runs (to prove efficacy):
- Run with global cache (no node_modules cache): [1m4s setup](https://github.com/Uniswap/interface/actions/runs/5346256239/jobs/9693538433)
- Run with node_modules cache (no global cache): [21s setup](https://github.com/Uniswap/interface/actions/runs/5346255742/jobs/9693004399?pr=6822) …
> build: rm global yarn cache

- src/tracing/errors.test.ts
- src/tracing/errors.ts
I've changed my mind on this a few times. First I added this filter https://github.com/Uniswap/interface/pull/6330 because it was high volume. Then I removed the filter here https://github.com/Uniswap/interface/pull/6533 because I felt this was something we should be handling. I then ignored it in Sentry directly so we didn't get alerted.
I do have a WIP to fix this here but haven't had time to finish it. https://github.com/Uniswap/interface/pull/6348
The problem is we now have an alert which checks for crash free session rate, and unfortunately ignored errors still count against that metric. So I'd like to temporarily pause sending these until we merge the other PR.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2398/catch-user-rejection-errors
> fix: filter user reject errors temporarily

- cypress/e2e/universal-search.test.ts
- src/components/WalletModal/Option.tsx
- src/components/Web3Provider/index.tsx
- src/connection/WalletConnectV2.ts
- src/connection/activate.test.ts
- src/connection/activate.ts
- src/connection/index.ts
- src/connection/types.ts
- yarn.lock
Passes the currently active chain as the required chain when first initializing WalletConnect v2, so that those wallets which do not support mainnet (like a gnosis safe created on an L2) will still be able to connect.
_Slack thread:_ https://uniswapteam.slack.com/archives/C03JTMYT96E/p1687948306256509
Create a gnosis safe on an L2 and try to connect it via WCv2
- Ensure Uniswap wallet can still connect
- Ensure gnosis safe issue is fixed
- Ensure another wallet can still connect via WCv2
> fix: allow wallets w/o mainnet to connect to WCv2

- package.json
- yarn.lock
Upgrades gnosis safe connector with latest safe packages to make sure permit2 works properly.
> fix: upgrade @web3-react/gnosis-safe

- src/pages/Pool/index.tsx
* position list row is overflowing its container on highlight
> fix: position list row highlight overflowing container

- src/components/AccountDrawer/AuthenticatedHeader.tsx
Fixes icon clipping in MiniPortfolio. 
Removed `overflow` style in `StatusWrapper` to prevent the icons from being clipped.
_Linear ticket:_ WEB-2349
1. Open up MiniPortfolio
> fix: icons no longer clip

- src/components/AccountDrawer/UniwalletModal.tsx
- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/WalletModal/index.tsx
- src/featureFlags/flags/walletConnectV2.ts
- src/featureFlags/index.tsx
Removes the defaulting logic as we should always show WalletConnect v2.
> chore: remove walletConnectV2 flag

- src/components/AccountDrawer/MiniPortfolio/Pools/useMultiChainPositions.tsx
- show bnb pool positions in mini port
> fix: show bnb pool positions in mini port

- package.json
- yarn.lock
This is unused since @web3-react already has this dependency defined with a more recent version.
> chore: remove @walletconnect/modal dependency

- src/nft/components/profile/view/__snapshots__/EmptyWalletContent.test.tsx.snap
- src/nft/components/profile/view/icons.tsx
Adds margins between empty pool icon and empty pool title. Increase height of the `EmptyPoolIcon` to make the svg larger and add more blank space between text and icon. 
_Linear ticket:_ WEB-2204
> fix: add margins for empty pool icon

- cypress/e2e/token-details.test.ts
- cypress/e2e/token-explore.test.ts
- src/components/Tokens/TokenTable/TokenRow.tsx
- src/components/Tokens/TokenTable/__snapshots__/TokenRow.test.tsx.snap
- Cypress tests are currently failing on main because there's a token in the top 100 with token name `ETH` this causes the simulated click to fail because there are multiple rows with the same key name as we index on token name. This PR switches the index to be based off address and updates tests and snapshots.
> fix: tokens with same name brake cypress test

- src/graphql/data/util.tsx
https://github.com/Uniswap/interface/pull/6887 upgraded prettier which updated typeof syntax requirements, but https://github.com/Uniswap/interface/pull/6878 was merged right before which caused a lint issue. This solves that.
> fix: update InterfaceGqlChain syntax

- cypress/e2e/landing.test.ts
- cypress/e2e/wallet-connection/connect.test.ts
- cypress/support/commands.ts
- cypress/utils/user-state.ts
this allows you to set custom `userState` in a test in combination with the default injected hardhat provider being automatically connected. 
1.  write a test with both the `hardhat` option and some custom initial `userState` and note that the wallet isn't automatically connected at the start of the test
> fix: combine userState with default injected wallet in cypress setup

- .github/workflows/1-main-to-staging.yml
- .github/workflows/test.yml
Fix usage of head commit sha by using the supplied [sha](https://github.com/actions/toolkit/blob/main/packages/github/src/context.ts#L13C14-L13C14) from github-script. This should fix `pre`/`post` checks on `main`.
> build: use context.sha

- public/index.html
- src/components/analytics/GoogleAnalyticsProvider.tsx
Disables Google Analytics by changing the provider to not send any events. Also removes Google Analytics and Google Tag Manager from the CSP.
Once we migrate the events to Amplitude, we can merge this PR: https://github.com/Uniswap/interface/pull/6554
N/A
> chore: remove Google Analytics from CSP

- src/theme/components/RadialGradientByChainUpdater.ts
- background gradient is not properly loading for avalanche due to the feature flag on prod, now that the feature is live this is no longer needed. This change will not be backported into main
> fix: remove avax flag check for background radiant

- src/graphql/data/nft/NftActivity.ts
- src/nft/utils/currency.ts
Main equivalent to #6935
- Scientific notation for price is causing a crash on the NFT Activity Page. This properly wraps the data point when parsed in to prevent the crash and allow the number to be converted to a `BigNumber`.
- Pushing for not using Scientific Notation for prices on our GQL BE
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2484/is-this-a-known-issue-%F0%9F%A4%94-getting-it-on-the-nft-e2e-test
_Slack thread:_ https://uniswapteam.slack.com/archives/C02T729PMQE/p1689349833728619
1. https://app.uniswap.org/#/nfts/collection/0xbd3531da5cf5857e7cfaa92426877b022e612cf8/activity
> fix: Handle Scientific Notation for NFT Collection Activity Prices

- src/hooks/useTokenAllowance.ts
* the nft pwat was crashing and it was due to a stack overflow error that seemed to be coming from here
> fix: pwat stack overflow

- src/components/AccountDrawer/MiniPortfolio/Activity/parseRemote.tsx
hides pending items returned by GQL, as our current strategy is to only show locally stored pending swaps
> fix: hide pending orders from GQL

- src/pages/Swap/UniswapXOptIn.tsx
`shouldLogImpression={isVisible}` doesn't work because the Trace component doesn't log an impression when the prop changes.
this simplifies the logic by making `shouldLogImpression` always true, so an impression logs every time the UI renders
> fix: log opt in impression

- .github/workflows/3-staging-to-prod.yml
Block promotion to prod on a successful test suite. See https://github.com/Uniswap/interface/pull/6898.
This has essentially been tested via staging, as staging already includes this block.
You can also verify that the required `Test / Promotion` status is set on commits pushed to the `releases/staging` branch.
> build: block promotion to prod on tests

- .github/actions/setup/action.yml
Removes the caching of generated gql across CI builds, as it was incorrectly keyed only on the backend schema, despite also being dependent on frontend queries.
Includes a TODO for a ticket (WEB-2498) to re-introduce a cache for the correct keys.
> fix: do not cache gql across CI

- src/pages/Swap/UniswapXOptIn.tsx
Fixes a double bounce on the X opt in animation.
https://github.com/Uniswap/interface/assets/12100/f690baf1-8ec8-4f9b-aaeb-f8f7029c2723
https://github.com/Uniswap/interface/assets/12100/242c3386-79b2-4ec2-afc0-7419c1fa6e0d
Need a X trade and trigger it basically.
> fix: uniswapx opt in double bounce animation

- src/components/NavBar/MenuDropdown.tsx
- src/components/NavBar/NavDropdown.css.ts
Removed the box shadow and gap for `NavDropdown` menus on mobile. 
_Linear ticket:_ WEB: 1010
> fix: remove shadow and gap on mobile

- src/lib/utils/analytics.ts
fixes the format of the values for `token_in_amount_max` and `token_out_amount_min` so that they don't create new properties in the aplitude backend. they should be formatted as strings when sent to amplitude.
> fix: format currency amounts as strings in logging

- package.json
- yarn.lock
- adds `@babel/plugin-proposal-private-property-in-object` as a dev dep
- resolves the following warning when running: 
```
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.
babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
```
1. Run main locally and be …
> fix: Resolve Babel dependency warning

- src/components/AccountDrawer/MiniPortfolio/__snapshots__/PortfolioLogo.test.tsx.snap
- src/components/swap/__snapshots__/SwapModalHeader.test.tsx.snap
- src/hooks/useAssetLogoSource.ts
Shows logos for all tokens, including blocked tokens.
_Slack thread:_ https://uniswapteam.slack.com/archives/C04D07TQBT4/p1689780623864559
|    Desktop    |
| ------------ |
| ![image](https://github.com/Uniswap/interface/assets/5403956/5372cb2b-184e-444b-9c40-d0ec157b5bc6) |
|    Desktop   |
| ----------- |
| ![image](https://github.com/Uniswap/interface/assets/5403956/aa84b794-f5e1-4d41-a29a-14cd9bd38156) |
Unsupported tokens will continue to not show logos:
> fix: show logos on warned tokens

- src/components/swap/PendingModalContent/PendingModalContent.test.tsx
- src/components/swap/PendingModalContent/index.tsx
replaces the text "Proceed in your wallet" with "view on explorer" after you've already submitted the swap transaction.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2482/change-proceed-in-your-wallet-to-view-on-block-explorer
1. go through the classic swap flow and check the text AFTER you've signed the transaction but BEFORE it is confirmed.
> fix: update text in ConfirmSwapModal

- src/components/AccountDrawer/index.tsx
on ios safari, the browser's bottom nav bar floats in and out of view, so we need to use 100vh to position the bottom sheet because it's responsive to this changing height.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2472/mini-portfolio-appears-on-scroll-on-tdp
see linear ticket
https://github.com/Uniswap/interface/assets/66155195/19dd454d-d30b-4931-b2d2-4d81224959bb
> fix: use 100vh to position bottom sheet

- src/nft/components/collection/CollectionNfts.tsx
* app crashes when url is loaded with price range because it is passing in a number instead of a string causing it to crash
https://linear.app/uniswap/issue/WEB-2523/[safari]-blank-page-and-then-get-something-went-wrong-error-when-set
> fix: fixing price range filter passing as number

- src/components/Logo/AssetLogo.tsx
Fix image loading so that already-loaded images do not fade in, but are immediately displayed.
This fixes the transition to /swap from the landing page. It also improves Token Selector transitions.
_before_
https://github.com/Uniswap/interface/assets/5403956/19619584-610c-4d46-8f27-4020f787aec8
> fix: display already-loaded imgs with no transition

- hardhat.config.js
- package.json
- yarn.lock
- Update UR SDK
- Import `UNIVERSAL_ROUTER_CREATION_BLOCK` to get dynamically get block height per chain that UR was deployed to
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2205/import-a-minimum-block-height-in-hardhatconfigjs-from-universal-router
> feat: update infura fork block height for cypress tests to be dynamic

- cypress/e2e/universal-search.test.ts
Fixes some flake in searchbar test.
Seems dubious but at least on my end I'm seeing the test fail due to not finding an element that actually is there... not actually on the "enter" event but the line before on .get() of the ethereum search result. But I can pause the debugger and its there during the test run.. seems like cypress issue? Or something else. It does success for me 3/4 times.
> fix: flaky test covering searchbar

- src/components/Suspense/SuspenseWithPreviousRenderAsFallback.tsx
use deferred value to avoid suspense issues with inputting text during supsended render causing errors
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2525/[web][ipados][search]-deleting-any-search-causes-an-error-in-the-page
If you hit backspace on a search it breaks search pretty often
No break
1.
> fix: use deferred value to avoid suspense issues with inputting text

- src/components/AccountDrawer/UniwalletModal.tsx
- src/connection/WalletConnectV2.ts
Updates the custom uniswap wallet connector to use a regular deeplink (uniswap://wc) rather than a universal link (uniswap.org/wc...), since the universal link stopped functioning correctly. This makes the uniswap modal's link consistent with the link the proprietary walletconnect connector uses.
Also updates the uniswap wallet modal to not display on iOS, correcting visual lag that would appear upon the the wallet navigating back to interface after successfully walletconnecting.
In addition, we now set `window.location.href` rather than using `window.open`, which is the more correct way to deeplink from mobile browsers (window.open may be hindered by popup blockers or security measures, whereas window.location.href enables the operating system to handle the link appropriately, …
> fix: uniswap wallet deeplinking

- src/hooks/useUniswapXSwapCallback.ts
Apparently we have a high rate of failures for orders posting to the backend. While we investigate why an order might fail to post once it's sent to the backend, in the meantime we can add logging to the client to help us debug.
see this [sheet](https://docs.google.com/spreadsheets/d/1rRZZBkTFmVAhaXIEqroOrpp7sdnGdKOq_Z6I6aBkc-4/edit#gid=2044419544) for a list of unique ura quote/request IDs which have duplicate SWAP_SIGNED events but no posted order to the backend. They probably have duplicates because the user is retrying when the first attempt fails.
1. unsure how to trigger an error response from backend....
> fix: add amplitude event for uniswapX orders failing to post

- src/pages/Landing/index.tsx
Fixes the page flash when loading the landing page. This was caused by hiding the landing chrome using state, which was initially set to hide the state. Instead, "hiding the landing chrome" should be done by redirecting to the swap route.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2438/im-often-seeing-the-landing-page-flash-when-loading-a-fresh-tab-or
---
**Reviewers:**
Hide white space when reviewing this change;
the bulk of this change is de-indentation from removing the conditional gating from the `showContent` state.
> fix: use redirect for landing

- package.json
- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/forceUniswapXOn.ts
- src/featureFlags/index.tsx
- src/lib/hooks/routing/useRoutingAPIArguments.ts
- src/state/routing/slice.ts
- yarn.lock
bumps SDK version
this also adds a feature flag, `forceUniswapXOn`, that forces the routing-api's backend feature flag to be on so we can test uniswapx on staging before the backend fully turns it back on.
> feat: bump uniswapx-sdk

- src/components/NetworkAlert/NetworkAlert.tsx
Fixes bug with network alert overlapping with swap modal. Reduced removed zIndex of `NetworkAlert` and added property `pointer-events: none` to component wrapper to ensure that bridge pointer bug does not return.
_Linear ticket:_ Web- 2440
1. Switch networks and open up swap modal
> fix: collision of network banner and swap settings

- src/lib/hooks/routing/useRoutingAPIArguments.ts
- src/state/routing/slice.ts
only requests classic quotes if the user has disabled UniswapX in swap settings
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2559/dont-fetch-with-dutch-order-config-if-user-has-opted-out-of-uniswapx
> feat: don't fetch UniswapX quotes if user has disabled UniswapX

- src/components/CurrencyInputPanel/index.tsx
[[WEB-2481]](https://linear.app/uniswap/issue/WEB-2481/new-pool-position-page-in-light-mode-has-drop-shadows-on-buttons) addresses styling issues with the dropdown for currency selection, which is used across several web pages:
* Add Liquidity (V2 and V3)
* Remove Liquidity (V2)
* Create Proposal
These pages all use the `CurrencyInputPanel`, which internally builds on the `CurrencySelect` component (the drop-down button, which has the `box-shadow` style applied to it). This PR removes the shadow.
In addition to the shadow, the `CurrencySelect` component on the V3 "Add Liquidity" page has a second issue. In the Deposit section of the page, the user is intended to enter the amounts of each currency that will be deposited into the pool. They cannot and should not use the `CurrencySelect` to …
> fix: improve currency select styling

- src/components/Menu/index.tsx
- src/pages/Pool/index.tsx
[WEB-2473](https://linear.app/uniswap/issue/WEB-2473/pool-page-on-mweb-new-position-and-more-buttons-should-be-50percent) identifies a couple of issues with the style of the buttons on the mobile web "Pools" page. As requested, this PR:
* Switches the order of the buttons so that (from left to right) "More" appears first, followed by "New Position"
* Changes the sizing of the buttons so that they share the space equally
* Switches the alignment of the fly-out menu from right to left, now that the "More" button is on the left side of the page
In order to include this last change, it was necessary to fix an issue with the `Menu` component, specifically the `MenuFlyout` implementation of alignment props and styling. The old implementation worked for larger screen sizes but was being …
> fix: change style of mobile pool buttons and menu

- src/components/AccountDrawer/MiniPortfolio/Tokens/index.tsx
Long single-word token names (e.g. "HarryPotterObamaSonic10Inu" a.k.a. "The People's Bitcoin") overflow the title area and overlap with other elements. This PR clips these names with an ellipsis, following the same convention as the balance text.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2595/token-names-that-dont-have-a-space-in-the-name-wont-wrap-see
| <img width="343" alt="Clip Name Before Mobile" src="https://github.com/Uniswap/interface/assets/18626088/65b8ba00-f041-488c-8667-33269d5c6938"> | <img width="1510" alt="Clip Name Before Desktop" src="https://github.com/Uniswap/interface/assets/18626088/aef05189-b675-41ac-b09e-22e80e5d6df7"> |
| <img …
> fix: clip long token names

- src/hooks/useENSAddress.ts
- src/hooks/useENSAvatar.ts
- src/hooks/useENSContentHash.ts
- src/hooks/useENSName.ts
- src/lib/utils/resolveENSContentHash.ts
- src/utils/safeNamehash.test.ts
- src/utils/safeNamehash.ts
Reverts part of #5958 to bring back `safeNamehash` due to bug with `ZERO_WIDTH_JOINER` emoji. 
_Linear ticket:_ WEB-2586
> fix: bring back safeNamehash

- src/components/AccountDrawer/DefaultMenu.tsx
- src/components/AccountDrawer/index.tsx
Closes the settings menu state when the account drawer is closed. Passes additional parameter `walletDrawerOpen` into `DefaultMenu` and adds a `useEffect` that changes `MenuState` back to `DEFAULT` if set to `SETTINGS`. Added 250 ms delay to allow close animation to happen properly before resetting the menu state. 
_Linear ticket:_ WEB-2542
https://github.com/Uniswap/interface/assets/35351983/15cf8051-7d46-4467-9c8b-4290219b877d
https://github.com/Uniswap/interface/assets/35351983/c088cd37-8599-4835-9fe3-8b9e76949087
> fix: closes settings state when MP is closed

- functions/tokens/[[index]].ts
- functions/utils/getToken.ts
Fixes failing native token cloud function tests by removing the conversion from `NATIVE` to zero address to instead `NATIVE` to `undefined` or a predefined address for specific chains.
> fix: failing token cloud function tests

- src/components/AnimatedDropdown/index.tsx
- src/components/Settings/Input/index.tsx
- src/components/Settings/index.tsx
- src/components/swap/__snapshots__/SwapDetailsDropdown.test.tsx.snap
Fixes issues where languages like French and Dutch are unable to adjust slippage because the slippage input is squished
_Linear ticket:_  https://linear.app/uniswap/issue/WEB-2522/cant-adjust-slippage-in-different-language
> fix: adjusting slippage in a different language

- src/components/RouterLabel/RouterLabel.test.tsx
- src/components/RouterLabel/UniswapXRouterLabel.test.tsx
- src/components/RouterLabel/__snapshots__/UniswapXRouterLabel.test.tsx.snap
- src/components/RouterLabel/index.tsx
- src/components/swap/__snapshots__/AdvancedSwapDetails.test.tsx.snap
- src/components/swap/__snapshots__/SwapDetailsDropdown.test.tsx.snap
- src/state/routing/types.ts
- src/test-utils/constants.ts
fixes a bug in the `RouterLabel` component where we checked an unused field to determine if the routing was client-side. now we correctly use the `QuoteMethod` field. 
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2597/fix-routerlabel-copy-for-local-routing
1. load a quote with client side routing forced and notice it still says "API"
> fix: Router label copy

- src/state/routing/slice.ts
currently we're disabling UniswapX if the user ever turns off the toggle, and we don't re-enable it. this fixes the behavior for when you re-enable the option in settings.
_Slack thread:_ https://uniswapteam.slack.com/archives/C02T729PMQE/p1691101980899769
1.  manually disable uniswapX, then look at the quote request and notice that we're not requesting UniswapX
> fix: re-enable UniswapX after disabling

- src/components/AccountDrawer/MiniPortfolio/Activity/hooks.ts
We are marking transactions as cancelled if we detect the same nonce but a different hash - even if that other transaction is on a different chain.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2621/screen-bugs-out-when-making-base-tx-while-mini-port-is-open
https://github.com/Uniswap/interface/assets/66155195/7efa4deb-f9dd-4712-936f-302345fec0e6
https://github.com/Uniswap/interface/assets/66155195/996670de-1adb-49aa-8ba3-a33d85070cd8
1. make a swap on base with the MP activity tab open
> fix: check chainId in findCancelTx

- src/components/AccountDrawer/MiniPortfolio/Activity/OffchainActivityModal.tsx
- src/components/swap/PendingModalContent/index.tsx
Fixes regression where a UniswapX order would immediately display as successful, before being filled or failing.
https://github.com/Uniswap/interface/assets/39385577/30ca80d1-277f-430c-a43e-9b9659b47f73
https://github.com/Uniswap/interface/assets/39385577/4c9101bb-ecc4-4cec-9e20-2b69e52c2ba5
1. Submit a gouda order, see immediate success rather than a swap pending state
e2e tests are being written for gouda swaps in a sep ticket
> fix: uniswapx review modal success display

- cypress/e2e/universal-search.test.ts
fixes failing cypress typecheck
> chore: fix typecheck error due to jest and cypress overlapping types

- public/.well-known/assetlinks.json
Adds SHA fingerprints for app signed with our local keystores since dev and beta variants are not usually signed by Google Play. 
* For dev bundle id, adds both dev keystore and debug keystore in case we want local testing. 
Manual testing once deployed to vercel + prod domain.
> feat: adding more fingerprints for deeplink apps

- src/components/Loader/styled.tsx
- src/pages/Pool/PositionPage.tsx
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2538/loading-state-for-pool-nft-looks-real-bad
https://github.com/Uniswap/interface/assets/12100/9ff86973-61dc-4564-b660-861c79bd72bd
https://github.com/Uniswap/interface/assets/12100/4bb3873b-54d3-4a34-8289-7cd4e0d1301c
https://github.com/Uniswap/interface/assets/12100/c8e21394-478c-4879-8e23-4eabd2c20e6d
Hard to test because it really doesn't load long, I just edited the code to force show the loading state in PositionPage.tsx line 713.
Can use this url: 
- http://localhost:3000/#/pools/545032
- http://app.uniswap.org/#/pools/545032
> fix: make loading indicator for pools nft card use a shine rather than spinner

- functions/constants.ts
- functions/global-setup.ts
- functions/utils/getColor.ts
Imports predefined colors from widgets to use for rich link previews.
Also updates `launchTimeout` due to increased flakiness caused by jest timing out before the server sets up properly.
> feat: custom colors for rich link previews

- .swcrc
- package.json
fixes breaking wallet connect / uniswap wallet connect on main
had to leave it in package.json because otherwise craco fails.
to repro: it was erroring if you hit connect => uniswap wallet and not allowing connection, this should fix that
> fix: make swc not break WalletConnect by targeting a newer version of es

- src/nft/utils/collection.ts
* Blocks the following infringing NFT collections:
COLLECTION: Zora, contract address: 0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7
COLLECTION: Zora API Genesis Hackathon, contract address: 0xd945f759d422ae30a6166838317b937de08380e3
COLLECTION: Zora Labs Project, contract address: 0x8e52fb89b6311bd9ec36bd7cea9a0c311fd27a92
COLLECTION: Zorb Viz, contract address: 0x2079c2765462af6d78a9ccbddb6ff3c6d4ba2e24
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2624/block-nft-infringing-collections
> chore: add to blocked nft infringing collections

- src/hooks/useContract.ts
- src/hooks/useUniversalRouter.ts
this may prevent a mysterious potential bug causing users to send funds to the mainnet UR address on base
from the ethers docs
transactionRequest.chainId ⇒ number | Promise< number >
The chain ID this transaction is authorized on, as specified by [EIP-155](https://eips.ethereum.org/EIPS/eip-155).
If the chain ID is 0 will disable EIP-155 and the transaction will be valid on any network. This can be dangerous and care should be taken, since it allows transactions to be replayed on networks that were possibly not intended. Intentionally-replayable transactions are also disabled by default on recent versions of Geth and require configuration to enable.
> fix: fail UR transaction if chain IDs don't match

- functions/api/image/tokens/[[index]].tsx
Removes 80% opacity dim for extracted colors from token rich link previews to match theming with widgets.
> fix: remove lowering opacity for token previews

- src/components/NavBar/SuggestionRow.tsx
* fixes the token icon margin in the searchbar
> fix: token margin in searchbar

- src/hooks/useUniswapXSwapCallback.ts
- src/hooks/useUniversalRouter.ts
- src/lib/utils/analytics.ts
This adds metrics about how long users take to sign uniswapx permit message and classic uniswap transaction requests
> feat: add time to sign analytics

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/priceRoutingApi.ts
- src/featureFlags/index.tsx
- src/lib/hooks/routing/useRoutingAPIArguments.ts
- src/state/routing/types.ts
- src/state/routing/utils.ts
delet feature flag and make routing-api the default for price lookups
> chore: feature flag cleanup for routing_api_price

- .github/workflows/test.yml
- functions/api/image/nfts/asset/nftImage.test.ts
- functions/api/image/nfts/collection/[index].tsx
- functions/api/image/tokens/[[index]].tsx
- functions/api/image/tokens/tokenImage.test.ts
- functions/global-setup.ts
- functions/global-teardown.ts
- functions/jest.config.json
- functions/setupAfterEnv.ts
Removed flakey tests from cloud functions and enabled setting to have jest retry tests 3 times upon fails. Increased setup time in `globalSetup` due to tests failing before the server has been setup properly. Also reduced `maxWorkers` to 1 to ensure that Jest does not overtake all resources and shut down proxy.
> fix: remove flakey tests from cloud functions and overall deflake

- src/graphql/data/SearchTokens.ts
- BE added BASE tokens in the universal search, but not for the TDP query
- This leads to users being able to get to a broken page from the search bar
- We also had manually listed BASE as coming soon and have some blocks on the UX
- FIX: filter out any results from chains the UX does not support
_Slack thread:_ https://uniswapteam.slack.com/archives/C04D07TQBT4/p1692096823352609
> fix: temp block BASE tokens in universal search

- cypress/e2e/universal-search.test.ts
- src/components/NavBar/SuggestionRow.tsx
- The Universal Search test is failing on main because the search for `uni` is returning two results with the ticker of `UNI` 
- We currently use the ticker as the unique identifier
- This PR changes to use the token address and chain as the unique identifier
_Slack thread:_ https://uniswapteam.slack.com/archives/C052ARNFZGU/p1692120073832699
> fix: test id based on address & chain instead of ticker

- public/apple-app-site-association
Adds real (not hash-based) paths to app site association, as described in https://developer.apple.com/documentation/xcode/supporting-associated-domains. This should enable deep-linking into the Uniswap Mobile Wallet when using path-based routing.
_Slack thread:_ https://uniswapteam.slack.com/archives/C02T729PMQE/p1692222996293519?thread_ts=1692219376.681979&cid=C02T729PMQE
> feat: add real paths to app site association

- functions/api/image/tokens/[[index]].tsx
- functions/utils/getColor.test.ts
- functions/utils/getColor.ts
Fixes issue of Token Rich Link Previews background color being too white from color extraction by adding an additional check at the end to check distance from [255, 255, 255] and dimming accordingly.
Before:
After:
> fix: add distance check from white for token rich link previews

- cypress/e2e/swap/unconnected.test.ts
- src/hooks/useEagerlyConnect.ts
- src/state/lists/updater.ts
follow up fixes to #6830 :
1. properly default to the network connector so we can still load quotes with no wallet
2. make sure to update the token safety lookup table once lists are rehydrated
> fix: network connector fix and lists fix

- cypress/e2e/wallet-dropdown.test.ts
- src/components/AccountDrawer/DefaultMenu.tsx
- src/components/AccountDrawer/LanguageMenu.tsx
- src/components/AccountDrawer/SettingsMenu.tsx
- src/components/AccountDrawer/SlideOutMenu.tsx
- src/featureFlags/flags/currencyConversion.ts
- src/theme/components/text.tsx
* updating language selection screen to new designs (behind a feature flag): [https://www.figma.com/file/MOvvpkzygJdxCA3BY9mN1O/Mini-portfolio-v1?type=design&node-id=1860-47891&mode=design&t=TKiQ94vfRQFBdQAg-0](url)
| ![Screen Shot 2023-08-15 at 6 26 47 PM](https://github.com/Uniswap/interface/assets/9094792/e2f7427e-27b0-49c0-9ecf-2d0c269c10fa) | ![Screen Shot 2023-08-15 at 6 26 10 PM](https://github.com/Uniswap/interface/assets/9094792/d2bd3aff-1a6f-4804-b7ef-68467d8c885e) |
| ![Screen Shot 2023-08-15 at 6 26 59 PM](https://github.com/Uniswap/interface/assets/9094792/752ad1a0-f72a-49b9-ae2c-339c1285d869) | ![Screen Shot 2023-08-15 at 6 26 31 …
> chore: moving language selection to own settings panel

- functions/api/image/tokens/[[index]].tsx
Increased line height for token preview with long names and slices symbol for some tokens to prevent symbol for crossing to 2 lines. 
Before:
After:
> fix: make line height bigger for token preview

- src/hooks/useUSDPrice.ts
- src/pages/Swap/index.tsx
Prefetches a currency's ETH price so that USD pricing can be available instantly once a quote loads.
Cleans up the `useUSDPrice` code to make it more readable and ensure we aren't making extra calls.
_Slack thread:_ https://uniswapteam.slack.com/archives/C02T729PMQE/p1692313576887119?thread_ts=1692235420.363889&cid=C02T729PMQE
>one thing we can do is not waterfall these requests.
>
>here's an example: UNI->AAVE. In the current state:
>- enter amount (1), triggers two requests: UNI->AAVE (quote) and UNI->ETH (usd price)
>- once UNI->AAVE loads, AAVE->ETH will load (usd price)
>in the proposed state, https://github.com/Uniswap/interface/pull/7187:
>- on token selection, triggers request: TOKEN->ETH; in this case, UNI->ETH (usd price) and AAVE->ETH (usd price)
>- enter amount (1), triggers …
> feat: prefetch eth price for swap currencies

- src/components/Loader/styled.tsx
- src/components/swap/__snapshots__/SwapDetailsDropdown.test.tsx.snap
- src/hooks/useDebouncedTrade.ts
- src/lib/hooks/routing/useRoutingAPIArguments.ts
- src/pages/Landing/__snapshots__/index.test.tsx.snap
- src/state/routing/slice.ts
- src/state/routing/useRoutingAPITrade.ts
- src/state/swap/hooks.tsx
Returns cache entries (using rtk's `useQueryState`) when debouncing quotes, to provide _instant_ quotes for already-loaded data.
_Relevant docs:_ https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#usequerystate
| <video src="https://github.com/Uniswap/interface/assets/5403956/a12013f7-c87f-460e-804d-0f52859e4fe2" > | <video src="https://github.com/Uniswap/interface/assets/5403956/e3c5791e-4c39-49ca-8303-7639d9f26f42" > |
> feat: use cache while debouncing quotes

- src/hooks/useUniversalRouter.ts
- src/lib/utils/analytics.ts
Adds amplitude logging for client side block number and router block number, to help diagnose whether potential mismatch between these two is causing price-movement swap failure.
> feat: add client and router blocknumbers to analytics

- src/tracing/utils.ts
sentry issue: https://linear.app/uniswap/issue/WEB-2733/elapsedtime-is-undefined-occasionally
on iOS webviews (not safari, embedded browsers in other apps), `performance.mark` does not return  a `PerformanceEntry` object. as a quick fix we should just fail gracefully and not log performance metrics for these browsers.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2733/elapsedtime-is-undefined-occasionally
1. load the app in an embedded browser on iOS (e.g. ...)
- Mobile Safari UI/WKWebView
> fix: null check on elapsedTime for some browsers

- src/pages/PoolFinder/index.tsx
v2 import liquidity back button will now correctly navigate back to v2 pool page
https://github.com/Uniswap/interface/assets/5773490/3a54b137-fe41-4aeb-98f5-f94eb006e64f
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1692625017980549
> fix: add v2 to lp importer link

- src/pages/CreateProposal/ProposalActionDetail.tsx
- src/pages/CreateProposal/ProposalActionSelector.tsx
- src/pages/CreateProposal/index.tsx
Proposal creation screen was broken on safari. 
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1692625017980549
| paste_before | <img width="853" alt="image" src="https://github.com/Uniswap/interface/assets/5773490/4f19785a-df44-4a59-8c97-ad64be314ad4"> |
| paste_after  | <img width="845" alt="image" src="https://github.com/Uniswap/interface/assets/5773490/1fbda16b-61c3-4ffe-b84c-59aad3093009"> |
> fix: proposal creation layout on safari

- src/state/routing/slice.ts
- Capture when UX receives a `NO_ROUTE` error from the routing API to help diagnose outages
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2727/add-no-route-error-logging
_Slack thread:_ https://uniswapteam.slack.com/archives/C05MPSE3WDQ
_Relevant docs:_ https://www.notion.so/uniswaplabs/V3-over-V2-routing-on-interface-e947a8e0f3f2486faca2490ee0ee8773
> feat: add sentry monitoring for NO_ROUTE error

- cypress/e2e/permit2.test.ts
- src/components/swap/ConfirmSwapModal.tsx
fixes a bug in the Resetting USDT logic - we only want to force the USDT approval if the setup approval step is needed in the first place. In other words, if the USDT setup approval is already large enough, we don't need to reset. 
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2620/investigate-permit2-bug-with-tether-reapproval-after-inactivity
issue #7083 
https://github.com/Uniswap/interface/assets/66155195/23450fad-5f45-4d7f-86c1-63db2f14048e
https://github.com/Uniswap/interface/assets/66155195/00b77d57-71c6-4e8c-8a4a-5c9470166df5
1. for USDT mainnet, set up your token approval to X
2. try to swap USDT to another token, with input amount <= X
3. notice that the reset step occurs even though you're swapping X or less USDT
> fix: reset USDT logic

- src/hooks/useUniversalRouter.ts
* fixes a bug that causes smart contract wallets to fail
linear: https://linear.app/uniswap/issue/WEB-2613/smart-contract-wallets-are-unsupported-investigative
slack: https://uniswapteam.slack.com/archives/C047U65H422/p1692894402092459
* smart contracts alter the calldata so checking if they are the same is not correct - better to check if it exists
> fix: smart contract wallets unsupported

- package.json
- src/hooks/useContract.ts
- src/lib/hooks/useCurrency.ts
- yarn.lock
- Adds logging for calls to a user's connect wallet provider that will be replaced with calls to our Be/infura in the new multichain UX as noted in [this doc](https://www.notion.so/uniswaplabs/MultiChain-Web-UX-127bdec19777423abf12b7b7ad98a60f)
- This includes:
- pool positions
- multicall token address searches in the token selector
- Dependent on the addition of the new analytics event https://github.com/Uniswap/analytics-events/pull/52
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2723/add-amplitude-tracking-for-current-wallet-provider-calls
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1692638017065729
> feat: track connected wallet provider calls to be replaced with BE/infura

- public/index.html
- src/components/NetworkAlert/NetworkAlert.tsx
Base chain selector now looks like on prod:
Gradient now matches the initial ETH gradient (we change based on chain) for light and dark (very subtle):
You can test this one ^ by setting a breakpoint at and checking it matches the react rendered bg:
1.
> fix: Spore color fixes

- src/pages/AddLiquidityV2/index.tsx
The information message on the AddLiquidityV2 page is not being translated correctly. Instead of the actual message, users are seeing a random string (likely an internal lingui hash). The root cause is the use of a `Trans` component inside of another `Trans` component. Un-nesting them resolves the issue and allows the intended message to be shown.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2783/weird-text-string-on-the-add-v2-liquidity-page-here
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1693507380586379
| <img width="405" alt="Screenshot 2023-08-31 at 6 08 51 PM" src="https://github.com/Uniswap/interface/assets/18626088/a0c01820-d062-400b-aae9-78be9b0ebd2f"> | <img width="487" …
> fix: un-nest translation on AddLiquidityV2 page

- src/components/AccountDrawer/MiniPortfolio/Activity/parseRemote.tsx
fixes incorrect tx parsing for exact_out swaps where the input token is native. This issue was caused by the fact that there is a third TokenTransfer for these types of swaps, representing a refund of any leftover (estimated_amt - actual_amt) native token after the swap.
| <img width="387" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/30dc82f0-0d84-4b69-8886-ccf9b71f4adb"> | <img width="392" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/6fb4307c-c569-40e4-a14e-ca27f2bc0cf0"> |
> fix: detect refunds on exact_out native swaps

- src/components/swap/SwapModalHeader.tsx
- src/components/swap/TradePrice.tsx
- src/constants/localCurrencies.tsx
- src/graphql/data/ConversionRate.ts
- src/hooks/useLocalCurrencyPrice.ts
- src/nft/hooks/useUsdPrice.ts
- src/pages/Swap/index.tsx
- src/utils/getFetchPolicyForKey.ts
* adding conversion rate hook where we can pass local currencies into it and get the conversion rate relative to USD
* this also updates the current `useUSDPrice` hooks to use this hook instead since it just wraps it
* this should have no impact (like no extra overhead) on users that are using USD (all our users since the currency selection is behind a feature flag)
> feat: adding currency conversion hook to useUSDPrice

- cypress/fixtures/mini-portfolio/full_activity.json
- src/components/AccountDrawer/MiniPortfolio/Activity/parseRemote.tsx
- src/graphql/data/activity.graphql
Updates AssetActivity queries to move off of deprecated fields, as these fields were made optional (by the schema) and so would lose type safety. Also: they are deprecated.
Hotfix of #7269 
_Slack thread:_ https://uniswapteam.slack.com/archives/C052ARNFZGU/p1694021868796429
_Relevant docs:_ https://github.com/Uniswap/data-api-graphql/pull/1116/files#diff-5424116e8713d835fc94a4a0b222638eebf7c61231381c46bee66d6e549855f4R279-R283
> fix: move off deprecated gql fields

- src/components/swap/AdvancedSwapDetails.tsx
- src/components/swap/SwapModalFooter.tsx
- src/lib/hooks/routing/useRoutingAPIArguments.ts
- src/state/routing/types.ts
- src/state/swap/hooks.tsx
the fotAdjustmentsEnabled gate was not actually being used, this updates the swap component to use the gate. Removes previous code that passed the flag as an argument to the routing slice (where it was not actually being used at all).
also adds a help center article for FOT tooltips
> fix: gate FOT UI in swap component

- src/components/swap/AdvancedSwapDetails.tsx
- src/components/swap/SwapModalFooter.tsx
- src/lib/hooks/routing/useRoutingAPIArguments.ts
- src/state/routing/types.ts
- src/state/swap/hooks.tsx
the fotAdjustmentsEnabled gate was not actually being used, this updates the swap component to use the gate. Removes previous code that passed the flag as an argument to the routing slice (where it was not actually being used at all).
also adds a help center article for FOT tooltips
> fix: gate FOT UI

- src/components/swap/AdvancedSwapDetails.tsx
- src/components/swap/SwapDetailsDropdown.test.tsx
- src/featureFlags/index.tsx
- src/hooks/useSwapTaxes.ts
Fixes visual bug where FOT details in swap dropdown were wrong color and lacked a loading state
this hotfix is also coupled with a change for which statsig flag is used to gate FOT logic. the current flag used in prod is having issues possibly related to caching
also removes sentry logging since we now expect tax lookups to fail regularly for tokens that have insufficient v2 liquidity
https://github.com/Uniswap/interface/assets/39385577/278fa5e8-24c2-43eb-b79c-1180fa6a0fc4  
https://github.com/Uniswap/interface/assets/39385577/0f1c1033-4fdd-406b-a81c-4baf64414fbe
> fix: hotfix fot ui bug in swap details dropdown + update flag and sentry

- src/components/swap/AdvancedSwapDetails.tsx
- src/components/swap/SwapDetailsDropdown.test.tsx
Fixes visual bug where FOT details in swap dropdown were wrong color and lacked a loading state
https://github.com/Uniswap/interface/assets/39385577/278fa5e8-24c2-43eb-b79c-1180fa6a0fc4  
https://github.com/Uniswap/interface/assets/39385577/0f1c1033-4fdd-406b-a81c-4baf64414fbe
> fix: fot ui bug in swap details dropdown

- cypress/fixtures/uniswapx/quote1.json
- cypress/fixtures/uniswapx/quote2.json
- src/hooks/useUniswapXSwapCallback.ts
- src/state/routing/types.ts
- src/state/routing/utils.ts
- src/test-utils/constants.ts
we want to use a server-defined value for the start time offset, instead of a constant 30s.
- https://github.com/Uniswap/unified-routing-api/pull/259
> feat: uniswapx start time buffer

- src/hooks/useSwapTaxes.ts
Removes sentry logging in `getSwapTaxes` since we expect tax lookups to fail regularly for tokens that have insufficient v2 liquidity
> fix: remove sentry warnings for failed tax fetches

- src/state/transactions/updater.tsx
we were incorrectly logging Swap Transaction Completed for all transaction types. this checks the transaction type before logging.
1. start a swap where the input token is an erc20 that doesn't have a setup approval
2. sign the setup approval transaction and notice that Swap Transaction Completed is logged when that transaction confirms
> fix: only log swap success for swap txs

- src/hooks/useUniversalRouter.ts
* `blocknumber` was added twice to the dep array due to merge of #7231
> chore: remove extra blocknumber from dep array

- src/components/Charts/PriceChart/utils.ts
- src/components/Charts/SparklineChart.tsx
- src/components/Tokens/TokenDetails/PriceChart.tsx
- src/components/Tokens/TokenTable/__snapshots__/TokenRow.test.tsx.snap
Breaks price chart utilities into utils file, improves performance of getPriceBounds and getNearestPricePoint, and improves readability / documentation.
> refactor: price chart utility functions

- src/components/TopLevelModals/index.tsx
Loads top-level modals synchronously, as they block the first paint.
This prevents a waterfall, which - on my 500 Mbps connection - improves cold load time by 200ms.
In the following diagnostic screenshots, the red vertical line denotes Load, which correlates to Largest Contentful Paint (LCP).
| Before | After |
| - | - |
| <image src="https://github.com/Uniswap/interface/assets/5403956/5ea85d77-d9d9-41e0-8f6a-5addcfa22320"/> | <image src="https://github.com/Uniswap/interface/assets/5403956/b603db8d-7e03-45c2-a21d-9535a62b7a0a"/> |
> fix: synchronously load first page

- patches/@web3-react+coinbase-wallet+8.2.2.patch
- patches/@web3-react+metamask+8.2.3.patch
- patches/@web3-react+walletconnect-v2+8.5.0.patch
Fixes web3-react so that large libs (especially coinbase) are lazy-loaded. This improves pageload, as coinbase is a ~500kb package.
This is an issue because cjs libs use `require`, which is not split into an async package by webpack (see https://webpack.js.org/api/module-methods/#requireensure).
Until a better fix is found - presumably either (a) re-compiling our own packages, or (b) adding a custom loader to translate `__importStar(require('package'))` to `__importStar(await import('package'))` - this is being done as a patch for web3-react, so that the *large* savings of not loading coinbase-wallet on pageload can be realized.
> fix: lazy-load web3-react libs

- src/components/NavBar/ChainSelector.tsx
- src/constants/chains.ts
Removes the hardcoded `UniWalletSupportedChains` config, and relies on supported chains from wallet connect 
- connect a uniswap wallet
- ensure that chains not currently supported by the uni wallet (bnb, celo) are not listed as chains you can connect to
- ensure the rest of the chains are able to be connected to
> chore: Remove Hardcoded Uni Wallet Supported Chains List

- src/pages/AddLiquidity/redirects.tsx
- src/pages/AddLiquidityV2/redirects.tsx
- src/pages/App.tsx
- src/pages/Landing/index.tsx
- src/pages/Swap/redirects.tsx
Lazy load all non-swap pages to improve pageload.
This may make non-swap pages load slower on first load, but should be a minor change, and will improve pageload overall.
To test:
- Navigate to the preview url
- Open your devtools (F12)
- In the Network pane, set throttling to "Fast 3G"
- Navigate to another page through the NavBar
> feat: lazy-load non-swap routes

- craco.config.cjs
- package.json
Fixes sourcemap generation so that ignoring warnings is no longer necessary.
> build: fix sourcemap warnings

- src/nft/components/profile/list/ListPage.tsx
- src/nft/components/profile/list/NFTListingsGrid.tsx
- Overlay behind listing page confirmation would cutoff on the left now it's the full length of the page
- The table header was also missing border-radius so I added it back
_Slack thread:_ https://uniswapteam.slack.com/archives/C04D07TQBT4/p1694730206799959
> feat: remove overlay cutoff

- src/components/Tokens/TokenDetails/index.tsx
- src/pages/Swap/index.tsx
Refactors some `Swap` inputs which were passed as objects to be passed as primitives, as they were not being memoized by the caller. This was causing spurious re-renders as the objects were recreated every time the parent component was rendered, thus forcing re-renders of `Swap`.
Passing them as primitives makes it harder to footgun by forgetting to memoize.
> fix: spurious Swap re-renders

- src/components/AccountDrawer/index.tsx
Avoids calling `scrollTo` on initial render, as this causes a style recalculation and delays the largest contentful paint (LCP).
> fix: avoid scrollTo on pageload

- cypress/e2e/mini-portfolio/accounts.test.ts
Deflakes mini portfolio prefetching by only spying on portfolio balance queries. This UI also fetches token spot prices, which was occasionally triggering and causing flakes.
> test: spy only on portfolio balances

- src/lib/i18n.tsx
- src/state/user/reducer.ts
Does not re-load and re-activate the locale if it has already been loaded.
This prevents a re-render during initialization for en-US users, improving pageload time.
> fix: do not re-init active locale

- src/state/lists/updater.ts
Waits to fetch token lists until state has been rehydrated, as lists should only be fetched if they are not already loaded, and that is impossible to tell without hydrated state. Effectively, this improves pageload by eliminating main thread usage.
Manually verified that token list requests were no longer going out as part of pageload, but were deferred.
> fix: wait to fetch lists until rehydration

- patches/@web3-react+gnosis-safe+8.2.3.patch
- src/connection/eagerlyConnect.ts
Lazy-loads Gnosis Safe, and only does so if we are on an iframe. This allows us to defer loading viem (used by Safe) unless we need to, and reduces the main bundle by 10%.
> feat: lazy-load safe only if iframed

- src/components/swap/ConfirmSwapModal.tsx
- src/components/swap/PendingModalContent/index.tsx
- src/components/swap/constants.ts
- src/constants/tokens.ts
LDO token has the same `approve` logic as USDT on mainnet which requires you to reset the allowance to zero before increasing the amount.
see the contract source code [here](https://etherscan.io/token/0x5a98fcbea516cf06857215779fd812ca3bef1b32#code)
```
function approve(address _spender, uint256 _amount) public returns (bool success) {
// ........
// To change the approve amount you first have to reduce the addresses`
//  allowance to zero by calling `approve(_spender,0)` if it is not
//  already 0 to mitigate the race condition described here:
//  https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729
require((_amount == 0) || (allowed[msg.sender][_spender] == 0));
// ........
}
```
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2857/generalize-reset-usdt-approval-step-t …
> fix: reset LDO approvals

- src/components/Settings/RouterPreferenceSettings/index.tsx
- src/lib/hooks/routing/useRoutingAPIArguments.ts
- src/state/reducerTypeTest.ts
- src/state/routing/slice.ts
- src/state/routing/types.ts
- src/state/user/hooks.tsx
- src/state/user/reducer.ts
updates the code for transitioning to UniswapX by default, or opt-out, phase. This change is needed because we want to opt-in users who only saw but dismissed the opt-in flow, but unfortunately right now we're treating them the same as users who actually tried uniswapX and then disabled it - both types of users would have `user.disabledUniswapX=true`. since we can't differentiate between those two groups of users, we are deciding to opt-in both groups when we roll out the on-by-default change.
now, when we flip on `isUniswapXDefaultEnabled`, we want to treat all users the same and opt them into uniswapX until they explicitly opt out again. 
as a reminder (and see the linked doc for more details), we are rolling this out gradually via the feature flag which is why we need these temporary …
> feat: uniswapX opt-out update

- src/components/CurrencyInputPanel/index.tsx
- src/components/NavigationTabs/index.tsx
- src/components/PrefetchBalancesWrapper/PrefetchBalancesWrapper.tsx
- src/pages/AddLiquidity/index.tsx
- src/pages/AddLiquidity/styled.tsx
fixes some visual bugs in the LP flow:
- make the token select buttons fill their parent container
- align the items in the header
- removed an unnecessary div and used `gap` instead for spacing the token select elements
the bug described in the ticket isn't happening for me.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2803/clicking-preview-when-creating-an-lp-position-requires-two-clicks
1. go through the add liquidity flow and use eyes
> fix: ui fixes on the add liquidity flow

- src/tracing/SwapEventTimestampTracker.test.ts
- src/tracing/SwapEventTimestampTracker.ts
- src/tracing/utils.ts
on some browsers like iOS webviews , `performance.mark` doesn't actually return the expected value. 
in this case a good approximate fallback is just measuring from the creation of the `SwapEventTimestampTracker` singleton.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2733/elapsedtime-is-undefined-on-ios-webview
https://github.com/Uniswap/interface/assets/66155195/7eb4e656-63f0-40c0-9e2f-ac5e250627ce
> fix: use Date as a performance tracker fallback

- src/components/NavigationTabs/index.tsx
- src/components/Settings/index.test.tsx
- src/components/Settings/index.tsx
- src/pages/AddLiquidity/index.tsx
- src/pages/AddLiquidityV2/index.tsx
- src/pages/MigrateV2/MigrateV2Pair.tsx
- src/pages/RemoveLiquidity/V3.tsx
- src/pages/RemoveLiquidity/index.tsx
* puts settings for slippage & transaction deadline back in LP flows
* SettingsTab should show routing settings only for trade/swaps
_Slack thread:_ https://uniswapteam.slack.com/archives/C04D07TQBT4/p1695326833684059
* oopsie add/remove liquidity don't have settings
|    Swap    |   Add Liquidity    | Remove Liquidity |
| ------------ | ------------ | ------------ |
| <img width="250" alt="Screenshot 2023-09-21 at 5 15 31 PM" src="https://github.com/Uniswap/interface/assets/27475332/17d63b7f-2fe0-47ab-93ea-fb513a8f4792"> | <img width="250" alt="Screenshot 2023-09-21 at 5 19 09 PM" src="https://github.com/Uniswap/interface/assets/27475332/3660131d-0f12-49b5-8e4d-437d47532bd9"> | <img width="250" alt="Screenshot 2023-09-21 at 5 19 25 PM" …
> fix: should show slippage/deadline on LP flow settings

- cypress/e2e/token-details.test.ts
It looks like backend stopped returning stats data for tokens with no prices, so this test is no longer true
> fix: Remove e2e test

- src/components/swap/ConfirmSwapModal.tsx
- src/components/swap/PendingModalContent/TransitionText.tsx
- src/components/swap/PendingModalContent/animations.ts
- src/components/swap/PendingModalContent/index.tsx
- src/hooks/useUniswapXSwapCallback.ts
- src/pages/Swap/index.tsx
- src/utils/errors.ts
problem: right now, some fillers are receiving uniswapx orders after startTime has already passed so they no longer have an exclusivity window. we think it's because users are taking too long to sign the permit signature in their wallet. the interface currently only re-prompts a signature if the submission happens after deadline
solution: change the re-prompt logic to happen after startTime instead (so moving up the time requirement), and also add copy in the swap submission modal to say that their signature has expired 
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2898/uniswapx-change-time-to-sign
_Slack thread:_ https://uniswapteam.slack.com/archives/C053G2YEK5M/p1695663790335929
https://github.com/Uniswap/interface/assets/66155195/18987195-1465-49cb-b287-4a43d0edce41
> feat: uniswapx deadline

- src/components/AccountDrawer/MiniPortfolio/Activity/__snapshots__/parseRemote.test.tsx.snap
- src/components/AccountDrawer/MiniPortfolio/Activity/fixtures/activity.ts
- src/components/AccountDrawer/MiniPortfolio/Activity/parseRemote.test.tsx
- src/components/AccountDrawer/MiniPortfolio/Activity/parseRemote.tsx
fix activity parsing for wrap/unwrap transactions that are labelled as "LEND" by zerion
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2721/[web][metamask]-inaccurate-title-and-transaction-hash-paragraph-in
1. wrap ETH or unwrap WETH, let the transaction confirm, then open the Mini Portfolio activity history and see "LEND"
> fix: wrap/unwrap activity parsing

- src/featureFlags/dynamicConfig/index.tsx
- src/featureFlags/dynamicConfig/quickRouteChains.ts
- src/featureFlags/index.tsx
Using statsig Dynamic Config to store list of chains that we want to support feature-flagging for.
Linear ticket: https://linear.app/uniswap/issue/WEB-2912/set-up-statsig-dynamic-config-for-the-interface-app
Statsig dynamic config: https://console.statsig.com/5M2TFMQiHkbY9RML95FAEa/dynamic_configs/quick_route_chains
1.
> feat: add chains dynamicconfig for feature flags

- src/constants/supportArticles.ts
- src/nft/components/collection/UnavailableCollectionPage.test.tsx
- src/nft/components/collection/UnavailableCollectionPage.tsx
- src/nft/pages/collection/index.tsx
This PR refreshes the user experience when visiting the NFT collection page when no assets exist at the given contract address and when the address is blocked, sharing an informative message and helping the user continue navigating the application.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2726/blocked-collectionfalse-url-page-treatment
|    Mobile Valid Collection    |   Desktop Valid Collection    |
| <img width="1624" alt="valid collection mobile before" src="https://github.com/Uniswap/interface/assets/18626088/58c739a8-c3fa-4973-831c-0f5de3342aa4"> | <img width="1624" alt="valid collection desktop before" src="https://github.com/Uniswap/interface/assets/18626088/f4393563-97a2-4ff5-b9a2-1c9126642bb1"> |
|    Mobile Nonexistent Collection    | …
> feat: polish blocked, nonexistent NFT collection page

- src/hooks/useAccountRiskCheck.test.ts
- src/hooks/useAccountRiskCheck.ts
* Change our address screening service from current cloudflare worker ([wallet-screening-server](https://github.com/Uniswap/wallet-screening-server)) to Uniswap /screen API
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2587/move-web-app-trm-checking-to-use-same-backend-endpoint-as-the-mobile
_PR to API repo:_ https://github.com/Uniswap/api/pull/110
* unit tests in /interface repo
* replace UNISWAP_API_V1 in .env using my deployed AWS dev API (https://xtr344xw65.execute-api.us-east-1.amazonaws.com/prod/screen)
> feat: change address screening service to Uniswap /screen API

- src/hooks/useUniswapXSwapCallback.ts
We just switched UniswapX signature deadlines to expire if the message gets signed past `startTime`, but it's a bit too strict, so move it back to `deadline`
Showing that it still submits after waiting for ~30s:
https://github.com/Uniswap/interface/assets/59578595/eb2dfd64-bd41-41d1-9a59-6423bc1d6075
- Wait in the signature screen between 30s and 2 minutes, and the signature should still submit.
- If you wait over 2 minutes, you should see the regular expiration message.
> feat: Move UniswapX signature expiry back to deadline

- src/hooks/useDebouncedTrade.ts
- src/state/routing/usePreviewTrade.ts
- src/state/routing/useRoutingAPITrade.ts
fixes a bug where we incorrectly used a stale quote when the `otherCurrency` was not defined.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2885/swap-shows-incorrect-quote-after-changing-chains-with-no-output
https://github.com/Uniswap/interface/assets/66155195/b2d83e31-6c61-45a3-aaaf-c25410f65c66
https://github.com/Uniswap/interface/assets/66155195/43b985a0-b8d3-4f98-9198-21ed42556d23
1. on chain A, select output token (leave input as ETH), and enter an amount to load a quote
2. switch to chain B. verify that the swap inputs are cleared but ETH is still the input token.
3. enter an input amount for ETH - note that a quote is incorrectly shown
> fix: no stale trade when otherCurrency is missing

- src/components/Tokens/TokenDetails/TokenDescription.test.tsx
- src/components/Tokens/TokenDetails/TokenDescription.tsx
- src/components/Tokens/TokenDetails/__snapshots__/TokenDescription.test.tsx.snap
to improve SEO , we should not hide any content behind a user interaction (like a click). web crawlers don't click so they don't see this content. the new solution keeps both strings in the DOM all the time, and just updates the CSS display property to toggle between them
_Relevant docs:_ https://www.notion.so/uniswaplabs/Web-SEO-Improvements-1de35e2d684648efac0ca36055a6f8ad#6aba3250e8d140cbbfac0ba4731c6a29
verified that truncation is still working on the pools page
> fix: update description truncation from TokenDescription

- cypress/e2e/universal-search.test.ts
- cypress e2e tests for universal search are failing right now, for some reason the check to enter on the eth search result is ending up on the trending Half Shiba page. I've updated the test so that instead of mocking a user hitting enter, it mocks directly clicking on the element.
1. Cypress e2e tests failing on the half shiba page
> fix: click on test row directly

- src/components/swap/SwapLineItem.tsx
- src/components/swap/__snapshots__/SwapDetailsDropdown.test.tsx.snap
- src/components/swap/__snapshots__/SwapLineItem.test.tsx.snap
- src/components/swap/__snapshots__/SwapModalFooter.test.tsx.snap
Removing the minus sign to come to parity with mobile
Ticket here: https://linear.app/uniswap/issue/WEB-2917/remove-in-front-of-fot-fee
1.
> fix: Remove Minus Sign for FOT Display

- src/state/index.ts
our large redux slices are causing console warnings (and unit test failures) in the immutable check middleware, so we should ignore them in this check.
these checks don't happen in prod, so this won't have any effect on users
> fix: ignore large slices in immutable check

- cypress/e2e/token-details.test.ts
- functions/[[index]].ts
- functions/components/metaTagInjector.test.ts
- functions/components/metaTagInjector.ts
- functions/nfts/asset/[[index]].ts
- functions/nfts/collection/[index].ts
- functions/tokens/[[index]].ts
- functions/utils/getRequest.ts
- src/pages/App.tsx
Support adding a list of blocked paths in cloudflare headers
Add a meta tag `<meta name="x:blocked-paths" content="/,/nfts" />` and see that the pages redirect
> feat: support redirects for a list of header paths

- src/nft/components/common/SortDropdown/FilterSortDropdown.tsx
- We removed the src for the checkmark svg used in the NFT Mobile Filter menu, this updates the component to use the React Feather component
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2921/[mweb][android][nft]-the-price-low-to-high-option-is-displayed-twice
|    Before    |   After   |
| <img width="404" alt="Screenshot 2023-10-02 at 4 28 24 PM" src="https://github.com/Uniswap/interface/assets/11512321/30bef388-6bc0-460d-95f0-47ed761e07e9">  | <img width="405" alt="Screenshot 2023-10-02 at 4 28 06 PM" src="https://github.com/Uniswap/interface/assets/11512321/418d05bb-9f96-4f4a-a4bc-6ff5a9dd1ff3"> |
> fix: broken Checkmark image for Mobile NFT Sort dropdown

- .github/workflows/1-main-to-staging.yml
- package.json
we don't want the sitemap script to run every time someone runs `yarn install` - this removes it from the `prepare` script and adds it as a step to the main -> staging pipeline
> feat: remove sitemap script from prepare step

- src/hooks/useColor.ts
- src/pages/PoolDetails/PoolDetailsStats.tsx
- src/pages/PoolDetails/__snapshots__/PoolDetailsStats.test.tsx.snap
- src/pages/PoolDetails/__snapshots__/index.test.tsx.snap
- Updates the color extract default to be accent1 to fit with spore
- In the PoolDetailsStats graph, fallback to blue for the second token in the case that both colors default to accent1
_Slack thread:_ https://uniswapteam.slack.com/archives/C05NXMASXNZ/p1696614227484049?thread_ts=1696355275.788919&cid=C05NXMASXNZ
> feat: [info] update color extract default and have PDP fallback

- src/pages/App.tsx
> fix: user prop updater staging

- public/.well-known/assetlinks.json
Adds new package names for deeplinks to mobile. Keeps the old ones for now, but will remove 
those later.
> chore(): update deeplink package names

- src/pages/routes.test.ts
sitemap URLs should exist as Router paths - should test that routerPaths contain each sitemap URL, not vice versa
Context: we are adding Router paths that aren't publicly-available yet
> fix: fix sitemaps routes test

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/featureFlags/flags/progressIndicatorV2.ts
- src/featureFlags/flags/useProgressIndicatorV2.ts
- src/featureFlags/index.tsx
- Adds a statsig feature flag to gate the new progress indicator on the swap flow
- https://console.statsig.com/5M2TFMQiHkbY9RML95FAEa/gates/progress_indicator_v2
Why use a feature flag for this?
- There are several parts of this new UX, which are most logical / impactful when bundled together
- This allows us to break up the changes into smaller PRs, making reviews easier and more thorough
- This modifies a core product experience, hence the ability to roll back the changes in case of error is vital
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2764/[swaptober]-progress-indicator-v2
_Relevant docs:_ https://www.figma.com/file/JX7QWhOXvVJEm0sY5IfFoW/Time-to-Swap?type=design&node-id=993-56975&mode=dev
> feat: add progress_indicator_v2 flag

- src/components/Settings/MenuButton/index.tsx
- src/components/Settings/index.tsx
if the loaded trade is X, don't show the slippage UI next to the menu button. the slippage setting is not relevant for X trades.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2934/remove-slippage-indicator-when-using-uniswapx
see linear ticket
> fix: hide slippage warning when trade is x

- src/constants/misc.ts
- src/state/migrations.test.ts
- src/state/migrations.ts
- src/state/migrations/1.test.ts
- src/state/migrations/1.ts
- src/state/reducer.ts
updates the default deadline from 30 minutes (1800 seconds) to 10 minutes (600 seconds). this includes changing the constant value used to seed the default state, but also includes a migration for all users who had the old default value persisted. 
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2938/30m-feels-high-for-classic-swaps-xinwan-and-austinadams-can-weigh-in
_Relevant docs:_ https://www.notion.so/Redux-migrations-in-interface-30aca899626a4ac4af7b070f92ce976d
> fix: change default tx deadline to 10m

- src/components/AccountDrawer/MiniPortfolio/PortfolioLogo.test.tsx
- src/components/AccountDrawer/MiniPortfolio/__snapshots__/PortfolioLogo.test.tsx.snap
- src/components/FiatOnrampModal/utils.ts
- src/constants/tokens.ts
- src/hooks/useStablecoinPrice.ts
moonpay will no longer support bridged USDC on arbitrum, which means we don't have a reason to keep this token in the codebase anymore
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1697038790829849
> fix: remove bridge usdc arbitrum

- public/sitemap.xml
- scripts/generate-sitemap.js
- src/pages/routes.test.ts
the old format was valid according to free sitemap validators, but Google Search Console seems to prefer this format.
> fix: sitemap format

- src/pages/App.tsx
moves all the `useEffect` hooks which set user properties into their own component.  this is important because it puts the logic within StatsigProvider and DarkModeQueryParamProvider, which can affect the values we set.
_Slack thread:_ https://uniswapteam.slack.com/archives/C052XQ3EUTT/p1696973999717179
manually verified that `isUniswapXDefaultEnabled` correctly updates to `true` at this callsite now - before it was never updating to the correct value
> fix: move user prop updater into statsigProvider

- src/pages/App.tsx
tl;dr: we're setting the user property to an incorrect value as we wait for the statsig and redux values to load into the app. 
here we delay setting the user property until we are certain we have the right value, to avoid setting multiple values in a short time span. even though user properties apply to all subsequent events, this is important because we usually send unrelated events between the two user-prop-setting moments which solidifies the user prop in the shortest time frame amplitude supports, 1 hour. so our charts and metrics are broken because we're counting users in both buckets for that time frame.
see the slack thread for all the nitty gritty details. 
_Slack thread:_ https://uniswapteam.slack.com/archives/C0574KNS77S/p1697137960543169 …
> fix: delay setting user.router_preference until statsig and redux initialize

- src/pages/Swap/UniswapXOptIn.tsx
UniswapX opt-in modal was rendering off-screen on the TDP. this fix just uses the small screen layout to avoid the issue on that page.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2964/token-details-page-is-rendering-the-uniswapx-modal-off-the-right-edge
> fix: position X opt in tooltip on TDP

- cypress/e2e/swap/settings.test.ts
- src/components/NavigationTabs/index.tsx
- src/components/RouterLabel/index.tsx
- src/components/Settings/RouterPreferenceSettings/index.test.tsx
- src/components/Settings/RouterPreferenceSettings/index.tsx
- src/components/Settings/index.test.tsx
- src/components/Settings/index.tsx
- src/hooks/useDebouncedTrade.test.ts
- src/hooks/useDebouncedTrade.ts
- src/pages/MigrateV2/MigrateV2Pair.tsx
- src/state/migrations.test.ts
- src/state/migrations.ts
- src/state/migrations/2.test.ts
- src/state/migrations/2.ts
- src/state/reducer.ts
- src/state/routing/slice.ts
- src/state/routing/types.ts
- src/state/routing/utils.ts
- src/test-utils/constants.ts
This PR removes the ability to force using client-side SOR. Users will now only use SOR in the case where the routing-api request fails.
| Mainnet | L2s | Polygon |
|---------|-----|---------|
|<img width="431" alt="image" src="https://github.com/Uniswap/interface/assets/59578595/2595e76e-c53e-40f5-a0f3-0011c3ed7116">|<img width="419" alt="image" src="https://github.com/Uniswap/interface/assets/59578595/d5ece6e0-a791-4a10-a9c1-3a4d5c9951a3">|<img width="379" alt="image" src="https://github.com/Uniswap/interface/assets/59578595/80143d1c-4bbb-44e7-a105-745002818a0e">|
| Mainnet | L2s | Polygon |
|---------|-----|---------|
|<img width="605" alt="image" src="https://github.com/Uniswap/interface/assets/59578595/e018ba15-a786-4481-85c9-363b52c85d2c">|<img width="605" alt="image" …
> feat: Remove local routing setting

- src/constants/misc.ts
- src/state/migrations.test.ts
- src/state/migrations.ts
- src/state/migrations/1.test.ts
- src/state/migrations/1.ts
- src/state/reducer.ts
copy of https://github.com/Uniswap/interface/commit/aee4df10a87c4d2bba2a21161ee595b47303ce6b
> fix: change default tx deadline to 10m (#7451) [hotfix for prod]

- src/components/AccountDrawer/MiniPortfolio/Pools/index.tsx
- src/components/PositionPreview/index.tsx
- src/components/RoutingDiagram/RoutingDiagram.tsx
- src/constants/misc.ts
- src/graphql/data/nft/NftBalance.ts
- src/hooks/useSwapTaxes.ts
- src/pages/PoolDetails/PoolDetailsHeader.tsx
- src/utils/computeFiatValuePriceImpact.tsx
- src/utils/prices.ts
replaces hardcoded usage of 10000 as bips base w/ a constant
> refactor: use bips base constant

- .github/workflows/1-main-to-staging.yml
failing action: https://github.com/Uniswap/interface/actions/runs/6512256939/job/17689537081
the dependencies aren't installed in this CI action, so we can't rely on xml2js ? reverting now to unblock release and will follow up with a fix
> fix: remove sitemap step from ci

- src/constants/lists.ts
replaces the ipfs gateway url to cloudflare's. this should help us get around the `ERR_CERT_COMMON_NAME_INVALID` error that we were sometimes getting
_Slack thread:_ https://uniswapteam.slack.com/archives/C047U65H422/p1697472005682969
test that the new URL is successfully fetched, on the preview URL
> fix: use a different ipfs gateway

- src/hooks/useSwapTaxes.ts
- If you try to use `useSwapTaxes` with only an `inputTokenAddress` you'll currently need to include a secondary argument of just `undefined`. This update allows you to not need that second argument.
> refactor: allow missing input for useSwapTaxes

- src/pages/MigrateV2/MigrateV2Pair.tsx
Knocking out ticket https://linear.app/uniswap/issue/WEB-3039/hey-there-is-a-missing-space-in-the-migrate-v2-liquidity-page
> fix: add space to migrateV2 link

- src/components/Tokens/TokenTable/NetworkFilter.tsx
* scrollbar ugly -> scrollbar not ugly
* changed border radius because thats currently how it is displayed in the app and there is no good way on gods green earth to add a margin to the side of a webkit scrollbar
Before (Chrome):
Before (Firefox):
After (Firefox):
After (Chrome):
After (Safari):
> fix: fixing ugly scrollbar

- src/utils/getExplorerLink.ts
- getExplorerLink had a syntactical split between arbitrum and the rest of the chains which seems like a no longer needed artifact as arbiscan follows the same format as the rest of the explorers
- This led to the explorer link on TDPs for arbitrum tokens to go to the contract address explorer instead of the token address explorer
- proof of token routing https://arbiscan.io/token/0x912ce59144191c1204e64559fe8253a0e49e6548
- there was also a bug with the explorer link for optimism block numbers that this fixes. you can see this by tapping on the bottom right Polling interval when on Optimism on this branch vs on main
- OP block explorer https://optimistic.etherscan.io/block/111634636
> refactor: clean up getExplorerLink helper fn

- src/hooks/useUniversalRouter.ts
We weren't using this `error` field, and it was logging every individual object property as a separate field, so let's remove it from logging here.
> feat: Remove logging whole error object for analytics

- src/hooks/useAutoSlippageTolerance.ts
* implements tina's idea to reuse the same routing-api result from the previous useUsdPrice call as explained in slack here: https://uniswapteam.slack.com/archives/C047U65H422/p1698868768687079
> chore: converting useStablecoinPrice to useUsdPrice in autoslippage

- src/connection/WalletConnectV2.ts
!! this should not be merged until uniwallet v1.15 is released !!
just updates the WalletConnect URI schema as requested by the mobile team. see the slack message below for details. according to that message, this new schema will result in the behavior:
* If the user doesn't have the wallet app, it opens the URL in the browser, which has the link to download the app.
* If the user has the wallet installed and reads the QR code with the camera app, it'll launch the app and show the WalletConnect sheet (after the fix above is live).
* If the user reads from the wallet's scan screen, it'll show the WalletConnect sheet (after the fix above is live).
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2982/update-the-url-for-wc-scan …
> fix: update uniwallet wc link

- src/graphql/data/nft/CollectionSearch.ts
- `nftCollections` query with an invalid address, such as an erc20 address, is returning a mostly null object which is being shown in the searchBar suggestions
- BE team has been notified but in the interim we can make a quick UX fix to hide nft address search results with 0 items
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-3068/when-you-paste-in-a-token-address-it-creates-a-dummy-nft-collection
_Slack thread:_ https://uniswapteam.slack.com/archives/C04QKTF9T35/p1699376536927179
> fix: hide invalid nft collections with 0 items from search bar

- cypress/e2e/add-liquidity.test.ts
- src/components/Pools/PoolDetails/PoolDetailsHeader.test.tsx
- src/components/Pools/PoolDetails/PoolDetailsLink.test.tsx
- src/components/Pools/PoolDetails/PoolDetailsStats.test.tsx
- src/components/Pools/PoolDetails/PoolDetailsStatsButtons.test.tsx
- src/components/Pools/PoolDetails/__snapshots__/PoolDetailsLink.test.tsx.snap
- src/components/Pools/PoolDetails/__snapshots__/PoolDetailsStats.test.tsx.snap
- src/lib/hooks/useCurrency.ts
- src/pages/PoolDetails/__snapshots__/index.test.tsx.snap
- src/pages/PoolDetails/index.test.tsx
fixes an issue on the `/add` page where token selections from the previous chain persist to the new chain, and are displayed as "UNKNOWN" ...
my fix here is to disallow any "unknown" tokens since they likely don't exist. an "unknown" token is one where we couldn't get valid decimals/name/symbol from the onchain call.
the token state on this page is actually managed via the URL route and is actually hard to change. (i tried using react router to reset the state in many different ways, but couldn't get it working). 
we might want to consider moving away from URL-based state management on this page at some point, but i wanted to submit this simpler fix as a short term solution.
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-3014/if-you-change-network-in-create-position-it-doesnt-clear- …
> fix: reset token selections when  changing chains on /add

- src/state/migrations.test.ts
- src/state/migrations.ts
- src/state/migrations/4.test.ts
- src/state/migrations/4.ts
- src/state/reducer.ts
* we removed German from supported locales so we need to flush redux locale storage for users that have German set as their preferred language
> fix: redux migration to flush german locale

- src/components/AccountDrawer/MiniPortfolio/PortfolioLogo.tsx
- src/components/AccountDrawer/MiniPortfolio/__snapshots__/PortfolioLogo.test.tsx.snap
- src/components/Tokens/TokenTable/TokenRow.tsx
- src/components/Tokens/TokenTable/__snapshots__/TokenRow.test.tsx.snap
_Linear ticket:_ https://linear.app/uniswap/issue/WEB-3047/token-table-icon-and-text-misaligned
| <img width="284" alt="image" src="https://github.com/Uniswap/interface/assets/39385577/db118f45-707e-45f7-81bf-9a2f11b3caa8"> | <img width="282" alt="Screenshot 2023-11-14 at 2 05 45 PM" src="https://github.com/Uniswap/interface/assets/39385577/66b43146-2e97-4aa2-93fa-a02b82c8c28a"> |
(logo is align w/ text now, l2 icon is slightly further right & down, and gap is slightly increase to account for l2 icon changes)
> fix: portfolioLogo alignment

- src/components/FeatureFlagModal/FeatureFlagModal.tsx
- src/components/swap/SwapBuyFiatButton.tsx
- src/components/swap/SwapHeader.test.tsx
- src/components/swap/SwapHeader.tsx
- src/components/swap/__snapshots__/SwapBuyFiatButton.test.tsx.snap
- src/components/swap/__snapshots__/SwapHeader.test.tsx.snap
- src/featureFlags/flags/limits.ts
- src/featureFlags/index.tsx
- src/pages/Landing/__snapshots__/index.test.tsx.snap
- src/pages/Swap/index.tsx
add feature flag for limits and refactor the swap UI a little bit to allow for the new tab.
_Relevant docs:_ https://www.notion.so/uniswaplabs/Limit-orders-kickoff-936d6300ef7844958851273babe89886
https://github.com/Uniswap/interface/assets/66155195/c689ba83-ca26-4a9f-a974-e9b580d61c3a
> feat: swap component refactor limits

- src/state/routing/gas.ts
We are way off for gas estimates for Arbitrum approvals, so disable until we fix
| <img width="533" alt="image" src="https://github.com/Uniswap/interface/assets/59578595/fb6b9308-de46-404c-824b-e201f5cc78f0"> | <img width="692" alt="image" src="https://github.com/Uniswap/interface/assets/59578595/c501ddce-9cf9-4df8-a234-4010640159bd"> |
> fix: disable showing approve cost for arbitrum

- src/components/swap/ConfirmSwapModal.tsx
Fixes issue where wrap amount for eth-input uniswapx trades was getting truncated by formatter function, resulting in an insufficient amount getting wrapped in some cases.
> fix: don't format uniswapx wrap amount [hotfix]

- src/components/swap/ConfirmSwapModal.tsx
Fixes issue where wrap amount for eth-input uniswapx trades was getting truncated by formatter function, resulting in an insufficient amount getting wrapped in some cases.
> fix: don't format uniswapx wrap amount [staging]

- src/components/swap/ConfirmSwapModal.tsx
Fixes issue where wrap amount for eth-input uniswapx trades was getting truncated by formatter function, resulting in an insufficient amount getting wrapped in some cases.
> fix: don't format wrap input amount

- cypress/e2e/swap/uniswapx.test.ts
- src/components/swap/ConfirmSwapModal.tsx
This fixes it an issue where the input currency would request WETH trades and would revert to classic swaps bcuz not enough user balance yet :)
https://github.com/Uniswap/interface/assets/59578595/531e2482-ad2d-44ad-8c2b-0401f5854ab3
- Try a small ETH input swap (larger amounts will always remain as UniswapX because of some tricky technical reasons.. DM me for more info)
manually tested
added e2e test
> fix: only change input currency to weth after eth wrap completes for uniswapx eth input trades

- src/pages/Swap/index.tsx
There's may still be a cached `trade` when the swap input becomes a wrap, so don't show the USD price difference in that case.
https://github.com/Uniswap/interface/assets/59578595/d35d50cb-b6e4-4382-9b74-f8ce4d029822
> fix: dont show USD price difference for wraps

- src/components/Banner/AndroidAnnouncementBanner/index.tsx
- src/utils/openDownloadApp.ts
DownloadButton, which is nested in TextContainer, is bubbling up its onClick to the textcontainer - causing problems. Need to prevent event from bubbling up to parent TextContainer.
> fix: android banner DownloadButton onClick should not propagate up
