src/assets/images/dropup-blue.svg, src/components/AddressInputPanel/address-input-panel.scss, src/components/CurrencyInputPanel/currency-panel.scss, src/components/CurrencyInputPanel/index.js, src/components/Header/header.scss, src/components/Header/index.js, src/components/TokenLogo/index.js, src/components/Web3Status/web3-status.scss, src/pages/Pool/AddLiquidity.js, src/pages/Send/index.js, src/pages/Swap/index.js, src/pages/Swap/swap.scss
* Input Field should preselect to ETH - helps have a single focus for next step
* If input is 0, text should say invalid amount or show the input error state. CTA should be disabled
* token icon should be smaller
* .web3-status padding should be .5rem all around
* CTA button should be disabled if not unlocked
* helper text if not unlocked "Unlock OMG to continue"
* Token address needs space
* Text size too small (recipient text)
* Needs to be disabled until recipient is filled out
* Refactor Send
* Context Help to the Bottom
* Change scroll area so that both switcher and CTA will scroll
* Hardcode Token Icon on test net
* when swapping DAI to ETH, min and max is the same because ETH is so much bigger
* only allow number greater than 0 for currencyInput
* contextual min/max should show …
=> Design feedback

src/components/CurrencyInputPanel/index.js
Forgot to push this up.
We need to add the extra allowance !== zero because if the allowance is 0 and the value is 0 then the unlock button won't show which is not what we want.
=> Fix approvals

src/pages/Pool/AddLiquidity.js
This oneliner should resolve the initial addLiquidity call surfaced by @haydenadams earlier today.
https://kyokan.slack.com/archives/GD4QV3RE0/p1540838490001500
Uses the same `.isNewExchange()` check as done in `minLiquidity`
/cc @chikeichan
=> Fix max_tokens for initial liquidity provider

src/pages/Pool/AddLiquidity.js
The exchange rate now doesn't show if there's no label now.
=> Don’t render exchange if no label

src/pages/Pool/RemoveLiquidity.js
The exchange rate for `Remove Liquidity` is now the same as `Add Liquidity`
=> Normalize remove liquidity exchange rate

src/components/ContextualInfo/contextual-info.scss, src/components/CurrencyInputPanel/currency-panel.scss, src/components/Header/header.scss, src/index.scss, src/pages/App.js, src/pages/App.scss, src/pages/Pool/index.js, src/pages/Pool/pool.scss, src/pages/Send/index.js, src/pages/Swap/index.js
device-width is deprecated and only works in chrome it seems. reworked to use regular min/max-width queries for both scss & react-responsive. submitted a ticket to react-responsive to fix
=> fix issue w/ responsiveness due to media querie

src/components/CurrencyInputPanel/currency-panel.scss
reverting this font-weight change because it’s really ugly @mikedemarais
=> fix too thin font-weight in currency-panel

package.json
As mentioned in the issue, accessing `/create-exchange/<address>` in production results in a crash:
https://uniswap.exchange/create-exchange/0x4a57E687b9126435a9B19E4A802113e266AdeBde
PR preview:
https://deploy-preview-335--uniswap.netlify.com/create-exchange/0x4a57E687b9126435a9B19E4A802113e266AdeBde
=> fix: incorrect homepage path in package.json

src/components/ExchangePage/index.jsx, src/utils/index.js
- allow users to enter 'ETH' as output currency (only valid if input currency is set to not ETH)
- change digit display to 6 digits on exchange rate (fix for now until sig figs)
=> Allow for ETH in output command, update to 6 digits on exchange rate

public/locales/en.json, src/constants/index.js, src/pages/Pool/AddLiquidity.js
- Fixes #336 
- added custom warning and disable button when trying to add liquidity for broken tokens
- using a hard coded list for now of broken tokens
=> create warning and disable add liquidity button for broken tokens

src/hooks/index.js
It seems web3-react v6 uses `chainId` instead of `networkId`, but the `useFactoryContract` Hook is still deconstructing the old field. Here's a [CodeSandbox](https://codesandbox.io/s/web3-react-v6-gv56z) that proves it (see the logs).
=> Replace networkId with chainId

src/components/AccountDetails/index.js
Not sure if this is a bug, but I noticed that in all components `useWeb3React` is imported from the local hooks folder, not from the `@web3-react/core` package, except for `AccountDetails`.
=> Import useWeb3React from the hooks folder

src/components/TransactionDetails/index.js
On Firefox (maybe other browsers as well) the lack of min-width results in the default `input` element min-width which is ~92px.  This results in the flex container overflowing the bounding element.  By setting min-width to 20px, the box will instead grow to fill the available space, which is defined by its parent that has the pink border.  This avoids the overflow issue (as long as the parent doesn't get too small, which it won't at the moment since it is fixed size).
Without `min-width` set in Firefox:
With `min-width` set in Firefox:
=> Adds min-width to custom slippage input.

src/hooks/index.js
When users can access the dapp only on mainnet, the "useENSName" Hook behaves correctly, but if you enable any other network, you get this error:
```
Uncaught (in promise) Error: network does not support ENS (operation="ENS", network="kovan", version=4.0.40)
at Object.n [as throwError] (ethers.min.js:557)
at ethers.min.js:5293
```
The reason is that ENS runs only on mainnet and the error thrown by ethers.js is never caught. The PR changes the try/ catch block with a `.catch(() => {})` handler.
=> Fix "useENSName" Hook

src/components/CurrencyInputPanel/index.js
This adds an opinionated sort to the `filteredTokenList` to prioritize `DAI` when a user inputs `DAI` into the token search.
Previous:
New:
=> Prioritize exact token symbol matches

README.md
Hey all, was setting up the frontend locally and noticed that the variable change in the `.env.local.example` (from #621) renamed `REACT_APP_NETWORK_ID` to `REACT_APP_CHAIN_ID` but the README still references the old variable name so addressing that documentation fix here
=> Update local env setup documentation

src/components/SearchModal/index.tsx
- Show part of the next token to indicate to user that list is scrollable
=> change results height on search modal

src/components/CurrencyInputPanel/index.tsx, src/components/NumericalInput/index.tsx
fixes a language localization problem where some mobile users were unable to type period as their decimal separator
=> replace commas with periods

src/constants/tokens/mainnet.ts
https://www.augur.net/blog/v2-launch/
TL;DR: Augur v2 launch is coming up and will introduce a new REP token.  FF has requested all exchanges rename REP to REPv1 to avoid confusion.
Going forward, REP tokens will contain versioning in their name/symbol on chain so this should be a one-time "fix" for Augur v1 REP.
=> Renames REP to REPv1.

src/components/TokenWarningCard/index.tsx, src/utils/index.test.ts, src/utils/index.ts
I think it makes more sense to view a token page rather than an address page
Example:
https://etherscan.io/token/0x85eee30c52b0b379b046fb0f85f4f3dc3009afec
vs
https://etherscan.io/address/0x85Eee30c52B0b379b046Fb0F85F4f3Dc3009aFEC
=> improvement(token warning card): link to the token page on etherscan instead of the address page

src/components/Menu/index.tsx
The discord invite link in the dropdown menu on uniswap was dead.  I replaced it with the working on off of the docs site.
**PLEASE DO NOT SUBMIT TOKEN ADDITIONS AS PULL REQUESTS**
All token requests should be made via an issue.
=> Updated dropdown menu index.tsx

src/constants/lists.ts
Based on https://github.com/Uniswap/token-lists/issues/17
This PR proposes to replace the CoinGecko tokens list with the `all.json` which is more up to date and complete than the initial version
=> Replace CoinGecko tokens list with all.json

src/constants/index.ts, src/pages/Vote/VotePage.tsx
Proposals currently last 40,320 blocks, which equates to exactly 7 days at 15s block times.
However, the [Muir Glacier fork](https://blog.ethereum.org/2019/12/23/ethereum-muir-glacier-upgrade-announcement/) in early 2020 decreased the average block time to [somewhere between 13-13.5s](https://etherscan.io/chart/blocktime). This equates to proposals lasting approximately 6.5 days or less. This may confuse people who rely on the UI to wait until the last minute to vote on a proposal.
This PR adds a more accurate (~10%) time when displaying the approximate end of the proposal. It leaves room for variance in block times by assuming 14s block times instead of the more accurate 13-13.5s so that the proposal display time has never passed before a proposal is actually over.
=> improve displayed proposal end time accuracy

src/state/governance/hooks.ts
The current implementation attempts to parse out the title from the description in the event logs, in the spirit of returning `title` and `description` as separate parsed out fields.
Unfortunately, the current implementation is quite fragile to the precise way in which the description is formatted, leading to situations where the returned description is improperly formatted — or not present at all (as demonstrated [here](https://app.uniswap.org/#/vote/2))
=> Remove title parsing from description output

tsconfig.json
Closes #1184
This PR sets `src` as `baseUrl` for typescript. This way, you can use absolut paths for importing. 
For example:
```
// You can change this
// import Header from '../components/Header'
// into this
import Header from 'components/Header'
```
For context https://create-react-app.dev/docs/importing-a-component
=> Allow absolute imports

src/components/Popups/ListUpdatePopup.tsx
Depending on how long a user waits between visits to uniswap, changes to the selected token list can accumulate. The current popup does not allow scrolling so the user can end up in a situation where they cannot accept or decline the most recent list because the buttons are outside of the view port.
This PR puts a limit on the height of the pop up and enables scroll if needed.
Before: 
After:
=> fix(list popup): big token list updates scroll issue

src/constants/index.ts
In the pool tab, when viewing your pooled wBTC balance, the number is off by a factor of 10. This is due to the decimal being set incorrectly in `src/constants/index.ts`.
=> fix: bug causing wbtc pooled amount to be off by a factor of 10

src/constants/index.ts, src/constants/proposals/index.ts, src/constants/proposals/uniswap_grants.ts, src/state/governance/hooks.ts
As title. Also includes the Uniswap grants proposal, since its description was fudged. https://gov.uniswap.org/t/rfc-uniswap-grants-program-v0-1/9081.
Overriding a proposal is as simple as adding it in the `constants/proposals` directory and exporting it via the PRELOADED_PROPOSALS map with its proposalId.
=> feat: allow overriding proposals in the UI

src/hooks/Tokens.ts
- if you paste certain tokens the ethers string parsing library errors out because no null terminator is found in symbol or name 
- example -> https://etherscan.io/address/0xbb9bc244d798123fde783fcc1c72d3bb8c189413#readContract
- see parsing logic here https://github.com/ethers-io/ethers.js/blob/master/packages/strings/src.ts/bytes32.ts
=> fix (string parsing error): catch error in bytes32 string parsing

src/components/SearchModal/ImportList.tsx, src/components/SearchModal/ImportToken.tsx, src/state/lists/updater.ts
- before only active lists were being updated, update all if loaded into lists
- make import token and list views scrollable on small screens
- fix typo in import
=> fix(modal cutoff, lists): make modal scrollable on small screens, fix typo, auto update all lists

yarn.lock
was getting some warnings about this being out of date
```
Target browser changes:
- and_chr 84
+ and_chr 88
- and_ff 68
+ and_ff 83
- and_qq 10.4
- chrome 83
- chrome 81
- chrome 80
- chrome 79
+ chrome 87
+ chrome 86
+ chrome 85
+ chrome 84
- edge 83
- edge 18
+ edge 87
- firefox 77
- firefox 76
+ firefox 84
+ firefox 83
- ios_saf 13.4-13.5
- ios_saf 13.0-13.1
- ios_saf 12.0-12.1
+ ios_saf 14.0-14.3
+ ios_saf 13.4-13.7
- opera 68
+ opera 72
- safari 13
- safari 12.1
+ safari 14
- samsung 11.1-11.2
+ samsung 13.0
```
=> run npx browserslist@latest --update-db

src/components/Modal/index.tsx
Refer to https://github.com/Uniswap/uniswap-interface/pull/1205
=> fix: modals stealing focus across frames

.github/workflows/release.yaml
=> [CI] Add Pin to Crust workflow

src/constants/index.ts
Reduction in routing pairs reduces the routing search space.
1. remove [MKR](https://info.uniswap.org/token/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2) ($15mm liquidity)
2. remove [COMP](https://info.uniswap.org/token/0xc00e94cb662c3520282e6f5717214004a7f26888) ($4mm liquidity)
=> fix(swap): restrict the routing space to not consider multihop via MKR or COMP

src/pages/Vote/VotePage.tsx, src/pages/Vote/index.tsx, src/pages/Vote/styled.tsx, src/state/governance/hooks.ts
Integer enum used for tracking proposal state in proposal data. Text values are derived from inverse key, value pairs in enum (e.g. ProposalState[0] will evaluate to 'Pending').
This means text values passed to components aren't lowercased anymore, but since styles are now derived from the enum values themselves and the display text is uppercased later, this doesn't cause any changes to the UI.
=> use enum for enumerateProposalState #1166

src/pages/Pool/PositionPage.tsx
Disabled NFT SVG animation, only enabled on hover
The animated SVG was causing serious performance issues because of the many layout changes. We should consider changes the SVG definition, but for now, this PR disables animations until hover.
The solution is to snapshot the SVG state onto a static canvas and show that canvas. On hover, show the actual image.
Other approaches considered:
- SVGSVGElement.pauseAnimations(): unfortunately, the SVG is received as a data:img payload, and inserting it on the page would not be safe
- Stopping CSS animations: CSS animations are not used in the SVG
Testing:
- Performance was monitored in Activity Monitor
- Low CPU usage, spike on hover, returns to low usage on leave
✅ macOS: Chrome, Firefox, Safari
✅ Android:  Chrome (animates on tap, stops on tap …
=> Fix NFT SVG performance issue in browser

src/pages/Pool/PositionPage.tsx
this PR removes the image jump on mouseExit
i'm pretty sure there is also a way to save the src on mouseExit and re-hydrate it on subsequent mouseEnter, but I haven't figured it out yet...
=> clean up svg animations

src/state/mint/v3/utils.ts
- right now if user types in price above/below the min/max ratio for a pool the price -> conversion logic crashes
- to handle this, check for this case and return min/max values instead when parsing the input
- fixes #1571
=> fix: update tick parsing to handle min/max prices

src/hooks/useV2Pairs.ts, src/state/mint/hooks.ts
fixes #1583
IUniswapV2Pair.getReserves() returns a 'valid' pair for some tokens (see #1583). However, the reserves are both set to 0 whhich leads to a division by zero down the line.
Fix suggested is to consider a pair where both reserves are 0 as NOT_EXISTS.
=> fix: division by 0 error when both reserves are 0

src/components/CurrencyInputPanel/index.tsx
The "outside of your specified range" text in the add liquidity UI needs padding. I've added a horizontal padding of `12px` so the text isn't squished on the sides.
This PR addresses #1693.
=> fix: add padding to price outside of range

src/components/SearchModal/ImportList.tsx, src/components/SearchModal/ManageLists.tsx, src/state/hooks.ts
create new hooks useAppDispatch and useAppSelector that have types embedded
keeping this PR small, will make the change to other files in a follow-up
=> chore: simplify redux types with ts inference

src/pages/Swap/index.tsx
It seems like during the i18n improvements (#1692 ) that a space had been [removed](https://github.com/Uniswap/uniswap-interface/pull/1692/files#diff-d2d2d34074b22ac06988a155c74cca892a97f5bb4e343d933a1a4f357d4bf888R468) for the `backToV3` swap button text causing a small visual regression.
**Before:** a missing space results in the text "Back toV3"
**After:** adding a space results in the text "Back to V3"
=> fix: add space to backToV3 swap button

src/hooks/Tokens.ts
`ExtendedEther.onChain` creates a new object from 'ETH' which causes dependencies to re-render
=> fix: memoize extendedEther to unnecessary rerenders

src/components/Modal/index.tsx
fixes #1909
fixes #1691
modal currently only have scrolling behavior on mobile but we got a few issues that desktop users with short windows cannot access buttons at the bottom of modals.
=> fix: allow modal scrolling on desktop

package.json, src/state/application/actions.ts, src/state/application/reducer.test.ts, src/state/application/reducer.ts, src/state/application/updater.ts, src/state/data/slice.ts, yarn.lock
Note. Will add non-mainnet chain urls in a follow-up cl
Queries against unsupported chain id will return an error. Queries should be built to handle this error.
=> feat: handle chain id in subgraph api

src/components/FeeSelector/index.tsx
removes the loading spinner which was hiding the 'edit/show' buttons.
=> fix: allow fee tier selection during data fetching

src/pages/AddLiquidity/index.tsx
Previously, `set price range` was duplicated when there was liquidity:
=> fix: remove duplicate `set price range` title when there is liquidity

package.json, yarn.lock
Update WalletLink and @web3-react/walletlink-connector to latest version
This will fix an error caused by unbound `this` when switching networks on Coinbase Wallet mobile apps.
=> fix: Update WalletLink and @web3-react/walletlink-connector

src/pages/AddLiquidity/index.tsx
If field A and field B are already populated, chances are the user wants them to remain the same and only wants to invert the price range selector.
The conversion isn't exact, but should be preferable to the previous behavior.
=> fix: toggle liquidity position when toggling rates

src/components/Header/index.tsx
This is to fix #2124  to remove setting the width, otherwise on small enough screens (Galaxy Fold 280px) the header would get cut off on the edges.
=> fix: update mobile header to fix overflow

src/hooks/useBestV3Trade.ts
note. will update integration tests as a follow-up. We will probably need to set up the mainnet fork in integration tests to make this workable.
=> fix: avoid running BestV3Trade when tokens are the same

package.json, src/connectors/index.ts, yarn.lock
Known Issues:
- Doesn't visually disconnect on the UI when the app user disconnects manually (not possible to handle in current `ethereum-provider` impl.: https://github.com/WalletConnect/walletconnect-monorepo/blob/v1.0/packages/providers/ethereum-provider/src/index.ts)
=> fix: use `@walletconnect/ethereum-provider` instead of `@walletconnect/web3-provider`

package.json
Fixes #2198. Touching en-US.po before extracting messages prevents lingui from adding a creation date, maintaining deterministic builds and IPFS hashes.
=> chore(i18n): touch en-US to prevent lingui from adding a creation date

src/utils/contenthashToUri.ts
Updates deprecated method `getCodec` to use `getNameFromData`.
=> chore: update multicodec usage

package.json, yarn.lock
redux-devtools-extension integration is already provided through @reduxjs/toolkit.
=> chore: rm redux-devtools-extension

src/components/Header/NetworkCard.tsx, src/components/Header/index.tsx
Makes the user's ETH balance non-selectable: no pointer-events and no user-select.
Makes the fallback network display (for non-MetaMask providers) non-selectable.
=> fix: make non-interactive header elements unselectable

src/components/Header/Polling.tsx
Adds a en-space to StyledPollingNumber so it is always painted. Fixes a layout shift when rendering the first block number.
StyledPollingNumber is taller than its container, so waiting to paint it causes a layout shift when rendering.
=> fix: always paint StyledPollingNumber

src/components/CurrencyInputPanel/index.tsx, src/components/CurrencyLogo/index.tsx, src/components/swap/UnsupportedCurrencyFooter.tsx, src/hooks/Tokens.ts, src/hooks/useIsSwapUnsupported.ts, src/hooks/useWrapCallback.ts, src/pages/Swap/index.tsx, src/state/swap/hooks.ts, src/state/swap/reducer.ts
Avoids a flash of "Select a token" on the input currency selector as the App initializes (and/or the output currency selector, if an inputCurrency/outputCurrency parameter is passed).
=> fix: do not paint currency selector until initialized

src/state/logs/hooks.ts, src/state/logs/utils.ts
`keyToFilter` had a bug fixed in that branch
=> fix: cherry pick the logs hook fix from the liquidity incentives branch

package.json, src/hooks/useBestV3Trade.ts, src/state/multicall/hooks.ts, yarn.lock
uses the new features introduced [here](https://github.com/Uniswap/uniswap-v3-sdk/pull/76) to format calldata passed to the quoter, as opposed to doing it manually.
as side effects:
- introduce new method `useSingleContractWithCallData` to call functions via multicall directly from encoded calldata. note: unlike `useSingleContractMultipleData`, this new method can call any number of different functions.
- as a cleanup, make `useSingleCallResult` a wrapper over `useSingleContractMultipleData`
=> feat: use SDK to format calldata passed to quoter

src/hooks/useFeeTierDistribution.ts, src/hooks/usePoolTickData.ts
adjust freshness params for l2s
I don't think we need to differentiate between l2 and l1 right now
=> fix: increase max block age for l2s

src/constants/misc.ts, src/hooks/web3.ts
Improves non-iframe pageload by 300ms. Fixes #2338.
The Gnosis check for a SafeApp races a postMessage and a 300ms timeout ([src]). The SafeApp embeds the interface in an iframe, so this avoids the check when not in iframes.
[src]: https://github.com/gnosis/safe-apps-sdk/blob/f224869dd5ae810db8cecad08fbbcfaa6c046d9d/packages/safe-apps-web3-react/src/connector.ts#L52
=> fix: only try SafeApp connection in an iframe

src/hooks/useActiveLocale.ts, src/hooks/useParsedQueryString.ts, src/i18n.tsx
Eagerly loads the active locale asset as soon as it is known, instead of waiting for React to bootstrap.
A continuation of #2204.
=> feat(i18n): initialize locale before React

src/utils/getTokenList.ts
Removes 125kb from main chunk. Moves ~90ms off of the critical pageload path.
=> feat: lazily load token list validator

package.json, src/components/Identicon/index.tsx, yarn.lock
This PR adds robust avatar image lookup support for ENS `avatar` text record lookup for the logged in user's avatar, using the [@davatar/react](https://github.com/TBDAO/davatar-helpers/tree/master/packages/react) package, which seeks to fulfill the spec outlined in [avatars.md](https://gist.github.com/Arachnid/9db60bd75277969ee1689c8742b75182).
Presently, we support all URI types except the NFT-metadata reference type, although that one is planned in a future package release. Our goal is to push forward usage of decentralized avatars using ENS, and this PR works toward making sure as people do so, they see their chosen avatar in the Uniswap app!
The component defaults to a Jazzicon, exactly as Uniswap currently behaves today, so if no avatar has been set by the user on their ENS reverse …
=> feat: add @davatar/react for robust avatar support

package.json, src/components/analytics/GoogleAnalyticsReporter.tsx, yarn.lock
Adds web vitals to our GA metrics so they can be tracked in the field, and not just in the lab (ie via Lighthouse or https://web.dev/measure). Along with being a good metric for page performance, web vitals are used to determine Google Search ranking (https://developers.google.com/search/blog/2021/04/more-details-page-experience#details).
=> feat: report web-vitals to ga

src/components/Header/index.tsx, src/components/Web3Status/index.tsx
- Inlines the logo SVG so it renders with no additional fetches
- Renders "Vote" link in navbar while awaiting connection to avoid layout shift
- Renders "Connect to a wallet" while awaiting connection to improve LCP
=> perf: render components on first frame

.eslintrc.json, src/hooks/useFeeTierDistribution.ts
Removing `from 'lodash'` reduces the uncompressed vendor bundle by 69.93 KB.
=> perf: import lodash only as modules

yarn.lock
Deduplicates packages, but has no effect on bundle size. These packages are used for build steps or for typings.
=> chore: dedup packages

.eslintrc.json, src/components/SearchModal/ImportToken.tsx, src/hooks/web3.ts, src/state/data/slice.ts, src/state/lists/reducer.ts, src/state/lists/wrappedTokenInfo.ts, src/state/mint/v3/hooks.ts, src/state/mint/v3/utils.ts, src/utils/index.ts
Effectively removes a full (non-tree-shakeable) copy of @uniswap/v3-sdk from the bundle, reducing the uncompressed vendor bundle by 0.21 KB (11.9%).
Importing from `dist/` may bundle a library twice (as with @uniswap/v3-sdk) because it is pulled from the package.json-specified entry point, as an ES module; and again when imported from `dist/`, as CommonJS. `dist/` is an implementation detail, and should not be accessed directly. The CommonJS library is also not tree-shakeable, so importing from `dist/` is effectively a larger import.
=> chore: restrict imports from dist

package.json, src/components/LiquidityChartRangeInput/Area.tsx, src/hooks/useColor.ts, yarn.lock
Updates node-vibrant to use a webpack-compatible version.
lodash was implicitly installed through node-vibrant (and its lack of tree-shaking); with this fixed, lodash is no longer provided.
=> chore: rm lodash

package.json, yarn.lock
There was a small bug identified in the library when ERC721/1155 token URIs were provided in uppercase, while The Graph expects lowercase contract IDs. This patch version fixes that bug and ensures IDs are all in lowercase.
=> fix: upgrade @davatar/react to 1.6.2, minor fix for ERC token URIs

src/pages/Swap/index.tsx
Changed "Remove send" to "Remove recipient" for clarification purposes. This also aligns better with the language used in the code itself. I guess it's also a good preparation for the future in case this feature is [re-added in v3](https://github.com/Uniswap/interface/issues/1440).
=> style: Clarify "Remove send" button in v2 interface

src/constants/tokens.ts, src/hooks/useClientSideV3Trade.ts
- USDC address was incorrect 
- quoter default has value was causing multicall errors 
- this 16M number is fairly arbitrary - would be nice to get a real estimate
=> fix: update gas quote for arbitrum and USDC address

src/state/routing/types.ts
add fields missing in `GetQuoteResult` and simplifies types.
ideally `QuoteResponse` would be exposed in `smart-order-router`. For now, re-create it in the interface.
https://github.com/Uniswap/routing-api/blob/41eef5cb3cdf08739aa813c4532fddc69b7566ec/lib/handlers/quote/schema/quote-schema.ts#L84
=> fix: improve routing slice types

package.json, yarn.lock
Updates walletlink-connector to 6.2.8 which bumps walletlink to a version that handles addEthereumChain+switchEthereumChain requests
=> fix: Update walletlink-connector to 6.2.8

src/components/Menu/index.tsx
@callil ptal I added Help Center to the menu. It got so long that a scroll bar appeared (see screenshot), so I deleted Analytics because we have that in the Chart tab in the header. Wdyt?
Other options
- we could also extend the height of the menu with no scroll bar
- we could selectively hide the Claim UNI button, but that's a bit more complex
for a quick fix this seems optimal
https://github.com/Uniswap/interface/issues/2130
=> feat: Menu update. Add help center & feature requests. Remove analytics & github.

src/hooks/useV3SwapPools.ts
- chore: add support for 0.01% tier
- only show 1bps on mainnet
- rename VERY_LOW to LOWEST
- upgrade to v3-sdk 3.7.0
- consider 0.01% tier in pool
=> fix: support 0.01% fee tier in client side router

package.json
There are two errors when deploying on Windows systems:
1. Using single quotes in path argument doesn't seem to be accepted in typechain command
2. `?(v3-core|v3-periphery)` operator doesn't work
Here are fixes/workarounds.
=> refactor: make package.json scripts run on Windows

package.json, src/abis/erc1155.json, src/abis/erc721.json, src/components/AccountDetails/index.tsx, src/components/Identicon/StatusIcon.tsx, src/components/Identicon/index.tsx, src/components/Web3Status/index.tsx, src/hooks/useContract.ts, src/hooks/useENSAvatar.ts, src/utils/uriToHttp.ts, yarn.lock
- Replaces @davatar/react so that interface arch can be leveraged
=> feat: display an ENS avatar

src/components/Identicon/index.tsx
Use `useRef`/`useLayoutEffect` to manipulate the DOM, instead of a ref-callback.
- Avoids unmounting the whole jazzicon span instead of just replacing the inserted DOM element.
- Avoids using a ref-callback for an undocumented purpose (DOM mutation), which is explicitly scoped to `useLayoutEffect` in the documentation.
=> refactor: use ref for jazzicon

src/utils/uriToHttp.ts
There was a typo left from a copy pasta when adding arweave support in URI resolution. I've received reports the ENS avatar implementation isn't working properly on a few avatar types, such as brantley.eth's avatar.
When we implemented `@davatar/react`, we went through a lot of trial and error covering edge cases @zzmp that you're going to need to re-discover now 😅 I would recommend testing with all of the ENS team member's avatars, as they each use very quirky NFT sets that push the edges of the spec and provide good coverage.
=> fix: typo in arweave URI recognition

src/hooks/useENSAddress.ts, src/hooks/useENSAvatar.ts, src/hooks/useENSContentHash.ts, src/hooks/useENSName.ts, src/utils/safeNamehash.test.ts, src/utils/safeNamehash.ts
closes #2876 
seems like there's probably some deeper unicode issue going on here, but this at least fixes the immediate problem for those with emojis in their ENS names
=> fix: introduce safeNamehash

src/components/PrivacyPolicy/index.tsx
One question:  how can I add a space between the period and the `ExternalLink`?
=> feat: Add learn more link in TRM description

src/hooks/useENS.ts, src/hooks/useENSAddress.ts, src/hooks/useENSAvatar.ts, src/hooks/useENSContentHash.ts, src/hooks/useENSName.ts, src/pages/Swap/index.tsx, src/state/mint/hooks.tsx, src/state/mint/v3/hooks.tsx, src/state/swap/hooks.tsx, src/state/wallet/hooks.ts
- Memoizes the returned object from all ENS hooks, so that consumers are guaranteed referential equality
- Memoizes any hooks used in an idle swap page to prevent infinite rerenders
Fixes inifinite swap page rerenders. This was occuring because objects were being passed to hooks inline, instead of useing memoization, which resulted in referential inequality and rerenders every cycle (of React). Passing args like `[address]` to a hook in React creates a new reference every time, because `[address] !== [address]`.
=> fix: memoize hooks from /swap

src/components/TransactionSettings/index.tsx
As per https://github.com/Uniswap/interface/issues/2744
=> fix: extend transaction deadline to 3 days

src/connectors/index.ts
fixes https://github.com/Uniswap/interface/issues/2477
walletlink/coinbase wallet used to only support mainnet but added other networks along the way
so we need to let `react-web3` know to only support certain chains
to reproduce the bug on main:
- disconnect your metamask/existing wallet connection
- connect to coinbase wallet using the QR code scanner
- on the coinbase wallet app, change your default network to any unsupported network (like polygon)
(thank you @NoahZinsmeister for your help!!)
=> fix: app crash on coinbase wallet + polygon network

package.json, src/lib/components/Web3Provider.tsx, src/lib/hooks/useActiveWeb3React.ts, src/lib/state/index.ts, yarn.lock
Uses exported EMPTY singleton instead of homegrown class.
Uses dedicated Url connector instead of Network.
=> fix: web3-react-fixes

src/lib/components/Swap/Input.tsx, src/lib/components/Swap/ReverseButton.tsx, src/lib/components/Swap/index.tsx
The reverse button was too high, which caused collision with large balances.
=> fix(widgets): correctly position the arrows

src/components/SearchModal/CurrencySearch.tsx, src/hooks/Tokens.ts, src/hooks/useSwapSlippageTolerance.ts, src/hooks/useWrapCallback.tsx, src/lib/hooks/useCurrency.ts, src/lib/hooks/useNativeCurrency.ts, src/lib/hooks/useTokenList/index.ts, src/lib/hooks/useTokenList/utils.ts
Separates the hook logic from application state so that the logic may be re-used by widgets.
=> refactor: mv token hooks to lib

src/components/vote/ProposalEmptyState.tsx
Current behavior:  if you visit the /vote page while connected to Polygon, Rinkeby, Ropsten, etc,  you see an empty page with no explanation.
Expected behavior:  you should see a message 
We already have this on optimism and arbitrum, but the conditional was overlooking Polygon, Rinkeby, etc
This was made more noticeable by Tina's PR for chain ID URL param https://github.com/Uniswap/interface/pull/3057
=> fix: display network message on vote page if not mainnet

src/hooks/useApproveCallback.ts, src/lib/components/Swap/Summary/index.tsx, src/lib/components/Swap/SwapButton.tsx, src/lib/hooks/swap/useSwapApproval.ts, src/lib/hooks/useApproval.ts, src/state/transactions/hooks.tsx, src/utils/getTxOptimizedSwapRouter.test.ts, src/utils/getTxOptimizedSwapRouter.ts
Decouples approval logic from transactions, by making "hasPendingApproval" lookups use a callback hook instead of coupled logic. This is necessary to allow the widget to use the same approval codepaths, as the widget does not yet track transactions, and will not do so using redux, as the app does.
=> refactor: isolate approval callback hooks

src/hooks/useAutoSlippageTolerance.ts, src/hooks/useSlippageToleranceFromTrade.ts, src/lib/components/Swap/Settings/MaxSlippageSelect.tsx, src/lib/hooks/swap/useSwapInfo.tsx, src/lib/state/atoms.ts, src/lib/state/settings.ts, src/state/swap/hooks.tsx
- change slippage type to `Percent | auto` to support auto slippage calculations based on trade details 
NB: This is a functional change - design/UI updates will be made in a separate PR.
=> feat: update slippage tolerance to use auto or custom

src/components/Header/NetworkSelector.tsx, src/constants/chains.ts, src/utils/routes.ts
fixes https://github.com/Uniswap/interface/issues/1893 https://github.com/Uniswap/interface/issues/3032
This allows users to add `chainId` to the URL to prompt the user to switch their wallet network if necessary.
Some considerations/assumptions here:
- By default (no `chainId` parameter), the network should be the wallet's network
- When no wallet is connected, the behavior should match that of switching the network option with no wallet that is currently in the app
- if `chainId` parameter exists, and is a supported chain id and is not the wallet current network, then fire a request to prompt network change
- We consider the wallet's network as the source of truth -> if the user rejects the network change request, remain on the current network
- When we switch networks on the app, …
=> feat: add chainId (network) as url parameter

src/lib/components/BrandedFooter.tsx, src/lib/components/BrandingFooter.tsx, src/lib/components/ExternalLink.tsx, src/lib/components/Header.tsx, src/lib/components/Swap/Output.tsx, src/lib/components/Swap/index.tsx, src/lib/components/Widget.tsx
=> feat(widgets): move uniswap protocol branding from header to bottom of output

src/lib/hooks/swap/useBestTrade.ts, src/lib/hooks/swap/useSwapInfo.tsx
- create an intermediate hook for fetching the best trade based on current swap state 
- the new hook mimics the same behavior as app and is used for two purposes: 
1. adds in logic to use the simple client side routing if the SOR package fails for any reason (this becomes extra helpful as we move from client side SOR to API, where API has potential downtime)
2. helps debounce amount values so less calls are made to the SOR logic (as it is very data intensive). This is how we get an accurate "syncing" state which the UI components can reference for loading animations
=> feat: create use best trade hook for widgets

src/lib/components/Widget.tsx
This is necessary for the dialog to be set. Otherwise, because the Widget does not see state update, the ref will never update, and the Widget will freeze when a dialog is triggered.
=> fix: set dialog wrapper with callback

package.json, src/hooks/useContract.ts, src/hooks/usePools.ts, src/hooks/useV2Pairs.ts, src/state/governance/hooks.ts, src/state/stake/hooks.tsx, yarn.lock
This is required by webpack 5, and is done to keep the widgets library compatible.
See https://webpack.js.org/migrate/5/#using-named-exports-from-json-modules
Note that this includes a version bump to capture similar upstream changes to @uniswap/v3-sdk.
=> fix: named imports (webpack 5 compat)

src/lib/components/Error/WidgetsPropsValidator.tsx, src/lib/index.tsx
ensures the integrator passes only supported locales
exports `SUPPORTED_LOCALES`
=> feat(widgets): ensure passed locale is supported

src/lib/components/Swap/Toolbar/index.tsx, src/lib/hooks/swap/index.ts
- only show loading status, insufficient liquidity, or trade info if the user has typed in an amount
=> fix: update widget loading state detection

src/lib/components/Swap/Toolbar/Caption.tsx, src/lib/components/Swap/index.tsx
Stops rendering the swap info updater on chains we don't support
=> fix(widgets): fix broken unsupported network message

rollup.config.ts
Without this change, `yarn widgets:build -w` will break on changes, because the intermediate files will have been deleted and are not marked for recreation. (idk why not.)
=> fix: leave intermediate artifacts in watch

src/lib/components/Button.tsx, src/lib/components/Swap/Settings/MaxSlippageSelect.tsx, src/lib/components/Swap/index.tsx, src/lib/components/Tooltip.tsx, src/lib/hooks/useHasFocus.ts, src/lib/hooks/useHasHover.ts
Uses native listeners for focus and hover instead of adding boilerplate for onFocus/onBlur/onMouseEnter/onMouseLeave. This implementation is slightly more complex, but the usages are significantly simpler.
=> feat: focus and hover hooks

src/lib/components/Swap/Summary/index.tsx
Fixes an issue where swap details transition with a scroll bar, then layout thrash when the scrollbar goes away. This occurs because they use a dynamic height, so the fix sets the height to a static 7.5em to fill available space.
=> fix: summary details heights

src/lib/components/Swap/Input.tsx, src/lib/components/Swap/Output.tsx, src/lib/components/Swap/Settings/MaxSlippageSelect.tsx, src/lib/components/Swap/Summary/Details.tsx, src/lib/components/Swap/Summary/index.tsx, src/lib/hooks/useAllowedSlippage.ts, src/lib/state/settings.ts, src/utils/prices.ts
- move price impact and slippage warning logic so that there is only one shared definition
- color price impact on the swap screen
=> feat: improved warning ux

src/lib/components/Web3Provider.tsx, src/lib/components/Widget.tsx
Allows ethers provider/signer to be passed instead of an EIP1193 provider.
The ethers provider/signer is bridged to an EIP1193 using require('@ethersproject/experiment').Eip1193Bridge.
=> feat: accept {provider, signer} as ethers provider

src/lib/components/Widget.tsx
Applying user-select to the widget element, and not its constituents, stops WebKit from preventing <input>s from receiving user focus.
NB: Defaulting to `user-select: none` is intentional. An audit is scheduled to go over which elements should have `user-select`. This PR is only meant to address a WebKit issue.
=> fix: allow input selection in WebKit

src/components/SearchModal/ImportToken.tsx
one is non-functional (I don't know why), but _1 seems to work 🤷
=> fix: use explicit value in Plural tag

src/components/Header/NetworkSelector.tsx
Fixes: #3117 
The networks menu will open upon hover and close upon mouse leaving on desktop.  Tested on iOS / Safari simulator and tapping the networks button continues to open the menu.
The extra wrapping component is required so that the menu doesn't hide when the user's mouse hits between the button and the dropdown.
=> feat: Open networks menu upon hover

src/lib/theme/type.tsx
Set appropriate types to nowrap. This prevents linebreaks during element resizing, as reported [1].
[1]: https://discord.com/channels/597638925346930701/947940283167936532/948229837649240114
=> fix: set appropriate types to nowrap

src/lib/i18n.tsx
CRAv5 requires that locales be fully specified (including the `.js` suffix) in order to load them. Doing so adds support for CRAv5 to the widgets lib.
=> fix: fully specify locales

src/lib/hooks/swap/useSyncTokenDefaults.ts
- currentlty the widget will crash when `ExtendedEther` is use as a token input on a network that has no native currency 
- this issue is only exposed through network switching (as we disable token select on those networks)
- when switching from unsupported to supported, a race condition causes ExtendedEther to be used on a network where there is no native currency 
-  to avoid this we should only use "NATIVE" as a token default if we have instantiated the native currency to be used within `ExtendedEther`
=> fix: update default tokens on unsupported networks

package.json, src/hooks/useBestTrade.ts, src/pages/Swap/index.tsx, src/state/routing/useRoutingAPITrade.ts, src/state/routing/utils.ts, src/utils/computeFiatValuePriceImpact.tsx, yarn.lock
-mostly to get this fix from rtk-query: https://github.com/reduxjs/redux-toolkit/issues/1339
for different hook args, `data` returned by `useQuery` was the same. To go around this behavior in the interface, we used a very ugly hack to detect when the `Trade` input/output were different from hook input/output. This is not needed anymore thanks to `currentData`
also fixed an existing bug with priceImpact relying on swap form inputs, rather than resolved Trade.input/output. Since we debounce the trade, price impact would often lag behind.
=> chore: upgrade to redux-toolkit 1.8

src/hooks/useCurrentBlockTimestamp.ts, src/hooks/useUSDCPrice.ts, src/lib/components/TokenSelect/index.tsx, src/lib/hooks/swap/index.ts, src/lib/hooks/useAllowedSlippage.ts
Fixes hooks which returned new instances of objects every call, by memoizing the return values to prevent re-renders.
This fixes all hooks that are used in a typical use of `src/lib/components/Swap/SwapButton`. No other codepaths were tested.
=> fix: incorrectly memoized hooks

src/lib/components/TokenSelect/index.tsx
Displays a "No results found" message in TokenSelect when appropriate:
=> feat: display "no results found" message

src/lib/components/Swap/SwapButton.tsx, src/lib/hooks/swap/useSwapInfo.tsx, src/lib/hooks/swap/useWrapCallback.tsx
This PR contains 4 changes. 
1. Add error catching to the `wrapCallback`. Before, if a user rejected the transaction in their wallet the `WrapState` would not reset the value for `loading`, which causes button to be disabled until page relod. Fix is to catch error within the callback and reset loading state if detected. 
2. Update amount parsing when wrapping and disable trade fetching. When a user is wrapping or unwrapping, we dont want to fetch an ETH <-> WETH trade, and we dont want to show the input/output amounts from that trade. Instead, force input/output amounts to be the typed value from user. 
3. Fix logic for detecting balance in wrapCallback. Currently we are only checking balance if the user has typed in the input field. This leads to an error when users type in the output …
=> fix: update wrap fail state callback and input values

src/lib/components/BrandedFooter.tsx, src/lib/components/Swap/SwapButton.tsx, src/lib/components/Swap/Toolbar/index.tsx, src/lib/components/TokenSelect/index.tsx
Improves rendering by preventing child components with no data displayed from re-rendering when the parent is re-rendered.
In particular, this memoizes:
- `BrandedFooter`
- `SwapButton`
- `Toolbar`
- `TokenSelect`
These components either rarely change, or have their own state, so they do not need to re-render when their parents render. See https://reactjs.org/docs/react-api.html#reactmemo.
=> fix: memoize nested components

src/lib/components/Swap/Summary/Summary.tsx
Fixes line wrapping in the Summary component. This was fixed, but inadvertently re-broken when resolving a merge conflict.
Before:
After:
=> fix: avoid summary wrap

src/hooks/usePools.ts
Pools are all fetched together, but re-instantiated any time any of them loads. This leads to repeated instantiation of the same pools (in a manual test, there were ~60 pools, but over 1000 instantiations when first fetching data, ie a >93% hit rate). Avoiding repeated instantiations shaves off ~15-25ms per data fetch, which leads to displaying swap prices ~45-75ms faster (because pools are fetched for 3 routes: the swap, and stablecoin prices for both coins).
This adds a simple FIFO cache of 128 pools (appx. 2 swaps) to avoid pool reinstantiation.
---
NB: The current bottleneck in rendering is both Pool instantiation and redux-multicall. If this is resolved, redux-multicall will be the bottleneck for rendering.
Reviewers: If you see code that would benefit from more …
=> fix(perf): cache pools to avoid cost of instantiation

src/hooks/useCurrentBlockTimestamp.ts, src/hooks/useGasPrice.ts, src/hooks/useIsArgentWallet.ts, src/hooks/useTotalSupply.ts
Memo-izes on-chain non-primitive results by converting them to a string, which is a primitive, and using that in `useMemo`/`useEffect` deps arrays. This prevents unnecessary re-renders when the same result is returned.
=> fix: memoize on-chain results

src/lib/components/Rule.tsx
Allows hr to extend to full width, despite any integrator hr-specific width styles.
=> fix: override Rule width

src/lib/hooks/swap/useSwapInfo.tsx
Propagates the exact amount to the trade currency amount without waiting for the trade to be computed. This allows things like insufficient balance or approval to be reflected in the UI while typing, instead of having a lag.
This screencap shows the issue that is being fixed:
https://user-images.githubusercontent.com/5403956/157987706-dbdbaa6f-8027-4bf6-aeac-ec9330be7cb1.mov
=> fix: input amount lag

src/lib/icons/index.tsx
See [notion](https://www.notion.so/uniswaplabs/Flip-review-carrot-direction-should-indicate-the-result-of-your-click-not-the-state-42d15f0f7eb447509ee44e9f0590c5cd)
=> fix: expando icon direction

src/lib/components/TokenSelect/TokenButton.tsx
Removes the overflow property from TokenButton, which prevents the vertical scrollbar from rendering.
See https://www.notion.so/uniswaplabs/y-overflow-causing-scrollbar-on-token-in-output-d5aa67a355694c86b5d9530878a121c2
=> fix: token button overflow

src/lib/components/Swap/Price.tsx, src/lib/components/Swap/Summary/index.tsx, src/lib/components/Swap/Toolbar/Caption.tsx, src/lib/utils/formatLocaleNumber.ts
- Simplifies the price logic on the toolbar (price is derived from execution price)
- Refactors `Price` to its own component so it can be used in both the toolbar and the summary screen
- Incidentally, add "click to reverse basis" functionality to the summary screen
As part of refactoring price logic, also fixes a bug in `formatLocaleNumber` where `fixedDecimals` was not respected.
=> chore: simplify Price in its own component

src/hooks/usePools.ts
- in `usePools` an error can surface when network is changed to an unsupported network 
- in the widget, on unsupported networks `slot0s` and `liquidities` will be empty arrays
- this fix adds a check that the element in the result array exists before attempting to reference it
- may fix notion issue [here ](https://www.notion.so/uniswaplabs/Widgets-UI-Polish-a7c6d4ece6124d4cb96e9be926e9e67f?p=7f1c80a961fd4e19a528ed46fc6afc8a)
=> fix: add check for undefined slot0 and liquidity call results

src/lib/components/Column.tsx, src/lib/components/Error/ErrorDialog.tsx, src/lib/components/Expando.tsx, src/lib/components/Swap/Summary/Details.tsx, src/lib/components/Swap/Summary/index.tsx
Refactors Expando into its own component, which is used in the status dialog and in the summary. Doing so greatly simplifies the dialog and summary.
Fixes https://www.notion.so/uniswaplabs/Swap-button-shifts-down-slightly-when-expanded-details-bc610bbad9364b2fb8e3d8115018d229.
=> feat: make Expando element

src/lib/components/TokenSelect/TokenButton.tsx
- reverts #3504, with the addition of overflow-x to avoid token button overflow
- adds a min-width to TokenButtonRow img so that the image will not be collapsed when the row shrinks
Fixes https://www.notion.so/uniswaplabs/Fix-token-icon-when-max-is-shown-see-x-roll-0df8f9152db048c1a852cd8af75dceeb
=> fix: token img overflow

src/lib/hooks/useEip1193Provider.ts
Allows providers to be passed that do not implement eth_requestAccounts, which is required to use web3-react [1].
An alternative solution would be to have web3-react fallback to using eth_accounts if eth_requestAccounts is not implemented. To be clear - I'm unsure if this is a failing of the provider for not supporting this, of the Eip1193Bridge for not polyfilling this, or of web3-react for not falling back to eth_accounts. @NoahZinsmeister - what would you advise?
This issue came up when trying to integrate a walletconnect provider through web3modal. It lacked eth_requestAccounts.
[1]: https://github.com/NoahZinsmeister/web3-react/blob/main/packages/eip1193/src/index.ts#L67
=> fix: fallback to eth_accounts in eip1193 bridge

src/state/governance/hooks.ts
fixes #3506 
fixes #3501 
fixes #3494 
fixes #3490 
fixes #3489 
fixes #3473 
fixes #3521 
fixes #3522 
fixes #3533 
fixes #3534
=> fix: typeError: Cannot read properties of undefined (reading 'split')

src/lib/components/Swap/SwapButton.tsx
- Fixes [this](https://www.notion.so/uniswaplabs/Widgets-UI-Polish-a7c6d4ece6124d4cb96e9be926e9e67f?p=a5ff30539c2844d6b4fa46f67f6a64ef)
- currenlty the swap button is enabled even if `trade`is undefined
=> fix: disable swap button if trade not populated

src/lib/components/Swap/Input.tsx, src/lib/components/Swap/Output.tsx, src/lib/components/Swap/Price.tsx, src/lib/components/Swap/Summary.fixture.tsx, src/lib/components/Swap/Summary/Details.tsx, src/lib/components/Swap/Summary/Summary.tsx, src/lib/components/Swap/Summary/index.tsx, src/lib/components/Swap/SwapButton.tsx, src/lib/components/Swap/Toolbar/Caption.tsx, src/lib/components/Swap/Toolbar/index.tsx, src/lib/hooks/swap/useSwapInfo.tsx, src/lib/hooks/useUSDCPriceImpact.ts
Prevents USDC from being computed multiple times each render. Greatly reduces blocking tasks on the main thread, and minimizes their time (whereas before they occured at every update for 150+ms, now they only occur for >60ms on the final update of a trade).
Removes cruft from computeSwapInfo to make it more maintainable / readable.
=> chore: include usdc in swap info

src/lib/components/Swap/Summary/index.tsx
Update the expando absolute height to not overflow the dialog, fixing the [grey bar](https://www.notion.so/uniswaplabs/safari-seeing-the-bottom-gray-bar-again-c9a8a5931db741ed8edc80f50ce71b82).
This will not work until https://github.com/Uniswap/interface/pull/3553 is merged, as rendering the price impact currently crashes the widget.
=> fix: summary expando height

src/lib/components/Expando.tsx, src/lib/components/Swap/Output.tsx, src/lib/components/Swap/Summary/Details.tsx, src/lib/components/Swap/Summary/Summary.tsx, src/lib/components/Swap/Summary/index.tsx, src/lib/components/Swap/Toolbar/Caption.tsx, src/lib/components/TokenImg.tsx, src/lib/hooks/swap/useSwapInfo.tsx, src/lib/hooks/useUSDCPriceImpact.ts
- Fixes price impact rendering, which was broken when attempting to render the PriceImpact object 😱 
- Fixes the fade-out gradient in WebKit by using `transparent` explicitly (instead of a hex version)
=> fix: impact rendering

src/lib/components/ActionButton.tsx, src/lib/components/EtherscanLink.tsx, src/lib/components/Swap/SwapButton.tsx, src/lib/hooks/swap/useSwapApproval.ts
Flips ApprovalState to pending as soon as a wallet interaction is requested, so that the interface does not look hung if the request is going to a mobile wallet. See [notion](https://www.notion.so/uniswaplabs/Wallet-connect-signing-states-88e49d02eb934a4597c7902f3e232a43) for more context.
=> fix: set approval to pending on wallet request

src/lib/components/TokenSelect/index.tsx
Fixes [jank when mounting TokenSelect](https://www.notion.so/uniswaplabs/safari-Token-selector-animation-wonky-551d5757740d42d990eec081b4ae7cdf) caused by WebKit scrolling the focused element (the search bar) into view during the Dialog mounting animation.
=> fix: prevent scroll on token select focus

src/lib/components/TokenImg.tsx
Re-render the token image when it changes by setting the alt as a key. This prevents rendering the stale image for a frame while the new image loads.
Alternatively, the currencyId could be used as a key, but it likely should not be re-rendered across chains with different addresses for the same currency name, so alt seems more appropriate.
The issue can be seen in this screencap. This can be reproduced by opening DevTools and disabling the cache.
https://user-images.githubusercontent.com/5403956/159192131-79f9bba9-9cb3-4baf-ae34-ac82143c9f8b.mov
=> fix: token img jank

src/lib/components/Input.tsx, src/lib/hooks/routing/useClientSideSmartOrderRouterTrade.ts
Fixes remaining latency on trade loading UI.
- Fixes useClientSideSmartOrderRouterTrade to return _the trade_, unless it is unavailable, and _then_ return the last trade
- This fixes a bug where the trade amount took an extra frame to render (visible when reversing currencies on already-loaded trades), because the _last trade_ was always returned first, until it was updated.
- Fixes Input to immediately render any changed value. The validation is removed, so that it now only occurs when the Input changes, not on the initial value that is set.
- This fixes a bug where the Input would take a frame to update (visible when reversing currencies to a trade that was already loaded, but is no longer, in which case it would flash the old trade then update to 0).
=> fix: trade UI latency

src/lib/components/Widget.tsx
Fixes the border radius on the Dialog wrapper, which was cutting of modals on top of it.
=> fix: modal border radius

src/lib/components/Input.tsx
Do not allow the input to be more than one 0 with nothing else.
This will no longer apply once anything but a 0 is input (eg ".").
=> fix: do not allow zeroes

src/lib/components/Swap/Toolbar/index.tsx
Prevent incorrect toolbar messages when the input is a zero value (like 0.000).
=> fix: empty toolbar for empty input

src/lib/components/ActionButton.tsx
Fixes the whole-widget height change when the action button's action transitions away, eg:
https://user-images.githubusercontent.com/5403956/159618009-bda33dae-0f05-4acc-87ef-0abcc0a413a5.mov
(See [notion](https://www.notion.so/uniswaplabs/Approvals-still-have-jank-d25a2f4dfe884d7fade2d2346f89fb0e) for more context.)
=> fix: action button jank

src/lib/hooks/useActiveWeb3React.tsx
Logs any web3-react errors to the console. These errors were silent before, and made it difficult to debug EIP-1193 incompatibilities.
=> fix: add web3 debug log

package.json, src/lib/hooks/useEip1193Provider.ts, yarn.lock
Upgrades @web3-react/eip1193 to a version that only requires an EIP1193 provider. Prior versions relied on eth_requestAccounts, specified in EIP1102.
For more context, see [the web3-react issue](https://github.com/NoahZinsmeister/web3-react/issues/469), [our past workaround](https://github.com/Uniswap/interface/pull/3516), or the [issue tracking notion card](https://www.notion.so/uniswaplabs/WalletConnect-rainbow-unable-to-connect-to-widget-5f0bcad9a1b442248890af336a9c51d9).
=> fix: upgrade @web3-react/eip1193 usage

src/lib/hooks/routing/useClientSideSmartOrderRouterTrade.ts
After fetching quote results, the SOR package takes >80ms to process the data (on a production build), resulting in dropped frames. This isn't _terrible_, but we then trigger a re-render by setting the quoteResult using a `useState` hook, tacking on an additional 40-80ms. This is a performance improvement which delays the re-render by a tick, allowing the browser to render a frame sooner and making the page feel snappier for integrations with other things happening on the page (like FWB's background graphic).
=> fix: tick before returning quote

src/hooks/usePools.ts, src/hooks/useV2Pairs.ts, src/state/claim/hooks.ts, src/state/governance/hooks.ts, src/state/stake/hooks.tsx
Improves package size by not bundling those parts of the JSON which are not used, as JSON is bundled inline with the library.
This undoes parts of 610f7d3581f7db6a6e79735dd2cbdae4f03be3c1, which are unnecessary because we are not using webpack 5 but rather are bundling inline with rollup.
=> chore: destructure json imports

src/constants/locales.ts, src/lib/i18n.tsx
Lazy loads en-US to avoid bundling it in the initial package, as integrators may be using a different initial locale.
This should not affect interface performance, as the locale loads before the font, and nothing will be rendered until the font is loaded anyway.
=> fix: lazy load en-us

src/constants/tokens.ts, src/hooks/usePoolTickData.ts, src/lib/.eslintrc.json, src/lib/hooks/routing/clientSideSmartOrderRouter.ts, src/lib/hooks/routing/useClientSideSmartOrderRouterTrade.ts, src/state/governance/hooks.ts
Lazy loading smart-order-router halves the package size on initial load by deferring a _large_ chunk of code until it is actually needed.
- Copies static token values into the codebase instead of importing _all_ of smart-order-router to get them
=> feat: lazy load the lib's smart-order-router

src/lib/components/Error/WidgetsPropsValidator.tsx, src/lib/components/Swap/SwapPropValidator.tsx, src/lib/components/Swap/index.tsx, src/lib/components/Widget.tsx
Rearranges the JSX DOM to avoid re-rendering children when state changes, by moving those state changes into their own leaves of the DOM.
This has a real effect on performance, and prevents cascading re-renders, especially during initial mount. Practically, this can make the difference between an initial render seeming instant or not.
=> fix: break unnecessary hierarchical deps

src/lib/components/Swap/TokenInput.tsx
WebKit always renders inputs at >1em height, which results in a 1em container having the input content cut off [1].
This is apparent (but subtle) with `font-family: Inter`, but more so with `font-family: Popper`:
This updates the TokenInput to use a height of 1.5em, with margin offsets to vertically center the content, in order to avoid cutting off the input content.
[1]: This is partially explained in https://www.456bereastreet.com/archive/201108/line-height_in_input_fields/
=> fix: token input height

src/lib/components/Swap/Toolbar/index.tsx, src/lib/hooks/swap/useSwapInfo.tsx
- Prevents the toolbar from showing "Fetching best price" when the "swap" is just a "wrap", as the price in this case is fixed.
=> fix: do not fetch wrap price

src/lib/hooks/routing/useClientSideSmartOrderRouterTrade.ts, src/lib/hooks/usePoll.ts
Prevents a `useState` setter from being called after its component unmounts, which had resulted in the React warning
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
=> fix: polling memory leak

src/lib/components/Swap/useValidate.tsx
Removes BigNumber from validation checks, as it fails for all but integers. Token amounts are specified as numbers or strings, and decimals are not supported by BigNumber.
=> fix: swap validator

src/lib/hooks/useBlockNumber.ts
Fixes block number stability, where it had been causing re-renders despite having the same value, because the chainBlock object (`{ chainId, block }`) was being re-instantiated with the same values.
=> fix: block number stability

src/lib/hooks/useCurrencyBalance.ts
Increases the gas requirement to 200,000 when calling the `balanceOf` function on a token.
Ensures that the token balance and "MAX" button appear in the Swap input component.
Tested on token 0xab167E816E4d76089119900e941BEfdfA37d6b32 which requires ~173k gas to read `balanceOf` with multicall.
=> fix: missing token balance

src/hooks/useIsWindowVisible.ts
Defers the use of `document` until the `useEffect` hook to avoid breaking nextjs SSR, which has no global `document`.
=> fix: omit document ref

src/lib/components/Widget.tsx
Reverts part of https://github.com/Uniswap/interface/pull/3687, which had disabled the multicall updater and prevented usdc prices from loading.
=> fix: always run global updaters

src/lib/hooks/swap/useSwapInfo.tsx
Fixes useSwapInfo such that it returns up-to-date currency values, instead of lagging behind, because it is triggered by updates to swapAtom and so is not always consistent with swapAtom.
As an example of what this fixes, reverse the currencies in the widget. You'll notice on the [current build](https://widgets-uniswap.vercel.app/), there is a lag in the UI when updating the swap info. This manifests in two ways, both of which should be fixed by this PR:
- When reversing a wrap, the text will update twice. You can see this if you capture the frames using the Chrome DevTools Performance tab.
- When reversing swap, the amounts will update twice, as the two fields will update on different frames.
=> fix: skewed swap info state

src/hooks/useV3PositionFees.ts, src/pages/Pool/PositionPage.tsx, src/pages/RemoveLiquidity/V3.tsx
Sometimes the `positionManager.callStatic.collect()` call fails in hooks/useV3PositionFees.ts. 
When this happens, the `useDerivedV3BurnInfo(position, receiveWETH)` function on line `87` of pages/RemoveLiquidity/V3.tsx returns `undefined` for `feeValue0` and `feeValue1` 
If `feeValue0` and `feeValue1` is `undefined`, then the `burn = useCallback` function on line 103  fails because `!feeValue0` and `!feeValue0` return `True`. So LPs cannot burn their position if the `collect()` call fails (which happens quite frequently for me)
To solve this, I removed the `!feeValue0` and `!feeValue1` conditions lines on 112+113, and also replaced `feeValue0`+`feeValue1` with `liquidityValue0`+`liquidityValue1` for `expectedCurrencyOwed0`+`expectedCurrencyOwed1` on lines 127 and 128. 
Maybe the …
=> fix: bug where user cannot burn lp position if fetching fee values fails.

src/components/ErrorBoundary/index.tsx
The initial implementation by @moodysalem was done in: https://github.com/Uniswap/interface/pull/3435. The problem there was if there was no update from the app it would get stuck refreshing infinitely.
I copied that PR but added a check to ensure that there is actually a new version being returned from the update and only in that case will the app update. I also had to add a few more lines that appear to be required to make the refresh happen properly which I copied from: https://github.com/facebook/create-react-app/issues/5316#issuecomment-591075209
=> fix: Reload the app when there is a javascript error and a new version of the app

src/lib/components/ActionButton.tsx, src/lib/components/Button.tsx, src/lib/components/Input.tsx, src/lib/components/Swap/Input.tsx, src/lib/components/Swap/Output.tsx, src/lib/components/Swap/ReverseButton.tsx, src/lib/components/Swap/SwapButton/index.tsx, src/lib/components/TokenSelect/TokenButton.tsx, src/lib/components/Widget.tsx, src/lib/css/loading.ts
These changes remove any jarring UX on initial provider connection. It adds a transition to any element that is already rendered initially (eg input and token buttons). It intentionally does _not_ add transitions to those elements which were not already rendered (eg "Connect your wallet").
- Cleans up the action button (including fixing a bug that allowed stale swaps)
- Adds fade in to reverse and token select buttons when transitioning from disabled state
- Adds fade in to input text
https://user-images.githubusercontent.com/5403956/163095872-b30cbf7e-41de-4614-8ac8-8eef1e4709b5.mov
=> fix: initial transitions

src/components/FeeSelector/shared.tsx
The fee tier is showing up on the UI and I was able to add liquidity for that fee tier. 
@justindomingue  helped me to test this by making sure a swap would go through the 1bp tier: 
The resulting transaction was https://mumbai.polygonscan.com/tx/0x744bb33f9f6086cc6b19c29ba604d3ad6bba6c3d9ab1d137bf27b19fc082b92c which we _think_ confirms that my swap went through that tier properly.
=> feat: add 1bp fee tier to polygon

src/lib/components/TokenImg.tsx
Stores the local version of a src as a badSrc on error, instead of using `e.target.src`, which may be normalized differently.
=> fix: missing token img

src/pages/AddLiquidity/index.tsx, src/state/mint/v3/hooks.tsx
Lets an outside application pre-set the price range, for example:
`/add/ETH/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/3000?minPrice=100&maxPrice=500`
=> feat: take tick range from URL

src/components/WalletModal/index.tsx
Use optional chaining to check `window.ethereum` object chain.
=> refactor: Use optional chaining

src/constants/governance.ts, src/pages/Vote/Landing.tsx, src/state/governance/hooks.ts, src/state/logs/hooks.ts, src/state/logs/slice.ts, src/state/logs/updater.ts, src/state/logs/utils.ts
in the vote tab, proposals weren't being displayed briefly because log fetching was failing. the root cause was an infura service degradation, tracked here: https://status.infura.io/incidents/q3mfstfbjzyy
this pr constrains the block range(s) over which logs are fetched in an attempt to alleviate load. additionally, historical logs are fetched once and only once now, as opposed to every block.
also hides cancelled proposals by default
=> perf: constrain log-fetching block ranges

package.json
If *.dbg.json files are present in the `/node_modules/@uniswap/**/artifacts/contracts/` directory, typechain will fail with
`$ typechain --target ethers-v5 --out-dir src/types/v3 "./node_modules/@uniswap/**/artifacts/contracts/**/*.json" --show-stack-traces
Error occured:  Not a valid ABI
Stack trace:  Error: Not a valid ABI`
This normally doesn't occur if `@uniswap` packages are installed via NPM as *.dbg.json files are excluded from the package, but when developing locally using either `file:...` syntax or `git+ssh:` these errors will occur.
This PR changes the `contracts:compile:v3` command to ignore `*.dbg.json` files.
=> fix: ignore dbg.json files during typechain

src/pages/Swap/index.tsx
closes #3056
opening an url swap?inputCurrency=not_existing_address
cause a state where you are not able to change input currency
same technique used here https://github.com/Uniswap/interface/blob/main/src/pages/AddLiquidity/index.tsx#L586
how it looks now:
=> fix: handle non existing inputCurrency from url #3056

src/components/PositionList/index.tsx, src/components/Toggle/SimpleToggle.tsx
This change adds the 'Hide closed positions' button to the mobile Pool page view. As referenced in #3344 , without this, the pool page can accumulate closed positions and the request can even time out with a large number of positions. We shouldn't limit user functionality due to mobile view whenever possible.
By default, the button is identical to the font size of the 'Your positions'. This supports widths up to 340px.
The smallest mobile view that I typically support is 320px (iPhone 5). With this, the bar overflows and doesn't look great.
With a font size of 14px on 'Hide closed positions', we are able to fit the 'Your positions' + 'Hide closed positions' in one line on screen widths as small as 320px.
=> fix: Mobile layout: hide closed positions disappears #3344

src/components/AccountDetails/TransactionSummary.tsx, src/components/earn/UnstakingModal.tsx, src/components/vote/DelegateModal.tsx, src/components/vote/ExecuteModal.tsx, src/components/vote/QueueModal.tsx, src/components/vote/VoteModal.tsx, src/pages/Vote/VotePage.tsx, src/state/application/hooks.ts, src/state/application/reducer.ts, src/state/governance/hooks.ts, src/state/transactions/types.ts
this PR introduces 2 new flows to queue successful proposals and execute queued proposals, when necessary
=> feat: add `Queue` and `Execute` buttons

src/utils/getLibrary.ts
This PR remove the `NETWORK_POLLING_INTERVALS` override for **Arbitrum** networks to improve performance by reducing number of rpc requests.
=> perf: remove Arbitrum polling override

src/constants/chains.ts, src/pages/Pool/v2.tsx
Fixed: 'Error: No V2 factory address on this chain' (#3762 #3777). Added messaging for unsupported V2 pool networks (Polygon, Optimism, Arbitrum).
=> fix: adds messaging for unsupported V2 pool networks (#3762 #3777)

cypress/e2e/swap.test.ts, src/pages/Swap/index.tsx
Fix: https://github.com/Uniswap/interface/issues/3906. Fixed to display the correct price estimates depending on whether it is a wrapped trade (eth -> weth should show no price impact).
Before:
After:
=> fix: show no price impact eth to weth

src/serviceWorker/document.test.ts, src/serviceWorker/document.ts
Always requests the app-shell from the same path as the cache key, in
order to guarantee that the etags will match should the cache be valid.
=> fix: serviceworker request path

src/hooks/Tokens.ts, src/lib/hooks/useTokenList/utils.ts, src/state/lists/wrappedTokenInfo.ts
Fix: doesn't crash app when searching for a particular token (HOP) where a particular coin list (CMC) has wrong token address, such that the checksum fails.
Before:
After:
gnosisSafe
=> fix: crash on HOP token search (#3904)

package.json, yarn.lock
Bumps version of @uniswap/token-lists package to latest version (1.0.0-beta.30). This is to bring in the changes that:
- fix an inconsistency with the tokenList type ([PR](https://github.com/Uniswap/token-lists/pull/140))
- increase the max length of token list names to 30 characters ([PR](https://github.com/Uniswap/token-lists/pull/136#pullrequestreview-998312835))
This will prevent issues when default tokenList is updated with cross-chain mappings and name is updated to "Uniswap Labs Default List" ([PR1](https://github.com/Uniswap/default-token-list/pull/1130) [PR2](https://github.com/Uniswap/default-token-list/pull/1129)).
=> chore(deps): bump token-lists

.github/workflows/release.yaml
Sleeps for 10m after pinning to IPFS to give cloudflare time to seed the assets
This will require manual intervention, and is done to facilitate deploying https://github.com/Uniswap/interface/pull/3990.
During the 10m interval, I will be pinging the cloudflare IPFS nodes to try to seed the assets.
=> build: sleep for 10m after pinning

src/serviceWorker/document.test.ts, src/serviceWorker/document.ts, src/serviceWorker/utils.ts
Explicitly sets content-type (and charset) on the cached document to prevent some browsers from serving it as plaintext.
Moves the injected script tag into the <body> in case having it in the <head> was confusing browsers charset detection.
Fixes #3947
=> fix: set content-type on cached document

.github/workflows/release.yaml
Disables release (for now) until it can be updated to include seeding IPFS nodes
=> build: disable release

src/components/SearchModal/CurrencyList/index.test.tsx, src/components/SearchModal/CurrencyList/index.tsx, src/components/WalletModal/Option.tsx, src/components/WalletModal/index.test.tsx, src/components/WalletModal/index.tsx, src/test-utils.tsx, src/theme/index.tsx
If we are in Coinbase Wallet browser then we need to show the Coinbase Wallet option in the WalletModal. Similar logic for MetaMask.
In the future, it would be good to figure out how to avoid special-casing this type of logic.
To reproduce the current issue:
- Open Metamask Mobile browser
- Navigate to app.uniswap.org
- Decline the signature request
- Click the connect button
You'll see a modal with no options like this:
After:
=> feat: show injected options in wallet browsers

src/components/Header/NetworkSelector.tsx, src/utils/switchChain.ts
We have a hook that currently handles two cases:
- If the network is switched outside of the app, make sure we change the URL accordingly
- If the a chain is added as a param in the URL, change the network in the app
There are two bugs:
- If the chainId has changed, confirm that the urlChainId is stale before switching the history
- If There is a urlChainId, make sure that it's actually changed before automatically selecting it in the app
On prod reproduce the bug by having no wallet selected, then switching from ETH to Polygon. It will switch back to ETH.
=> fix: resolves network switch race condition

.github/workflows/crowdin-sync.yaml
Hey everyone,
Since the `main` branch is protected, the download translations workflow is failing. Just updated the workflow to push translations into the separate branch and create a PR with the translations instead of direct pushing them into the `main`.
#3747
=> fix: Crowdin translations download

src/components/AccountDetails/index.tsx
If on MetaMask or Coinbase Wallet browser, you shouldn't be able to change into a different wallet.
=> feat: don't allow disconnect/change on injected mobile wallets

src/components/Explore/SearchBar.tsx, src/pages/Explore/index.tsx
add explore search bar UI (non-functional filtering hehe)
=> feat: explore search bar UI

cypress/e2e/swap.test.ts, src/serviceWorker/document.ts
Responses are immutable, so altering these headers was causing a TypeError.
This fixes that by copying the headers into a new mutable Headers object.
=> fix: alter headers on cached response

src/components/Explore/SearchBar.tsx, src/components/Explore/TokenRow.tsx
fix favoriting bug by copying the array by value (not by address). Favorite and unfavorite a token should be ~speedy ~ (and update some color scheme stuff)
=> fix: fix slow favoriting bug

src/components/Explore/SearchBar.tsx, src/components/Explore/TokenRow.tsx, src/components/Explore/TokenTable.tsx, src/components/Explore/constants.ts, src/pages/Explore/index.tsx
fix search bar responsiveness in filtering bar above table and clean up some padding
=> feat: search responsiveness

src/components/PrivacyPolicy/index.tsx
Update privacy policy here to show Google Analytics & Amplitude, to prepare for integrating amplitude analytics into interface codebase:
=> feat: update privacy policy to include amplitude

.github/workflows/release.yaml
Add sleep in the release process to allow IPFS to seed.
=> build: add sleep in release

.github/workflows/release.yaml
Use a different action to wait on tests, as the old action could not disambiguate check suites.
=> build: wait on tests

.github/workflows/release.yaml, cypress.release.config.ts, cypress/release.ts
Instead of waiting 10m for IPFS to propagate, test every minute for 30m for a pageload using cypress.
=> build: wait on passing cypress

src/components/CurrencyInputPanel/index.tsx
Revert button jump fix on currency panel because of padding issues (https://github.com/Uniswap/interface/pull/4017)
=> fix: revert "fix button jump on currency panel"

package.json, src/hooks/useEagerlyConnect.ts, yarn.lock
This web3-react update fixes connectEagerly on MM Mobile browser, so we don't need to call activate manually.
=> chore(web3-react): fix connectEagerly for MetaMask mobile

.eslintrc.json, package.json, src/components/RoutingDiagram/__snapshots__/RoutingDiagram.test.tsx.snap, src/components/SearchModal/CurrencyList/__snapshots__/index.test.tsx.snap, yarn.lock
Vig found invalid hook call warnings after react 18 upgrade PR (https://github.com/Uniswap/interface/pull/3992) : https://reactjs.org/warnings/invalid-hook-call-warning.html in console on local build. 
Fixed by updating styled-components to latest version, which apparently is needed by React 18. See thread here: https://github.com/facebook/react/issues/21848
=> fix: update styled-components in package.json to latest to remove react invalid hook call warnings

.github/workflows/release.yaml, cypress/e2e/swap.test.ts
Reverts Uniswap/interface#4102
Once https://github.com/Uniswap/interface/pull/4103 is merged
=> build: Revert "build: pause deploy"

cypress/e2e/link.test.ts, cypress/e2e/pool.test.ts, package.json, src/components/Header/index.tsx, src/pages/Pool/PositionPage.tsx, src/pages/Pool/index.tsx, yarn.lock
I'm not sure if anyone noticed that the `<Link />` component is broken now under development mode.
E.g., 
It seems to be incompatibility between React 18 StrictMode and React router dom V5, see https://github.com/remix-run/react-router/issues/7870#issuecomment-1085478601 for an example.
And I believe they have fixed it in https://github.com/remix-run/react-router/pull/8831.
In this pull request:
1. updated `react-router-dom` to the latest V5 version to fix the bug in development mode.
2. added a e2e test to ensure the `Link` component works as expected.
Btw, let me know if you want to upgrade `react-router-dom` to v6, I think I can help with a pull request.
=> chore: upgrades react-router-dom, fixes dev-mode linking

src/components/Popover/index.tsx
If we zoom in, we can find the arrow not really an arrow:
=> fix: fixes Popover arrow positioning

src/hooks/useColor.ts
Just noticed the CI for my pull requests kept failing with an error like this:
And I believe it's related to this bug in `node-vibrant` https://github.com/Vibrant-Colors/node-vibrant/issues/101 because it tries to load image from remote server to extract color.
And there's another issue reported here https://github.com/Uniswap/interface/issues/4011 which might be related to the same bug.
Hopefully the e2e tests for this pull request should succeed without error above.
=> fix: catch vibrant failure

src/components/Explore/SearchBar.tsx
search bar shouldn't collapse when there is a string in it
=> fix: expand state

package.json
I always found this confusing, but I think it was because Widgets used to be in this repo.
=> build: change project name to @uniswap/interface

package.json, yarn.lock
Seems like this PR made some changes in the lock file: https://github.com/Uniswap/interface/pull/4128
Then this PR failed the unit-tests based on snapshots: https://github.com/Uniswap/interface/pull/4125
Then this PR updated the snapshots as an unrelated issue: https://github.com/Uniswap/interface/pull/4130
This issue states that 7.0.8 (latest version) has a bug where the sc-* classNames from styled-components are regenerated randomly, leading the snapshot flakes: https://github.com/styled-components/jest-styled-components/issues/405, https://github.com/styled-components/jest-styled-components/issues/276#issuecomment-1149749113
So this re-adds some potentially necessary pieces of the yarn.lock, and also fixes the jest-styled-components version for now.
=> build: lock jest-styled-components@7.0.7

src/components/Header/NetworkSelector.tsx
I accidentally merged https://github.com/Uniswap/interface/pull/4019 because it was on auto-merge, even though stuff failed. This removes an unused line.
=> fix: unused onClickOutside reference

src/hooks/useClientSideV3Trade.ts
This circumvents the 'out of gas' error thrown by the multicall
=> fix: add celo gas override

.github/workflows/test.yml
Attempting to run both `fewer` and `highest` strategies creates conflicts. We had it so we manually removed specific packages from being tested, which is super fragile.
=> build: only test for highest yarn-deduplicate strategy

package.json, yarn.lock
Swap details was not expanding on my local build. 
Need to update use-resize-observer to latest version (9.0.2), and this fixes the issue.
=> fix: fix swap details expanded not working on local build

src/components/AmplitudeAnalytics/TraceEvent.tsx, src/components/AmplitudeAnalytics/constants.ts, src/components/AmplitudeAnalytics/index.ts, src/components/CurrencyInputPanel/index.tsx, src/components/swap/ConfirmSwapModal.tsx, src/components/swap/SwapDetailsDropdown.tsx, src/components/swap/SwapRoute.tsx, src/pages/Swap/index.tsx
Added "shouldLogImpression" property, defaulting to true, onto TraceEvent component as well, because some events require conditional logging. For example, we want to log when the auto router visualization is opened, but not send the same event again when it is closed.
Events created by this PR: 
1. <img width="497" alt="Screen Shot 2022-07-20 at 4 58 24 PM" src="https://user-images.githubusercontent.com/41491154/180091562-6a3fee26-d0f1-4595-bdb1-edf44ec9b361.png">
2. <img width="468" alt="Screen Shot 2022-07-20 at 4 58 32 PM" src="https://user-images.githubusercontent.com/41491154/180091565-6c9dee8b-e90c-41f2-87d7-f25757adf16f.png">
3. <img width="491" alt="Screen Shot 2022-07-20 at 4 58 38 PM" src="https://user-images.githubusercontent.com/41491154/180091567-e37c451d-30b5-46c6-8501-e54941 …
=> feat: implement other swap events part 1

package.json, yarn.lock
=> chore: upgrade cypress

src/pages/App.tsx
When I was adding liquidity on my cellphone through the in-app browser of metamask, I noticed that every time I click the +/- buttons, the page would scroll to top:
Here's why it happens: when we click the +/- buttons, the url would change, e.g.,
from: `/#/add/ETH/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/3000?chain=mainnet&maxPrice=3261.7&minPrice=919.71`
to: `/#/add/ETH/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/3000?chain=mainnet&maxPrice=3261.7&minPrice=919.71`
I.e., the `history` object changes, hence `scrollTo` would get called every time I click the +/- buttons.
Which is obviously wrong, we shouldn't call `scrollTo` when query strings change because we are still on the same page.
=> fix: scroll to top only when pathname changes

src/pages/CreateProposal/index.tsx
Current Propose documentation link on line #241 directs to old doc page and resulting to Page Not Found error thus now
changed it to
https://docs.uniswap.org/protocol/reference/Governance/governance-reference#propose
=> fix: updated external docs link for Propose

src/theme/colors.ts
Update theme color (critical red) HEX
=> fix: update critical red HEX

src/components/AmplitudeAnalytics/constants.ts, src/components/AmplitudeAnalytics/index.ts, src/components/WalletModal/index.tsx
first PR, implement wallet related custom user properties. second PR coming up will implement the misc other custom properties, like "light_mode".
Note: I changed the last / first seen dates from WALLET last/first seen date to USER last/first seen date, because of the way amplitude Identify API works. hard to track last/first seen date by wallet.
=> feat: Web 262 user model custom properties first PR

.vscode/settings.json, src/components/Explore/TokenDetails/LoadingTokenDetail.tsx, src/components/Explore/TokenDetails/TokenDetail.tsx, src/pages/TokenDetails/index.tsx
make the loading state for token details page responsive based on screen width (to match loaded token details)
https://user-images.githubusercontent.com/62825936/181374884-243e42b3-268c-4885-b7b2-49f7d7d9382b.mov
=> fix: make token details loading state responsive

.vscode/settings.json, src/components/Explore/TokenDetails/BalanceSummary.tsx, src/components/Explore/TokenDetails/NetworkBalance.tsx, src/components/Explore/TokenDetails/Resource.tsx, src/components/Explore/TokenDetails/ShareButton.tsx, src/components/Explore/TokenDetails/TokenDetail.tsx, src/constants/chainInfo.ts
Update colors in token detail pages and add colors for network (no more deprecated!)
s
=> fix: update colors on token details page

src/components/AmplitudeAnalytics/constants.ts, src/components/AmplitudeAnalytics/utils.ts, src/components/SearchModal/CommonBases.tsx, src/components/SearchModal/CurrencySearch.tsx, src/components/swap/ConfirmSwapModal.tsx, src/components/swap/SwapDetailsDropdown.tsx, src/components/swap/SwapModalFooter.tsx, src/pages/Swap/index.tsx
1. quote_latency_milliseconds
2. duration_from_first_quote_to_swap_submission_milliseconds
Also changed native token address (eg: eth) from undefined to constant "NATIVE". 
I also modified where and how swap quote received is being logged. It was being logged twice previously (when there was little to no change in the trade). Now it's only logged when user inputs have changed, and only once (it doesn't log again when price updates/syncing occurs etc).
=> feat: add time / duration based event properties to swap events

src/components/Explore/TokenDetails/BalanceSummary.tsx
Add error state for network balance summary and do not display anything during loading state of network balances
=> feat: add error state for network balance summary

src/components/Explore/TokenDetails/TokenDetail.tsx, src/components/Explore/loading.tsx, src/constants/chainInfo.ts, src/theme/colors.ts, src/theme/index.tsx, src/theme/styled.d.ts
added network badge to token details page for Polygon, Optimism, and Arbitrum AND change loading state bubble color
=> feat: network badge on token details page

src/components/Header/NetworkSelector.tsx
At present, if you hover over the network selector to open the dropdown, the currently selected network text shows the text cursor.  This isn't text you'd want to copy, so the text cursor is inappropriate.  The default cursor is probably best.
Effects the cursor when hovering over this area:
=> fix: hide text cursor on network selector hover

src/components/AccountDetails/index.tsx, src/components/WalletModal/index.tsx, src/state/index.ts, src/state/wallets/hooks.tsx, src/state/wallets/reducer.ts, src/state/wallets/types.ts
Added functionality for amplitude wallet connect events to include is_reconnect field, which is true if the user's wallet is disconnected and reconnected without them pressing the disconnect button
=> feat: amplitude logs is_reconnect

src/components/Explore/TokenTable/TokenRow.tsx, src/pages/TokenDetails/index.tsx
remove underline for clickable link for Explore page
BEFORE: 
AFTER:
=> fix: rm underline for token details

src/hooks/useAutoSlippageTolerance.ts
Updates the local gas estimation algorithm used to compute auto slippage to be more similar to the one used in the Auto Router.
Adds a 10% buffer to the gas estimates overall. Gas estimates from the routing API sometimes under-estimate which can lead to very tight auto-slippage being set, especially on L2s where gas costs are low anyway
=> feat: Adjust gas estimates for auto slippage

.gitignore
Adds `.vercel` folder to gitignore. Only used when using vercel to build and deploy locally
=> ci: add .vercel to gitignore

src/components/SearchModal/CurrencySearchModal.tsx, src/pages/Swap/index.tsx
The new token safety components were exposed; added old token import component back in to be shown under phase0flag control
=> fix: phaseflagging token import modals

src/components/Header/NetworkSelector.tsx
My previous PR was a bit aggressive.  The intention of the PR can be verified as follows:
1.  Hover over the Network Selector's currently selected network -- see default cursor
2.  Hover over "Select a Network" -- see default cursor
3.  Hover over each network name in the list -- see pointer cursor, signaling that clicking would change something.
=> fix: Ensure proper cursor for network dropdown

src/components/Explore/TokenTable/TokenTable.tsx
fix background color on explore table
=> fix: change background color on Explore table

src/components/Explore/TokenTable/TokenTable.tsx
We can use the same number as the top tokens count (100) so that the loading state -> loaded state transition is seamless.
=> fix: update TokenTable loading row count

src/components/Charts/PriceChart.tsx
Defaults to the selected time period for the price chart data! Ideally, I'd like to consolidate the time period display stuff later on.
=> feat: use filterTimeAtom for PriceChart

src/lib/hooks/transactions/updater.tsx, src/lib/hooks/useBlockNumber.tsx
I was looking through the updater implementation and I noticed this hook is actually not being used.
=> refactor: removes unused useFastForwardBlockNumber

src/hooks/useAutoSlippageTolerance.ts
Currently Polygon txs are failing at a 30% rate, mostly with a slippage exceeded error. For now we will increase the slippage, but we need to find a root cause of the issue still (potentially on the auto-router api side).
=> fix: increase Polygon auto-slippage min

src/lib/hooks/useTokenList/fetchTokenList.test.ts
The tests are not comprehensive and are also using actual fetches to validate responses.
I'd be open to mocking the fetch calls (there are a few) and testing the other error cases if we feel that's a good use of time.
=> test: skip fetchTokenList tests

src/components/Header/NetworkSelector.tsx, src/hooks/useOnSelectChain.ts, src/hooks/useSelectChain.ts, src/hooks/useSyncChainQuery.ts, src/pages/App.tsx
- Combines 3 effects into one (for syncing the chainId query param)
- Moves syncing query param logic into App.tsx
- Creates `useSelectChain` useCallback
=> refactor: split ChainId useEffects

src/components/FeatureFlagModal/FeatureFlagModal.tsx
Was using the explore flag accidentally
=> fix: use tokenSafety flag in Modal

cypress/support/e2e.ts, src/hooks/useEagerlyConnect.ts, src/hooks/useOrderedConnections.ts, src/state/connection/constants.ts, src/state/user/reducer.ts
Removes the backfilling logic. Now that we've had the code merged in main for 2 months our active users will have had their `selectedWallet` properties set. This means that we only need to lazily load the various connectors after this is merged for new users, which should reduce load time.
We want to remove Fortmatic in a separate PR still, which has a very large load time and is not lazily loaded currency.
=> chore: remove selectedWalletBackfilled

src/components/Button/index.tsx, src/components/CurrencyInputPanel/index.tsx, src/components/Explore/TokenDetails/TokenDetail.tsx, src/components/Explore/TokenTable/FavoriteButton.tsx, src/components/Explore/TokenTable/SearchBar.tsx, src/components/Explore/TokenTable/TokenRow.tsx, src/components/FeatureFlagModal/FeatureFlagModal.tsx, src/components/NumericalInput/index.tsx, src/components/SearchModal/CommonBases.tsx, src/components/swap/SwapDetailsDropdown.tsx, src/pages/AppBody.tsx, src/theme/colors.ts, src/theme/index.tsx, src/theme/styled.d.ts
Deprecates theme.none in favor of explicitly using 'transparent'.
=> refactor: deprecate theme.none

src/components/AmplitudeAnalytics/constants.ts, src/pages/App.tsx
Creates a new event, `Web Vitals`, with properties for each web vital (CLS, FCP, FID, LCP). Sends each vital in a separate call because they are available at different times, through callbacks. This may result in multiple events, but [should be parseable in Amplitude using the median](https://community.amplitude.com/instrumentation-and-data-management-57/exploiting-event-properties-when-the-event-contains-several-properties-to-be-reported-core-web-vitals-292).
=> feat: send web vitals

src/hooks/useAutoSlippageTolerance.ts
Turns out the Polygon slippage issues were coming from specifically the v3 router and not the new swap router. We're going to make the interface only use the latest router and monitor.
=> fix: undo polygon auto-slippage changes

src/components/NavBar/MenuDropdown.css.ts, src/components/NavBar/MenuDropdown.tsx, src/components/NavBar/MobileSidebar.css.ts, src/components/NavBar/MobileSidebar.tsx, src/components/NavBar/NavDropdown.css.ts, src/components/NavBar/NavDropdown.tsx, src/components/NavBar/NavIcon.css.ts, src/components/NavBar/NavIcon.tsx, src/components/NavBar/Navbar.css.ts, src/components/NavBar/Navbar.tsx, src/nft/css/sprinkles.css.ts, src/nft/themes/darkTheme.ts, src/nft/themes/lightTheme.ts
- Adds tabs to route to the different pages in phase 0. Make sure you have the explore feature flag toggle on to see that path. 
- Adds sidebar menu that holds routes when on mobile and other routes such as socials, info, and governance
=> feat: add routing functionality to navbar

src/components/FeatureFlagModal/FeatureFlagModal.tsx, src/components/Header/index.tsx, src/components/NavBar/Navbar.tsx, src/featureFlags/flags/explore.ts, src/featureFlags/flags/tokens.ts, src/featureFlags/index.tsx, src/pages/App.tsx
For consistency, keeping the names aligned.
=> chore: rename flag explore -> tokens

src/theme/colors.ts
left off a colon when defining a new drop shadow color
=> fix: add missing colon to end of drop shadow color

src/components/Tokens/TokenDetails/BalanceSummary.tsx, src/pages/TokenDetails/index.tsx
fix: widget width and network balances align
=> fix: width of widget and network balances on token details

src/pages/App.tsx
Reverts Uniswap/interface#4400
The expected behavior was already correct. Under phase1, the padding-top should be 72px. Under control, it should be 120px. If there is any further misunderstanding here we should resolve it separately.
=> fix: Revert "feat: fix padding"

src/components/Tokens/TokenDetails/LoadingTokenDetail.tsx, src/components/Tokens/TokenDetails/TokenDetail.tsx
Token Details State when there is no token information available (e.g. we aren’t supporting Celo so will have no data for any token on that network): https://uniswaplabs.atlassian.net/browse/WEB-731
=> feat: add no information available state for token details

src/pages/Vote/VotePage.tsx
Fixes unresponsive image in description section of the vote page
=> fix: Fix unresponsive image in vote page

src/components/NavBar/MenuDropdown.tsx, src/components/NavBar/MobileSidebar.tsx, src/nft/pages/asset/Asset.tsx, src/nft/pages/sell/sell.tsx, src/pages/App.tsx
- I'll be working on migrating these two pages to the main app this week, this creates the placeholder files and routes in App.tsx behind the NFt feature flag
- Also added feature flagged routing to Sell page in the Navbar
Screenshots:
Blank Sell Page with Correct Pathing
Blank Details Page with correct Pathing
Desktop and Mobile Navbar w/o NFT Feature Flag
Desktop and Mobile Navbar w/ NFT Feature Flag
=> feat: Placeholder NFT Details and NFT Sell Pages

src/components/Tokens/TokenDetails/PriceChart.tsx, src/components/Tokens/TokenTable/TimeSelector.tsx, src/components/Tokens/TokenTable/TokenRow.tsx
fix time selector on Explore page to be accurate and also use PriceChart logic
Before: 
After:
=> fix: time selector updated to align with price chart 

.npmrc, package.json
This is the version we use to build on IPFS and is listed in our .nvmrc. Vanilla-extract also doesn't work on anything over 14 properly, so local builds won't work otherwise.
=> build: enforce node/npm versions

src/components/Tokens/TokenDetails/PriceChart.tsx, src/components/Tokens/TokenDetails/TokenDetail.tsx
Turned overflow off for TokenDetail's TopArea so that the chart would resize correctly
=> fix: chart size responsiveness issue

src/components/NavBar/Navbar.tsx
When we switched from `/explore` to `/tokens` the isActive check was not updated for the desktop navbar
=> fix: active state for Token Explore

src/components/Tokens/TokenTable/SearchBar.tsx
The border-width for the non-focused state is 1.5px, so we should not change that on focus.
Avoids this case:
https://user-images.githubusercontent.com/4899429/186234237-8f7c20cc-2ede-442c-8252-4e8e431867ae.mov
=> fix: makes SearchBar focus border-width consistent

src/components/Tokens/TokenDetails/LoadingTokenDetail.tsx, src/components/Tokens/TokenDetails/TokenDetail.tsx
Truncates token descriptions longer than 400 characters.
https://uniswaplabs.atlassian.net/browse/WEB-778?atlOrigin=eyJpIjoiNTBiOWExNDU1OThhNGRlNGJmMTg2OGFhNWY4OTQxYjQiLCJwIjoiaiJ9
=> fix: truncates to token details descriptions

src/components/Tokens/TokenTable/TokenRow.tsx, src/components/Tokens/TokenTable/TokenTable.tsx
=> fix: respect padding in cells with proper hover

src/components/DoubleLogo/index.tsx
The secondary icon on pool positions had a high zindex which caused it to display over navbar on scroll.
Before:
After:
=> fix: /pool position second icon zindex issue

src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx, src/components/CurrencyInputPanel/index.tsx, src/pages/Swap/index.tsx
revert currency input panel in non-swap use cases. 
for example in add liquidity: 
reason: redesign should exist in swap use case only, or else the other use cases look messed up.
=> feat: make currencyInputPanel redesign changes apply only to swap

src/components/AccountDetailsV2/LogoView.tsx, src/components/AccountDetailsV2/TransactionBody.tsx, src/components/Popups/PopupItem.tsx, src/components/WalletDropdown/SlideOutMenu.tsx
This is a follow up to this commit
https://github.com/Uniswap/interface/commit/9b07d8ce64878f5becf88cb6d8e77639b3493299
Added the following transactions
Wrap
Collect Fees
Approval
Claim
I tested, this is what it looks like
This is preloaded txs, but what uni and eth look like
=> feat: Adding in remaining transactions to transaction history

src/components/Tokens/TokenDetails/TokenDetail.tsx
1. Fix styling when no token info available
2. Make sure Read more button doesn't display when token description is short enough (sub 400 char)
=> feat: fix visual bugs on truncate token description

src/pages/Swap/index.tsx
removes UNI currency logo from swap widget approval button - https://uniswaplabs.atlassian.net/browse/WEB-920
before:
expected:
=> fix: remove UNI currency logo from swap widget approval button

src/components/Toggle/index.tsx, src/components/TransactionSettings/index.tsx
change toggle and input placeholder colors on swap settings flyout, and toggle padding - https://uniswaplabs.atlassian.net/browse/WEB-893
before:
after:
=> fix: change toggle and input placeholder colors on swap settings flyout 

src/components/AccountDetailsV2/TransactionBody.tsx
Noticed this while reviewing the most recent Crowdin PR.
=> fix: don't translate UNI

src/components/TokenSafety/index.tsx, src/theme/components.tsx
https://uniswaplabs.atlassian.net/browse/WEB-879
I'd refer to the ticket for the before view and figma spec for what it's supposed to look like now
For the close only render, I couldn't find a token that met the criteria, so the copy isn't correct but the color scheme is  
Screen Shots
=> fix: Fixing token modal warning to match figma design

src/components/NavBar/Navbar.css.ts, src/components/NavBar/Navbar.tsx, src/components/NavBar/SearchBar.tsx
As part of the updated mobile spec, full searchbar is shown on tablet (breakpoint md+) before switching to the magnifying glass icon on mobile (sm).
Screenshots:
=> feat: show searchbar on tablet size

src/components/NavBar/ChainSwitcher.tsx
Previously if a network had no info, nothing would be shown. Now it is treated as Unsupported.
Before:
After:
=> fix: bug with network with no info

src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
after this fix, clicking the reverse arrow doesn't cause the layout to move around subtly.
=> fix: fix swap small layout shifts when clicking reverse tokens button

src/components/Tokens/TokenDetails/LoadingTokenDetail.tsx, src/components/Tokens/TokenDetails/TokenDetail.tsx
- Moves About section below Market Stats
=> fix: Token Details - move About section below Market Stats

src/components/Tokens/TokenTable/TokenRow.tsx, src/components/Tokens/types.ts
- Changes copy text on '% change' column to include selected timeperiod, ie: '1D change'
Before
After
=> fix: update Token table headers to match latest Figma

src/components/swap/ConfirmSwapModal.tsx, src/components/swap/SwapModalFooter.tsx, src/state/transactions/updater.tsx
context: don't want to have to join on transaction_hash between Swap Submitted and Completed events.
=> feat: add volume trade info to swap completed event

src/components/Tokens/TokenDetails/PriceChart.tsx, src/utils/formatDollarAmt.tsx
Fix price formatting on token details page: Show 6 decimal points or <0.000001 (i.e. shouldn't show $0.00) - https://uniswaplabs.atlassian.net/browse/WEB-881
before:
after:
=> fix: fix decimal formatting of token price on details page

src/components/WalletDropdown/index.tsx, src/components/Web3Status/index.tsx, src/hooks/useOnClickOutside.ts
The issue
The mobile wallet would close when clicking on or interacting with it.  This occurred because the wallet is coded to close any time a click occurs outside the web3status ref.  In mobile, we were using a portal, so the wallet was technically outside of this ref.  The reason wallet is under the status ref is due to a tricky edge case.  Clicking the status should toggle the wallet close and clicking outside the wallet should also close it.  If the ref only lives on the wallet and not status, this would lead to an edge case that would close and then immediately reopen the wallet.  I put the wallet under status so that when clicking on it, you are not technically clicking outside of wallet.  This results in the proper behavior of closing the wallet when clicking status and closing …
=> fix: Fix to mobile wallet experience

src/components/WalletDropdown/DefaultMenu.tsx, src/components/WalletDropdown/SlideOutMenu.tsx, src/components/WalletDropdown/index.tsx
1. no border  radius on bottom of wallet for  mobile ui
2. no box shadow for mobile ui
3. Increased connect button width on mobile for disconnect
3. Stick back section was sticking out on language and transaction history menu.  I will come up with a better solution, but want this fixed for bug bash so I set width to 99% for now
=> fix: wallet mobile ui changes

src/components/Tokens/TokenTable/TokenRow.tsx
center the header text - https://uniswaplabs.atlassian.net/browse/WEB-983
before: 
after:
=> fix: vertically center the explore table header text

src/components/NavBar/ChainSwitcher.tsx, src/components/NavBar/NavDropdown.css.ts
Mobile network switcher wasn't full screen width and would close instead of switching networks when clicked on mobile. This fixes that.
Screenshots:
=> fix: mobile network switcher

src/pages/TokenDetails/index.tsx
rm right side padding on token details - https://uniswaplabs.atlassian.net/browse/WEB-989
before:
after:
=> fix: rm right padding on token details

src/components/Tokens/TokenTable/TokenRow.tsx
fix: formatted delta on mobile view of token explore
before: 
after:
=> fix: formatted delta on mobile view of token explore

src/components/Tokens/TokenTable/FavoriteButton.tsx
favorites button should only change to heart on 320px 
before:
after:
=> fix: fix favorites button responsiveness on tokens explore

src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
https://uniswaplabs.atlassian.net/browse/WEB-996?atlOrigin=eyJpIjoiZDdjZTY3N2JmNTI5NDBhYmJmNThmOTJlN2UyYzJlMjMiLCJwIjoiaiJ9
to reproduce: 
- dont connect any wallet
- dont select second output token
- click reverse tokens button on swap page
- there should be no layout movements
=> fix: stop swap layout shifts when reverse token button clicked

src/components/Header/NetworkSelector.tsx, src/lib/hooks/useCurrency.ts, src/utils/switchChain.ts
Since `isChainAllowed` was only being used for checking if Fortmatic could switch to a chain (only Mainnet was supported), we no longer need it. Now we can just check if it's an allowed chain, which `isSupportedChain` handles.
=> refactor: remove isChainAllowed

src/components/NavBar/SearchBar.tsx, src/components/NavBar/SuggestionRow.tsx, src/nft/utils/currency.ts
The trending collections endpoint is experiencing a bug and is returning collections with a null floor price. While this is being investigated by data team this allows for more graceful handling.
=> fix: add null check to collection floor price

src/components/NavBar/SearchBar.tsx, src/components/NavBar/SuggestionRow.tsx
Use `debouncedSearchValue` to prevent a flash of 'no tokens found' while typing
Dependent on #4528 
Screenshot:
=> fix: search flash of no tokens found when typing

package.json, src/components/Charts/LineChart.tsx, src/components/Charts/SparklineChart.tsx, src/components/Tokens/TokenDetails/PriceChart.tsx, src/react-app-env.d.ts
- Uses d3 curveCardinalOpen instead of d3-curve-circlecorners to fix inconsistency between glyph placement and chart line on steep data points.
=> fix: [TokenDetails] Glyph placement on line chart

src/components/Tokens/TokenTable/TokenTable.tsx, src/theme/colors.ts, src/theme/widget.ts
Update Dark Mode BackgroundModule to Grey800 to match new design spec
Update Widgets theme to use BackgroundModule for Module
Update Token List in Explore page to use Surface instead of Module
Add Scrolled Surface color definition
=> fix: updated color definitions for backgroundModule, add scrolledSurface

src/components/NavBar/NavDropdown.css.ts
Hide's left and right border on mobile dropdowns as requested by https://uniswaplabs.atlassian.net/browse/WEB-1001
Screenshots:
=> fix: hide right and left border on mobile dropdown

src/components/Tokens/TokenDetails/PriceChart.tsx
=> fix: missing segments of price chart

src/components/WalletDropdown/DefaultMenu.tsx, src/components/Web3Status/index.tsx
https://uniswaplabs.atlassian.net/browse/WEB-988
1. The divider border top/bottom were overlapping causing it to be too big.  Setting only border-bottom fixes this
2. Request for button size to be reduced slightly
=> fix: Fixing border overlap and reducing button size

src/components/Tokens/TokenDetails/PriceChart.tsx, src/utils/formatChartTimes.ts
for year view we want to consistently show the 1st of the month, not vary between 1st and end of month on diff ticks. 
before:
after:
=> fix: modify chart axis to to match crosshairs in year view

src/components/NavBar/SearchBar.tsx
- When using universal search, the first suggestion, either via trending, recent history, or actual search results will be highlighted by default. Pressing enter will let you select that highlighted option.
- Fixed a bug where arrow down would scroll behind the results
Screenshots:
=> feat: highlight first result by default

src/components/Tokens/TokenTable/TokenRow.tsx
- On TokenRows the line number cell had a different height than the rest of the row causing misalignment. This PR bumps the height to match (conditionally, based on a header boolean flag so the header row does not change). 
Before
After
=> fix: Bump height on LineNumberCell and pass header boolean

src/components/Tokens/TokenTable/FavoriteButton.tsx, src/components/Tokens/TokenTable/NetworkFilter.tsx, src/components/Tokens/TokenTable/TimeSelector.tsx, src/theme/index.tsx, src/theme/styled.d.ts
To avoid special-casing a specific color into the theme, we are migrating all usage of theme.blue200 to theme.accentActive.
=> chore: remove theme.blue200

src/components/NavBar/SearchBar.css.ts, src/components/NavBar/SearchBar.tsx
- Fixes issues seen on Safari desktop and iOS where searchbar and magnifying glass icon would shift around
- Bug was caused by absolute positioning and flexbox being handled differently(and inconsistently) by Safari vs Chrome/Firefox
- Fixed by changing searchbar's container from flex to `inline-block`
- Undoes fix #4556 in favor of this solution
Screenshots:
Safari desktop
Chrome on iOS
https://user-images.githubusercontent.com/11512321/187941529-5c642f33-a865-492c-9f16-f73607f01b9f.MP4
=> fix: change from flex to inline to fix safari bugs

src/components/NavBar/SuggestionRow.tsx
https://uniswaplabs.atlassian.net/browse/WEB-976?atlOrigin=eyJpIjoiYmQxOGQzYzU4MjVjNDEyOGFjOWIyMjRhY2U0MzkzZGEiLCJwIjoiaiJ9
I tested before and after typing "SHI" into search bar.
=> fix: remove warning icon on search 

src/components/Web3Status/index.tsx
Per this conversation: https://uniswapteam.slack.com/archives/C02T729PMQE/p1662576603879399?thread_ts=1662576192.202619&cid=C02T729PMQE
We have inconsistent size of avatars on web status.
=> fix: Making sure all icons are 24px

src/hooks/useBestTrade.test.ts, src/hooks/useBestTrade.ts, src/hooks/useStablecoinPrice.ts, src/lib/hooks/routing/clientSideSmartOrderRouter.ts, src/lib/hooks/routing/useRoutingAPIArguments.ts, src/state/routing/slice.ts, src/state/routing/useRoutingAPITrade.ts
- Cache AlphaRouter (instead of the BaseProvider passed to the router), to prevent router re-instantiation
- Adds a new RouterPreference: PRICE
- Adds the ability to explicitly tune each preference: API, CLIENT, PRICE
-  A PRICE tuning is defined, but unused - this will be activated after determining the performance of router caching
=> feat: optimize AlphaRouter usage

src/connection/index.ts, src/constants/networks.ts, src/hooks/useFetchListCallback.ts, src/lib/hooks/useBlockNumber.tsx, src/state/routing/slice.ts
Use StaticJsonRpcProvider when able to avoid re-fetching chainId with every event loop.
About halves the number of JSON-RPC requests to infura.
=> fix: use static rpc urls

src/state/routing/useRoutingAPITrade.ts
There shouldn't be a need to refetch on focus as we keep the state in sync regardless. This will reduce a large number of Infura requests we make via the smart-order-router.
=> fix: remove refetchOnFocus for routing-api

src/components/NavBar/SearchBar.tsx
There was a bug where after pressing enter on the searchbar, changing tabs, and then changing back, the searchbar would open. This fixes that bug.
Screenshots:
=> fix: bug where changing tabs can open the searchbar

src/components/NavBar/SearchBar.css.ts, src/components/NavBar/SearchBar.tsx
Previously, when the universal search input was shifted to the center in the unopened state for phase 0, the width would not change and the user could click or hover to the right of the searchbar and trigger the open search or hover state respectively. This bug adjusts the width of the input to fix this.
Screenshots:
=> fix: adjust search input width

src/featureFlags/index.tsx
- Avoids including the set value in the deps - instead uses the current value from the setter
- Sets a new reference for the value, triggering a re-render
=> fix: update feature flags on update

src/pages/Swap/index.tsx
Fetches the stablecoin price without waiting for the quote API to resolve.
=> fix: fetch the usd price from parsed amount

src/components/NavBar/MenuDropdown.tsx, src/nft/components/collection/Card.tsx, src/nft/components/details/Traits.tsx, src/pages/App.tsx
* fix pointing nft links to `/nfts` vs. `/nft`
=> fix: pointing nft links to the right url hash

src/components/Tokens/TokenDetails/PriceChart.tsx
On the Token Details price chart, when selecting all the x-axis tick intervals were too short causing overlaps in the tick labels: 
Before: 
After:
=> fix: Tick collisions on token detail price chart

package.json, src/components/Widget/index.tsx, yarn.lock
- Upgrades @uniswap/widgets to 2.8.1
- Passes in app-defined providers to the widget
- Avoids creating additional network providers, and uses any add'l features of the app providers (ie caching, tracing)
=> feat: upgrade widget

src/components/NavBar/MenuDropdown.css.ts
- add full width to secondary menu links
=> style: Extend hover on secondary dropdown menu links

src/components/Tokens/TokenDetails/PriceChart.tsx
- Tweaks curveTension on 1H chart to fix line tapering
Before:
After
=> fix: Token Details chart: adjust curveTension on 1H chart timeframe

src/theme/components.tsx
Instead of defaulting to the center of the parent, we show the text where the button was clicked.
=> fix: show copied text where address was clicked

src/components/Tokens/TokenDetails/PriceChart.tsx
before: display price and % delta only loads after scrubbing
after: display price and % delta correctly set to ending price upon first load of token detail page. 
https://uniswaplabs.atlassian.net/browse/WEB-1113?atlOrigin=eyJpIjoiMDg0NzNlNjI3NjM5NDcxYThhYjA5NWFlNzJlNzBmZTEiLCJwIjoiaiJ9
=> fix: load correct initial display price and % delta w/o need for scrubbing on token detail chart

src/components/Tokens/TokenDetails/FooterBalanceSummary.tsx
To buy a certain token, it should be the output token, not input token.
=> fix: pass outputCurrency not inputCurrency

src/components/AmplitudeAnalytics/index.ts
We should just have one event function to track, and that function should send to the correct instance based on your API key and environment. If events aren't supposed to be sent to production that should be validated within this function rather than enforcing a separate function.
=> fix: remove sendTestAnalyticsEvent

src/components/Widget/inputs.tsx
When the URL of a page changes the defaultToken of the Widget should change. Right now that state doesn't get reset on re-renders, so you may see a stale token input.
=> fix: updates Widget defaultToken on URL change

src/components/Web3Provider/index.tsx
Added optional chaining to networkProvider to fix an error that causes the interface to crash when the user while being connected switches the network from an unsupported one to a supported one.
=> fix: networkProvider error

src/components/Web3Status/index.tsx
=> fix: center Web3StatusConnectButton

cypress/e2e/wallet.test.ts, src/components/WalletModal/index.tsx
Once the new Web3Status is released we can deprecate the Wallet info view in WalletModal as well
=> fix: close WalletModal on connection

src/components/Popups/index.tsx
Since the header height changed we want to make sure the error is always visible. Ideally, this should be done more dynamically but that's outside the scope of this fix.
=> fix: makes sure wallet error is visible

src/components/NavBar/SearchBar.css.ts
after:
before:
Honestly, not sure why this is necessary. I think longer term we'll want to handle this horizontal centering within Nav via `justify-self: center` rather than fixed positioning.
=> fix: center SearchBar vertically

src/components/Tokens/TokenDetails/PriceChart.tsx
chart changes:
1) make chart full width as per https://uniswaplabs.atlassian.net/browse/WEB-1181?atlOrigin=eyJpIjoiMzYwN2VmOWYwOGJlNGY1ODlkYTMyNGM5N2M4OWFkM2EiLCJwIjoiaiJ9
2) add offsets to start and end time in x axis so the dates dont get cut off (because chart extends full width now) 
3) Limit to 6 ticks on "All" time chart, which has variable time frame, to avoid situations like this:
=> fix: make token detail chart full width and x axis fixes

src/analytics/constants.ts, src/hooks/useWrapCallback.tsx
Throw an error before deposits can be made to the wrapped native currency on the wrong chain.
Includes a deep link in the error message for filing a bug, to encourage reporting.
=> feat: weth check

src/components/Tokens/TokenDetails/BalanceSummary.tsx, src/components/Tokens/TokenDetails/FooterBalanceSummary.tsx, src/pages/TokenDetails/index.tsx
When balance is non zero: 
When balance is zero:
=> fix: show real balance in footer summary instead of dummy data

src/components/Tokens/TokenTable/SearchBar.tsx, src/components/Tokens/TokenTable/TokenRow.tsx, src/components/Tokens/TokenTable/TokenTable.tsx, src/graphql/data/TopTokens.ts
1) get rid of data flickering when you change time period 
2) fix search string being ignored if you change the time period you’re viewing
3) make search filter queries reset /disappear when you navigate to a different page and come back. 
4) when user starts typing a search term, show correct number of loading rows (we have this info from prefetched top 100 tokens query), and load actual rows once price history token data becomes available. 
5) add local "cache" of preloaded tokens with price history (if we have already rendered them previously)
=> fix: fix explore table filtering and sorting bugs

src/components/Tokens/TokenTable/SearchBar.tsx, src/pages/Tokens/index.tsx
eliminates the random flash of data you see when you have a filter string in explore token, navigate away to another tab, then navigate back.
=> fix: simplify search bar filter string handling and reduce # of state changes

src/components/NavBar/ShoppingBag.css.ts, src/nft/components/collection/Card.css.ts, src/nft/components/collection/Card.tsx, src/nft/css/sprinkles.css.ts, src/nft/themes/darkTheme.ts, src/nft/themes/lightTheme.ts
- Update card colors to match figma
- Has states for permutations of: 
- hovered vs not hovered
- In bag and not in bag
- For sale and Not For Sale
- Rename backgroundAction to accentAction
=> refactor: update card colors and rename backgroundAction

src/components/Tokens/TokenTable/SearchBar.tsx, src/pages/Tokens/index.tsx
Reverts Uniswap/interface#4716
introduces new bugs: when you change duration with a filter applied, it clears the filter string and doesn't filter.
=> fix: revert simplify search bar filter string handling and reduce # of state changes"

src/nft/components/collection/Card.css.ts, src/nft/css/sprinkles.css.ts, src/nft/themes/darkTheme.ts, src/nft/themes/lightTheme.ts
Add deep shadow as detailed in Figma specs
Add deep shadow to nft cards on hover
=> feat: add deep shadow on card hover

src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
Also essentially a bug fix so it's not behind redesign flag.
After:
https://user-images.githubusercontent.com/4899429/192634591-1ecdb66d-52e9-44cf-9e4b-dc1eaa72fd89.mov
Before:
https://user-images.githubusercontent.com/4899429/192635523-379f6167-0d78-40fb-8f0d-9fc11aa45c77.mov
=> fix: no hover on balance text in swap

src/components/CurrencyInputPanel/FiatValue.tsx
After:
https://user-images.githubusercontent.com/4899429/192635111-1efd48d9-66d2-4aa2-a807-fcdb9711ccf9.mov
Before:
https://user-images.githubusercontent.com/4899429/192635523-379f6167-0d78-40fb-8f0d-9fc11aa45c77.mov
Discussed with Fred that this isn't worth gating since it's more of a bug than part of a re-design.
=> fix: no hover on price estimate in swap

src/components/Tokens/TokenDetails/PriceChart.tsx
=> fix: center TimeButton in PriceChart

src/components/Tokens/TokenTable/NetworkFilter.tsx
=> fix: network filter container shouldn't expand on mobile

src/components/NavBar/SearchBarDropdown.tsx
Generally, we should not be ignoring exhaustive deps checks as it can lead to subtle bugs. I believe the component is working still while adding this back in.
The core issue is we should not be storing React elements in state from a useEffect. We should be caching just the data and re-rendering the components as needed. If that is expensive then we should be memoizing the component. I think for now we can do this, but should re-think the architecture a bit potentially.
=> fix: remove ignore exhaustive deps in SearchBarDropdown

src/components/Widget/index.tsx, src/pages/TokenDetails/index.tsx
=> fix: update TokenDetails layout sizing

src/components/Tokens/TokenDetails/PriceChart.tsx, src/components/Tokens/TokenTable/TokenRow.tsx
=> fix: display 0 percent change on explore

src/pages/TokenDetails/index.tsx
When the text doesn't take up the full space of the container, the max-width won't be reached by the left panel. Instead, we want to expand fully up until we hit the max-width.
=> fix: grow left panel in token details

src/components/LiquidityChartRangeInput/index.tsx
This condition will always return 'false' since JavaScript compares objects by reference, not value. ts(2839)
=> fix: Comparing formattedData reference with [] doesn't work as expected

src/nft/components/collection/Card.tsx
* updating tooltip to "This NFT is part of a liquidity pool. Buying this will increase the price of the remaining pooled NFTs."
=> chore: updating pool tooltip

src/components/Header/ChainConnectivityWarning.tsx
https://uniswaplabs.atlassian.net/browse/WEB-1324?atlOrigin=eyJpIjoiNWM3OTFjYzVjY2Q2NDg3NWIyODI2N2M3M2ZmN2ZlOWQiLCJwIjoiaiJ9
i got these screenshots by forcing the connectivity warning to always be displayed temporarily:
=> fix: update network warning styling

src/components/Widget/index.tsx, src/pages/TokenDetails/index.tsx
Fixes an issue where the widget was being cleared because the token was reinstantiated in every render.
Also fixes the same issue with balance checking.
=> fix: memoize tokens in TokenDetails

src/components/Tokens/TokenTable/TokenTable.tsx, src/graphql/data/TopTokens.ts
https://uniswaplabs.atlassian.net/browse/WEB-1377?atlOrigin=eyJpIjoiYjZmMTFiYmNhN2ZhNGI1MGI5ZjgxM2M4YzgzZDIzOTkiLCJwIjoiaiJ9
tldr relay is not my friend lmao. 
summary of problem: 
usePrefetchTopTokens, aka useLazyLoadQuery from relay, was refetching and returning a "new" list of top 100 tokens even though nothing had changed (duration, chain) on each load more. hence you see things flashing and scrolling and looking generally awful because the whole table is reloading. 
^ this wasn't happening in the last demo, but somehow that has changed....
solution: 
i'm now using good old fetch query -> toPromise to STOP the unnecessary reloading. see new function loadTokensWithoutPriceHistory.
=> fix: glitchy lazy loading (big jump / unnecessary scroll)

src/components/Tokens/TokenTable/TokenTable.tsx, src/graphql/data/TopTokens.ts
after fix loom: https://www.loom.com/share/a0f5b0bb59f2435081297f2328571b78
Notice: 
- when you search something, it already knows how many rows there will be, so we show that number of loading rows
- when you change duration (with a filter applied), the same number of rows will exist with new duration. so we show that number of loading rows.
=> fix: make number of loading rows make more sense when filtering, changing duration etc

src/nft/components/collection/CollectionStats.css.ts, src/nft/components/collection/CollectionStats.tsx
1. I noticed a loading state wasn't showing properly b/c it is missing a height.  
2. It wasn't working because it wasn't showing due to the loading state.  I added it as a hook dependency to recheck once the state loads
=> fix: fixes show more not showing on long collection description

src/components/swap/SwapDetailsDropdown.tsx, src/pages/Swap/index.tsx
This allows the dropdown to be clicked by making sure the :before element doesn't swallow the click event.
=> fix: allows SwapDetailsDropdown to be opened

src/graphql/data/Token.ts, src/pages/TokenDetails/index.tsx
52W high/low was missing after switching to the graph, now it's available again
=> feat: add 52 w highlow

src/components/Tokens/TokenDetails/ChartSection.tsx, src/graphql/data/Token.ts, src/pages/TokenDetails/index.tsx
TokenDetails now uses one hook to fetch priceHistory data and token data in tandem for faster render time. This also prevents the page from ever re-suspending/rendering upon switching time durations
=> perf: improve token details query performance

src/components/CurrencyInputPanel/SwapCurrencyInputPanel.tsx
[When updating ](https://github.com/Uniswap/interface/pull/4771) introduced a bug where the selected/hover states were reversed.
=> fix: update hover states in control CurrencyInputSelector

src/components/Tokens/TokenDetails/PriceChart.tsx
=> fix: center TimeButton in PriceChart horizontally

src/components/NavBar/SuggestionRow.tsx, src/components/NavBar/index.tsx, src/components/Tokens/TokensBanner.tsx, src/graphql/data/util.ts, src/hooks/useGlobalChainSwitch.ts, src/pages/Tokens/index.tsx
this is a code organization/QoL patch
`useGlobalChainName` is currently exported from `src/graphql/data/utils` and accesses the connected chainId from redux (non-standard).
the `useGlobalChainName` doesn't need to be a hook and is more useful if it accepts chainId as a parameter. 
I've renamed it to `chainIdToBackendName`, which better explains the purpose of the util in the graphql context and allows more flexible usage.
=> fix: refactors the way chainId is accessed in some places

cypress/e2e/add-liquidity.test.ts, cypress/e2e/remove-liquidity.test.ts, cypress/support/e2e.ts, cypress/support/ethereum.ts, src/utils/anonymizeLink.test.ts, src/utils/getExplorerLink.test.ts
Skips the tests that require the Goerli test environment to work properly for now, which we can add back later.
=> test: use goerli

src/components/Tokens/TokenTable/TokenRow.tsx
=> style: increase name column width in token table

src/components/Tokens/TokenDetails/BalanceSummary.tsx, src/components/Tokens/TokenDetails/MobileBalanceSummaryFooter.tsx, src/pages/TokenDetails/index.tsx
There's some inconsistency with the nft codebase's use of breakpoints that don't match those in `src/theme/index.ts`. I've tried to get as close to the figma's spec as I can without touching the nft team's navbar code, as I don't feel confident adjusting their work there w/o a significant amount of debugging/communications work.
=> fix(token-details): make breakpoints more consistent and use only theme.breakpoint values

src/utils/formatDollarAmt.test.ts, src/utils/formatDollarAmt.ts
when numbers r tiny (< 0.1), we want precision to 3 sig figs. otherwise, we want up to 3 decimals.
=> fix: handle tiny numbers

src/components/Tokens/TokenDetails/PriceChart.tsx, src/utils/formatDollarAmt.test.ts, src/utils/formatDollarAmt.ts
1) adds comma to thousands in prices (eg: $1000 => $1,000) 
2) format token details price properly
This PR fixes #2 and #3 on this jira: https://uniswaplabs.atlassian.net/browse/WEB-1487?atlOrigin=eyJpIjoiNjY4ZDBiZTY3NWUxNGM4Y2IzMmZhMGIzMGVkZjFlNzAiLCJwIjoiaiJ9
=> fix: price formatting spot check fixes

src/components/NumericalInput/index.tsx, src/theme/colors.ts
Swap input placeholder text color was textSecondary when it should be textTertiary.
Before:
After:
Also fix border-radius color to be more minimal.
=> fix: Update input placeholder text color

src/components/NavBar/SearchBarDropdown.tsx, src/nft/hooks/useSearchHistory.ts
Syncs searchHistory with trendingTokenResults, which were otherwise (potentially) fetching more updated results than the searchHistory cache.
WEB-1508
=> fix: keep search history synced with trending

src/components/Tokens/TokenTable/TokenRow.tsx
Since we now show the rank based in sorting order not just index... we should track both
=> fix: track token_list_rank

src/pages/Tokens/index.tsx
Looks this isn't necessary as we do the loading states inline now.
=> chore: remove unused TokensLoading

src/components/Tokens/TokenDetails/MobileBalanceSummaryFooter.tsx, src/pages/TokenDetails/index.tsx
Uses the same address creation logic from the parent
=> fix: updates outputCurrency link in mobile balance footer

src/components/Tokens/TokensBanner.tsx, src/pages/Tokens/index.tsx
We don't need the logic to specifically route to the chain in the /tokens url as the redirect happens in Tokens page component.
We also need to replace the url instead of redirecting, so that backspace will work.
=> fix: handle backspace out of /tokens

src/components/Tokens/TokenDetails/MobileBalanceSummaryFooter.tsx, src/components/Tokens/TokensBanner.tsx, src/pages/TokenDetails/index.tsx, src/pages/Tokens/index.tsx
- Revert "fix: handle backspace out of /tokens (#4879)"
- Revert "fix: add padding-bottom to TokenDetailsLayout (#4882)"
- Revert "fix: updates outputCurrency link in mobile balance footer (#4885)"
=> revert: removing phase0 bug fixes temporarily

public/index.html, src/theme/RadialGradientByChainUpdater.ts
since we needed to check feature flags before we showed phase0, the old `background` value was always the first thing to render
=> fix: remove old background-color flash

package.json, src/components/Widget/index.tsx, src/components/Widget/inputs.tsx, src/lib/hooks/useCurrency.ts, src/lib/hooks/useCurrencyBalance.ts, src/pages/TokenDetails/index.tsx, yarn.lock
- Prevents balance fetching cross-chain. Balances are fetched on-chain, so cross-chain balances would be invalid.
- Adds an onSwitchChain handler to the widget to allow it to control the global chain.
- This requires upgrade of the widget.
- In order to make this visually clean, also adds hysteresis to the widget:
- A loading token does not update the widget's output token.
- The widget will continue to render as a skeleton until it has a token specified.
- Loads the Token Details token (the initial widget token) using query data.
- This is faster (fewer on-chain calls), only requiring a call for decimals.
- Uses the RPC provider for the cross-chain, if applicable, to ensure valid data.
---
REVIEWER: These changes are split across specific commits. You may review this as one PR, but you …
=> feat: load token from query data

src/analytics/Trace.tsx, src/analytics/index.ts
add origin property to every analytics event, not just trace events. request from @blairmason
=> fix: add origin to every event

src/components/Widget/inputs.tsx
Use Currency.equals for Currency comparison in the widget wrapper.
This prevents the same currency from appearing in both input and output in the widget.
=> fix: disallow duplicate currencies in widget

src/graphql/data/util.ts
Clears extensions from unwrapped tokens so that the wrapped token is not considered native for other chains, which would result in bad links (using the wrapped address instead of NATIVE).
=> fix: prevent marking x-chain wrapped as native

src/components/CurrencyLogo/index.tsx, src/components/Tokens/TokenDetails/ChartSection.tsx, src/pages/TokenDetails/index.tsx
Passes the loaded WrappedTokenInfo (which includes a logoURI) into the chart header so its logo can be displayed.
Falls back if the queried data's logoURI fails (which was occuring for Optimism USDC).
=> fix: display loaded logo on token details

src/theme/index.tsx
Now that we have ungated phase0, we can continue to have `deprecated_colorX` to use the current hex values in the new theme. However, over time we should move away from using the colors directly towards using the theme variables. This can be done incrementally and separately.
=> chore: remove deprecated colors

src/components/Tokens/TokenTable/TokenRow.tsx
Since the clickable area is the entire cell, we should make sure the hover state shows for any part of the cell.
=> fix: hover state shows for full header cell

src/pages/TokenDetails/index.tsx, src/state/lists/updater.ts
Moved token warning to allow it to appear even when backend returns no data for a token
i.e. Grump Cat at http://localhost:3000/#/tokens/ethereum/0x93B2FfF814FCaEFFB01406e80B4Ecd89Ca6A021b
the unsupported tokenlist also appeared to be failing to skip validation locally so I also modified the list updater code. (These lists need to skip validation because many blocked tokens have long names that don't fit validation criteria)
=> fix: show blocked tokens warning

src/components/swap/AdvancedSwapDetails.tsx, src/components/swap/SwapDetailsDropdown.tsx, src/components/swap/SwapModalHeader.tsx, src/components/swap/SwapRoute.tsx, src/components/swap/styleds.tsx, src/pages/Swap/index.tsx
Necessary so we can remove the redesign flag from base components.
=> chore: remove redesign flag in swap

src/components/SearchModal/CurrencySearch.tsx, src/lib/hooks/useTokenList/sorting.ts
Configured token selector to show wrapped native assets at top of token selector list by default
Also fixed bug where ETH wouldn't show up when searching "ether"
+ small performance improvements in sort methods
WEB-1176
=> feat: show wrapped native asset at top of token selector

src/components/Popups/PopupItem.tsx, src/components/WalletDropdown/SlideOutMenu.tsx
Scroll no longer works on language and transactions overflow, this a quick fix for that.  I picked a height slightly larger than the wallet that should fit for pretty much any screen size to allow users to select all languages
Bugs:
fix
=> fix: overflow and empty popup

src/components/Tokens/TokenTable/TokenRow.tsx, src/components/Tokens/TokenTable/TokenTable.tsx
This makes sure that there is no jump once the tokens are loaded
=> fix: add padding to LoadingRow

src/components/Tokens/TokenTable/TokenTable.tsx
Since the LoadedRows do not have a margin top, there shouldn't be any on LoadingRows either. This way there isn't a jump once the data is fetched.
=> fix: no margin-top for LoadingRows

src/components/WalletModal/index.tsx
Syncs the network connector to any active user connector (eg wallet) while the network connector is not the priority connector. Effectively, this maintains the network connector chain when a wallet is disconnected.
=> fix: sync network connector to wallet

src/components/SearchModal/CurrencySearch.tsx, src/hooks/Tokens.ts
To reproduce the bug this PR fixes in main, search in token selector by contract address i.e. 0x0cEC1A9154Ff802e7934Fc916Ed7Ca50bDE6844e, acknowledge warning, and then try to search for it again.
Fixed by including user-added tokens when search input exists
=> fix: token selector contract address search

src/components/Tokens/TokenDetails/LoadingTokenDetails.tsx, src/components/Widget/index.tsx, src/components/Widget/inputs.tsx, src/pages/TokenDetails/index.tsx
Updates the Token Details page to match the token selected in the widget, if the current page's token is no longer displayed.
NB: This has a visual bug where navigating to the new token goes back to a LoadingTokenDetails state. <s>I'm working on fixing this, but it will likely be a follow-up (unless it is a very small change).</s> This is fixed in a follow-up: #4981.
See WEB-1467
=> feat: navigate to widget-selected token

src/components/WalletModal/index.tsx
Removes the internal border in the connect wallet border, which should not be included.
The only border should be on the entire modal. The existing border is adjacent to WalletConnect with no padding, so it does not look good.
_Before_
_After_
=> fix: rm connect wallet border

src/components/NavBar/SuggestionRow.tsx
Verified icons for collections in Search were accidentally deleted. This re-adds them.
=> fix: re-add verification icon for collections in search

src/components/Widget/inputs.tsx
Tracks whether the default has been set in the widget, so that a new default can be displayed immediately (with useMemo) instead of waiting for an effect to run.
This allows navigations to show the widget without showing a flash of old state.
=> fix: display updated widget token immediately

src/nft/utils/currency.ts
This makes sure we show <0.001 ETH for any usage of this function.
=> fix: show <.001 ETH in collection floors

.github/workflows/release.yaml
Right now if someone merges a PR on Thursday afternoon it won't deploy until Monday. I don't think that's preferable since we will have someone available during working hours on Friday incase any issues arise.
I can't tell how to test a github action, but I don't think there's a good way.
=> build: deploy on friday AMs

src/components/NavBar/SearchBarDropdown.tsx, src/nft/queries/genie/SearchCollectionsFetcher.ts
When restructuring GenieCollection type, floor price stopped showing in universal search results. This fixes that bug.
=> fix: add back floor to search results

src/nft/utils/asset.ts
Marketplaces returned from gql are in all caps, this has them match the format of the public icons.
=> fix: marketplace icons on details page

src/graphql/data/RelayEnvironment.ts, src/graphql/data/nft/Asset.ts
Implements NFT polling on a 999ms interval if the user has not yet loaded any additional pages.
- Fixes the RelayEnvironment to allow bypassing the cache (using `fetchQuery`), by removing the redundant cache around `fetchGraphQL` and relying solely on the store.
- Fixes Asset.ts to memoize returned assets, preventing redundant work in render cycles when they have not changed.
- Implements polling using the technique described in the relay docs: https://relay.dev/docs/guided-tour/refetching/refetching-queries-with-different-data/#if-you-need-to-avoid-suspense-1
- The InfiniteScroll does not mark which asset the user has on-screen, and does not use window virtualization, so polling only occurs if the user has not yet loaded any additional pages. This is necessary to avoid loading …
=> feat: nft polling

src/constants/providers.ts, src/lib/hooks/useBlockNumber.tsx, src/state/routing/useRoutingAPITrade.ts
- Updates network providers to only poll for a new block every 12s, to match mainnet's block frequency.
- Exports this polling interval, and reuses it for routing staleness.
=> fix: only poll every 12s

src/nft/components/profile/view/WalletAssetDisplay.tsx
markets returned from gql are in all caps, convert to lowercase to show correct icon
=> fix: lowercase markets for gql profile cards

src/nft/components/explore/TrendingCollections.tsx
=> style: Fix Trending Table filter borders on Safari (mobile & desktop)

src/nft/components/explore/CollectionTable.tsx
Handle null floor value for sorting on Explore Table.
=> fix: sort explore table null values

src/nft/pages/collection/index.tsx
Nouns for example have no banner image, so if that's the case we should just make the bg empty.
=> fix: show transparent box on empty banner

src/components/Loader/index.tsx
the loader does not currently show up when doing a swap transaction.  This is because the stroke color defaults to accentAction instead of prioritizing the stroke first
Before
After
=> fix: fixing loader

src/graphql/data/nft/Asset.ts, src/nft/components/collection/CollectionNfts.tsx, src/nft/components/collection/Sweep.tsx, src/nft/utils/calcPoolPrice.ts
Replace sweep queries with graphql. This is the last query that'll need to be migrated.
Out of Scope:
- Apollo migration
- Adding larvalabs and sudo to Sweep (routing code currently doesn't support)
=> refactor: replace sweep query with gql call

src/components/NavBar/SearchBar.tsx
This will avoid failing requests in productions, since we can't avoid the rule of hooks (useQuery can't be conditionally called).
=> fix: don't fetch collections without flag

src/components/Widget/inputs.tsx
Clears the amount when the token with an amount is switched.
Swaps the active token if the token with an amount is moved to the other spot.
=> fix: clear or retain amounts on token select

src/pages/App.tsx
Initializes analytics outside of React. Initializing inside of React often leads to multiple calls, and initializeAnalytics is not set up to be idempotent.
=> fix: initialize analytics outside of react lifecycle

src/nft/components/collection/CollectionNfts.css.ts, src/nft/components/collection/CollectionNfts.tsx, src/nft/components/collection/FilterButton.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2064
1. The box shadow from the nfts shows the edges of the navbar
2. Moving everything 14px in (left and right) moves the edges of the navbar away from the box shadow so it doesn't show the edges
3. 14px was the smallest width I could find where this works
4. See Jira for before and after
=> fix: fixing header on light mode

src/hooks/useMachineTime.ts, src/lib/hooks/useInterval.test.tsx, src/lib/hooks/useInterval.ts
Updates `useInterval` to defer the next interval until the callback has completed.
For synchronous callbacks, this has no effect. For callbacks returning a `Promise`, this prevents stacking invocations, should the invocation take longer than the interval.
=> fix: defer useInterval until callback resolves

src/nft/components/collection/Card.tsx, src/nft/components/collection/CollectionAssetLoading.tsx, src/nft/components/collection/CollectionNfts.tsx
Sets the loading assets to the same height as loaded assets.
This also fixes an inconsistent bug where the uniformHeight would be reset due to an inconsistent aspect ratio.
=> fix: enforce uniform asset height

src/graphql/data/nft/Asset.ts
Disables polling after scroll event loads more assets. Stops bug where loading more than 100 assets causes the page to refresh. TODO is to figure out how to continuously poll the first 25 assets after scroll. Optional to setup pullDownToRefresh on infinite scroll component.
=> fix: disable polling after scroll

src/nft/css/common.css.ts
Updated `headlineLarge`, `headlineMedium`, and `headlineSmall` to adhere to latest design system by changing the font weight from `normal` to `medium`. 
This also fixes [this issue](https://uniswaplabs.atlassian.net/browse/WEB-2037), which asks for a thicker font on NFT collection pages.
I tested by manually viewing pages affected by these updates and making sure the font weights looked alright.
=> chore: Change font weights for headlines from normal -> medium.

src/nft/components/details/AssetPriceDetails.tsx
Fixes https://uniswaplabs.atlassian.net/browse/WEB-2124.
Note:
`collection.collectionName` is nullable, but `asset.address` is not nullable. This means we'll always be able to link to the collection page, even if we don't get a `collectionName`. So defaulted to generic "this collection," text to allow the link to still work. Most likely, `collection.collectionName` won't be null though.
=> fix: Collection name should link to collection page.

src/nft/components/explore/CarouselCard.tsx
Adds "ETH" at the end of floor prices for trending collections in the explore banner. 
Hardcoded ETH for now and included a small variable name change to make the logic more explicit and as a quick reminder that we'll need to change that logic if we want to be more flexible with floor price displays in the future.
Fixes https://uniswaplabs.atlassian.net/browse/WEB-2141
=> fix: Add ETH to the floor price in trending collections banner.

package.json, yarn.lock
This was added as an updated peerDep in web3-react: https://github.com/Uniswap/web3-react/pull/702
See here for more context: https://github.com/WalletConnect/walletconnect-monorepo/pull/977
I haven't yet figured out how to deploy web3-react, feel free to do that and update this PR if you want also.
Other thoughts:
- should we be lazy loading wallet connect
- should we upgrade to v2
=> fix: resolves infinite load for WalletConnect

src/components/swap/ConfirmSwapModal.tsx, src/hooks/useSwapCallback.tsx
Send the SWAP_SIGNED event when the swap is signed, _not_ when the signing is inferred.
This should make the SWAP_SIGNED event more reliable.
=> fix: imperatively send SwapSigned

src/lib/hooks/swap/useSendSwapTransaction.tsx, src/utils/swapErrorToUserReadableMessage.tsx
Omit tracking modified transactions, and instead show the user an error modal warning them to immediately cancel their tx.
Some wallets allow users to modify transactions before approving them, but this (a) risks converting the tx to something else, like a `transfer()`; and (b) means that we no longer have accurate data with which to track the tx in our transactions history views.
=> fix: err and warn if user modifies tx

src/nft/components/bag/BagFooter.tsx
old behavior: when user hit "connect a wallet" on mobile, the bag was open over the wallet connection modal. This will close the bag when the user clicks "connect a wallet" so they can see the wallet connection prompt.
=> fix: close bag when the user needs to connect a wallet

package.json, src/pages/App.tsx, yarn.lock
- This PR integrates the codebase with the `1.1.1` version of the analytics package.
- The main driver for the change is that the new package's initialization method accepts a `defaultEventName`, which used to be hardcoded in the *analytics* package.
- The hardcoding (as a string vs an enum) in the *anaytics* package, cause a misanming to occur. The reason it was hardcoded as a string inside the *analytics* package, is because we don't want the *infra* portion to be tied to the *analytics-events* package
- This change ensures that the consuming app defines the `defaultEventName`
=> fix: update analytics package to use default event

.env
When developing it is really helpful to comment out sections of code (for example, if wanting to test a loading or failure state). However, the no-unused-imports for example will get triggered quickly when that is done.
We can ignore these lint issues on build, and devs can add the requirements to their editor, pre-commit hook, etc. The build will also fail on GitHub anyways, so it will be obvious.
=> build: don't fail local build on lint

src/components/Tokens/TokenDetails/BalanceSummary.tsx
Balance summary was linking to its current page (no-op) so removed it.
=> fix(token-details): remove balance summary links to current page

src/components/NavBar/SearchBarDropdown.tsx
issue
Clicking on search causes maximum depth error.  It's because an object is being passed to the dependency array
after
=> fix: max depth error

src/nft/components/icons.tsx
Unfortunately, Safari doesn't support `transform` of SVG2 spec. More cross-browser approach is to use CSS + styled components.
=> fix: right arrow in carousel not rotated

src/nft/components/collection/TransactionCompleteModal.css.ts, src/nft/components/collection/TransactionCompleteModal.tsx
Allows for overflow of tx complete screens. Also removes underline on tx hash urls. There are designs for full screen tx complete pages to replace these so I purposefully didn't convert them to styled components as it would all be throwaway work.
=> fix: tx screen overflow

src/nft/components/explore/Banner.tsx
Sometimes Safari would render the Banner as if it had overflow set to hidden. This is odd because that does not happen on Chrome. The issue happens when there's a filter (blur) applied to an element and there's a hover state triggered either on that element or any of the elements on top of it. 
Applying `translate3d` seems to do the trick. Decided to link to the StackOverflow issue because this is a strong workaround and there's not many resources on it, beyond that answer. 
While reviewing, check the details on Slack: https://uniswapteam.slack.com/archives/C04822DFATE/p1668686941493839?thread_ts=1668668097.346379&cid=C04822DFATE
My guess is that the glitch doesn't happen when GPU acceleration kicks in for that element, which we achieve by applying `translate3d`.
=> fix: rendering of glow effect on mobile safari

src/nft/components/bag/BagRow.tsx, src/nft/components/bag/profile/ProfileAssetRow.tsx, src/nft/components/profile/list/ListPage.tsx
Sell bag assets now match the styles in the buy bag. I looked into refactoring the BagRow to take a WalletAsset but there is a lot of price update logic that is unnecessary for wallet assets so I opted to import the shared styles instead.
I also fixed a bug where items in list would wrap when overflowing.
=> feat: Sell bag styling

public/manifest.json
Kept seeing the above warning. We intended it to be `FC72FF`.
=> fix: theme color hex typo

src/components/Settings/index.tsx
Simply removing this unnecessary casting that can be fixed by properly defining the type in `useRef` and initializing it with `null`.
=> refactor: remove unnecessary casting

src/nft/components/profile/view/FilterSidebar.tsx, src/nft/components/profile/view/ProfilePage.tsx, src/nft/pages/collection/index.tsx, src/theme/styles.ts
- Fixes the bug on collection and profile page where you could scroll assets underneath
- Stops the cards from moving around underneath the bag causing them to snap in place when the bag was closed
- Fixes the laggy animation when filters were opened/closed on profile
=> fix: Can't scroll behind bag

src/nft/components/explore/Cells/Cells.tsx, src/nft/components/explore/CollectionTable.tsx, src/nft/components/explore/Table.tsx, src/theme/components/index.tsx, src/theme/components/text.tsx
Fixes WEB-1978
Other changes:
- Breakpoints in CSS are inclusive, so changed `<` to `<=` so that the Table behavior for hiding columns matches the one from CSS
- Added two Text variants that I've found in Figma (used on this screen), it would be good to increase that usage in the future
I'm not sure whether we should stick to CSS media queries for displaying/hiding elements or use React to do it, but I think we will have to decide on the best path to handle it. For example, while we're currently rendering `BodyPrimary` vs `BodySmall` based on `isMobile`, we could've just made a single `BodyPrimary` component with an appropriate media query for small devices.
I haven't implemented that change in this PR, as it would most likely affect the entire website, but I think it's something to think …
=> feat: add floor change on mobile

src/components/SearchModal/CurrencySearch.tsx, src/hooks/Tokens.ts, src/state/user/hooks.tsx, src/types/tokens.ts
- Retools the `useXTokens` hooks to only include userAdded tokens for `useAllTokens`
- Instantiates userAdded tokens as `UserAddedToken` instances
- Filters out `UserAddedToken`s from the selector if they have no balance
=> fix: include user-added tokens in selector

src/nft/components/bag/profile/ListingModal.tsx
Previously we let you approve all collections all at once, this work on desktop but isn't possible on mobile as you can't queue up the requests. Now all collections must be approved one by one (unless already approved)
=> feat: approve collections 1x1

src/nft/components/explore/CarouselCard.tsx
Fixes WEB-2376
When collection name is too large, we want to split it into two lines and eventually, truncate when the name is too long. We also want to center things vertically while keeping the overall header height. 
This is done with a `line-ellipsis` CSS feature that has relatively good support across the landscape, despite being under a prefix (Edge & Firefox support it under this prefix too). In case this is not supported, I added a maximum height for the title component that corresponds to two lines and added an `overflow: hidden`. This will hide overflowing text without putting an ellipsis, but I think it's a fair trade-off give how easy this is to support with pure CSS.
Since this is hard to reproduce without manually repeating the collection name programatically, I left some …
=> feat: multiline ellipsis when text is too large

src/nft/components/bag/profile/ListingModal.tsx, src/nft/components/bag/profile/ListingSection.tsx, src/nft/css/sprinkles.css.ts, src/nft/themes/darkTheme.ts, src/nft/themes/lightTheme.ts
Previously if a user had failed or rejected txs and they successfully retried via in line button press, the listing button would still be inactive. This fix checks for that case and put button back in active state.
Also fixes a color discrepancy.
https://uniswaplabs.atlassian.net/browse/WEB-2337
https://uniswaplabs.atlassian.net/browse/WEB-2373
=> fix: after retry, put listing button in a ready state

src/nft/components/profile/list/NFTListingsGrid.tsx
Fixes WEB-2362: Bug: Period (.) ignored by price input field on the listing page.
Fixed it by leaving all string equivalents of `0` (like '0.") as is if price is undefined. Feels a tiny bit hacky, but couldn't think of a better solution that leaves a small footprint.
=> fix: Issue where decimal appears as 0 on listings page.

src/nft/components/explore/Carousel.tsx, src/nft/components/explore/CarouselCard.tsx
Fixes WEB-2399
Fixes:
- display badge next to collection title when collection name is broken down into two lines
- text-align columns to the left (as well as hide marketplace name) when the banner width is more or less under 400px*
- slightly faster animation on carousel (follow-up from previous PR)
- smaller paddings on mobile for banner to fit more text (follow-up from previous PR)
- updated arrow colours to black/white on light/dark mode
The reason I said `more or less`:
Initially, our intention was to use CSS container queries to write a rule in a similar fashion to media queries, but relative to container width. This would let us automatically hide/show certain UI elements based on the parent dimensions.
Here's an example:
```
@supports (container-type: inline-size) {
@container …
```
=> chore: various responsive tweaks to carousel

src/components/SearchModal/CurrencyList/__snapshots__/index.test.tsx.snap, src/theme/components/text.tsx
Before:
After:
Eventually, I think we're going to migrate away from this Rebass Text component, so I consider this a temporary solution. Ideally, we shouldn't be passing any of the props down the tree, or even configure it this way.
For example, this:
```js
export const ThemedText = {
HeadlineSmall(props: TextProps) {
return <TextWrapper fontWeight={600} fontSize={20} lineHeight="28px" color="textPrimary" {...props} />
},
};
```
could be as simple as
```js
export const HeadlineSmall = styled(BaseText)`
fontWeight: 600;
fontSize: 20px;
lineHeight: 28px;
color: ${({theme}) => theme.textPrimary}
`
```
Like I said, something to keep in mind for the future
=> chore: fix invalid css color prop on text components

src/nft/components/collection/CollectionNfts.tsx
Previously we had a bug where when you loaded a page with a url that included filters, when you tried to remove a filter it would re-appear. This was caused by the useeffect that applied filters to the url and vice versa firing when it shouldn't have. This removes the unneeded triggering condition. You should still be able to apply and remove filters as usual and when you land on a page from a url with filters and remove it, the url should be updated and the filter should not re-appear.
=> fix: Stop traits from url re-appearing

src/components/Modal/index.tsx, src/nft/components/explore/WelcomeModal.tsx, src/state/user/reducer.ts
Modal is a really useful component, but in reality, it's has a behaviour closer to a bottom sheet on mobile devices. This results in a welcome modal being rendered full-screen on mobile.
After discussing with product and @ianlapham, decided to differentiate that behaviour behind a `isBottomSheet` prop.
Also did some smaller refactoring of a styled component, mainly:
- removed `attrs` and just passed a regular `aria-label` (HTML output is the same)
- removed props destructuring. If we really don't want to pass props down to an underlying component, we can prefix with a $ sign
- added types to make sure we don't misuse some of the props
- removed extraneous "as" from StyledDialogOverlay - it is a StyledDialogOverlay anyway, so that line was redundant 
- added `onSwipe` to be used instead of …
=> feat: differentiate modal from bottomsheet

src/nft/components/bag/profile/utils.ts, src/nft/components/profile/list/NFTListingsGrid.tsx, src/nft/utils/listNfts.ts
LooksRare has a flat 0.5% creator royalty fee as opposed to using the creator set basis points. This information is now correctly displayed to users. The listing functionality already took that into account and did not need to be updated.
=> fix: incorrect looks rare creator royalties

src/nft/components/collection/Card.tsx
fixes https://uniswaplabs.atlassian.net/browse/WEB-2384?filter=10136
Solution looks a bit hacky, but if we want the space consistently there we'll have to explicitly add a space.
I considered another option where I set card height to 100% (full), which makes the card heights equal across a row, but could result in different sized rows depending on whether there's >= 1 listed NFT present on the row.
=> fix: Display blank row if no listing price.

src/nft/components/collection/MarketplaceSelect.tsx
Change ordering of markets in filter menu. Requested here: https://uniswapteam.slack.com/archives/C04822DFATE/p1669229291484899?thread_ts=1669227223.337589&cid=C04822DFATE
=> refactor: change marketplace ordering

src/nft/components/explore/CarouselCard.tsx
now (seeing on firefox/windows): 
prior:
=> fix(banner): fix 1px non-overlay gap

.github/workflows/test.yml, cypress.config.ts
running into lots of timeouts with tests that do testnet interactions
=> fix(cypress): patch to add another parallelization and make timeout longer than block time

src/nft/hooks/useBag.ts
This makes it so the bagManuallyClosed state doesn't reset when it goes to 0 items in the bag.
=> fix: keep bag closed after manual close

src/graphql/data/fetchGraphQL.ts
Api key gate is no longer needed for nft graphql queries. Approved by product. Tested and got data locally.
=> feat: remove gated key for graphql query

src/nft/components/collection/Card.tsx
Collection names on profile cards were truncating early
=> fix: collection names truncating early

src/nft/utils/listNfts.ts
ENS tokenIds were too large and needed to be properly formatted to be cast to a BigNumber
=> fix: listing ens to x2y2

src/nft/utils/listNfts.ts
My previous fix did not actually allow you to list the ENS just allow you to be prompted. The fix was actually very simple in that the tokenId needed to be passed into BigNumber.from as a string to avoid the scientific notation error
=> fix: successfully list ENS to x2y2

src/nft/components/profile/list/NFTListingsGrid.tsx
When a user typed `.` followed by `0` into the listing price input, the decimal would be cleared, this fixes that bug
=> fix: allow 0 after decimal

.github/workflows/release.yaml
Releases to Cloudflare Pages.
Retools the release.yaml file so that a release is created after pinning, and is not dependent on deployment.
=> build: release to cloudflare pages

src/components/Tokens/TokenTable/TokenRow.tsx
=> fix: full width for all TokenRow breakpoints

src/pages/App.tsx, src/pages/Swap/redirects.tsx
I'd like to start simplifying the swap/home redirect logic as we start working on a landing page, and this is the first step. I think this is reasonable enough to remove.
=> chore: remove /swap/:outputCurrency redirect

src/pages/Swap/index.tsx
=> fix: making colors correct on approval screen
